services:
  - type: web
    name: pipserver
    runtime: python
    plan: free
    rootDir: server
    buildCommand: pip install -r requirements.txt
    startCommand: python3 appstore_notification_listener.py
    healthCheckPath: /
