import 'words_data.dart';

const kBeautifulExtras2 = <Word>[
  Word('beautiful', 'luminous', 'adj.', 'Full of soft, glowing light', 'The lake turned luminous as the moon climbed over the hills.'),
  Word('beautiful', 'radiant', 'adj.', 'Shining brightly and full of joy', 'She gave a radiant smile when she spotted them in the crowd.'),
  Word('beautiful', 'serene', 'adj.', 'Calm, peaceful, and untroubled', 'A serene quiet settled over the valley at dusk.'),
  Word('beautiful', 'sublimity', 'n.', 'The quality of awe-inspiring grandeur', 'The sheer sublimity of the canyon left them speechless.'),
  Word('beautiful', 'shimmer', 'v.', 'To shine with a soft, wavering light', 'Sunlight made the calm sea shimmer all afternoon.'),
  Word('beautiful', 'glimmer', 'n.', 'A faint, gentle gleam of light', 'A glimmer of dawn crept along the edge of the curtains.'),
  Word('beautiful', 'twilight', 'n.', 'The soft glowing light after sunset', 'They walked home through the cool blue twilight.'),
  Word('beautiful', 'dawn', 'n.', 'The first soft light of morning', 'At dawn the garden was hushed and silver with dew.'),
  Word('beautiful', 'dusk', 'n.', 'The gentle dimness at the end of day', 'Fireflies began to glow as dusk thickened over the field.'),
  Word('beautiful', 'aglow', 'adj.', 'Softly shining or radiant with warmth', 'Her face was aglow in the candlelight.'),
  Word('beautiful', 'balmy', 'adj.', 'Pleasantly warm and soothing', 'A balmy breeze drifted in from the open sea.'),
  Word('beautiful', 'breezy', 'adj.', 'Pleasantly windy and light', 'It was a breezy spring morning, perfect for the orchard.'),
  Word('beautiful', 'placid', 'adj.', 'Calm and free from disturbance', 'The placid pond mirrored the willows along its bank.'),
  Word('beautiful', 'tranquility', 'n.', 'The state of deep calm and peace', 'There is a rare tranquility to a snowfall at midnight.'),
  Word('beautiful', 'soothing', 'adj.', 'Gently calming to the senses', 'The soothing hush of waves lulled her to sleep.'),
  Word('beautiful', 'gentle', 'adj.', 'Soft, mild, and tender in nature', 'A gentle rain freshened the dusty lane.'),
  Word('beautiful', 'mild', 'adj.', 'Soft and pleasant, not harsh', 'The mild evening invited a long, slow stroll.'),
  Word('beautiful', 'velvety', 'adj.', 'Smooth and soft like velvet', 'The night sky was a velvety blue dotted with stars.'),
  Word('beautiful', 'silken', 'adj.', 'Soft, smooth, and lustrous like silk', 'A silken mist lay over the meadow at first light.'),
  Word('beautiful', 'feathery', 'adj.', 'Light and delicate like feathers', 'Feathery clouds drifted across the pale sky.'),
  Word('beautiful', 'downy', 'adj.', 'Soft and fluffy like fine down', 'The newborn lamb had a downy white coat.'),
  Word('beautiful', 'wispy', 'adj.', 'Thin, light, and delicate', 'Wispy strands of fog curled around the lampposts.'),
  Word('beautiful', 'airy', 'adj.', 'Light, open, and full of fresh air', 'The airy cottage felt bright even on cloudy days.'),
  Word('beautiful', 'delicate', 'adj.', 'Finely made and easily harmed', 'A delicate frost laced the windowpane overnight.'),
  Word('beautiful', 'dainty', 'adj.', 'Small, pretty, and finely made', 'Dainty wildflowers bordered the garden path.'),
  Word('beautiful', 'graceful', 'adj.', 'Moving with smooth, elegant ease', 'The dancer crossed the stage in a single graceful arc.'),
  Word('beautiful', 'elegant', 'adj.', 'Gracefully refined and tasteful', 'The swan made an elegant turn across the still water.'),
  Word('beautiful', 'exquisite', 'adj.', 'Extremely beautiful and finely crafted', 'The jeweler showed them an exquisite enamel brooch.'),
  Word('beautiful', 'sumptuous', 'adj.', 'Richly luxurious and splendid', 'The hall was draped in sumptuous folds of crimson silk.'),
  Word('beautiful', 'opulent', 'adj.', 'Lavishly rich and magnificent', 'Roses spilled in opulent waves over the garden wall.'),
  Word('beautiful', 'lavish', 'adj.', 'Abundant and richly generous', 'A lavish sunset spread orange and gold across the bay.'),
  Word('beautiful', 'lush', 'adj.', 'Rich, green, and full of growth', 'The rain left the hillside lush and gleaming.'),
  Word('beautiful', 'verdure', 'n.', 'Fresh green growth of plants', 'Spring brought a tender verdure to the bare branches.'),
  Word('beautiful', 'blossom', 'v.', 'To bloom and flourish beautifully', 'The orchard began to blossom in a haze of pink.'),
  Word('beautiful', 'bloom', 'n.', 'The flowering and freshness of beauty', 'The roses were in full bloom along the trellis.'),
  Word('beautiful', 'florid', 'adj.', 'Richly ornate and flowery', 'The ceiling bore a florid pattern of gilded vines.'),
  Word('beautiful', 'fragrant', 'adj.', 'Having a sweet, pleasant smell', 'The fragrant lilacs perfumed the whole courtyard.'),
  Word('beautiful', 'aromatic', 'adj.', 'Filled with a pleasant fragrance', 'Aromatic herbs lined the sunny kitchen window.'),
  Word('beautiful', 'balm', 'n.', 'Something that soothes and comforts', 'The quiet garden was a balm after the busy week.'),
  Word('beautiful', 'solace', 'n.', 'Comfort in times of sorrow', 'She found solace in the sound of the evening tide.'),
  Word('beautiful', 'repose', 'n.', 'A state of restful calm', 'The cat lay in soft repose by the warm hearth.'),
  Word('beautiful', 'respite', 'n.', 'A welcome pause of rest or relief', 'The shaded grove offered a cool respite from the heat.'),
  Word('beautiful', 'calm', 'n.', 'A peaceful stillness', 'A deep calm hung over the harbor before sunrise.'),
  Word('beautiful', 'stillness', 'n.', 'Complete quiet and lack of motion', 'In the stillness she could hear the snow falling.'),
  Word('beautiful', 'lull', 'n.', 'A soothing interval of quiet', 'There was a tender lull between the songs of the birds.'),
  Word('beautiful', 'murmur', 'n.', 'A low, soft, continuous sound', 'The murmur of the brook followed them up the trail.'),
  Word('beautiful', 'rustle', 'n.', 'A soft fluttering sound', 'A gentle rustle of leaves marked the coming breeze.'),
  Word('beautiful', 'chime', 'n.', 'A clear, musical ringing sound', 'The faint chime of bells drifted across the snowy town.'),
  Word('beautiful', 'melody', 'n.', 'A sweet and pleasing series of notes', 'A wistful melody floated from the open window.'),
  Word('beautiful', 'harmony', 'n.', 'A pleasing blend of sounds or parts', 'The garden and the old house lived in quiet harmony.'),
  Word('beautiful', 'cadence', 'n.', 'A graceful, rhythmic flow', 'Her words carried the soft cadence of a lullaby.'),
  Word('beautiful', 'lyrical', 'adj.', 'Expressing emotion in a beautiful, songlike way', 'The poem had a lyrical sweetness that lingered.'),
  Word('beautiful', 'melodic', 'adj.', 'Pleasant and tuneful to hear', 'The fountain made a melodic trickle in the courtyard.'),
  Word('beautiful', 'tuneful', 'adj.', 'Full of pleasing melody', 'A tuneful chorus of birds greeted the morning.'),
  Word('beautiful', 'silvery', 'adj.', 'Soft, bright, and gleaming like silver', 'The river ran silvery beneath the rising moon.'),
  Word('beautiful', 'golden', 'adj.', 'Warm and glowing like gold', 'Golden light pooled across the meadow at evening.'),
  Word('beautiful', 'rosy', 'adj.', 'Softly pink and glowing', 'A rosy flush spread over the eastern clouds.'),
  Word('beautiful', 'azure', 'adj.', 'Bright, clear sky-blue', 'The bay stretched out in a sheet of perfect azure.'),
  Word('beautiful', 'cerulean', 'adj.', 'A deep, clear sky-blue', 'A cerulean dome of sky arched over the wheat fields.'),
  Word('beautiful', 'amber', 'adj.', 'Warm honey-gold in color', 'The lamps cast an amber glow along the quiet street.'),
  Word('beautiful', 'roseate', 'adj.', 'Tinted a soft rose color', 'A roseate dawn warmed the snow on the peaks.'),
  Word('beautiful', 'pearly', 'adj.', 'Soft and lustrous like a pearl', 'The morning had a pearly sheen after the rain.'),
  Word('beautiful', 'glistening', 'adj.', 'Sparkling with a wet, soft shine', 'Glistening dewdrops clung to every blade of grass.'),
  Word('beautiful', 'sparkling', 'adj.', 'Shining with quick points of light', 'The stream ran sparkling over the smooth stones.'),
  Word('beautiful', 'glittering', 'adj.', 'Shining with bright flashes', 'The harbor lay glittering beneath the winter stars.'),
  Word('beautiful', 'gleaming', 'adj.', 'Shining softly and steadily', 'The freshly waxed floor lay gleaming in the sun.'),
  Word('beautiful', 'sunlit', 'adj.', 'Brightened by warm sunlight', 'They lingered in the sunlit corner of the orchard.'),
  Word('beautiful', 'moonlit', 'adj.', 'Lit by the soft glow of the moon', 'A moonlit path wound down to the silent shore.'),
  Word('beautiful', 'starry', 'adj.', 'Filled with the light of stars', 'They lay back to watch the vast starry sky.'),
  Word('beautiful', 'misty', 'adj.', 'Softened and veiled by mist', 'The misty hills faded gently into the morning gray.'),
  Word('beautiful', 'dewy', 'adj.', 'Fresh and moist with dew', 'The dewy lawn sparkled in the first light.'),
  Word('beautiful', 'frosted', 'adj.', 'Covered in a delicate layer of frost', 'Every twig was frosted white by the cold dawn.'),
  Word('beautiful', 'wintry', 'adj.', 'Having the quiet beauty of winter', 'A wintry hush lay over the snow-laden pines.'),
  Word('beautiful', 'vernal', 'adj.', 'Relating to the freshness of spring', 'A vernal sweetness filled the warming air.'),
  Word('beautiful', 'autumnal', 'adj.', 'Having the mellow beauty of autumn', 'The grove glowed with autumnal reds and golds.'),
  Word('beautiful', 'sylvan', 'adj.', 'Relating to peaceful woods and forests', 'A sylvan calm settled among the tall green firs.'),
  Word('beautiful', 'pastoral', 'adj.', 'Showing the gentle beauty of the countryside', 'The valley offered a pastoral scene of sheep and meadows.'),
  Word('beautiful', 'arcadian', 'adj.', 'Idyllically rural and serene', 'They wandered through an arcadian landscape of streams and groves.'),
  Word('beautiful', 'picturesque', 'adj.', 'Charmingly pretty like a picture', 'The picturesque village clung to the hillside above the lake.'),
  Word('beautiful', 'scenic', 'adj.', 'Offering beautiful views', 'They took the scenic road that hugged the coast.'),
  Word('beautiful', 'panorama', 'n.', 'A wide and beautiful view', 'From the ridge a glorious panorama opened before them.'),
  Word('beautiful', 'vista', 'n.', 'A pleasing distant view', 'The window framed a vista of rolling green hills.'),
  Word('beautiful', 'splendor', 'n.', 'Magnificent beauty or brilliance', 'The autumn forest blazed in all its splendor.'),
  Word('beautiful', 'grandeur', 'n.', 'Impressive and majestic beauty', 'The mountains rose in silent grandeur above the clouds.'),
  Word('beautiful', 'majesty', 'n.', 'Stately and awe-inspiring beauty', 'The waterfall fell with thunderous majesty into the gorge.'),
  Word('beautiful', 'magnificence', 'n.', 'Splendid and impressive beauty', 'The cathedral\'s magnificence hushed everyone who entered.'),
  Word('beautiful', 'glory', 'n.', 'Radiant beauty and brilliance', 'The sunset spread its glory across the entire sky.'),
  Word('beautiful', 'allure', 'n.', 'A quiet, captivating charm', 'The old garden held an allure that drew them back each evening.'),
  Word('beautiful', 'charm', 'n.', 'The quality of delighting and attracting', 'The cottage had a quiet charm that won them over at once.'),
  Word('beautiful', 'grace', 'n.', 'Effortless beauty of form or movement', 'She moved through the room with unhurried grace.'),
  Word('beautiful', 'poise', 'n.', 'Calm and graceful composure', 'The heron stood in perfect poise at the water\'s edge.'),
  Word('beautiful', 'comely', 'adj.', 'Pleasant and attractive in appearance', 'The comely garden was the pride of the whole street.'),
  Word('beautiful', 'fetching', 'adj.', 'Charmingly attractive', 'She wore a fetching sprig of jasmine in her hair.'),
  Word('beautiful', 'winsome', 'adj.', 'Sweetly and innocently charming', 'The child gave a winsome wave from the gate.'),
  Word('beautiful', 'lovely', 'adj.', 'Beautiful and delightful', 'It was a lovely morning, all birdsong and golden light.'),
  Word('beautiful', 'fair', 'adj.', 'Pleasingly beautiful and bright', 'A fair and cloudless sky promised a perfect day.'),
  Word('beautiful', 'rapture', 'n.', 'A feeling of intense joy and delight', 'She listened to the music in pure rapture.'),
  Word('beautiful', 'bliss', 'n.', 'Perfect and serene happiness', 'A whole afternoon by the river was simple bliss.'),
  Word('beautiful', 'wonder', 'n.', 'A feeling of awe at something beautiful', 'The children gazed at the auroras in silent wonder.'),
  Word('beautiful', 'awe', 'n.', 'Reverent wonder at something grand', 'Standing beneath the redwoods filled her with awe.'),
];
