import 'words_data.dart';

const kBiologyExtras = <Word>[
  Word('biology', 'mitosis', 'n.', 'Cell division that makes two identical copies', 'During mitosis the chromosomes line up before the cell splits in two.'),
  Word('biology', 'meiosis', 'n.', 'Cell division that makes egg and sperm cells', 'Meiosis halves the chromosome count so offspring get two full sets.'),
  Word('biology', 'allele', 'n.', 'One of the different versions of a gene', 'The allele for brown eyes is dominant over the one for blue.'),
  Word('biology', 'phenotype', 'n.', 'The visible traits an organism actually shows', 'Two plants with the same genes can have a different phenotype in poor soil.'),
  Word('biology', 'genotype', 'n.', 'The full set of genes an organism carries', 'A pea plant\'s genotype can hide a recessive trait that never appears.'),
  Word('biology', 'enzyme', 'n.', 'A protein that speeds up chemical reactions', 'This enzyme breaks starch into sugar within seconds of contact.'),
  Word('biology', 'homeostasis', 'n.', 'Keeping the body\'s internal conditions stable', 'Sweating helps maintain homeostasis when the temperature climbs.'),
  Word('biology', 'symbiosis', 'n.', 'A close living relationship between two species', 'The clownfish and the anemone are a classic example of symbiosis.'),
  Word('biology', 'mutualism', 'n.', 'A relationship where both species benefit', 'Bees and flowers practice mutualism: food for one, pollen spread for the other.'),
  Word('biology', 'apoptosis', 'n.', 'The body\'s controlled, programmed cell death', 'Apoptosis quietly removes cells that are damaged beyond repair.'),
  Word('biology', 'organelle', 'n.', 'A tiny structure inside a cell with a job', 'Each organelle handles a task, much like rooms in a factory.'),
  Word('biology', 'mitochondrion', 'n.', 'The organelle that produces a cell\'s energy', 'It\'s often called the mitochondrion\'s job to power the whole cell.'),
  Word('biology', 'photosynthesis', 'n.', 'How plants turn sunlight into food', 'Through photosynthesis, leaves convert light and water into sugar.'),
  Word('biology', 'taxonomy', 'n.', 'The science of naming and grouping organisms', 'Modern taxonomy now relies heavily on DNA comparisons.'),
  Word('biology', 'gamete', 'n.', 'A reproductive cell, like an egg or sperm', 'Each gamete carries only half of the parent\'s genetic material.'),
  Word('biology', 'zygote', 'n.', 'The single cell formed when egg meets sperm', 'The zygote begins dividing within hours of fertilization.'),
  Word('biology', 'ribosome', 'n.', 'The cell structure that builds proteins', 'A ribosome reads the genetic code and stitches amino acids together.'),
  Word('biology', 'plasmid', 'n.', 'A small ring of DNA found in bacteria', 'Scientists insert new genes into a plasmid to engineer bacteria.'),
  Word('biology', 'endemic', 'adj.', 'Found naturally only in one specific place', 'The lemur is endemic to Madagascar and lives nowhere else.'),
  Word('biology', 'niche', 'n.', 'The role and place a species fills in nature', 'Each woodpecker species occupies a slightly different niche on the tree.'),
  Word('biology', 'biome', 'n.', 'A large region defined by its climate and life', 'The tundra biome supports only hardy, low-growing plants.'),
  Word('biology', 'vestigial', 'adj.', 'A leftover body part that lost its function', 'The human appendix is widely regarded as a vestigial organ.'),
  Word('biology', 'epigenetics', 'n.', 'How genes are switched on or off without changing DNA', 'Epigenetics explains why identical twins can age so differently.'),
  Word('biology', 'pathogen', 'n.', 'A microbe that causes disease', 'Washing your hands removes many a pathogen before it can spread.'),
  Word('biology', 'antibody', 'n.', 'A protein that targets a specific invader', 'After infection, the body keeps an antibody ready for next time.'),
  Word('biology', 'antigen', 'n.', 'A substance that triggers an immune response', 'A vaccine introduces a harmless antigen to train the immune system.'),
  Word('biology', 'cytoplasm', 'n.', 'The jelly-like fluid filling a cell', 'Organelles float and drift within the cell\'s cytoplasm.'),
  Word('biology', 'nucleus', 'n.', 'The cell\'s control center holding its DNA', 'The nucleus directs nearly everything the cell does.'),
  Word('biology', 'chromosome', 'n.', 'A coiled package of DNA inside a cell', 'Humans normally carry forty-six chromosomes in each cell.'),
  Word('biology', 'chlorophyll', 'n.', 'The green pigment that captures sunlight', 'Chlorophyll gives leaves their color and powers photosynthesis.'),
  Word('biology', 'chloroplast', 'n.', 'The plant organelle where photosynthesis happens', 'Each chloroplast is packed with light-trapping green pigment.'),
  Word('biology', 'osmosis', 'n.', 'Water moving across a membrane toward saltier side', 'Osmosis pulls water into the root cells from the damp soil.'),
  Word('biology', 'diffusion', 'n.', 'Particles spreading from crowded to empty areas', 'Oxygen reaches the blood by simple diffusion across thin lung walls.'),
  Word('biology', 'metabolism', 'n.', 'All the chemical reactions that keep you alive', 'A fast metabolism burns calories even while you rest.'),
  Word('biology', 'genome', 'n.', 'The complete set of an organism\'s genes', 'Sequencing the human genome took more than a decade.'),
  Word('biology', 'mutation', 'n.', 'A change in the DNA sequence', 'A single mutation can make bacteria resistant to a drug.'),
  Word('biology', 'recessive', 'adj.', 'A trait hidden unless both genes match', 'Red hair is a recessive trait that often skips generations.'),
  Word('biology', 'dominant', 'adj.', 'A trait that shows even with one such gene', 'The dominant gene masks its recessive partner entirely.'),
  Word('biology', 'heredity', 'n.', 'The passing of traits from parents to offspring', 'Heredity explains why she has her father\'s dimples.'),
  Word('biology', 'adaptation', 'n.', 'A trait that helps a species survive better', 'The camel\'s hump is an adaptation for going long without water.'),
  Word('biology', 'natural selection', 'phr.', 'Survival of the traits best suited to survive', 'Natural selection favored moths that blended into sooty trees.'),
  Word('biology', 'speciation', 'n.', 'The splitting of one species into two new ones', 'Isolation on separate islands drove rapid speciation in the finches.'),
  Word('biology', 'extinction', 'n.', 'The complete dying out of a species', 'Habitat loss is pushing many frogs toward extinction.'),
  Word('biology', 'ecosystem', 'n.', 'A community of living things and their surroundings', 'Removing one predator can throw the whole ecosystem off balance.'),
  Word('biology', 'biodiversity', 'n.', 'The variety of life in a place', 'Rainforests hold an astonishing amount of biodiversity.'),
  Word('biology', 'food web', 'phr.', 'The network of who eats whom in an area', 'A single oil spill can unravel an entire coastal food web.'),
  Word('biology', 'producer', 'n.', 'An organism that makes its own food from light', 'Grasses act as the main producer in a prairie ecosystem.'),
  Word('biology', 'decomposer', 'n.', 'An organism that breaks down dead matter', 'Fungi serve as a decomposer, recycling nutrients back into soil.'),
  Word('biology', 'herbivore', 'n.', 'An animal that eats only plants', 'The gentle herbivore grazed on the riverbank all afternoon.'),
  Word('biology', 'carnivore', 'n.', 'An animal that eats other animals', 'A lion is a carnivore built for hunting large prey.'),
  Word('biology', 'omnivore', 'n.', 'An animal that eats both plants and animals', 'As an omnivore, the bear eats berries and fish alike.'),
  Word('biology', 'pollination', 'n.', 'Moving pollen so a plant can make seeds', 'Bees handle most of the pollination in the orchard.'),
  Word('biology', 'germination', 'n.', 'The sprouting of a seed into a young plant', 'Warmth and moisture together trigger germination.'),
  Word('biology', 'transpiration', 'n.', 'Water evaporating from a plant\'s leaves', 'On hot days transpiration pulls water up from the roots faster.'),
  Word('biology', 'stomata', 'n.', 'Tiny pores on a leaf that let gases pass', 'The leaf\'s stomata close at midday to save water.'),
  Word('biology', 'xylem', 'n.', 'Plant tissue that carries water upward', 'Xylem moves water from the roots all the way to the top.'),
  Word('biology', 'phloem', 'n.', 'Plant tissue that carries food made in leaves', 'Sugar travels through the phloem to feed the growing roots.'),
  Word('biology', 'cellulose', 'n.', 'The tough fiber that builds plant cell walls', 'Cellulose gives celery its satisfying crunch.'),
  Word('biology', 'membrane', 'n.', 'The thin layer that surrounds a cell', 'The membrane decides what gets to enter the cell.'),
  Word('biology', 'cytology', 'n.', 'The scientific study of cells', 'Her cytology training let her spot the abnormal cells at once.'),
  Word('biology', 'flagellum', 'n.', 'A whip-like tail that helps a cell move', 'The bacterium spins its flagellum to swim toward food.'),
  Word('biology', 'cilia', 'n.', 'Tiny hairs that beat to move fluid or cells', 'Cilia in your airways sweep dust back up the throat.'),
  Word('biology', 'lysosome', 'n.', 'The organelle that digests cell waste', 'The lysosome breaks down worn-out parts inside the cell.'),
  Word('biology', 'vacuole', 'n.', 'A storage sac inside a cell', 'A plant cell\'s large vacuole keeps it firm and full.'),
  Word('biology', 'prokaryote', 'n.', 'A simple cell with no true nucleus', 'A bacterium is a prokaryote with its DNA floating free.'),
  Word('biology', 'eukaryote', 'n.', 'A cell that keeps its DNA in a nucleus', 'Plants, animals, and fungi are all built from eukaryote cells.'),
  Word('biology', 'bacterium', 'n.', 'A single-celled microbe without a nucleus', 'A single bacterium can multiply into millions overnight.'),
  Word('biology', 'virus', 'n.', 'A tiny agent that hijacks cells to copy itself', 'A virus cannot reproduce until it invades a living cell.'),
  Word('biology', 'microbe', 'n.', 'A living thing too small to see unaided', 'A single drop of pond water teems with microbe life.'),
  Word('biology', 'fungus', 'n.', 'An organism like mold, yeast, or mushrooms', 'The fungus spread its threads through the rotting log.'),
  Word('biology', 'protozoa', 'n.', 'Single-celled animals that often live in water', 'Under the microscope the protozoa darted across the slide.'),
  Word('biology', 'plankton', 'n.', 'Tiny drifting organisms in seas and lakes', 'Whales filter tons of plankton from the cold water.'),
  Word('biology', 'larva', 'n.', 'The young, immature form of some animals', 'The butterfly begins life as a leaf-eating larva.'),
  Word('biology', 'metamorphosis', 'n.', 'A dramatic change in an animal\'s body form', 'A tadpole undergoes metamorphosis to become a frog.'),
  Word('biology', 'pupa', 'n.', 'The resting stage between larva and adult insect', 'Inside the pupa the caterpillar rebuilds itself entirely.'),
  Word('biology', 'gestation', 'n.', 'The time an animal carries its young before birth', 'An elephant\'s gestation lasts nearly two years.'),
  Word('biology', 'nocturnal', 'adj.', 'Active mainly during the night', 'Owls are nocturnal hunters with remarkable night vision.'),
  Word('biology', 'diurnal', 'adj.', 'Active mainly during the daytime', 'Most songbirds are diurnal and fall silent after dusk.'),
  Word('biology', 'hibernate', 'v.', 'To pass winter in a deep, sleep-like state', 'Bears hibernate through the coldest months to save energy.'),
  Word('biology', 'migrate', 'v.', 'To travel between regions with the seasons', 'Monarch butterflies migrate thousands of miles each fall.'),
  Word('biology', 'forage', 'v.', 'To search widely for food in the wild', 'Squirrels forage for nuts to bury before winter.'),
  Word('biology', 'predation', 'n.', 'The act of one animal hunting another', 'Predation keeps the rabbit population from exploding.'),
  Word('biology', 'parasite', 'n.', 'An organism that feeds off another, harming it', 'The tapeworm is a parasite living inside its host\'s gut.'),
  Word('biology', 'host', 'n.', 'An organism that a parasite lives on or in', 'The tick waits patiently for a passing host.'),
  Word('biology', 'camouflage', 'n.', 'Coloring that helps an animal blend in', 'The moth\'s camouflage made it vanish against the bark.'),
  Word('biology', 'nutrient', 'n.', 'A substance a living thing needs to grow', 'Decaying leaves return every nutrient to the forest floor.'),
  Word('biology', 'respiration', 'n.', 'How cells release energy from food', 'Cellular respiration turns sugar and oxygen into usable energy.'),
  Word('biology', 'circulation', 'n.', 'The flow of blood around the body', 'Steady circulation delivers oxygen to every tissue.'),
  Word('biology', 'neuron', 'n.', 'A cell that carries signals in the body', 'Each neuron passes a tiny electrical message to the next.'),
  Word('biology', 'synapse', 'n.', 'The gap where one neuron signals another', 'Chemicals leap across the synapse to relay the message.'),
  Word('biology', 'hormone', 'n.', 'A chemical messenger that travels in the blood', 'A surge of one hormone triggers the body\'s growth spurt.'),
  Word('biology', 'gland', 'n.', 'An organ that makes and releases substances', 'The sweat gland helps cool you down on a hot day.'),
  Word('biology', 'tissue', 'n.', 'A group of similar cells working together', 'Muscle tissue contracts to move the bones of the arm.'),
  Word('biology', 'cartilage', 'n.', 'The flexible tissue cushioning many joints', 'Cartilage in the knee keeps the bones from grinding.'),
  Word('biology', 'tendon', 'n.', 'The tough cord linking muscle to bone', 'Stretching first helps protect the tendon from tearing.'),
  Word('biology', 'capillary', 'n.', 'The smallest blood vessel in the body', 'Oxygen slips out of each tiny capillary into the tissue.'),
  Word('biology', 'alveolus', 'n.', 'A tiny air sac deep inside the lungs', 'Each alveolus swaps oxygen for carbon dioxide with the blood.'),
  Word('biology', 'secrete', 'v.', 'To produce and release a substance', 'Certain cells secrete mucus to protect the stomach lining.'),
  Word('biology', 'dormant', 'adj.', 'Alive but temporarily inactive', 'The seeds stay dormant in the soil until the spring rains.'),
  Word('biology', 'fertile', 'adj.', 'Able to produce offspring or support growth', 'The fertile valley supported three harvests a year.'),
  Word('biology', 'genus', 'n.', 'A group of closely related species', 'The wolf and the dog belong to the same genus.'),
  Word('biology', 'convergent evolution', 'phr.', 'Unrelated species evolving similar traits', 'Wings in birds and bats are a case of convergent evolution.'),
  Word('biology', 'keystone species', 'phr.', 'A species that holds an ecosystem together', 'The sea otter is a keystone species protecting the kelp forest.'),
  Word('biology', 'gene expression', 'phr.', 'When a gene is actively used to make a protein', 'Stress can alter the gene expression of these cells overnight.'),
];
