import 'words_data.dart';

const kBusinessExtras2 = <Word>[
  Word('business', 'accountability', 'n.', 'the obligation to answer for one\'s actions and results', 'The new manager stressed accountability for every team member.'),
  Word('business', 'accreditation', 'n.', 'official recognition that a standard has been met', 'The school sought accreditation from a national body.'),
  Word('business', 'actuary', 'n.', 'a professional who assesses financial risk using statistics', 'The insurer hired an actuary to price the new policy.'),
  Word('business', 'adjudicate', 'v.', 'to make a formal judgment on a dispute', 'A panel was chosen to adjudicate the contract claim.'),
  Word('business', 'aggregator', 'n.', 'a service that collects items from many sources into one place', 'The travel aggregator compared prices from dozens of airlines.'),
  Word('business', 'amalgamate', 'v.', 'to combine two or more organizations into one', 'The two regional banks decided to amalgamate.'),
  Word('business', 'annuity', 'n.', 'a fixed sum paid to someone at regular intervals', 'She bought an annuity to provide steady retirement income.'),
  Word('business', 'appreciation', 'n.', 'an increase in the value of an asset over time', 'Investors enjoyed strong appreciation in the property market.'),
  Word('business', 'arrears', 'n.', 'money owed that should have been paid earlier', 'The tenant fell into arrears on the rent.'),
  Word('business', 'assignee', 'n.', 'a person to whom a right or property is transferred', 'The lease named a new assignee for the contract.'),
  Word('business', 'augment', 'v.', 'to increase the size or value of something', 'They augmented the team with three contract specialists.'),
  Word('business', 'autonomy', 'n.', 'the freedom to act independently within an organization', 'Field offices were given more autonomy over budgets.'),
  Word('business', 'aversion', 'n.', 'a strong dislike or reluctance, often toward risk', 'His aversion to debt kept the firm conservative.'),
  Word('business', 'bailout', 'n.', 'financial rescue of a failing company or institution', 'The airline received a government bailout during the crisis.'),
  Word('business', 'bellwether', 'n.', 'something regarded as an indicator of a trend', 'The retailer is a bellwether for consumer spending.'),
  Word('business', 'beneficiary', 'n.', 'a person who receives benefits or money from something', 'She named her children as beneficiaries of the policy.'),
  Word('business', 'bequest', 'n.', 'money or property left to someone in a will', 'The foundation grew thanks to a generous bequest.'),
  Word('business', 'brick-and-mortar', 'adj.', 'relating to a physical store rather than online', 'The brand expanded from online into brick-and-mortar shops.'),
  Word('business', 'brinkmanship', 'n.', 'pushing a confrontation to the edge to gain advantage', 'The labor talks dissolved into pure brinkmanship.'),
  Word('business', 'buoyant', 'adj.', 'tending to rise or remain strong, as a market', 'Demand stayed buoyant despite higher prices.'),
  Word('business', 'cannibalize', 'v.', 'to reduce sales of one product by introducing another', 'The cheaper model began to cannibalize premium sales.'),
  Word('business', 'capitalize', 'v.', 'to provide a business with money or to record a cost as an asset', 'The startup was capitalized with two million in seed funding.'),
  Word('business', 'caveat', 'n.', 'a warning or qualifying condition', 'The forecast came with a caveat about supply risks.'),
  Word('business', 'centralize', 'v.', 'to bring control or activity under one authority', 'The firm chose to centralize its purchasing department.'),
  Word('business', 'circumvent', 'v.', 'to find a way around a rule or obstacle', 'They tried to circumvent the new tariff with reshipping.'),
  Word('business', 'clawback', 'n.', 'the recovery of money already paid out', 'The contract included a clawback if targets were missed.'),
  Word('business', 'clearance', 'n.', 'official permission, or a sale of remaining stock', 'The shipment awaited customs clearance at the port.'),
  Word('business', 'clientele', 'n.', 'the customers of a business collectively', 'The boutique built a loyal clientele over the years.'),
  Word('business', 'commensurate', 'adj.', 'matching in size, degree, or amount', 'Pay should be commensurate with experience.'),
  Word('business', 'commodity', 'n.', 'a basic good traded in bulk, like grain or oil', 'Copper is a commodity sensitive to global demand.'),
  Word('business', 'comptroller', 'n.', 'a senior officer who oversees financial accounts', 'The comptroller flagged an error in the quarterly report.'),
  Word('business', 'conglomerate', 'n.', 'a large corporation made of many varied businesses', 'The conglomerate owned everything from media to chemicals.'),
  Word('business', 'consignment', 'n.', 'goods sent to a seller who pays only after they sell', 'The artist placed her work in the gallery on consignment.'),
  Word('business', 'consortium', 'n.', 'a group of companies cooperating on a venture', 'A consortium of banks financed the new airport.'),
  Word('business', 'contingent', 'adj.', 'dependent on something else happening', 'The bonus was contingent on hitting the revenue goal.'),
  Word('business', 'conveyance', 'n.', 'the legal transfer of property from one party to another', 'The conveyance of the warehouse closed last week.'),
  Word('business', 'creditor', 'n.', 'a person or firm to whom money is owed', 'Creditors lined up to recover funds from the bankrupt firm.'),
  Word('business', 'curtail', 'v.', 'to reduce or cut back on something', 'They had to curtail spending after the slow quarter.'),
  Word('business', 'debtor', 'n.', 'a person or firm that owes money', 'The bank pursued several delinquent debtors.'),
  Word('business', 'decentralize', 'v.', 'to distribute authority away from a central point', 'The company decentralized decisions to regional managers.'),
  Word('business', 'deductible', 'n.', 'the amount paid before insurance coverage begins', 'The policy had a high deductible but low premiums.'),
  Word('business', 'delinquent', 'adj.', 'overdue or failing to pay a debt on time', 'The account became delinquent after three missed payments.'),
  Word('business', 'demographic', 'n.', 'a particular segment of a population', 'The product targets a younger demographic.'),
  Word('business', 'denomination', 'n.', 'the face value of a unit of money or a bond', 'Bonds were issued in denominations of one thousand.'),
  Word('business', 'depository', 'n.', 'a place where things, especially money, are stored', 'Securities were held in a central depository.'),
  Word('business', 'devaluation', 'n.', 'a reduction in the official value of a currency', 'The devaluation made the country\'s exports cheaper abroad.'),
  Word('business', 'differentiate', 'v.', 'to make a product distinct from competitors', 'They differentiate their service through faster support.'),
  Word('business', 'disbursement', 'n.', 'the act of paying out money from a fund', 'The grant disbursement arrived at the start of the quarter.'),
  Word('business', 'disclosure', 'n.', 'the act of making information formally known', 'Securities law requires full disclosure to investors.'),
  Word('business', 'discretionary', 'adj.', 'available to be spent or used as one chooses', 'Households cut discretionary spending during the downturn.'),
  Word('business', 'disposable', 'adj.', 'remaining available to spend after taxes', 'Rising prices ate into disposable income.'),
  Word('business', 'divestiture', 'n.', 'the sale or disposal of a business asset', 'The divestiture of the unit raised needed cash.'),
  Word('business', 'docket', 'n.', 'a list of cases or items to be dealt with', 'The proposal was added to next week\'s board docket.'),
  Word('business', 'dossier', 'n.', 'a collection of documents about a subject', 'The analyst compiled a dossier on the takeover target.'),
  Word('business', 'downsize', 'v.', 'to reduce the number of employees', 'The firm downsized after losing its biggest client.'),
  Word('business', 'downturn', 'n.', 'a decline in economic or business activity', 'Hiring froze during the downturn.'),
  Word('business', 'drawdown', 'n.', 'a reduction in funds, or a decline from a peak', 'The fund suffered a sharp drawdown in March.'),
  Word('business', 'duress', 'n.', 'pressure or threats used to force agreement', 'He claimed the contract was signed under duress.'),
  Word('business', 'echelon', 'n.', 'a level or rank within an organization', 'She rose quickly to the upper echelons of management.'),
  Word('business', 'embezzle', 'v.', 'to steal money entrusted to one\'s care', 'The treasurer was caught trying to embezzle funds.'),
  Word('business', 'emolument', 'n.', 'a salary, fee, or profit from employment', 'The contract listed every emolument the director received.'),
  Word('business', 'encumbrance', 'n.', 'a claim or liability attached to property', 'The title search revealed no encumbrance on the land.'),
  Word('business', 'endorsement', 'n.', 'public approval or backing of a product or person', 'The athlete\'s endorsement boosted the brand\'s sales.'),
  Word('business', 'endowment', 'n.', 'a fund of donated money invested to provide income', 'The university\'s endowment funds many scholarships.'),
  Word('business', 'entrepreneur', 'n.', 'a person who starts and runs a business venture', 'The young entrepreneur launched three startups.'),
  Word('business', 'envoy', 'n.', 'a representative sent to negotiate or deliver a message', 'The company sent an envoy to the trade summit.'),
  Word('business', 'expedite', 'v.', 'to make a process happen more quickly', 'They paid extra to expedite the shipment.'),
  Word('business', 'expenditure', 'n.', 'an amount of money spent', 'Capital expenditure rose as the plant expanded.'),
  Word('business', 'expropriate', 'v.', 'to take property, especially by the state', 'The government threatened to expropriate the mine.'),
  Word('business', 'fabricate', 'v.', 'to manufacture, or to invent falsely', 'The plant can fabricate custom steel parts.'),
  Word('business', 'facilitate', 'v.', 'to make an action or process easier', 'A broker facilitated the sale between the two firms.'),
  Word('business', 'fiscal', 'adj.', 'relating to government or business finances', 'The company closed a strong fiscal year.'),
  Word('business', 'fixed cost', 'n.', 'an expense that stays the same regardless of output', 'Rent is a fixed cost that must be paid every month.'),
  Word('business', 'fledgling', 'adj.', 'new and inexperienced, just getting started', 'The fledgling firm struggled to find its first clients.'),
  Word('business', 'fluctuate', 'v.', 'to rise and fall irregularly', 'Oil prices fluctuate with global tensions.'),
  Word('business', 'foothold', 'n.', 'a secure position from which to make progress', 'The brand gained a foothold in the Asian market.'),
  Word('business', 'forfeit', 'v.', 'to lose a right or possession as a penalty', 'He had to forfeit his deposit when the deal collapsed.'),
  Word('business', 'fortify', 'v.', 'to strengthen against difficulty or attack', 'They moved to fortify the balance sheet before the recession.'),
  Word('business', 'franchising', 'n.', 'the business model of licensing a brand to operators', 'Franchising let the chain expand without owning every store.'),
  Word('business', 'fraudulent', 'adj.', 'involving deception for unfair gain', 'Auditors uncovered several fraudulent invoices.'),
  Word('business', 'frugal', 'adj.', 'careful and economical with money', 'The founder stayed frugal even after the windfall.'),
  Word('business', 'garnish', 'v.', 'to withhold money from wages to pay a debt', 'The court ordered the firm to garnish his wages.'),
  Word('business', 'glut', 'n.', 'an oversupply of something on the market', 'A glut of unsold inventory forced deep discounts.'),
  Word('business', 'grievance', 'n.', 'a formal complaint, often by an employee', 'The union filed a grievance over the schedule change.'),
  Word('business', 'gross', 'adj.', 'total before any deductions are made', 'Gross revenue rose, but profits stayed flat.'),
  Word('business', 'illiquid', 'adj.', 'not easily converted into cash', 'Real estate is an illiquid asset.'),
  Word('business', 'impasse', 'n.', 'a situation in which no progress is possible', 'The negotiations reached an impasse over wages.'),
  Word('business', 'impetus', 'n.', 'a force or stimulus that drives something forward', 'The merger gave fresh impetus to the expansion.'),
  Word('business', 'impound', 'v.', 'to seize and hold legally', 'Customs officials impounded the undeclared goods.'),
  Word('business', 'incentivize', 'v.', 'to motivate by offering a reward', 'They incentivized referrals with cash bonuses.'),
  Word('business', 'incremental', 'adj.', 'increasing gradually in small amounts', 'The update brought incremental gains in efficiency.'),
  Word('business', 'incur', 'v.', 'to become liable for a cost or loss', 'The firm will incur penalties if it ships late.'),
  Word('business', 'indemnify', 'v.', 'to compensate someone for loss or damage', 'The contract indemnifies the buyer against defects.'),
  Word('business', 'indices', 'n.', 'a set of statistical measures of a market', 'Stock indices fell sharply at the open.'),
  Word('business', 'inducement', 'n.', 'something offered to persuade someone to act', 'A signing bonus served as an inducement to join.'),
  Word('business', 'ingress', 'n.', 'the act or right of entering a place', 'The lease guaranteed ingress to the loading dock.'),
  Word('business', 'insolvency', 'n.', 'the state of being unable to pay debts', 'Mounting losses pushed the retailer toward insolvency.'),
  Word('business', 'institutional', 'adj.', 'relating to large organizations that invest money', 'Institutional investors hold most of the shares.'),
  Word('business', 'instrumental', 'adj.', 'serving as an important means to an end', 'She was instrumental in closing the deal.'),
  Word('business', 'intermediary', 'n.', 'a person who acts as a link between parties', 'A broker served as the intermediary in the sale.'),
  Word('business', 'inventory turnover', 'n.', 'how many times stock is sold and replaced in a period', 'High inventory turnover signals strong sales.'),
  Word('business', 'jurisdiction', 'n.', 'the official authority to make legal decisions', 'The dispute fell under the jurisdiction of the local court.'),
  Word('business', 'kickback', 'n.', 'an illegal payment for favorable treatment', 'The official took a kickback to award the contract.'),
  Word('business', 'lapse', 'v.', 'to become void through disuse or time', 'The insurance policy will lapse if you stop paying.'),
  Word('business', 'latitude', 'n.', 'freedom to act or decide as one wishes', 'Managers were given latitude to set their own targets.'),
  Word('business', 'layoff', 'n.', 'the dismissal of workers, often temporarily', 'The plant announced a round of layoffs.'),
  Word('business', 'lessee', 'n.', 'a person who holds the lease of a property', 'As lessee, she was responsible for repairs.'),
  Word('business', 'lessor', 'n.', 'a person who grants a lease of a property', 'The lessor agreed to lower the monthly rent.'),
  Word('business', 'liaison', 'n.', 'a person who maintains communication between groups', 'She acted as liaison between the two departments.'),
  Word('business', 'lucrative', 'adj.', 'producing a great deal of profit', 'The consulting work proved highly lucrative.'),
  Word('business', 'macroeconomic', 'adj.', 'relating to the economy as a whole', 'Macroeconomic data shaped the bank\'s outlook.'),
  Word('business', 'malfeasance', 'n.', 'wrongdoing, especially by a public official', 'The executive was charged with financial malfeasance.'),
  Word('business', 'mandatory', 'adj.', 'required by rule or law', 'Safety training is mandatory for all staff.'),
  Word('business', 'manpower', 'n.', 'the workers available for a task', 'The project lacked the manpower to finish on time.'),
  Word('business', 'mediation', 'n.', 'intervention to help two parties reach agreement', 'They turned to mediation to settle the dispute.'),
  Word('business', 'memorandum', 'n.', 'a written note recording terms or information', 'The two firms signed a memorandum of understanding.'),
  Word('business', 'meritocracy', 'n.', 'a system where advancement is based on ability', 'The firm prides itself on being a meritocracy.'),
  Word('business', 'mitigate', 'v.', 'to make something less severe or harmful', 'Hedging helped mitigate the currency risk.'),
  Word('business', 'monetize', 'v.', 'to earn revenue from an asset or activity', 'The app struggled to monetize its large user base.'),
  Word('business', 'mogul', 'n.', 'a powerful and wealthy business figure', 'The media mogul controlled several networks.'),
  Word('business', 'multinational', 'adj.', 'operating in several countries', 'The multinational firm employs staff on five continents.'),
  Word('business', 'negotiable', 'adj.', 'open to discussion or able to be transferred', 'The salary is negotiable for the right candidate.'),
  Word('business', 'nominal', 'adj.', 'very small, or stated rather than real', 'They charged a nominal fee for membership.'),
  Word('business', 'notarize', 'v.', 'to certify a document with an official seal', 'You must notarize the affidavit before filing.'),
  Word('business', 'obsolescence', 'n.', 'the process of becoming outdated', 'Rapid obsolescence forces constant upgrades in tech.'),
  Word('business', 'oligarch', 'n.', 'a very rich businessperson with great influence', 'The oligarch owned ports and pipelines across the region.'),
  Word('business', 'onus', 'n.', 'the responsibility or burden for something', 'The onus is on the seller to prove the goods are genuine.'),
  Word('business', 'operative', 'adj.', 'in effect or functioning', 'The new policy becomes operative next month.'),
  Word('business', 'ordinance', 'n.', 'a rule or law made by an authority', 'A local ordinance limits store hours on Sundays.'),
  Word('business', 'outlay', 'n.', 'an amount of money spent on something', 'The initial outlay for equipment was steep.'),
  Word('business', 'overdraft', 'n.', 'a withdrawal exceeding the account balance', 'The business arranged an overdraft to cover payroll.'),
  Word('business', 'overhaul', 'v.', 'to thoroughly revise or rebuild something', 'Management decided to overhaul the supply chain.'),
  Word('business', 'oversubscribe', 'v.', 'to receive more demand than supply', 'The bond issue was heavily oversubscribed.'),
  Word('business', 'overvalue', 'v.', 'to estimate worth as higher than it is', 'Analysts warned the stock was overvalued.'),
  Word('business', 'paradigm', 'n.', 'a typical model or pattern of doing something', 'Streaming created a new paradigm for media sales.'),
  Word('business', 'parlay', 'v.', 'to turn a small advantage into something greater', 'She parlayed one client into a thriving agency.'),
  Word('business', 'patron', 'n.', 'a regular customer or financial supporter', 'The cafe rewarded its most loyal patrons.'),
  Word('business', 'payee', 'n.', 'the person to whom a payment is made', 'Write the payee\'s name clearly on the check.'),
  Word('business', 'payroll', 'n.', 'the list of employees and the wages they receive', 'The startup struggled to make payroll that month.'),
  Word('business', 'penetration', 'n.', 'the extent a product has entered a market', 'Market penetration doubled after the price cut.'),
  Word('business', 'perpetuity', 'n.', 'a state of continuing forever', 'The grant funds the chair in perpetuity.'),
  Word('business', 'pertinent', 'adj.', 'relevant to the matter at hand', 'She raised several pertinent points about the budget.'),
  Word('business', 'philanthropy', 'n.', 'the practice of donating to good causes', 'The founder devoted his fortune to philanthropy.'),
  Word('business', 'placeholder', 'n.', 'something used temporarily in place of the real thing', 'They put a placeholder figure in the draft budget.'),
  Word('business', 'plummet', 'v.', 'to fall steeply and suddenly', 'Shares plummeted after the earnings miss.'),
  Word('business', 'portfolio', 'n.', 'a collection of investments or products held together', 'She diversified her portfolio across several sectors.'),
  Word('business', 'precarious', 'adj.', 'uncertain and likely to fail', 'The firm\'s finances were in a precarious state.'),
  Word('business', 'preclude', 'v.', 'to prevent something from happening', 'The clause precludes any side deals with rivals.'),
  Word('business', 'premise', 'n.', 'a building used for business, or a basic assumption', 'No food may be consumed on the premises.'),
  Word('business', 'premium', 'n.', 'an amount paid in addition, as for insurance or quality', 'Customers pay a premium for the brand name.'),
  Word('business', 'prerogative', 'n.', 'a right or privilege belonging to a person or role', 'Setting the agenda is the chair\'s prerogative.'),
  Word('business', 'prevalent', 'adj.', 'widespread or common in a particular area', 'Remote work is now prevalent in the industry.'),
  Word('business', 'privatize', 'v.', 'to transfer from public to private ownership', 'The government moved to privatize the railway.'),
  Word('business', 'proceeds', 'n.', 'the money gained from a sale or event', 'Proceeds from the sale funded a new venture.'),
  Word('business', 'proficient', 'adj.', 'competent and skilled at something', 'He is proficient in financial modeling.'),
  Word('business', 'profiteer', 'n.', 'one who makes excessive profit unfairly', 'The crisis bred profiteers who hoarded supplies.'),
  Word('business', 'pro forma', 'adj.', 'done as a formality, or based on projections', 'The bank reviewed the pro forma financial statements.'),
  Word('business', 'proliferate', 'v.', 'to increase rapidly in number', 'Subscription services proliferated in recent years.'),
  Word('business', 'proponent', 'n.', 'a person who advocates for an idea or plan', 'She was a leading proponent of the merger.'),
  Word('business', 'proprietary', 'adj.', 'owned exclusively, as a protected technology', 'The firm guards its proprietary algorithm closely.'),
  Word('business', 'proprietor', 'n.', 'the owner of a business', 'The proprietor greeted every customer by name.'),
  Word('business', 'prudent', 'adj.', 'showing care and good judgment, especially with money', 'It was prudent to keep a cash reserve.'),
  Word('business', 'purveyor', 'n.', 'a person or company that supplies goods', 'They became a leading purveyor of fine coffee.'),
  Word('business', 'quantify', 'v.', 'to express or measure as an amount', 'It is hard to quantify the value of goodwill.'),
  Word('business', 'quarterly', 'adj.', 'occurring every three months', 'The firm released its quarterly earnings report.'),
  Word('business', 'ramp up', 'phr.', 'to increase production or activity', 'The factory will ramp up output for the holidays.'),
  Word('business', 'ratify', 'v.', 'to formally approve an agreement', 'The board voted to ratify the new contract.'),
  Word('business', 'rationalize', 'v.', 'to reorganize for greater efficiency', 'They rationalized the product line to cut costs.'),
  Word('business', 'reciprocal', 'adj.', 'given or done in return by both parties', 'The countries signed a reciprocal trade deal.'),
  Word('business', 'redeem', 'v.', 'to exchange for cash, goods, or value', 'You can redeem the points for travel.'),
  Word('business', 'redress', 'n.', 'remedy or compensation for a wrong', 'Customers sought redress for the faulty product.'),
  Word('business', 'redundancy', 'n.', 'the loss of a job because it is no longer needed', 'Automation led to redundancies across the plant.'),
  Word('business', 'reimburse', 'v.', 'to repay money spent on one\'s behalf', 'The company will reimburse your travel costs.'),
  Word('business', 'reinvest', 'v.', 'to put profits back into the business', 'They chose to reinvest earnings rather than pay dividends.'),
  Word('business', 'remunerate', 'v.', 'to pay someone for work or services', 'The firm remunerates consultants by the hour.'),
  Word('business', 'rescind', 'v.', 'to cancel or revoke formally', 'The board voted to rescind the earlier decision.'),
  Word('business', 'reserves', 'n.', 'funds kept available for future needs', 'The company drew on its cash reserves during the slump.'),
  Word('business', 'resilient', 'adj.', 'able to recover quickly from difficulties', 'The brand proved resilient through the recession.'),
  Word('business', 'restitution', 'n.', 'the restoring of something lost or its value', 'The court ordered restitution to the defrauded clients.'),
  Word('business', 'retrench', 'v.', 'to cut back spending or staff to save money', 'The firm had to retrench after losing market share.'),
  Word('business', 'revamp', 'v.', 'to give something a new and improved form', 'They revamped the website to boost sales.'),
  Word('business', 'revoke', 'v.', 'to officially cancel a right or permission', 'The agency revoked the firm\'s trading license.'),
  Word('business', 'rigorous', 'adj.', 'extremely thorough and demanding', 'The audit followed a rigorous review process.'),
  Word('business', 'scalable', 'adj.', 'able to grow easily without losing efficiency', 'They built a scalable platform for millions of users.'),
  Word('business', 'scrutiny', 'n.', 'close and critical examination', 'The deal came under heavy regulatory scrutiny.'),
  Word('business', 'seasoned', 'adj.', 'highly experienced in a field', 'They hired a seasoned executive to lead the turnaround.'),
  Word('business', 'sediment', 'n.', 'material that settles, sometimes used of stale inventory', 'Old stock formed a sediment of dead inventory.'),
  Word('business', 'sequester', 'v.', 'to set apart or isolate funds or assets', 'The funds were sequestered pending the investigation.'),
  Word('business', 'shareholding', 'n.', 'the shares of a company owned by someone', 'He sold his entire shareholding in the firm.'),
  Word('business', 'shortfall', 'n.', 'a deficit when something falls short of a target', 'A revenue shortfall forced budget cuts.'),
  Word('business', 'showcase', 'v.', 'to display or present something prominently', 'The expo lets startups showcase their products.'),
  Word('business', 'slump', 'n.', 'a prolonged period of poor performance', 'Sales fell into a deep slump over the winter.'),
  Word('business', 'solicit', 'v.', 'to ask for or try to obtain something', 'The firm began to solicit bids from contractors.'),
  Word('business', 'solvent', 'adj.', 'having enough money to pay debts', 'Careful management kept the company solvent.'),
  Word('business', 'speculate', 'v.', 'to trade in risky assets hoping for profit', 'Investors speculated heavily on the new currency.'),
  Word('business', 'spearhead', 'v.', 'to lead an effort or initiative', 'She spearheaded the push into overseas markets.'),
  Word('business', 'stagnant', 'adj.', 'showing no growth or activity', 'Wages remained stagnant for a decade.'),
  Word('business', 'staple', 'n.', 'a basic, regularly used product', 'Rice is a staple sold in huge volumes.'),
  Word('business', 'startup', 'n.', 'a newly established business venture', 'The startup grew from two founders to a hundred staff.'),
  Word('business', 'stewardship', 'n.', 'the careful management of resources entrusted to you', 'Investors praised the board\'s stewardship of capital.'),
  Word('business', 'stipulate', 'v.', 'to specify as a condition of an agreement', 'The contract stipulates delivery within ten days.'),
  Word('business', 'streamline', 'v.', 'to make a process simpler and more efficient', 'They streamlined approvals to speed up hiring.'),
  Word('business', 'subcontract', 'v.', 'to hire another firm to do part of a job', 'They subcontracted the wiring to a local crew.'),
  Word('business', 'subsidiary', 'n.', 'a company controlled by a larger one', 'The bank sold its insurance subsidiary.'),
  Word('business', 'substantial', 'adj.', 'large in amount, size, or importance', 'They made a substantial investment in research.'),
  Word('business', 'succession', 'n.', 'the process of passing leadership to a successor', 'The board prepared a careful succession plan.'),
  Word('business', 'surcharge', 'n.', 'an extra charge added to the usual price', 'A fuel surcharge was added to every shipment.'),
  Word('business', 'surety', 'n.', 'a guarantee, or one who guarantees a debt', 'A bond served as surety for the project.'),
  Word('business', 'surplus', 'n.', 'an amount left over after needs are met', 'The trade surplus widened last quarter.'),
  Word('business', 'sustainable', 'adj.', 'able to continue over the long term', 'They sought a sustainable rate of growth.'),
  Word('business', 'syndicated', 'adj.', 'sold or arranged among a group of investors', 'The loan was syndicated across several banks.'),
  Word('business', 'tabulate', 'v.', 'to arrange data in a table or list', 'Staff tabulated the survey responses overnight.'),
  Word('business', 'tactical', 'adj.', 'relating to short-term planned actions', 'They made a tactical price cut to win the contract.'),
  Word('business', 'tangible', 'adj.', 'physical and able to be touched or measured', 'Factories are tangible assets on the balance sheet.'),
  Word('business', 'taxation', 'n.', 'the system of imposing and collecting taxes', 'Changes in taxation affected the firm\'s profits.'),
  Word('business', 'telecommute', 'v.', 'to work from home using technology', 'Many staff now telecommute three days a week.'),
  Word('business', 'tenable', 'adj.', 'able to be defended or maintained', 'Their pricing was no longer tenable against rivals.'),
  Word('business', 'tentative', 'adj.', 'not certain or fixed; provisional', 'They reached a tentative agreement on the terms.'),
  Word('business', 'threshold', 'n.', 'a level that must be reached for something to happen', 'Spending crossed the threshold for a volume discount.'),
  Word('business', 'thrive', 'v.', 'to grow and succeed strongly', 'Small shops thrived in the renovated district.'),
  Word('business', 'tradesman', 'n.', 'a skilled manual worker in a particular trade', 'The firm hired a tradesman to fit the cabinets.'),
  Word('business', 'transact', 'v.', 'to conduct or carry out business', 'They transact in several currencies daily.'),
  Word('business', 'transparent', 'adj.', 'open and easy to understand or see through', 'Investors demanded a more transparent reporting process.'),
  Word('business', 'treasury', 'n.', 'the funds or financial department of an organization', 'The treasury managed the firm\'s cash and debt.'),
  Word('business', 'trustee', 'n.', 'a person who manages property or funds for others', 'The trustee oversaw the family\'s investments.'),
  Word('business', 'turnkey', 'adj.', 'ready for immediate use upon delivery', 'They sold a turnkey solution that needed no setup.'),
  Word('business', 'tycoon', 'n.', 'a wealthy and powerful business leader', 'The shipping tycoon owned a fleet of tankers.'),
  Word('business', 'unencumbered', 'adj.', 'free of debts or restrictions', 'The property was sold unencumbered by any lien.'),
  Word('business', 'unsecured', 'adj.', 'not backed by collateral', 'Credit cards are a form of unsecured debt.'),
  Word('business', 'untenable', 'adj.', 'impossible to defend or maintain', 'The position became untenable after the scandal.'),
  Word('business', 'uptick', 'n.', 'a small increase or improvement', 'There was a modest uptick in demand last month.'),
  Word('business', 'usury', 'n.', 'the practice of lending at unfairly high interest', 'The lender was accused of usury.'),
  Word('business', 'venture', 'n.', 'a risky business undertaking', 'The new venture attracted bold investors.'),
  Word('business', 'verbatim', 'adv.', 'in exactly the same words', 'The clerk recorded the terms verbatim.'),
  Word('business', 'viable', 'adj.', 'capable of working successfully', 'They needed a viable plan to reach profitability.'),
  Word('business', 'volatile', 'adj.', 'liable to change rapidly and unpredictably', 'The stock proved too volatile for cautious investors.'),
  Word('business', 'voluminous', 'adj.', 'very large in volume or amount', 'The merger generated voluminous paperwork.'),
  Word('business', 'wares', 'n.', 'goods offered for sale', 'The vendor displayed his wares at the market.'),
  Word('business', 'windfall', 'n.', 'an unexpected gain of money', 'The patent payout was a welcome windfall.'),
  Word('business', 'withhold', 'v.', 'to keep back, especially money or information', 'Employers withhold taxes from each paycheck.'),
  Word('business', 'workforce', 'n.', 'all the people employed by an organization', 'The firm trained its entire workforce on the new system.'),
  Word('business', 'writeoff', 'n.', 'an asset or debt cancelled as a loss', 'The bad loan became a complete writeoff.'),
];
