import 'words_data.dart';

const kBusinessExtras = <Word>[
  Word('business', 'revenue', 'n.', 'The total money a business takes in from sales', 'The company posted record revenue in the fourth quarter.'),
  Word('business', 'profit', 'n.', 'What is left after costs are subtracted from revenue', 'They reinvested most of last year\'s profit into product development.'),
  Word('business', 'loss', 'n.', 'When expenses exceed income over a period', 'The startup posted a small loss while it scaled the team.'),
  Word('business', 'equity', 'n.', 'Ownership value in a company after debts', 'Early employees were paid mostly in equity rather than cash.'),
  Word('business', 'debt', 'n.', 'Money a business owes to lenders', 'They paid down debt aggressively after the refinancing.'),
  Word('business', 'asset', 'n.', 'Something a business owns that has value', 'Patents are often the most valuable asset on a tech firm\'s books.'),
  Word('business', 'liability', 'n.', 'A financial obligation a company owes to others', 'Pension promises sit on the balance sheet as a long-term liability.'),
  Word('business', 'dividend', 'n.', 'A share of profits paid out to shareholders', 'The board voted to raise the quarterly dividend by ten percent.'),
  Word('business', 'shareholder', 'n.', 'A person or entity that owns stock in a company', 'Activist shareholders pushed for a leaner cost structure.'),
  Word('business', 'investor', 'n.', 'Someone who puts money into a venture expecting a return', 'A patient investor backed the firm through two rough years.'),
  Word('business', 'invoice', 'n.', 'A bill listing goods or services and amounts owed', 'Accounting flagged three invoices that were past due.'),
  Word('business', 'receivable', 'n.', 'Money owed to a company by its customers', 'The CFO chased a major receivable that had aged ninety days.'),
  Word('business', 'payable', 'n.', 'Money a company owes to its suppliers', 'We stretched payables to manage cash through the slow season.'),
  Word('business', 'ledger', 'n.', 'A record of all financial transactions', 'The audit traced every entry back through the general ledger.'),
  Word('business', 'audit', 'n.', 'A formal review of a company\'s financial records', 'The annual audit turned up two material weaknesses.'),
  Word('business', 'compliance', 'n.', 'The act of following laws and regulations', 'Compliance reviewed the new product before it could launch in Europe.'),
  Word('business', 'fiduciary', 'adj.', 'Bound by trust to act in another party\'s interest', 'Board members have a fiduciary duty to the company\'s owners.'),
  Word('business', 'indemnity', 'n.', 'A promise to cover someone else\'s loss or harm', 'The contract included an indemnity clause for IP infringement.'),
  Word('business', 'warranty', 'n.', 'A promise about a product\'s quality or performance', 'The supplier offered a two-year warranty on every shipment.'),
  Word('business', 'covenant', 'n.', 'A binding promise inside a loan or contract', 'The loan covenant required the firm to keep debt below a set ratio.'),
  Word('business', 'arbitration', 'n.', 'Settling a dispute outside court through a neutral party', 'The contract sent any disagreement to binding arbitration.'),
  Word('business', 'litigation', 'n.', 'The process of taking a dispute to court', 'Litigation dragged on for three years before a settlement.'),
  Word('business', 'tort', 'n.', 'A civil wrong that causes another party harm', 'The plaintiff sued for the tort of negligence after the spill.'),
  Word('business', 'breach', 'n.', 'A failure to honor a contract or duty', 'Late delivery was treated as a material breach of the agreement.'),
  Word('business', 'settlement', 'n.', 'An agreement that ends a dispute, often with payment', 'They reached a quiet settlement before the trial began.'),
  Word('business', 'escrow', 'n.', 'Funds or documents held by a third party until terms are met', 'The buyer wired the deposit into escrow on Friday.'),
  Word('business', 'lien', 'n.', 'A legal claim on property until a debt is paid', 'The bank placed a lien on the warehouse pending repayment.'),
  Word('business', 'collateralize', 'v.', 'To pledge an asset to secure a loan', 'They collateralized the loan with the firm\'s receivables.'),
  Word('business', 'underwrite', 'v.', 'To take on risk in exchange for a fee or premium', 'The bank agreed to underwrite the bond offering.'),
  Word('business', 'syndicate', 'n.', 'A group that pools resources to share a deal\'s risk', 'A syndicate of three banks led the financing.'),
  Word('business', 'tranche', 'n.', 'A portion of a larger investment or loan', 'The senior tranche of the deal got the safest yield.'),
  Word('business', 'debenture', 'n.', 'A long-term loan secured only by the borrower\'s credit', 'The firm raised capital by issuing a ten-year debenture.'),
  Word('business', 'coupon', 'n.', 'The interest rate paid by a bond', 'The new note carried a coupon of four and a half percent.'),
  Word('business', 'yield', 'n.', 'The return earned on an investment, usually as a percent', 'Investors fled to bonds when the yield jumped.'),
  Word('business', 'spread', 'n.', 'The difference between two related prices or rates', 'The bid-ask spread widened during the volatile open.'),
  Word('business', 'basis', 'n.', 'A small unit measuring rate changes, equal to one hundredth of a percent', 'The central bank lifted rates by twenty-five basis points.'),
  Word('business', 'derivative', 'n.', 'A contract whose value comes from another asset', 'Options and futures are the best-known derivative products.'),
  Word('business', 'option', 'n.', 'The right but not the obligation to buy or sell at a set price', 'She exercised her option before it expired worthless.'),
  Word('business', 'warrant', 'n.', 'A long-dated option a company issues on its own stock', 'Investors received warrants alongside the convertible note.'),
  Word('business', 'futures', 'n.', 'Contracts to buy or sell a commodity later at a fixed price', 'Farmers use wheat futures to lock in next season\'s price.'),
  Word('business', 'forward', 'n.', 'A private contract to trade an asset at a future date', 'They hedged the euro exposure with a six-month forward.'),
  Word('business', 'swap', 'n.', 'A deal where two parties exchange cash flows', 'The treasurer used an interest-rate swap to fix the floating cost.'),
  Word('business', 'overlay', 'n.', 'A separate strategy layered over an existing portfolio', 'A currency overlay hedges the international exposure.'),
  Word('business', 'arbitrageur', 'n.', 'A trader who profits from tiny price gaps', 'The arbitrageur made pennies a share on huge volume.'),
  Word('business', 'depth', 'n.', 'How much volume a market can absorb without moving price', 'Thin market depth means even small orders move the quote.'),
  Word('business', 'solvency', 'n.', 'The ability to meet long-term debts', 'Auditors raised doubts about the firm\'s solvency.'),
  Word('business', 'insolvent', 'adj.', 'Unable to pay debts when they come due', 'The retailer filed for bankruptcy after becoming insolvent.'),
  Word('business', 'bankruptcy', 'n.', 'A legal process for handling a company that can\'t pay debts', 'They filed for bankruptcy to reorganize under court protection.'),
  Word('business', 'restructure', 'v.', 'To reorganize a company\'s debts or operations', 'Management chose to restructure rather than liquidate.'),
  Word('business', 'workout', 'n.', 'A negotiated plan to fix troubled debt', 'The bank put the loan into workout instead of seizing assets.'),
  Word('business', 'haircut', 'n.', 'A reduction in the value lenders accept on a claim', 'Bondholders took a thirty percent haircut in the restructuring.'),
  Word('business', 'recapitalize', 'v.', 'To restructure the mix of debt and equity', 'The PE firm recapitalized the business after the buyout.'),
  Word('business', 'leveraged', 'adj.', 'Funded largely with borrowed money', 'It was a heavily leveraged buyout that left the firm thinly capitalized.'),
  Word('business', 'buyout', 'n.', 'The purchase of a controlling stake in a company', 'The management buyout took the company private.'),
  Word('business', 'spinoff', 'n.', 'A new company created from part of a parent', 'The chip division became a spinoff with its own listing.'),
  Word('business', 'carveout', 'n.', 'A business unit sold or separated from its parent', 'The pharma giant announced a carveout of its consumer brands.'),
  Word('business', 'rollup', 'n.', 'Buying many small firms and combining them', 'The investor pursued a rollup of regional dental clinics.'),
  Word('business', 'consolidation', 'n.', 'Combining companies or operations into fewer units', 'Industry consolidation left only three big players.'),
  Word('business', 'acquirer', 'n.', 'The company that buys another in a deal', 'The acquirer paid a thirty percent premium for the shares.'),
  Word('business', 'target', 'n.', 'The company being bought in a deal', 'Lawyers spent weeks combing through the target\'s contracts.'),
  Word('business', 'earnout', 'n.', 'A deal payment based on future performance', 'Half the price came as an earnout tied to next year\'s revenue.'),
  Word('business', 'lockup', 'n.', 'A period after an IPO when insiders cannot sell shares', 'Founders waited out the six-month lockup before any selling.'),
  Word('business', 'prospectus', 'n.', 'A formal document describing an offering to investors', 'The prospectus laid out every risk factor in detail.'),
  Word('business', 'allocation', 'n.', 'How shares are split among investors in an offering', 'Big funds got a heavier allocation than retail.'),
  Word('business', 'roadshow', 'n.', 'A tour to pitch an offering to potential investors', 'The CEO is on a two-week roadshow for the bond deal.'),
  Word('business', 'pitch', 'n.', 'A short presentation to win business or investment', 'Her pitch nailed the problem in the first thirty seconds.'),
  Word('business', 'deck', 'n.', 'A slide presentation used in business meetings', 'Send me the latest deck before tomorrow\'s board call.'),
  Word('business', 'valuation', 'n.', 'A formal estimate of a company\'s worth', 'Their valuation tripled in the latest funding round.'),
  Word('business', 'multiple', 'n.', 'A ratio used to compare value to earnings or sales', 'Software firms trade at a much higher revenue multiple than retailers.'),
  Word('business', 'comparable', 'n.', 'A similar company used to benchmark a valuation', 'We used three public comparables to triangulate the price.'),
  Word('business', 'precedent', 'n.', 'A past deal used as a benchmark', 'The bankers cited a recent precedent transaction in the same sector.'),
  Word('business', 'writedown', 'n.', 'A reduction in the recorded value of an asset', 'A goodwill writedown crushed reported earnings for the quarter.'),
  Word('business', 'intangible', 'n.', 'An asset without physical form, like a brand or patent', 'Brand strength is the firm\'s biggest intangible.'),
  Word('business', 'accretive', 'adj.', 'Adding to a company\'s earnings per share', 'The deal is expected to be accretive within twelve months.'),
  Word('business', 'dilutive', 'adj.', 'Reducing existing earnings or ownership per share', 'Issuing more stock would be dilutive to current holders.'),
  Word('business', 'preferred', 'n.', 'A class of stock with priority over common shares', 'The investor took preferred shares with a liquidation preference.'),
  Word('business', 'common', 'n.', 'The basic class of stock that holds voting rights', 'Founders kept all of their common stock through the round.'),
  Word('business', 'tender', 'n.', 'An offer to buy shares directly from shareholders', 'The raider launched a tender at twelve dollars a share.'),
  Word('business', 'proxy', 'n.', 'Authority given to vote shares on behalf of an owner', 'Activists waged a bitter proxy fight for two board seats.'),
  Word('business', 'quorum', 'n.', 'The minimum attendance needed for a valid vote', 'The meeting couldn\'t start until a quorum was confirmed.'),
  Word('business', 'bylaw', 'n.', 'A rule that governs how a company operates', 'A new bylaw set term limits for board members.'),
  Word('business', 'charter', 'n.', 'The founding legal document of a company', 'They amended the charter to authorize a new share class.'),
  Word('business', 'governance', 'n.', 'The system of rules and oversight inside a company', 'Investors pushed for stronger governance after the scandal.'),
  Word('business', 'directorship', 'n.', 'A seat on a company\'s board of directors', 'She took a directorship at a fintech startup last spring.'),
  Word('business', 'chair', 'n.', 'The person who leads a board of directors', 'The chair called a special session to discuss the offer.'),
  Word('business', 'ceo', 'n.', 'The top executive who runs a company', 'The new ceo started by flattening three layers of management.'),
  Word('business', 'cfo', 'n.', 'The executive in charge of finance', 'The cfo walked analysts through the updated guidance.'),
  Word('business', 'coo', 'n.', 'The executive who oversees daily operations', 'The coo owns the supply chain transformation program.'),
  Word('business', 'cmo', 'n.', 'The executive who leads marketing', 'The cmo unveiled the brand refresh on stage.'),
  Word('business', 'cto', 'n.', 'The executive who leads technology', 'The cto championed the move to a service-oriented architecture.'),
  Word('business', 'cio', 'n.', 'The executive who runs information systems', 'The cio centralized procurement for all software contracts.'),
  Word('business', 'mandate', 'n.', 'A formal instruction from leadership or owners', 'The board gave her a clear mandate to cut costs.'),
  Word('business', 'delegate', 'v.', 'To assign work to someone else to do', 'Good managers delegate so they can focus on strategy.'),
  Word('business', 'escalate', 'v.', 'To pass an issue up to a higher level for action', 'Escalate this to legal if the vendor pushes back again.'),
  Word('business', 'memo', 'n.', 'A short written note that communicates an idea or decision', 'The CEO wrote a memo explaining the new travel policy.'),
  Word('business', 'minutes', 'n.', 'A written record of what happened in a meeting', 'Please send the minutes to anyone who missed the call.'),
  Word('business', 'agenda', 'n.', 'A planned list of items to cover in a meeting', 'The agenda was tight and left no room for off-topic chatter.'),
  Word('business', 'briefing', 'n.', 'A short, focused update for a busy audience', 'The team gave a fifteen-minute briefing to the executive committee.'),
  Word('business', 'cadence', 'n.', 'A regular rhythm for meetings or reporting', 'They set a weekly cadence for cross-functional syncs.'),
  Word('business', 'workflow', 'n.', 'A defined sequence of steps to complete work', 'The new workflow cut approval time in half.'),
  Word('business', 'handoff', 'n.', 'Passing responsibility from one person or team to another', 'A clean handoff between sales and onboarding saves the customer pain.'),
  Word('business', 'kickoff', 'n.', 'A meeting that formally starts a project', 'The vendor flew in for the kickoff workshop.'),
  Word('business', 'scope', 'n.', 'The boundary of what is included in a project', 'Mid-project changes blew up the original scope.'),
  Word('business', 'creep', 'n.', 'Gradual expansion of a project beyond its plan', 'Scope creep is what killed the original timeline.'),
  Word('business', 'gantt', 'n.', 'A bar chart that maps tasks against time', 'The PM keeps a gantt chart pinned in the war room.'),
  Word('business', 'critical', 'adj.', 'On the path that determines a project\'s finish date', 'Any slip on a critical task pushes the entire launch.'),
  Word('business', 'dependency', 'n.', 'A task that must finish before another can start', 'The integration has a hard dependency on the API team.'),
  Word('business', 'blocker', 'n.', 'Something that stops work from moving forward', 'The legal review is the only blocker left on the launch.'),
  Word('business', 'backlog', 'n.', 'A prioritized list of work waiting to be done', 'Engineering grooms the backlog every other Friday.'),
  Word('business', 'burndown', 'n.', 'A chart of work remaining over time', 'The burndown showed the team finishing two days early.'),
  Word('business', 'velocity', 'n.', 'How much work a team completes per cycle', 'Our velocity stabilized once we stopped pulling people across squads.'),
  Word('business', 'capacity', 'n.', 'The amount of work a team can take on', 'We don\'t have the capacity to start a second initiative this quarter.'),
  Word('business', 'staffing', 'n.', 'How people are assigned across initiatives', 'Staffing for the new program is still being worked out.'),
  Word('business', 'utilization', 'n.', 'The share of capacity actually used', 'Consulting firms watch billable utilization like a hawk.'),
  Word('business', 'billable', 'adj.', 'Work that can be charged to a client', 'Internal meetings are not billable hours.'),
  Word('business', 'rate', 'n.', 'The price charged per unit of time or work', 'Their hourly rate jumped after they raised a new fund.'),
  Word('business', 'retainer', 'n.', 'A regular fee paid in advance for ongoing services', 'The firm pays a monthly retainer to outside counsel.'),
  Word('business', 'engagement', 'n.', 'A formal piece of paid client work', 'The consulting engagement runs for twelve weeks.'),
  Word('business', 'scoping', 'n.', 'Defining what an engagement will and won\'t cover', 'A messy scoping call leads to a messy project.'),
  Word('business', 'sow', 'n.', 'A document detailing the work to be done', 'Both sides countersigned the sow before kickoff.'),
  Word('business', 'rfp', 'n.', 'A formal request seeking proposals from vendors', 'They issued an rfp for the new payments platform.'),
  Word('business', 'rfq', 'n.', 'A request asking suppliers for prices on specific items', 'Procurement sent an rfq to five steel mills.'),
  Word('business', 'bidder', 'n.', 'A party that submits a bid for work or assets', 'Five firms emerged as serious bidders for the asset.'),
  Word('business', 'bid', 'n.', 'A formal offer to do work for a stated price', 'Their bid came in twenty percent below the others.'),
  Word('business', 'procurement', 'n.', 'The process of sourcing and buying for a business', 'Procurement standardized vendors across all offices.'),
  Word('business', 'sourcing', 'n.', 'Finding and selecting suppliers', 'They moved sourcing closer to home after the disruption.'),
  Word('business', 'vendor', 'n.', 'A company that supplies goods or services', 'We rate every vendor on quality, speed, and price.'),
  Word('business', 'supplier', 'n.', 'A company that provides inputs further up the chain', 'A single supplier handles all of their custom plastics.'),
  Word('business', 'logistics', 'n.', 'The flow of goods, information, and resources', 'Logistics teams worked overtime through the holiday rush.'),
  Word('business', 'freight', 'n.', 'Goods being moved in bulk', 'Ocean freight rates have finally normalized.'),
  Word('business', 'cargo', 'n.', 'Goods carried by ship, plane, or truck', 'The cargo cleared customs in under an hour.'),
  Word('business', 'manifest', 'n.', 'A list of cargo on a shipment', 'The manifest was missing two pallets at the dock.'),
  Word('business', 'pallet', 'n.', 'A wooden platform that holds goods for shipping', 'Each pallet held forty cases of bottled water.'),
  Word('business', 'sku', 'n.', 'A unique code that identifies a product variant', 'They cut the catalog from two thousand to four hundred skus.'),
  Word('business', 'inventory', 'n.', 'The stock of goods a business holds', 'Excess inventory ties up working capital.'),
  Word('business', 'stockout', 'n.', 'A situation where a product is unavailable for sale', 'A stockout on our hero product cost us the whole weekend.'),
  Word('business', 'reorder', 'v.', 'To buy more stock before it runs out', 'The system reorders when inventory dips below the threshold.'),
  Word('business', 'leadtime', 'n.', 'The time between ordering and receiving goods', 'Asian leadtimes stretched from eight weeks to twenty.'),
  Word('business', 'fulfillment', 'n.', 'The process of getting an order to a customer', 'Their fulfillment network now covers most of the country in a day.'),
  Word('business', 'warehouse', 'n.', 'A building used to store goods', 'The new warehouse triples picking capacity for the region.'),
  Word('business', 'pick', 'v.', 'To gather items in a warehouse to fill an order', 'Workers pick items into totes guided by a wrist scanner.'),
  Word('business', 'pack', 'v.', 'To box up an order before it ships', 'Each station can pack roughly sixty parcels an hour.'),
  Word('business', 'dispatch', 'v.', 'To send a shipment out to a customer', 'They dispatch orders twice a day from the regional hub.'),
  Word('business', 'carrier', 'n.', 'A company that physically moves freight', 'They split volume across three carriers for resilience.'),
  Word('business', 'last-mile', 'adj.', 'Relating to the final delivery to the customer', 'Last-mile costs are the hardest part of e-commerce economics.'),
  Word('business', 'returns', 'n.', 'Goods customers send back after purchase', 'Apparel returns can eat the margin on the original sale.'),
  Word('business', 'reverse', 'adj.', 'Flowing back from customer to seller', 'Reverse logistics is a serious cost center for online retailers.'),
  Word('business', 'cogs', 'n.', 'The direct cost of producing what a company sells', 'Rising cogs squeezed gross profit despite higher prices.'),
  Word('business', 'sga', 'n.', 'Selling, general, and administrative expenses', 'They trimmed sga by consolidating back-office functions.'),
  Word('business', 'accrue', 'v.', 'To record revenue or expense before cash moves', 'You accrue salary expense in the month it\'s earned.'),
  Word('business', 'reconcile', 'v.', 'To match records to confirm they agree', 'The team reconciles bank statements to the ledger every month.'),
  Word('business', 'variance', 'n.', 'The gap between actual and planned numbers', 'A negative variance on travel showed up in March.'),
  Word('business', 'budget', 'n.', 'A plan for spending and earning over a period', 'Marketing came in five percent under budget for the year.'),
  Word('business', 'model', 'v.', 'To build a quantitative projection of business performance', 'We model quarterly revenue using a bottom-up build.'),
  Word('business', 'guidance', 'n.', 'A company\'s public expectations for results', 'The CFO raised full-year guidance on the earnings call.'),
  Word('business', 'earnings', 'n.', 'A company\'s reported profits for a period', 'Earnings beat expectations on stronger services revenue.'),
  Word('business', 'beat', 'v.', 'To exceed what analysts expected', 'They beat on both top and bottom lines this quarter.'),
  Word('business', 'miss', 'v.', 'To fall short of expected results', 'A miss on subscriber growth tanked the stock.'),
  Word('business', 'guide', 'v.', 'To set or update expectations for investors', 'Management guided revenue toward the upper end of the range.'),
  Word('business', 'topline', 'n.', 'Total revenue before any costs are subtracted', 'New products lifted the topline by eleven percent.'),
  Word('business', 'bottomline', 'n.', 'The net profit after all expenses', 'Cost cuts moved straight to the bottomline.'),
  Word('business', 'consensus', 'n.', 'The average expectation among analysts', 'Earnings landed two cents above consensus.'),
  Word('business', 'analyst', 'n.', 'A professional who studies companies and recommends stocks', 'A sell-side analyst upgraded the stock to a buy.'),
  Word('business', 'rating', 'n.', 'A recommendation an analyst puts on a stock or bond', 'The credit rating slipped one notch into speculative territory.'),
  Word('business', 'downgrade', 'v.', 'To lower a rating or recommendation', 'Two agencies downgraded the firm after the missed quarter.'),
  Word('business', 'upgrade', 'v.', 'To raise a rating or recommendation', 'The agency upgraded the bond on improving cash flow.'),
  Word('business', 'outlook', 'n.', 'A forward-looking view on results or conditions', 'Management offered a cautious outlook for the second half.'),
  Word('business', 'headwind', 'n.', 'A force working against business performance', 'Currency was a headwind for international segments.'),
  Word('business', 'tailwind', 'n.', 'A force that helps business performance', 'A weak dollar gave exporters a tailwind.'),
  Word('business', 'macro', 'adj.', 'Related to the broad economy', 'Macro conditions are the biggest swing factor this year.'),
  Word('business', 'micro', 'adj.', 'Related to individual firms or markets', 'On the micro level, the company\'s execution is sharper than ever.'),
  Word('business', 'inflation', 'n.', 'A general rise in prices across the economy', 'Inflation cooled but stayed above the central bank\'s target.'),
  Word('business', 'deflation', 'n.', 'A general drop in prices across the economy', 'Sustained deflation can paralyze consumer spending.'),
  Word('business', 'stagflation', 'n.', 'Slow growth combined with high inflation', 'Policymakers worry that energy shocks could spark stagflation.'),
  Word('business', 'recession', 'n.', 'A meaningful, broad decline in economic activity', 'The recession lasted longer than economists first expected.'),
  Word('business', 'expansion', 'n.', 'A period of growing economic activity', 'The expansion ran for nearly a decade before reversing.'),
  Word('business', 'cycle', 'n.', 'A recurring pattern of expansion and contraction', 'Real estate is famously sensitive to the credit cycle.'),
  Word('business', 'gdp', 'n.', 'The total value of goods and services in an economy', 'Quarterly gdp came in stronger than the consensus call.'),
  Word('business', 'cpi', 'n.', 'A measure of consumer prices over time', 'The cpi print pushed bond yields higher overnight.'),
  Word('business', 'ppi', 'n.', 'A measure of prices producers receive for their output', 'Easing ppi suggests cost pressures are fading.'),
  Word('business', 'fomc', 'n.', 'The committee that sets US monetary policy', 'Markets parsed every word of the fomc statement.'),
  Word('business', 'fed', 'n.', 'The central bank of the United States', 'The fed signaled it would pause hikes at the next meeting.'),
  Word('business', 'tightening', 'n.', 'Raising rates or pulling money out of the economy', 'Quantitative tightening kept upward pressure on yields.'),
  Word('business', 'easing', 'n.', 'Lowering rates or injecting money into the economy', 'Talk of policy easing lifted growth stocks across the board.'),
  Word('business', 'benchmark', 'n.', 'A reference rate or index used for comparison', 'The fund trailed its benchmark for three consecutive years.'),
  Word('business', 'prime', 'n.', 'The benchmark rate banks charge their best customers', 'Variable-rate loans move when the prime rate changes.'),
  Word('business', 'libor', 'n.', 'A retired benchmark rate that priced trillions in debt', 'Most contracts have shifted off libor to newer benchmarks.'),
  Word('business', 'sofr', 'n.', 'A benchmark rate used for many dollar-based loans', 'The loan resets to sofr plus a spread each quarter.'),
  Word('business', 'fx', 'n.', 'Trading or values of foreign currencies', 'Multinationals run a treasury desk just to manage fx risk.'),
  Word('business', 'parity', 'n.', 'A condition where two currencies trade one-for-one', 'The euro briefly slid to parity with the dollar.'),
  Word('business', 'remittance', 'n.', 'Money workers send home from another country', 'Remittance fees fell sharply with new digital options.'),
  Word('business', 'tariff', 'n.', 'A tax on goods crossing a border', 'The new tariff lifted prices on imported electronics.'),
  Word('business', 'quota', 'n.', 'A cap on how much can be imported or exported', 'A steel quota protected domestic mills for years.'),
  Word('business', 'embargo', 'n.', 'An official ban on trade with a country', 'The embargo cut off the firm\'s biggest export market.'),
  Word('business', 'sanction', 'n.', 'A government penalty restricting trade or finance', 'New sanctions blocked any dollar transactions with the bank.'),
  Word('business', 'cartel', 'n.', 'A group of firms that coordinate to limit competition', 'Regulators broke up the cement cartel after a long probe.'),
  Word('business', 'antitrust', 'adj.', 'Designed to stop unfair competition or monopolies', 'Antitrust regulators are reviewing the merger closely.'),
  Word('business', 'monopoly', 'n.', 'A market controlled by a single seller', 'The utility long held a monopoly on residential power.'),
  Word('business', 'oligopoly', 'n.', 'A market dominated by a few large players', 'Mobile networks here form a textbook oligopoly.'),
  Word('business', 'duopoly', 'n.', 'A market controlled by exactly two players', 'The duopoly between the two retailers shaped consumer prices.'),
  Word('business', 'externality', 'n.', 'A side effect a transaction imposes on others', 'Pollution is a classic negative externality of heavy industry.'),
  Word('business', 'subsidy', 'n.', 'A government payment that lowers cost for producers or buyers', 'The subsidy made domestic solar panels far cheaper.'),
  Word('business', 'incentive', 'n.', 'A reward designed to encourage a behavior', 'Tax incentives drew the data center to the region.'),
  Word('business', 'rebate', 'n.', 'A partial refund given after a purchase', 'A mail-in rebate cut the effective price by thirty dollars.'),
  Word('business', 'voucher', 'n.', 'A document redeemable for goods, money, or a discount', 'Each attendee got a voucher for a free coffee at the cafe.'),
  Word('business', 'discount', 'n.', 'A reduction from the listed price', 'Bulk buyers get a discount on every order above a threshold.'),
  Word('business', 'markdown', 'n.', 'A reduction from a product\'s original retail price', 'Aggressive markdowns cleared the seasonal inventory.'),
  Word('business', 'promotion', 'n.', 'A short-term marketing push to lift sales', 'The summer promotion drove a measurable bump in foot traffic.'),
  Word('business', 'campaign', 'n.', 'A coordinated marketing effort with a goal', 'The brand campaign ran across TV, social, and out-of-home.'),
  Word('business', 'creative', 'n.', 'The actual ads, images, and copy used in marketing', 'New creative tested twice as well as the original spot.'),
  Word('business', 'copy', 'n.', 'The written text in advertising or marketing', 'A copywriter tightened every line on the landing page.'),
  Word('business', 'tagline', 'n.', 'A short, memorable phrase that captures a brand', 'The tagline hasn\'t changed in twenty years.'),
  Word('business', 'slogan', 'n.', 'A catchy phrase tied to a campaign or brand', 'Their slogan stuck in every consumer\'s head.'),
  Word('business', 'branding', 'n.', 'The work of shaping how a company is perceived', 'Branding took the lead on the new identity system.'),
  Word('business', 'rebrand', 'v.', 'To overhaul the look and feel of a company', 'They rebranded to shed the old industrial image.'),
  Word('business', 'logo', 'n.', 'A graphic mark that represents a brand', 'The simplified logo works at every size and surface.'),
  Word('business', 'mark', 'n.', 'A protected sign that identifies goods or services', 'The trademark covers both word and logo mark.'),
  Word('business', 'trademark', 'n.', 'A legal protection for a brand identifier', 'The company filed a trademark on the new product name.'),
  Word('business', 'patent', 'n.', 'A government-granted right to a new invention', 'The patent runs for twenty years from the filing date.'),
  Word('business', 'copyright', 'n.', 'A legal right over creative works like text or images', 'Stock photos saved them from a costly copyright fight.'),
  Word('business', 'royalty', 'n.', 'A payment for using someone\'s creative or intellectual property', 'Authors earn a royalty on every printed copy.'),
  Word('business', 'license', 'n.', 'Permission to use property under specific terms', 'They paid a license fee to embed the codec.'),
  Word('business', 'franchise', 'n.', 'A business model where owners run branded local outlets', 'She bought a coffee franchise after leaving corporate.'),
  Word('business', 'franchisee', 'n.', 'A person who operates a franchised business', 'Each franchisee pays a slice of revenue to the parent.'),
  Word('business', 'franchisor', 'n.', 'The company that owns the brand and licenses it out', 'The franchisor mandates standard supplies across all locations.'),
  Word('business', 'territory', 'n.', 'A defined geographic area assigned to a salesperson or partner', 'Each rep owns a clear territory with quotas tied to it.'),
  Word('business', 'goal', 'n.', 'A specific outcome a person or team aims to hit', 'She blew past her sales goal in the second month of the year.'),
  Word('business', 'commission', 'n.', 'A payment tied to sales results', 'Top reps earn most of their pay from commission.'),
  Word('business', 'lead', 'n.', 'A potential customer who has shown interest', 'Marketing handed three hundred fresh leads to sales last week.'),
  Word('business', 'prospect', 'n.', 'A qualified potential customer worth pursuing', 'The rep flew out to meet a strategic prospect.'),
  Word('business', 'qualify', 'v.', 'To check whether a lead is worth pursuing', 'We qualify every lead before booking a demo.'),
  Word('business', 'demo', 'n.', 'A live product walkthrough for a prospect', 'The demo went well and they asked for pricing on the spot.'),
  Word('business', 'discovery', 'n.', 'An early call to understand a prospect\'s needs', 'A solid discovery call sets up the rest of the deal.'),
  Word('business', 'objection', 'n.', 'A concern a prospect raises during a sale', 'The most common objection is price, not feature gaps.'),
  Word('business', 'close', 'v.', 'To finalize a sale and get a signed contract', 'She closed the largest deal in company history last quarter.'),
  Word('business', 'upsell', 'v.', 'To get a customer to buy a more expensive option', 'The team learned to upsell larger seats during renewals.'),
  Word('business', 'crosssell', 'v.', 'To sell another product to an existing customer', 'They crosssell analytics seats into every base contract.'),
  Word('business', 'renewal', 'n.', 'Extending an existing customer contract', 'Renewal rates tell you more than new logo growth.'),
  Word('business', 'netnew', 'n.', 'Growth from existing customers buying more', 'Netnew revenue offset some of last year\'s logo churn.'),
  Word('business', 'newlogo', 'n.', 'A brand-new customer account, in sales lingo', 'They added forty newlogo deals in the enterprise segment.'),
  Word('business', 'onboarding', 'n.', 'Getting a new customer or employee up and running', 'A smooth onboarding lifts every downstream metric.'),
  Word('business', 'csm', 'n.', 'A customer success manager who keeps accounts healthy', 'Each enterprise account is paired with a dedicated csm.'),
  Word('business', 'nps', 'n.', 'A score measuring how likely customers are to recommend a brand', 'Their nps climbed after the support overhaul.'),
  Word('business', 'csat', 'n.', 'A score measuring customer satisfaction with a touchpoint', 'Post-ticket csat is reviewed in every weekly support standup.'),
  Word('business', 'survey', 'n.', 'A set of questions used to gather feedback', 'The annual employee survey drove the new hybrid policy.'),
  Word('business', 'segment', 'n.', 'A defined slice of a market or customer base', 'The premium segment grew twice as fast as the budget one.'),
  Word('business', 'persona', 'n.', 'A fictional profile of a typical customer', 'Every PRD references the small-business persona by name.'),
  Word('business', 'icp', 'n.', 'A profile describing a company\'s ideal customer', 'We rewrote the icp once we hit a real product-market fit.'),
  Word('business', 'fit', 'n.', 'How well a product matches a market or buyer', 'Strong fit means customers pull, not push, the conversation.'),
  Word('business', 'demand', 'n.', 'How much customers want a product at a given price', 'Strong demand let them raise prices twice in a year.'),
  Word('business', 'supply', 'n.', 'How much of a good or service is available', 'Tight supply pushed up spot prices across the region.'),
  Word('business', 'elasticity', 'n.', 'How much demand responds to a price change', 'Luxury goods often show surprising price elasticity.'),
  Word('business', 'price', 'v.', 'To set what a product or service costs', 'They priced the new tier above the old enterprise plan.'),
  Word('business', 'tier', 'n.', 'A pricing level with its own bundle of features', 'The mid tier draws the bulk of new signups.'),
  Word('business', 'bundle', 'n.', 'Several products sold together as one offer', 'A family bundle improved attach rates across the board.'),
  Word('business', 'attach', 'n.', 'The rate at which add-ons sell with a base product', 'Warranty attach is critical to electronics margin.'),
  Word('business', 'subscription', 'n.', 'A recurring payment for ongoing access', 'Subscription revenue smoothed out the seasonal swings.'),
  Word('business', 'recurring', 'adj.', 'Repeating on a regular schedule', 'Investors love a high share of recurring revenue.'),
  Word('business', 'usage', 'n.', 'How much of a service a customer consumes', 'Pricing flips to usage-based above a base allocation.'),
  Word('business', 'metering', 'n.', 'Measuring usage to bill customers accurately', 'Engineering owns the metering pipeline end to end.'),
  Word('business', 'paywall', 'n.', 'A barrier that requires payment to access content', 'The publisher loosened its paywall around big news events.'),
  Word('business', 'freemium', 'adj.', 'Offering a free tier alongside paid plans', 'A freemium funnel feeds the enterprise sales motion.'),
  Word('business', 'trial', 'n.', 'A limited free period to try a product', 'A two-week trial converts at about twenty percent.'),
  Word('business', 'convert', 'v.', 'To turn a visitor or trial user into a paying customer', 'The landing page A/B test helped them convert nine points more visitors.'),
  Word('business', 'attribution', 'n.', 'Assigning credit to the channels that drove a sale', 'Multi-touch attribution gave a clearer view than last-click.'),
  Word('business', 'roas', 'n.', 'Return on ad spend, measured in revenue per dollar', 'They paused any campaign with roas below two.'),
  Word('business', 'cpm', 'n.', 'The cost to show an ad to a thousand people', 'CPM rates climbed steadily through the holiday quarter.'),
  Word('business', 'cpc', 'n.', 'The cost charged for each click on an ad', 'Branded cpc stayed cheap while non-branded soared.'),
  Word('business', 'impression', 'n.', 'One display of an ad to a single viewer', 'The campaign racked up two million impressions in a week.'),
  Word('business', 'reach', 'n.', 'The number of unique people exposed to a message', 'Outdoor ads gave the campaign citywide reach.'),
  Word('business', 'frequency', 'n.', 'How often the average person sees an ad', 'A frequency of three or four is the sweet spot here.'),
  Word('business', 'organic', 'adj.', 'Earned rather than paid through media', 'Most signups still come from organic search.'),
  Word('business', 'paid', 'adj.', 'Driven by media bought from a platform', 'Paid social drove the bulk of trial signups.'),
  Word('business', 'referral', 'n.', 'A new customer brought in by an existing one', 'Half their hires came through internal referral.'),
  Word('business', 'affiliate', 'n.', 'A partner who earns commission for driving sales', 'The affiliate program paid out millions to creators.'),
  Word('business', 'influencer', 'n.', 'A creator who shapes audience purchase behavior', 'A single influencer drove a measurable sales spike.'),
  Word('business', 'seo', 'n.', 'Practices that help a site rank in search results', 'The seo audit found dozens of quick wins.'),
  Word('business', 'sem', 'n.', 'Paid search marketing, mostly on search engines', 'They spend most of their sem budget on brand keywords.'),
  Word('business', 'serp', 'n.', 'The page of results a search engine shows', 'Their snippet now occupies prime serp real estate.'),
  Word('business', 'crm', 'n.', 'Software that tracks customer relationships and deals', 'Reps log every meaningful customer touchpoint in the crm.'),
  Word('business', 'erp', 'n.', 'Software that runs core business operations', 'The erp upgrade took eighteen months and gobbled the IT budget.'),
  Word('business', 'saas', 'n.', 'Software delivered over the internet on subscription', 'Saas pricing typically scales with seats or usage.'),
  Word('business', 'paas', 'n.', 'A platform that hosts and runs applications for customers', 'A paas vendor handles the plumbing so developers focus on code.'),
  Word('business', 'iaas', 'n.', 'On-demand computing resources sold over the internet', 'They run the whole stack on a single iaas provider.'),
  Word('business', 'tenant', 'n.', 'A separate customer account inside a shared system', 'Each tenant\'s data lives in an isolated logical store.'),
  Word('business', 'seat', 'n.', 'A single user license on a software subscription', 'They closed a fifteen-thousand-seat enterprise deal.'),
  Word('business', 'token', 'n.', 'A small unit used to meter access in some software', 'Heavy users burn through token budgets faster.'),
  Word('business', 'platform', 'n.', 'A base that others build products or services on', 'Their platform supports thousands of third-party developers.'),
  Word('business', 'ecosystem', 'n.', 'The network of partners, developers, and customers around a product', 'A healthy ecosystem multiplies a platform\'s value.'),
  Word('business', 'marketplace', 'n.', 'A platform where buyers and sellers meet', 'The marketplace takes a percent on every transaction.'),
  Word('business', 'takerate', 'n.', 'The cut a marketplace keeps from each transaction', 'A higher takerate boosts margin but invites competition.'),
  Word('business', 'gmv', 'n.', 'The total value of goods sold through a marketplace', 'Holiday gmv set a new company record.'),
  Word('business', 'ads', 'n.', 'Paid promotional placements across media', 'A third of revenue comes from ads on the platform.'),
  Word('business', 'adslot', 'n.', 'A piece of ad space a publisher can sell', 'Premium video adslot prices command a steep price.'),
  Word('business', 'placement', 'n.', 'Where an ad appears within an experience', 'The above-the-fold placement is the most expensive on the site.'),
  Word('business', 'targeting', 'n.', 'Choosing who should see an ad or message', 'Behavioral targeting lifted click-through dramatically.'),
  Word('business', 'remarketing', 'n.', 'Showing ads to people who visited before', 'A remarketing flight chased recent cart abandoners.'),
  Word('business', 'cart', 'n.', 'The collection of items a shopper plans to buy online', 'A streamlined cart cut checkout time in half.'),
  Word('business', 'checkout', 'n.', 'The final step where a shopper pays', 'Twenty percent of carts never complete checkout.'),
  Word('business', 'abandonment', 'n.', 'A shopper leaving without completing a purchase', 'Cart abandonment usually peaks at the shipping screen.'),
  Word('business', 'merchandising', 'n.', 'The art of presenting products to drive sales', 'Smart merchandising kept the new collection front and center.'),
  Word('business', 'planogram', 'n.', 'A diagram showing how products are arranged in a store', 'Every store reset to the new planogram on Sunday.'),
  Word('business', 'shelf', 'n.', 'A physical or digital place where products are displayed', 'Premium brands fight for eye-level shelf space.'),
  Word('business', 'foot', 'n.', 'A unit measuring store visits, as in foot traffic', 'Foot traffic recovered after the renovation.'),
  Word('business', 'footprint', 'n.', 'The physical or operational presence of a business', 'They trimmed their retail footprint by closing weaker stores.'),
  Word('business', 'flagship', 'n.', 'A landmark store or product that shows off the brand', 'The flagship in Manhattan anchors the entire brand identity.'),
  Word('business', 'popup', 'n.', 'A temporary retail space used to test or promote a brand', 'The popup ran for six weeks before the lease ended.'),
  Word('business', 'kiosk', 'n.', 'A small, self-contained sales point in a public space', 'They opened a kiosk in every major mall over the holidays.'),
  Word('business', 'concession', 'n.', 'A small business operating inside a larger venue', 'The cosmetics concession outperformed every owned counter.'),
  Word('business', 'lease', 'n.', 'A contract giving use of property for a fixed term', 'The five-year lease included an option to renew.'),
  Word('business', 'sublet', 'v.', 'To rent leased space out to another tenant', 'They sublet two floors after going remote.'),
  Word('business', 'landlord', 'n.', 'The owner who rents out property to tenants', 'The landlord agreed to a rent abatement during the renovation.'),
  Word('business', 'anchor', 'n.', 'A large, long-term tenant that draws traffic to a property', 'The anchor store signed a fifteen-year lease.'),
  Word('business', 'reit', 'n.', 'A company that owns and manages income-producing real estate', 'The reit pays out most of its income as a dividend.'),
  Word('business', 'noi', 'n.', 'Net operating income from a property, before financing', 'Stable noi makes a building easier to refinance.'),
  Word('business', 'caprate', 'n.', 'A measure of a property\'s yield based on income and price', 'Trophy office sold at a sub-five caprate.'),
  Word('business', 'occupancy', 'n.', 'The share of space being rented out', 'Suburban occupancy held up better than downtown.'),
  Word('business', 'vacancy', 'n.', 'Space sitting empty in a property', 'Office vacancy hit a record high in the central business district.'),
  Word('business', 'amenities', 'n.', 'Extras a property offers beyond basic space', 'Class A amenities now include cafes and wellness studios.'),
  Word('business', 'buildout', 'n.', 'The work to finish a leased space for a tenant', 'The buildout took three months and went over budget.'),
  Word('business', 'broker', 'n.', 'An intermediary who arranges deals for clients', 'The broker shopped the property to a short list of buyers.'),
  Word('business', 'finder', 'n.', 'A fee paid to someone who sources a deal or hire', 'A finder fee went to the consultant who introduced the buyer.'),
  Word('business', 'deposit', 'n.', 'Money paid upfront to secure a deal or purchase', 'The buyer wired the deposit pending the inspection.'),
  Word('business', 'closing', 'n.', 'The event at which a deal is finalized', 'Closing took place over a long afternoon at the lawyer\'s office.'),
  Word('business', 'contingency', 'n.', 'A condition that must be met before a deal goes through', 'The offer carried a financing contingency.'),
  Word('business', 'appraisal', 'n.', 'A professional estimate of an asset\'s value', 'The appraisal came in below the agreed price.'),
  Word('business', 'inspection', 'n.', 'A formal check of property condition before a deal', 'The inspection turned up an old roof leak.'),
  Word('business', 'title', 'n.', 'Legal ownership of a property or asset', 'The title company cleared a stray lien before closing.'),
  Word('business', 'deed', 'n.', 'A signed document transferring ownership of property', 'They recorded the deed the morning after closing.'),
  Word('business', 'mortgage', 'n.', 'A loan secured by real estate', 'They refinanced the mortgage when rates dipped.'),
  Word('business', 'amortization', 'n.', 'Paying down a loan with regular installments', 'Most of the early payments are interest, not amortization.'),
  Word('business', 'principal', 'n.', 'The original amount of a loan, not counting interest', 'They paid down principal aggressively in the final year.'),
  Word('business', 'refinance', 'v.', 'To replace an old loan with a new one on better terms', 'They refinanced to lock in a longer fixed rate.'),
  Word('business', 'foreclosure', 'n.', 'A lender taking property after a borrower defaults', 'A flood of foreclosures hit the market that fall.'),
  Word('business', 'default', 'v.', 'To fail to make required payments', 'The borrower defaulted and the bank stepped in.'),
  Word('business', 'forbearance', 'n.', 'A temporary pause on required payments', 'The lender offered forbearance during the storm cleanup.'),
  Word('business', 'rollover', 'n.', 'Renewing a debt or position when it matures', 'A wave of rollover risk loomed on the maturity wall.'),
  Word('business', 'maturity', 'n.', 'The date when a debt becomes due', 'The bond hits maturity in three more years.'),
  Word('business', 'managingdirector', 'n.', 'A senior leader who runs a business unit or office', 'The new managingdirector reorganized the regional team.'),
  Word('business', 'partner', 'n.', 'A senior owner in a professional services firm', 'She made partner at the consultancy after eight years.'),
  Word('business', 'associate', 'n.', 'A junior professional in a firm', 'Associates rotate through three groups before specializing.'),
  Word('business', 'junior', 'n.', 'A worker early in their career path', 'Juniors at the bank work brutal hours their first year.'),
  Word('business', 'intern', 'n.', 'A short-term worker, often a student', 'The summer intern shipped a tool the senior team still uses.'),
  Word('business', 'apprentice', 'n.', 'A learner training under a skilled worker', 'The apprentice graduated to journeyman after two years.'),
  Word('business', 'mentor', 'n.', 'A more experienced person who guides another\'s career', 'Her mentor pushed her to take the stretch role.'),
  Word('business', 'sponsor', 'n.', 'A senior leader who actively advocates for someone', 'A sponsor is more valuable than a mentor for promotions.'),
  Word('business', 'tenure', 'n.', 'How long someone has been in a role or organization', 'Tenure on the team averaged nearly seven years.'),
  Word('business', 'raise', 'n.', 'An increase in pay for the same role', 'Her raise was announced alongside the move to a senior title.'),
  Word('business', 'demotion', 'n.', 'Moving down to a lower role at work', 'A quiet demotion is sometimes used to manage someone out.'),
  Word('business', 'regret', 'n.', 'The kind of departure a company wishes it could have prevented', 'Regret departures from senior engineering rose sharply.'),
  Word('business', 'turnover', 'n.', 'The rate at which employees leave and are replaced', 'High turnover in support points to a deeper culture problem.'),
  Word('business', 'recruiter', 'n.', 'A person who finds and screens candidates', 'A good recruiter is worth their weight in offers.'),
  Word('business', 'headhunt', 'v.', 'To recruit talent directly, often from a competitor', 'They headhunted a senior leader away from a rival.'),
  Word('business', 'screening', 'n.', 'Filtering applicants before deeper interviews', 'Phone screening cuts the slate down to a handful.'),
  Word('business', 'interview', 'n.', 'A meeting to evaluate a candidate for a role', 'The onsite interview ran for most of the day.'),
  Word('business', 'panel', 'n.', 'A group that interviews a candidate together', 'A four-person panel rates each candidate on the same rubric.'),
  Word('business', 'rubric', 'n.', 'A set of criteria used to evaluate candidates or work', 'The hiring rubric scored ownership and craft most heavily.'),
  Word('business', 'offer', 'n.', 'A proposal of pay and terms to a candidate', 'The candidate accepted the offer the same day.'),
  Word('business', 'compensation', 'n.', 'The total pay and benefits an employee receives', 'Compensation includes salary, bonus, and equity.'),
  Word('business', 'salary', 'n.', 'A fixed yearly pay amount for a role', 'Base salary is just part of the overall package.'),
  Word('business', 'bonus', 'n.', 'Extra pay tied to performance or outcomes', 'Annual bonus pools shrank after the weak quarter.'),
  Word('business', 'rsu', 'n.', 'A stock grant that vests over time', 'A chunk of the offer came as rsus on a four-year vest.'),
  Word('business', 'stipend', 'n.', 'A small regular payment for a specific purpose', 'Each employee gets a learning stipend every year.'),
  Word('business', 'allowance', 'n.', 'A budget given to cover specific expenses', 'The relocation allowance covered moving and storage costs.'),
  Word('business', 'perk', 'n.', 'A small benefit beyond regular pay', 'Free lunch is the perk everyone misses most.'),
  Word('business', 'benefits', 'n.', 'Non-cash items that come with employment', 'Their benefits package is competitive for the industry.'),
  Word('business', 'pension', 'n.', 'A retirement plan that pays out over time', 'Old-style pension plans are rare in tech.'),
  Word('business', '401k', 'n.', 'A common US employer-sponsored retirement plan', 'The 401k match vests over four years.'),
  Word('business', 'vacation', 'n.', 'Paid time off from work', 'Unused vacation paid out when she left the company.'),
  Word('business', 'sabbatical', 'n.', 'An extended paid leave from regular work', 'She took a three-month sabbatical to travel and write.'),
  Word('business', 'remote', 'adj.', 'Working from somewhere other than a central office', 'The role is fully remote with quarterly offsites.'),
  Word('business', 'hybrid', 'adj.', 'Mixing remote and in-office work', 'The hybrid policy requires three days a week onsite.'),
  Word('business', 'offsite', 'n.', 'A team gathering held away from the office', 'The leadership offsite shaped next year\'s plan.'),
  Word('business', 'onsite', 'adj.', 'Taking place at the company\'s physical location', 'Final interviews are always onsite at headquarters.'),
  Word('business', 'allhands', 'n.', 'A company-wide meeting for everyone to attend', 'The CEO answered tough questions at the monthly allhands.'),
  Word('business', 'townhall', 'n.', 'An open meeting where leaders take questions', 'The townhall format encourages frank conversation.'),
  Word('business', 'review', 'n.', 'A formal evaluation of someone\'s performance', 'The mid-year review surfaced a few development gaps.'),
  Word('business', 'feedback', 'n.', 'Information about how someone is performing', 'Direct feedback delivered with care lands the best.'),
  Word('business', 'calibration', 'n.', 'A group review to align ratings across managers', 'Calibration helps prevent grade inflation across teams.'),
  Word('business', 'pip', 'n.', 'A formal performance improvement plan', 'A pip is meant to set clear expectations, not just exit someone.'),
  Word('business', 'exit', 'n.', 'An employee\'s departure from the company', 'Every exit interview goes to a central HR team.'),
  Word('business', 'offboarding', 'n.', 'The process of a person leaving an organization', 'Tight offboarding protects company data on the way out.'),
  Word('business', 'noncompete', 'n.', 'A clause restricting work for rivals after leaving', 'Many states have curbed how strict a noncompete can be.'),
  Word('business', 'nondisclosure', 'n.', 'An agreement to keep certain information secret', 'Each contractor signs a nondisclosure before they see the roadmap.'),
  Word('business', 'whistleblower', 'n.', 'An insider who reports wrongdoing', 'A whistleblower triggered the regulator\'s investigation.'),
  Word('business', 'harassment', 'n.', 'Unwanted behavior that creates a hostile workplace', 'The training reminds managers how to handle harassment complaints.'),
  Word('business', 'discrimination', 'n.', 'Treating people unfairly based on personal traits', 'The lawsuit alleged systemic discrimination in pay.'),
  Word('business', 'diversity', 'n.', 'A mix of backgrounds and perspectives in a workforce', 'Diversity numbers in leadership shifted slowly over the decade.'),
  Word('business', 'inclusion', 'n.', 'Practices that make all employees feel they belong', 'Inclusion goes beyond who is in the room to who actually gets heard.'),
  Word('business', 'fairness', 'n.', 'Treatment that accounts for different needs and contexts', 'A fairness audit found pay gaps in two job families.'),
  Word('business', 'union', 'n.', 'An organized group of workers that negotiates collectively', 'The union pushed for a higher base wage at the plant.'),
  Word('business', 'strike', 'n.', 'A coordinated stoppage of work to press demands', 'A two-week strike shut down rail traffic on the coast.'),
  Word('business', 'bargaining', 'n.', 'Negotiating between an employer and a labor group', 'Collective bargaining wrapped up after eight late-night sessions.'),
  Word('business', 'contractor', 'n.', 'A worker hired on a temporary, non-employee basis', 'A small army of contractors built the new platform.'),
  Word('business', 'freelancer', 'n.', 'An independent worker who takes on short projects', 'A freelancer designed the icon set in a weekend.'),
  Word('business', 'gig', 'n.', 'A short-term, often app-based piece of work', 'The gig economy reshaped how people earn on the side.'),
  Word('business', 'wage', 'n.', 'Pay based on hours worked', 'They raised the starting wage by two dollars an hour.'),
  Word('business', 'overtime', 'n.', 'Hours worked beyond the standard schedule', 'Hourly staff earn overtime past forty hours a week.'),
  Word('business', 'timesheet', 'n.', 'A log of hours worked, used for billing or pay', 'Consultants submit a timesheet at the end of every week.'),
  Word('business', 'shift', 'n.', 'A scheduled block of working hours', 'The night shift handles the heaviest distribution runs.'),
  Word('business', 'rota', 'n.', 'A roster showing who works which shifts', 'A balanced rota keeps weekend coverage fair.'),
  Word('business', 'productivity', 'n.', 'Output produced per unit of input or time', 'Productivity rose after the workflow tools rolled out.'),
  Word('business', 'efficiency', 'n.', 'Producing more with less waste', 'The efficiency program shaved eight points off operating costs.'),
  Word('business', 'lean', 'adj.', 'Run with minimal waste and overhead', 'The lean startup approach favors fast learning over big plans.'),
  Word('business', 'sixsigma', 'n.', 'A disciplined approach to reducing process defects', 'Sixsigma belts run small projects across the factory.'),
  Word('business', 'kaizen', 'n.', 'A culture of small, continuous improvements', 'Kaizen turned a stale process into a daily practice.'),
  Word('business', 'kanban', 'n.', 'A visual system for managing work in flight', 'A kanban board on the wall keeps the team aligned.'),
  Word('business', 'wip', 'n.', 'Work in progress, not yet finished', 'Capping wip per person sped up overall throughput.'),
  Word('business', 'throughput', 'n.', 'How much work moves through a system in a time', 'Throughput doubled after the bottleneck was relieved.'),
  Word('business', 'bottleneck', 'n.', 'A step that limits overall flow', 'Quality review was the bottleneck in the release process.'),
  Word('business', 'cycletime', 'n.', 'The time it takes to complete one unit of work', 'Cycletime dropped from twelve days to four.'),
  Word('business', 'turnaround', 'n.', 'How quickly work moves from request to delivery', 'Long turnaround is the biggest customer complaint.'),
  Word('business', 'jit', 'n.', 'A strategy of producing or buying only when needed', 'Just-in-time, often shortened to jit, slashes inventory costs.'),
  Word('business', 'mrp', 'n.', 'Software that plans materials needed for production', 'The mrp module schedules raw material orders weeks out.'),
  Word('business', 'bom', 'n.', 'A list of materials needed to build a product', 'Each finished unit ties back to a detailed bom.'),
  Word('business', 'qc', 'n.', 'Quality control, the checks that catch defects', 'Qc flagged a batch with a faulty plastic component.'),
  Word('business', 'qa', 'n.', 'Quality assurance, the processes that prevent defects', 'Qa rolled out new test scripts ahead of the launch.'),
  Word('business', 'recall', 'n.', 'Pulling a defective product back from customers', 'The recall covered every unit shipped over six months.'),
  Word('business', 'defect', 'n.', 'A flaw that makes a product unfit for use', 'A subtle defect slipped past the line for weeks.'),
  Word('business', 'passrate', 'n.', 'The share of output that meets quality standards', 'Factory passrate rose after the new tooling went in.'),
  Word('business', 'scrap', 'n.', 'Material discarded because it can\'t be used', 'Scrap costs eat into margin on tight-tolerance parts.'),
  Word('business', 'rework', 'n.', 'Fixing a defective item rather than discarding it', 'High rework rates point to upstream quality issues.'),
  Word('business', 'examine', 'v.', 'To formally review records or operations', 'Internal teams examine each plant on a rolling schedule.'),
  Word('business', 'inspect', 'v.', 'To examine items or work for problems', 'A team will inspect every line before reopening.'),
  Word('business', 'cert', 'n.', 'A certification proving a standard is met', 'Their iso cert was renewed for another three years.'),
  Word('business', 'iso', 'n.', 'A widely used set of international quality standards', 'Iso certification is table stakes for industrial customers.'),
  Word('business', 'standard', 'n.', 'An agreed level of quality or practice', 'The new safety standard tightened tolerances across the line.'),
  Word('business', 'spec', 'n.', 'Detailed requirements that define a product', 'A clear spec saved weeks of back-and-forth with the vendor.'),
  Word('business', 'prd', 'n.', 'A product requirements document for engineering teams', 'The prd lists every must-have for v1.'),
  Word('business', 'theme', 'n.', 'A multi-quarter direction grouping a set of investments', 'Each engineering theme rolls up a handful of related projects.'),
  Word('business', 'feature', 'n.', 'A capability of a product that customers can use', 'The new feature went into a slow rollout.'),
  Word('business', 'release', 'n.', 'A version of a product made available to users', 'The release notes ran for several pages.'),
  Word('business', 'rollout', 'n.', 'The gradual introduction of a change to users', 'A phased rollout limited the blast radius of any bug.'),
  Word('business', 'launch', 'v.', 'To introduce a new product or feature to market', 'They plan to launch in three new countries this quarter.'),
  Word('business', 'beta', 'n.', 'An early test version released to a limited audience', 'The beta program shaped the final polish.'),
  Word('business', 'ga', 'n.', 'General availability, when a product is open to everyone', 'The feature moves to ga next Tuesday.'),
  Word('business', 'sunset', 'v.', 'To phase out a product or feature', 'They will sunset the legacy plan over the next six months.'),
  Word('business', 'eol', 'n.', 'End of life, when support for a product ends', 'The hardware hit eol two years ago.'),
  Word('business', 'sla', 'n.', 'A formal promise about service performance', 'They missed the uptime sla and issued credits.'),
  Word('business', 'uptime', 'n.', 'The share of time a service is available', 'They report four-nines uptime across all regions.'),
  Word('business', 'outage', 'n.', 'A period when a service is unavailable', 'A short outage cascaded across several downstream tools.'),
  Word('business', 'incident', 'n.', 'An unplanned disruption to normal service', 'Every incident gets a written postmortem.'),
  Word('business', 'postmortem', 'n.', 'A review of what went wrong and what to fix', 'The postmortem turned up three contributing factors.'),
  Word('business', 'runbook', 'n.', 'A document with steps for handling a known issue', 'A solid runbook saved precious minutes during the outage.'),
  Word('business', 'oncall', 'n.', 'A rotation for responding to urgent issues', 'The oncall engineer paged at 3 a.m. for a payments alert.'),
  Word('business', 'escalation', 'n.', 'Passing an issue to a higher level for handling', 'Severe incidents follow a clear escalation path.'),
  Word('business', 'ticket', 'n.', 'A logged request for support or work', 'The support queue had three hundred open tickets that morning.'),
  Word('business', 'queue', 'n.', 'A waiting line of items to be worked on', 'The queue grew faster than the team could clear it.'),
  Word('business', 'breachclock', 'n.', 'The countdown until a service promise is missed', 'Tickets older than the breachclock window get auto-escalated.'),
  Word('business', 'tier1', 'n.', 'The first level of support that handles common requests', 'Tier1 deflects most issues without escalating.'),
  Word('business', 'deflection', 'n.', 'Resolving an issue without involving a human agent', 'Better help docs lift deflection across the board.'),
  Word('business', 'chatbot', 'n.', 'An automated agent that handles customer messages', 'A smart chatbot now handles half of routine inquiries.'),
  Word('business', 'ivr', 'n.', 'A phone menu that routes callers using prompts', 'A clean ivr menu reduces caller drop-off.'),
  Word('business', 'callcenter', 'n.', 'A facility that handles inbound and outbound calls', 'The callcenter shifted to remote agents permanently.'),
  Word('business', 'bpo', 'n.', 'Outsourcing a business process to a third party', 'They moved billing operations to a bpo partner overseas.'),
  Word('business', 'offshore', 'v.', 'To move work to a lower-cost country', 'They offshored part of QA without losing quality.'),
  Word('business', 'nearshore', 'v.', 'To move work to a nearby lower-cost country', 'They nearshored development to keep time zones aligned.'),
  Word('business', 'onshore', 'adj.', 'Located in the company\'s home country', 'Sensitive work stayed onshore for compliance reasons.'),
  Word('business', 'outsource', 'v.', 'To hire an outside firm to do work', 'They outsourced payroll to focus on the core business.'),
  Word('business', 'insource', 'v.', 'To bring outsourced work back in-house', 'They insourced design after a string of mediocre vendors.'),
  Word('business', 'consultant', 'n.', 'A paid outside expert who advises a business', 'The consultant ran a six-week assessment of the org.'),
  Word('business', 'activity', 'n.', 'A user\'s actions inside a product', 'Daily activity is the metric the product team obsesses over.'),
  Word('business', 'stickiness', 'n.', 'How regularly users come back to a product', 'Stickiness improved once the notification logic was reworked.'),
  Word('business', 'dau', 'n.', 'Daily active users of a product', 'Dau crossed a million for the first time last week.'),
  Word('business', 'mau', 'n.', 'Monthly active users of a product', 'They report mau alongside revenue every quarter.'),
  Word('business', 'wau', 'n.', 'Weekly active users of a product', 'Wau is a less noisy signal than dau for some products.'),
  Word('business', 'powerlaw', 'n.', 'A distribution where a few items dominate the rest', 'Marketplace economics often follow a brutal powerlaw.'),
  Word('business', 'longtail', 'n.', 'Many small items adding up alongside a few hits', 'The longtail of niche titles drove half of the catalog\'s revenue.'),
  Word('business', 'flywheel', 'n.', 'A self-reinforcing loop that builds momentum', 'Every new seller makes the flywheel spin a little faster.'),
  Word('business', 'network', 'n.', 'An effect where each new user makes a product more valuable', 'Strong network effects are hard for rivals to replicate.'),
  Word('business', 'lockin', 'n.', 'Conditions that make it hard for customers to switch', 'Data gravity creates real lockin for enterprise customers.'),
  Word('business', 'switching', 'n.', 'The cost or friction of moving to a competitor', 'High switching costs protect installed-base businesses.'),
  Word('business', 'incumbentadv', 'n.', 'The structural edge that established firms enjoy', 'Distribution is the deepest incumbentadv in this market.'),
  Word('business', 'firstmover', 'n.', 'A company that enters a market before others', 'Being a firstmover does not guarantee winning the market.'),
  Word('business', 'fastfollower', 'n.', 'A firm that learns from pioneers and improves on them', 'A nimble fastfollower can out-execute a sloppy pioneer.'),
  Word('business', 'whitespace', 'n.', 'An unserved or underserved part of a market', 'The team found whitespace in mid-market healthcare.'),
  Word('business', 'beachhead', 'n.', 'A focused initial market used to enter a larger one', 'They picked law firms as their beachhead segment.'),
  Word('business', 'wedge', 'n.', 'A narrow initial use case that opens a bigger door', 'A simple time-tracker was the wedge into bigger workflows.'),
  Word('business', 'crossing', 'n.', 'Moving a product from early adopters to mainstream buyers', 'Crossing the chasm is where many promising products stall.'),
  Word('business', 'chasm', 'n.', 'A tough gap between early adopters and the mainstream', 'They prepared for the chasm with a fresh sales playbook.'),
  Word('business', 'playbook', 'n.', 'A documented set of steps that work for a situation', 'The enterprise playbook codifies what their best reps already do.'),
  Word('business', 'motion', 'n.', 'A repeatable approach to selling or marketing', 'Their sales motion blends self-serve with strategic accounts.'),
  Word('business', 'selfserve', 'adj.', 'Designed for customers to buy without sales help', 'A polished selfserve flow drives most low-end signups.'),
  Word('business', 'highvelocity', 'adj.', 'Selling with short cycles and many small deals', 'Their highvelocity team closes dozens of deals each week.'),
  Word('business', 'fieldsales', 'n.', 'Selling done in person at customer sites', 'Fieldsales reps work the largest accounts in their territory.'),
  Word('business', 'inside', 'n.', 'Selling done over phone, email, and video', 'Inside sales handles the broad middle of the market.'),
  Word('business', 'enabler', 'n.', 'A person or system that helps sellers be more effective', 'Sales enablement built a fresh objection-handling guide.'),
  Word('business', 'enablement', 'n.', 'The function that equips a sales team with tools and training', 'Enablement rolled out a new pitch deck this morning.'),
  Word('business', 'forecasting', 'n.', 'Predicting what sales will close in a given period', 'Forecasting got tighter once deal stages were standardized.'),
  Word('business', 'commit', 'n.', 'The deals a rep promises to close in a period', 'Her commit number was below quota for the first time.'),
  Word('business', 'bestcase', 'n.', 'A more aggressive scenario for what could close', 'The bestcase scenario assumed two stretch deals would land.'),
  Word('business', 'sandbag', 'v.', 'To set targets low so they\'re easier to beat', 'Some reps sandbag at the start of the quarter on purpose.'),
  Word('business', 'pulledforward', 'adj.', 'Pulled in from a future period to hit current numbers', 'A pulledforward deal can leave next quarter looking thin.'),
  Word('business', 'discounting', 'n.', 'Cutting price to win a deal', 'Heavy discounting at quarter end erodes overall margin.'),
  Word('business', 'tradeoff', 'n.', 'A compromise given to close a negotiation', 'They won a longer term in exchange for a price tradeoff.'),
  Word('business', 'walkaway', 'n.', 'The worst deal one side will still accept', 'Knowing your walkaway keeps you from caving under pressure.'),
  Word('business', 'batna', 'n.', 'Your best option if a negotiation fails', 'A strong batna lets you negotiate from a position of strength.'),
  Word('business', 'redline', 'v.', 'To mark up a contract with proposed changes', 'Counsel redlined the master agreement overnight.'),
  Word('business', 'msa', 'n.', 'A master agreement that governs ongoing work', 'New projects ride under the existing msa.'),
  Word('business', 'evergreen', 'adj.', 'Renewing automatically until canceled', 'The contract was evergreen with sixty days\' notice to terminate.'),
];
