import 'words_data.dart';

const kCuisineExtras = <Word>[
  Word('cuisine', 'simmer', 'v.', 'To cook gently just below a boil', 'Let the stew simmer for an hour until the lamb is fork-tender.'),
  Word('cuisine', 'blacken', 'v.', 'To coat in spices and sear until charred', 'Paul Prudhomme made blackened redfish a Cajun signature dish.'),
  Word('cuisine', 'char', 'v.', 'To scorch the surface for smoky flavor', 'Char the scallions directly over the gas flame for a smoky bite.'),
  Word('cuisine', 'roast', 'v.', 'To cook with dry heat in an oven', 'Roast the chicken at 425 until the juices run clear.'),
  Word('cuisine', 'grill', 'v.', 'To cook over open flame or hot grates', 'Grill the swordfish four minutes a side and squeeze a lemon over it.'),
  Word('cuisine', 'broil', 'v.', 'To cook with intense heat from above', 'Broil the gratin until the top is bubbling and golden.'),
  Word('cuisine', 'steam', 'v.', 'To cook in vapor above boiling liquid', 'Steam the dumplings ten minutes in a bamboo basket.'),
  Word('cuisine', 'parboil', 'v.', 'To partially cook in boiling water', 'Parboil the potatoes before crisping them in duck fat.'),
  Word('cuisine', 'scald', 'v.', 'To heat liquid just to the point of steaming', 'Scald the milk before whisking it into the custard base.'),
  Word('cuisine', 'flambé', 'v.', 'To set alight with spirits for flavor and show', 'The waiter flambéed the crêpes Suzette right at our table.'),
  Word('cuisine', 'brine', 'v.', 'To soak in salt water for moisture and seasoning', 'Brine the turkey overnight and it will roast up juicy.'),
  Word('cuisine', 'pickle', 'v.', 'To preserve in vinegar or brine', 'I pickle a jar of red onions every week for tacos.'),
  Word('cuisine', 'cold-smoke', 'v.', 'To smoke at low temperature without cooking', 'They cold-smoke the salmon over alder for a Scandinavian style.'),
  Word('cuisine', 'sous vide', 'n.', 'Cooking sealed in a precise temperature water bath', 'The kitchen does the duck sous vide before crisping the skin.'),
  Word('cuisine', 'spatchcock', 'v.', 'To butterfly poultry by removing the backbone', 'Spatchcock the chicken so it lies flat and roasts evenly.'),
  Word('cuisine', 'deep-fry', 'v.', 'To cook fully submerged in hot oil', 'Deep-fry the calamari in batches so the oil stays hot.'),
  Word('cuisine', 'shallow-fry', 'v.', 'To fry in a thin layer of oil', 'Shallow-fry the schnitzel until each side is golden brown.'),
  Word('cuisine', 'stir-fry', 'v.', 'To toss quickly over high heat in a wok', 'Stir-fry the bok choy with garlic in under two minutes.'),
  Word('cuisine', 'pan-roast', 'v.', 'To start on the stove then finish in the oven', 'Pan-roast the halibut so the skin stays crisp.'),
  Word('cuisine', 'griddle', 'v.', 'To cook on a flat hot iron surface', 'They griddle the smash burgers thin and lacy at the edges.'),
  Word('cuisine', 'mother sauce', 'n.', 'One of five classic French base sauces', 'Béchamel is the mother sauce behind any good mac and cheese.'),
  Word('cuisine', 'béchamel', 'n.', 'A white sauce of milk thickened with roux', 'A proper lasagna alternates ragù with rich béchamel.'),
  Word('cuisine', 'espagnole', 'n.', 'A brown sauce built on dark roux and stock', 'Espagnole is the backbone for many classical brown sauces.'),
  Word('cuisine', 'hollandaise', 'n.', 'An emulsion of butter and egg yolk with lemon', 'Eggs Benedict lives or dies by the hollandaise.'),
  Word('cuisine', 'béarnaise', 'n.', 'Hollandaise flavored with tarragon and shallot', 'Béarnaise is the only sauce a good ribeye really needs.'),
  Word('cuisine', 'tomate', 'n.', 'The classical French mother sauce based on tomato', 'Sauce tomate is the foundation under countless pasta dishes.'),
  Word('cuisine', 'remoulade', 'n.', 'A tangy mayonnaise-based sauce with capers and herbs', 'A spoon of remoulade lifts the crab cake beautifully.'),
  Word('cuisine', 'aioli', 'n.', 'A garlicky Provençal emulsion of oil and yolk', 'The fries arrived with a saffron aioli for dipping.'),
  Word('cuisine', 'romesco', 'n.', 'A Catalan sauce of roasted peppers and nuts', 'Smear the plate with romesco before laying down the lamb.'),
  Word('cuisine', 'chimichurri', 'n.', 'An Argentine herb sauce of parsley, garlic, and vinegar', 'No grilled steak in Buenos Aires comes without chimichurri.'),
  Word('cuisine', 'salsa verde', 'n.', 'A green sauce of herbs, capers, and oil', 'Italian salsa verde works on poached fish or boiled meats.'),
  Word('cuisine', 'pesto', 'n.', 'A pounded sauce of basil, pine nuts, and cheese', 'Genoese pesto belongs on trofie or trenette pasta.'),
  Word('cuisine', 'gremolata', 'n.', 'A topping of lemon zest, garlic, and parsley', 'Finish the osso buco with a generous spoon of gremolata.'),
  Word('cuisine', 'mostarda', 'n.', 'An Italian fruit relish flavored with mustard oil', 'Mostarda di Cremona is a classic alongside boiled meats.'),
  Word('cuisine', 'sofrito', 'n.', 'A slow-cooked base of onion, pepper, and tomato', 'Every Puerto Rican kitchen starts dinner with sofrito in the pan.'),
  Word('cuisine', 'soffritto', 'n.', 'The Italian aromatic base of onion, carrot, and celery', 'A patient soffritto is the soul of a good ragù.'),
  Word('cuisine', 'mirin', 'n.', 'A sweet Japanese rice wine for cooking', 'A splash of mirin balances the salt in the teriyaki glaze.'),
  Word('cuisine', 'sake', 'n.', 'A Japanese fermented rice beverage', 'Warm sake suits a cold winter izakaya night.'),
  Word('cuisine', 'dashi', 'n.', 'A Japanese stock of kombu and bonito flakes', 'Good miso soup begins with a fresh pot of dashi.'),
  Word('cuisine', 'kombu', 'n.', 'A dried kelp used to make dashi', 'Steep the kombu in cold water for an hour before heating.'),
  Word('cuisine', 'bonito', 'n.', 'Dried, smoked, and shaved tuna flakes', 'Bonito flakes dance on top of hot okonomiyaki.'),
  Word('cuisine', 'katsuobushi', 'n.', 'Dried fermented skipjack tuna shaved into flakes', 'Katsuobushi gives dashi its deep, smoky umami backbone.'),
  Word('cuisine', 'miso', 'n.', 'A fermented soybean paste used as a seasoning', 'White miso adds sweet umami to a salmon glaze.'),
  Word('cuisine', 'shoyu', 'n.', 'Japanese-style brewed soy sauce', 'A dash of shoyu seasons the broth without overpowering the noodles.'),
  Word('cuisine', 'tamari', 'n.', 'A wheat-free Japanese soy sauce', 'I keep tamari on hand for the gluten-free guests.'),
  Word('cuisine', 'ponzu', 'n.', 'A citrusy Japanese soy-based sauce', 'Dip the seared tuna in ponzu and watch it disappear.'),
  Word('cuisine', 'yuzu', 'n.', 'A fragrant Japanese citrus fruit', 'A few drops of yuzu transform a plain vinaigrette.'),
  Word('cuisine', 'shiso', 'n.', 'A minty Japanese herb related to perilla', 'Wrap the tartare in a shiso leaf for one perfect bite.'),
  Word('cuisine', 'wasabi', 'n.', 'A pungent green Japanese horseradish', 'Real wasabi is grated fresh from the rhizome on a sharkskin board.'),
  Word('cuisine', 'nori', 'n.', 'Dried sheets of edible seaweed', 'Toast the nori briefly to bring out its briny flavor.'),
  Word('cuisine', 'panko', 'n.', 'Light, flaky Japanese-style breadcrumbs', 'Panko gives the cutlet a shattering crisp crust.'),
  Word('cuisine', 'tempura', 'n.', 'A light Japanese batter-fried preparation', 'The shrimp tempura comes out lacy and ungreasy.'),
  Word('cuisine', 'donburi', 'n.', 'A Japanese rice bowl topped with savory ingredients', 'Order the eel donburi if you want a real treat.'),
  Word('cuisine', 'onigiri', 'n.', 'A Japanese rice ball wrapped in seaweed', 'Salted plum onigiri is the perfect train snack.'),
  Word('cuisine', 'ramen', 'n.', 'Japanese wheat noodles served in seasoned broth', 'Tonkotsu ramen demands a pork broth simmered for half a day.'),
  Word('cuisine', 'soba', 'n.', 'Thin Japanese noodles made from buckwheat', 'Chilled soba with dipping sauce is a summer essential.'),
  Word('cuisine', 'udon', 'n.', 'Thick chewy Japanese wheat noodles', 'Udon in a kitsune broth warms you on a cold day.'),
  Word('cuisine', 'izakaya', 'n.', 'A casual Japanese pub serving small dishes with drinks', 'We hopped from izakaya to izakaya all through Shinjuku.'),
  Word('cuisine', 'yakitori', 'n.', 'Japanese skewered grilled chicken', 'The yakitori chef knows every part of the bird by name.'),
  Word('cuisine', 'gochujang', 'n.', 'A Korean fermented red chili paste', 'A spoon of gochujang gives the marinade depth and heat.'),
  Word('cuisine', 'doenjang', 'n.', 'A Korean fermented soybean paste', 'Doenjang stew tastes funkier and earthier than miso soup.'),
  Word('cuisine', 'ssamjang', 'n.', 'A Korean dipping paste of gochujang and doenjang', 'Smear ssamjang on the lettuce wrap before adding the pork.'),
  Word('cuisine', 'kimchi', 'n.', 'A Korean fermented vegetable, usually napa cabbage', 'A side of kimchi cuts through the richness of fried chicken.'),
  Word('cuisine', 'bulgogi', 'n.', 'Thinly sliced Korean marinated beef', 'Grill the bulgogi over charcoal and tuck it into rice.'),
  Word('cuisine', 'galbi', 'n.', 'Korean grilled short ribs', 'Galbi marinates in pear juice for tenderness.'),
  Word('cuisine', 'bibimbap', 'n.', 'A Korean rice bowl with vegetables and chili paste', 'Stone bowl bibimbap forms a perfect crust at the bottom.'),
  Word('cuisine', 'jjigae', 'n.', 'A bubbling Korean stew served straight from the pot', 'Sundubu jjigae is silky tofu in a fiery broth.'),
  Word('cuisine', 'tteokbokki', 'n.', 'Korean rice cakes in a sweet-spicy sauce', 'Street vendors in Seoul serve tteokbokki in paper cups.'),
  Word('cuisine', 'mandu', 'n.', 'Korean dumplings filled with meat or vegetables', 'Crispy mandu hit the table sizzling on the cast iron.'),
  Word('cuisine', 'sambal', 'n.', 'A Southeast Asian chili-based condiment', 'Pass the sambal — the noodles need a little fire.'),
  Word('cuisine', 'nuoc cham', 'n.', 'A Vietnamese fish sauce dipping sauce', 'Vietnamese spring rolls live and die by the nuoc cham.'),
  Word('cuisine', 'pho', 'n.', 'A Vietnamese rice noodle soup with aromatic broth', 'A perfect pho broth simmers for at least eight hours.'),
  Word('cuisine', 'banh mi', 'n.', 'A Vietnamese sandwich on a baguette', 'The banh mi balances pickled daikon, pâté, and chilies in one bite.'),
  Word('cuisine', 'bun bo hue', 'n.', 'A spicy Vietnamese noodle soup from Hue', 'Bun bo hue has more punch than its cousin pho.'),
  Word('cuisine', 'pad thai', 'n.', 'A Thai stir-fried rice noodle dish', 'A real pad thai has dried shrimp and tamarind in the sauce.'),
  Word('cuisine', 'pad see ew', 'n.', 'A Thai stir-fry of wide noodles in dark soy', 'Pad see ew should taste of wok smoke and char.'),
  Word('cuisine', 'tom yum', 'n.', 'A hot and sour Thai soup', 'Lemongrass and galangal give tom yum its bracing zing.'),
  Word('cuisine', 'tom kha', 'n.', 'A Thai coconut soup with galangal and chili', 'Tom kha gai folds rich coconut milk around chicken and herbs.'),
  Word('cuisine', 'galangal', 'n.', 'A piney rhizome related to ginger', 'Galangal smells nothing like ginger once you slice it open.'),
  Word('cuisine', 'lemongrass', 'n.', 'A citrusy stalk used in Southeast Asian cooking', 'Bruise the lemongrass before tossing it into the broth.'),
  Word('cuisine', 'kaffir lime', 'n.', 'A knobby citrus whose leaves flavor Thai food', 'A torn kaffir lime leaf perfumes the green curry.'),
  Word('cuisine', 'fish sauce', 'n.', 'A pungent Southeast Asian seasoning of fermented anchovies', 'A few drops of fish sauce make any soup taste deeper.'),
  Word('cuisine', 'shrimp paste', 'n.', 'A fermented seafood paste used across Southeast Asia', 'Shrimp paste smells alarming but tastes incredible cooked.'),
  Word('cuisine', 'massaman', 'n.', 'A mild Thai curry with Persian influence', 'Massaman with beef cheek is a cold-weather indulgence.'),
  Word('cuisine', 'panang', 'n.', 'A rich, dry-style Thai curry', 'Panang curry clings to the chicken in a thick coat.'),
  Word('cuisine', 'rendang', 'n.', 'A slow-cooked Indonesian dry beef curry', 'Rendang reduces for hours until the coconut milk caramelizes.'),
  Word('cuisine', 'nasi goreng', 'n.', 'Indonesian-style fried rice', 'Nasi goreng usually comes with a fried egg on top.'),
  Word('cuisine', 'satay', 'n.', 'Southeast Asian grilled skewered meat with peanut sauce', 'Chicken satay is the easiest crowd-pleaser at a barbecue.'),
  Word('cuisine', 'laksa', 'n.', 'A spicy coconut or sour-tamarind noodle soup', 'Penang laksa is fishy and sour while Singapore laksa is creamy and rich.'),
  Word('cuisine', 'congee', 'n.', 'A Chinese rice porridge eaten with savory toppings', 'Congee with century egg and pork is the ultimate comfort breakfast.'),
  Word('cuisine', 'dim sum', 'n.', 'Cantonese small plates served from rolling carts', 'We sat down for dim sum and didn\'t leave for three hours.'),
  Word('cuisine', 'siu mai', 'n.', 'An open-topped Cantonese pork-and-shrimp dumpling', 'Siu mai are a dim sum staple, topped with a dot of roe.'),
  Word('cuisine', 'har gow', 'n.', 'A translucent shrimp dumpling from Cantonese tradition', 'A proper har gow has at least seven pleats.'),
  Word('cuisine', 'xiao long bao', 'n.', 'Shanghainese soup dumplings', 'Bite a corner off the xiao long bao before slurping the broth.'),
  Word('cuisine', 'mapo tofu', 'n.', 'A Sichuan dish of silken tofu in chili bean sauce', 'A good mapo tofu numbs your lips in the best way.'),
  Word('cuisine', 'kung pao', 'n.', 'A Sichuan stir-fry with peanuts and dried chilies', 'Kung pao chicken should taste of toasted Sichuan pepper.'),
  Word('cuisine', 'Sichuan peppercorn', 'n.', 'A tingly, citrusy Chinese spice', 'Sichuan peppercorn delivers that signature numbing buzz called málà.'),
  Word('cuisine', 'málà', 'adj.', 'Numbing and spicy in the Sichuan style', 'The málà hot pot left my tongue happily tingling for an hour.'),
  Word('cuisine', 'doubanjiang', 'n.', 'A Sichuan fermented broad-bean and chili paste', 'Doubanjiang gives mapo tofu its deep red color and savory heat.'),
  Word('cuisine', 'hoisin', 'n.', 'A sweet, salty Chinese dipping and glaze sauce', 'Roll the duck pancake with hoisin and slivered scallion.'),
  Word('cuisine', 'oyster sauce', 'n.', 'A thick savory Chinese sauce of oyster extract', 'Stir-fried gai lan needs nothing more than oyster sauce.'),
  Word('cuisine', 'wok hei', 'n.', 'The smoky breath of the wok over fierce heat', 'Real wok hei is impossible to fake on a home stove.'),
  Word('cuisine', 'lap cheong', 'n.', 'A sweet Chinese cured pork sausage', 'Lap cheong steamed over rice flavors every grain underneath.'),
  Word('cuisine', 'char siu', 'n.', 'Cantonese sweet-glazed roast pork', 'A pile of char siu over rice is the city worker\'s lunch in Hong Kong.'),
  Word('cuisine', 'Peking duck', 'n.', 'A roasted duck with lacquered crisp skin', 'The Peking duck arrived carved tableside in three courses.'),
  Word('cuisine', 'masala', 'n.', 'A blend of spices used in South Asian cooking', 'Every household has its own masala for chai or curry.'),
  Word('cuisine', 'tikka', 'n.', 'Skewered chunks of marinated meat from South Asia', 'Chicken tikka picks up smoke off the tandoor charcoal.'),
  Word('cuisine', 'tandoor', 'n.', 'A clay oven fired with charcoal or wood', 'The tandoor blasts heat upwards of 900 degrees.'),
  Word('cuisine', 'naan', 'n.', 'A leavened Indian flatbread baked on a tandoor wall', 'Tear off a piece of garlic naan to mop up the dal.'),
  Word('cuisine', 'paratha', 'n.', 'A flaky layered Indian flatbread', 'Aloo paratha stuffed with potato is breakfast in Punjab.'),
  Word('cuisine', 'roti', 'n.', 'An unleavened Indian griddled bread', 'A stack of fresh roti makes any meal feel like home.'),
  Word('cuisine', 'paneer', 'n.', 'A fresh, non-melting Indian cheese', 'Paneer takes on the color of whatever masala it joins.'),
  Word('cuisine', 'ghee', 'n.', 'Clarified butter cooked until nutty', 'A spoon of ghee melts into the dal at the end.'),
  Word('cuisine', 'dal', 'n.', 'A South Asian lentil-based stew', 'A bowl of dal and rice is the most consoling thing I know.'),
  Word('cuisine', 'biryani', 'n.', 'A layered Indian rice dish cooked with spices and meat', 'Hyderabadi biryani sits sealed under dough as it steams.'),
  Word('cuisine', 'korma', 'n.', 'A mild Indian curry enriched with cream or nuts', 'Korma is the gentle, royal cousin of vindaloo.'),
  Word('cuisine', 'vindaloo', 'n.', 'A fiery Goan curry with vinegar and chili', 'Order vindaloo only if you can take real heat.'),
  Word('cuisine', 'dosa', 'n.', 'A South Indian fermented crêpe of rice and lentil', 'The dosa stretched across the table in a giant crisp tube.'),
  Word('cuisine', 'idli', 'n.', 'A steamed South Indian rice and lentil cake', 'Idli with coconut chutney is the gentlest of breakfasts.'),
  Word('cuisine', 'sambar', 'n.', 'A South Indian lentil stew with tamarind and vegetables', 'Sambar pairs with everything from idli to rice.'),
  Word('cuisine', 'chaat', 'n.', 'Indian savory snacks with sweet, sour, and spicy elements', 'Chaat is meant to assault every taste bud at once.'),
  Word('cuisine', 'garam masala', 'n.', 'A warm Indian spice blend added near the end of cooking', 'A pinch of garam masala wakes up the curry just before serving.'),
  Word('cuisine', 'turmeric', 'n.', 'A bright yellow rhizome used as a spice', 'Turmeric stains the cutting board but earns its keep in flavor.'),
  Word('cuisine', 'fenugreek', 'n.', 'A maple-scented seed and herb used in Indian cooking', 'Toast the fenugreek seeds carefully — they turn bitter fast.'),
  Word('cuisine', 'cardamom', 'n.', 'An aromatic pod used in sweet and savory dishes', 'Crush green cardamom into the rice for biryani.'),
  Word('cuisine', 'asafoetida', 'n.', 'A pungent dried resin used as a savory seasoning', 'A pinch of asafoetida bloomed in oil mimics onion and garlic.'),
  Word('cuisine', 'tadka', 'n.', 'A tempering of spices bloomed in hot fat', 'Pour the sizzling tadka over the dal right before serving.'),
  Word('cuisine', 'harissa', 'n.', 'A North African paste of chilies, garlic, and spices', 'A spoonful of harissa wakes up the lamb shank braise.'),
  Word('cuisine', 'ras el hanout', 'n.', 'A complex North African spice blend', 'Ras el hanout can have over twenty spices in a single jar.'),
  Word('cuisine', 'preserved lemon', 'n.', 'Lemons cured in salt and their own juice', 'Preserved lemon brightens any tagine I make.'),
  Word('cuisine', 'tagine', 'n.', 'A North African stew named for its conical clay pot', 'Lamb tagine with apricots and almonds is a Marrakech classic.'),
  Word('cuisine', 'couscous', 'n.', 'Steamed semolina granules from North Africa', 'Fluff the couscous with a fork and dot it with butter.'),
  Word('cuisine', 'merguez', 'n.', 'A spicy lamb or beef sausage from North Africa', 'Grill the merguez until the casings blister and split.'),
  Word('cuisine', 'shakshuka', 'n.', 'Eggs poached in a spiced tomato and pepper sauce', 'Brunch is shakshuka in a cast-iron skillet, no exceptions.'),
  Word('cuisine', 'za\'atar', 'n.', 'A Levantine blend of thyme, sumac, and sesame', 'Toast pita with olive oil and za\'atar in the morning.'),
  Word('cuisine', 'sumac', 'n.', 'A tart, ruby-red Middle Eastern spice', 'A dust of sumac brightens a fattoush salad.'),
  Word('cuisine', 'tahini', 'n.', 'A paste of ground sesame seeds', 'Drizzle tahini over the roasted carrots before serving.'),
  Word('cuisine', 'hummus', 'n.', 'A puréed dip of chickpeas, tahini, and lemon', 'Real hummus should be silky and warm, not stiff from the fridge.'),
  Word('cuisine', 'baba ghanoush', 'n.', 'A smoky eggplant dip from the Levant', 'Char the eggplant on a flame for proper baba ghanoush.'),
  Word('cuisine', 'labneh', 'n.', 'Strained yogurt thickened to a soft cheese', 'Spoon labneh into a bowl and drown it in olive oil.'),
  Word('cuisine', 'kibbeh', 'n.', 'Bulgur and meat croquettes from the Levant', 'Fried kibbeh has the perfect crunch-to-tender ratio.'),
  Word('cuisine', 'fattoush', 'n.', 'A Levantine bread salad with sumac and pita chips', 'Fattoush is the salad I crave all summer long.'),
  Word('cuisine', 'tabbouleh', 'n.', 'A Levantine parsley and bulgur salad', 'Real tabbouleh is mostly parsley, with bulgur as accent.'),
  Word('cuisine', 'shawarma', 'n.', 'Spit-roasted meat sliced into wraps', 'Late-night shawarma in Beirut is a sacred ritual.'),
  Word('cuisine', 'falafel', 'n.', 'Fried croquettes of ground chickpeas or fava', 'A proper falafel is green inside and shatters on the outside.'),
  Word('cuisine', 'kebab', 'n.', 'Skewered or ground grilled meat from the Middle East', 'A wood-fire kebab is half the appeal of a Persian dinner.'),
  Word('cuisine', 'kofta', 'n.', 'Spiced ground-meat skewers or meatballs', 'Lamb kofta with yogurt is hard to beat off the grill.'),
  Word('cuisine', 'baklava', 'n.', 'A flaky pastry layered with nuts and syrup', 'A square of baklava with strong coffee ends the meal.'),
  Word('cuisine', 'kunafa', 'n.', 'A cheese pastry soaked in syrup with shredded phyllo', 'Order kunafa hot, with the cheese still pulling in strands.'),
  Word('cuisine', 'phyllo', 'n.', 'Paper-thin sheets of unleavened dough', 'Brush each phyllo sheet with butter before stacking.'),
  Word('cuisine', 'pistachio', 'n.', 'A small green nut from the Middle East', 'Crushed pistachio finishes the kunafa with crunch and color.'),
  Word('cuisine', 'pomegranate molasses', 'n.', 'A tart syrup reduced from pomegranate juice', 'A drizzle of pomegranate molasses brightens the muhammara.'),
  Word('cuisine', 'muhammara', 'n.', 'A Syrian dip of roasted peppers and walnuts', 'Spread muhammara on warm flatbread for a perfect snack.'),
  Word('cuisine', 'rosewater', 'n.', 'A perfumed liquid distilled from rose petals', 'A whisper of rosewater lifts the rice pudding.'),
  Word('cuisine', 'saffron', 'n.', 'A costly spice of dried crocus stigmas', 'Bloom the saffron in warm broth to release its color.'),
  Word('cuisine', 'paella', 'n.', 'A Spanish rice dish cooked in a wide flat pan', 'A good paella forms a crust called socarrat at the bottom.'),
  Word('cuisine', 'socarrat', 'n.', 'The crispy rice crust at the bottom of paella', 'Every Spaniard fights for the corner with the most socarrat.'),
  Word('cuisine', 'pintxo', 'n.', 'A small Basque snack speared with a toothpick', 'A bar crawl through San Sebastián means a pintxo at every stop.'),
  Word('cuisine', 'pulpo', 'n.', 'Octopus, especially the Galician preparation', 'Pulpo a la gallega comes dusted with paprika and good olive oil.'),
  Word('cuisine', 'chorizo', 'n.', 'A smoky Spanish pork sausage seasoned with paprika', 'Slice the chorizo into the lentils for instant depth.'),
  Word('cuisine', 'jamón', 'n.', 'A Spanish dry-cured ham', 'Jamón ibérico melts on your tongue like savory butter.'),
  Word('cuisine', 'manchego', 'n.', 'A firm Spanish sheep\'s milk cheese', 'Aged manchego with quince paste is the ideal nightcap.'),
  Word('cuisine', 'membrillo', 'n.', 'A dense Spanish quince paste', 'Slice the membrillo thin to pair with manchego.'),
  Word('cuisine', 'pimentón', 'n.', 'Spanish smoked paprika', 'Pimentón de la Vera carries actual oak-fire smoke.'),
  Word('cuisine', 'sherry', 'n.', 'A fortified Spanish wine from Andalusia', 'A glass of fino sherry pairs beautifully with almonds and olives.'),
  Word('cuisine', 'fino', 'n.', 'A bone-dry style of sherry', 'Chill the fino hard and serve it with anchovies.'),
  Word('cuisine', 'oloroso', 'n.', 'A nutty, oxidative style of sherry', 'Oloroso brings caramel and walnut notes to the glass.'),
  Word('cuisine', 'amontillado', 'n.', 'A sherry style aged between fino and oloroso', 'The amontillado smells of hazelnut and dried citrus.'),
  Word('cuisine', 'cava', 'n.', 'A Spanish sparkling wine', 'Cava on a hot terrace beats Champagne for value any day.'),
  Word('cuisine', 'gazpacho andaluz', 'n.', 'A chilled Andalusian raw tomato soup', 'Gazpacho andaluz is summer in a tall glass.'),
  Word('cuisine', 'salmorejo', 'n.', 'A thick cold Spanish tomato and bread soup', 'Salmorejo is gazpacho\'s richer Cordoban cousin.'),
  Word('cuisine', 'tortilla española', 'n.', 'A Spanish potato and egg omelet', 'A proper tortilla española should be runny in the middle.'),
  Word('cuisine', 'patatas bravas', 'n.', 'Spanish fried potatoes with spicy sauce', 'Patatas bravas demand both the bravas and the aioli.'),
  Word('cuisine', 'croqueta', 'n.', 'A Spanish breaded fritter of béchamel and meat', 'A jamón croqueta should burst with molten béchamel.'),
  Word('cuisine', 'risotto', 'n.', 'An Italian rice dish cooked with broth added gradually', 'Stir the risotto patiently to coax out the starch.'),
  Word('cuisine', 'arborio', 'n.', 'A short-grain Italian rice used for risotto', 'Arborio is the everyday rice for a creamy risotto.'),
  Word('cuisine', 'carnaroli', 'n.', 'A premium Italian short-grain rice for risotto', 'Carnaroli holds its bite better than arborio.'),
  Word('cuisine', 'gnocchi', 'n.', 'Italian dumplings, often made from potato', 'Light gnocchi should melt on the tongue, not sit there like a stone.'),
  Word('cuisine', 'tagliatelle', 'n.', 'Long ribbon-shaped Italian pasta', 'Tagliatelle is the proper noodle for Bolognese ragù.'),
  Word('cuisine', 'pappardelle', 'n.', 'Wide flat ribbons of Italian pasta', 'Pappardelle catches a hearty wild boar ragù.'),
  Word('cuisine', 'orecchiette', 'n.', 'Small ear-shaped Italian pasta from Puglia', 'Orecchiette with broccoli rabe is a Pugliese classic.'),
  Word('cuisine', 'rigatoni', 'n.', 'Large ridged tube-shaped Italian pasta', 'Rigatoni holds onto a chunky meat sauce better than penne.'),
  Word('cuisine', 'bucatini', 'n.', 'Thick hollow Italian spaghetti', 'Bucatini all\'amatriciana belongs in every Roman pasta canon.'),
  Word('cuisine', 'amatriciana', 'n.', 'A Roman pasta sauce of guanciale, tomato, and chili', 'Amatriciana needs guanciale — pancetta won\'t do.'),
  Word('cuisine', 'cacio e pepe', 'n.', 'A Roman pasta of pecorino and black pepper', 'Cacio e pepe seems simple until you actually try it.'),
  Word('cuisine', 'carbonara', 'n.', 'A Roman pasta of guanciale, egg, and pecorino', 'A true carbonara never sees cream or onions.'),
  Word('cuisine', 'guanciale', 'n.', 'Italian cured pork jowl', 'Guanciale renders into the most decadent fat for pasta.'),
  Word('cuisine', 'pancetta', 'n.', 'Italian cured pork belly', 'Crisp the pancetta and toss it into the pasta with its fat.'),
  Word('cuisine', 'prosciutto', 'n.', 'Italian dry-cured ham', 'A slice of prosciutto draped over a fig is summer in a bite.'),
  Word('cuisine', 'mortadella', 'n.', 'A large smooth Italian pork sausage from Bologna', 'A mortadella sandwich on focaccia is a Bologna staple.'),
  Word('cuisine', 'bresaola', 'n.', 'Italian air-dried salt-cured beef', 'Drape bresaola over arugula with shaved parmesan.'),
  Word('cuisine', 'speck', 'n.', 'A smoked cured ham from the South Tyrol', 'Speck has the smoke of bacon and the salt of prosciutto.'),
  Word('cuisine', 'lardo', 'n.', 'Italian cured strips of pork fatback', 'Thin slices of lardo melt on warm toast like edible silk.'),
  Word('cuisine', 'osso buco', 'n.', 'A Milanese braise of cross-cut veal shank', 'Osso buco served with risotto alla milanese is a winter feast.'),
  Word('cuisine', 'saltimbocca', 'n.', 'Roman veal scallops with prosciutto and sage', 'Saltimbocca literally means jump in the mouth.'),
  Word('cuisine', 'vitello tonnato', 'n.', 'Cold sliced veal under a creamy tuna sauce', 'Vitello tonnato sounds odd until you taste it.'),
  Word('cuisine', 'caprese', 'n.', 'A salad of tomato, mozzarella, and basil', 'A caprese is only as good as its tomato.'),
  Word('cuisine', 'burrata', 'n.', 'A fresh cheese with a creamy interior of cream and curd', 'Tear into the burrata and watch it ooze across the plate.'),
  Word('cuisine', 'mozzarella di bufala', 'n.', 'Italian mozzarella made from water buffalo milk', 'Mozzarella di bufala is grassy, milky, and a little tangy.'),
  Word('cuisine', 'pecorino', 'n.', 'A hard Italian sheep\'s milk cheese', 'Grate pecorino over the bucatini with a heavy hand.'),
  Word('cuisine', 'parmigiano', 'n.', 'A hard aged Italian cow\'s milk cheese', 'A wedge of real parmigiano deserves a wax-paper wrap.'),
  Word('cuisine', 'gorgonzola', 'n.', 'A creamy Italian blue cheese', 'Crumble gorgonzola dolce into the polenta off the heat.'),
  Word('cuisine', 'taleggio', 'n.', 'A washed-rind northern Italian cheese', 'Taleggio melts into a pungent, oozy dream on bread.'),
  Word('cuisine', 'polenta', 'n.', 'Italian cooked cornmeal', 'Stir the polenta forty minutes for that classic creamy texture.'),
  Word('cuisine', 'focaccia', 'n.', 'A flat Italian olive-oil bread', 'A dimpled focaccia rosemary-scented just out of the oven is hard to resist.'),
  Word('cuisine', 'ciabatta', 'n.', 'A rustic Italian bread with an airy crumb', 'Ciabatta soaks up olive oil better than any other loaf.'),
  Word('cuisine', 'grissini', 'n.', 'Long thin Italian breadsticks', 'The bread basket arrives with grissini wrapped in prosciutto.'),
  Word('cuisine', 'panettone', 'n.', 'A tall sweet Italian Christmas bread', 'Panettone gets better toasted on the second day.'),
  Word('cuisine', 'tiramisu', 'n.', 'An Italian dessert of coffee-soaked ladyfingers and mascarpone', 'Tiramisu is comfort food in formalwear.'),
  Word('cuisine', 'mascarpone', 'n.', 'A rich Italian fresh cheese resembling cream', 'Fold mascarpone into the whipped cream for body.'),
  Word('cuisine', 'cannoli', 'n.', 'Sicilian fried pastry shells filled with sweet ricotta', 'A proper cannoli is filled to order so the shell stays crisp.'),
  Word('cuisine', 'sfogliatella', 'n.', 'A Neapolitan shell-shaped pastry with ricotta filling', 'A sfogliatella shatters into a hundred crispy layers when you bite it.'),
  Word('cuisine', 'gelato', 'n.', 'Italian-style dense low-fat ice cream', 'Real gelato is denser and warmer than American ice cream.'),
  Word('cuisine', 'sorbet', 'n.', 'A frozen fruit ice without dairy', 'A lemon sorbet between courses resets the palate.'),
  Word('cuisine', 'granita', 'n.', 'A semi-frozen Sicilian flavored ice', 'Sicilian breakfast is granita and a brioche.'),
  Word('cuisine', 'bagna càuda', 'n.', 'A Piedmontese warm dip of anchovy, garlic, and oil', 'Bagna càuda turns raw winter vegetables into a feast.'),
  Word('cuisine', 'aperol spritz', 'n.', 'An Italian aperitif of Aperol, prosecco, and soda', 'The Aperol spritz is the official drink of every Italian summer.'),
  Word('cuisine', 'negroni', 'n.', 'An Italian cocktail of gin, Campari, and vermouth', 'A negroni is the most adult drink ever invented.'),
  Word('cuisine', 'amaro', 'n.', 'A bitter Italian herbal liqueur', 'A glass of amaro is the proper end to a heavy meal.'),
  Word('cuisine', 'limoncello', 'n.', 'An Italian lemon liqueur from the Amalfi coast', 'They keep the limoncello in the freezer until shot time.'),
  Word('cuisine', 'grappa', 'n.', 'An Italian pomace brandy', 'A small glass of grappa settles a long Italian dinner.'),
  Word('cuisine', 'pastis', 'n.', 'An anise-flavored French aperitif', 'A pastis louches into a cloudy yellow when water hits it.'),
  Word('cuisine', 'absinthe', 'n.', 'A high-proof anise liquor with wormwood', 'Drip cold water over a sugar cube into absinthe for the proper ritual.'),
  Word('cuisine', 'vermouth', 'n.', 'A fortified aromatized wine', 'A dry vermouth on ice with an orange twist is summer in a glass.'),
  Word('cuisine', 'bitters', 'n.', 'Concentrated herbal extracts used in cocktails', 'A dash of Angostura bitters turns whiskey into an Old Fashioned.'),
  Word('cuisine', 'mezcal', 'n.', 'A smoky Mexican agave spirit', 'Mezcal carries the smoke of the pit where the agave roasted.'),
  Word('cuisine', 'tequila', 'n.', 'A Mexican spirit distilled from blue agave', 'Sip the tequila slowly — it deserves more than a shot glass.'),
  Word('cuisine', 'reposado', 'n.', 'A tequila aged briefly in oak', 'A reposado bridges the gap between blanco and añejo.'),
  Word('cuisine', 'añejo', 'n.', 'A tequila aged at least a year in oak', 'Añejo tequila comes out closer to a fine bourbon.'),
  Word('cuisine', 'mole', 'n.', 'A complex Mexican sauce with chilies, nuts, and chocolate', 'Mole poblano can simmer for two days before it\'s right.'),
  Word('cuisine', 'pozole', 'n.', 'A Mexican hominy and meat stew', 'Pozole rojo on a cold night fixes almost anything.'),
  Word('cuisine', 'menudo', 'n.', 'A Mexican tripe and hominy soup', 'Sunday menudo is the cure for Saturday night.'),
  Word('cuisine', 'birria', 'n.', 'A Mexican spiced stew, often of goat or beef', 'Dip the birria taco into the consomé before each bite.'),
  Word('cuisine', 'al pastor', 'n.', 'Mexican spit-roasted marinated pork', 'Tacos al pastor crown a slice of pineapple on top.'),
  Word('cuisine', 'carnitas', 'n.', 'Mexican slow-cooked pork confit', 'Carnitas should be tender inside and crackling outside.'),
  Word('cuisine', 'barbacoa', 'n.', 'Slow-cooked Mexican pit-roasted meat', 'Sunday barbacoa is a generations-old ritual in Oaxaca.'),
  Word('cuisine', 'cochinita pibil', 'n.', 'A Yucatecan slow-roasted pork with achiote', 'Wrap the cochinita pibil in banana leaves before pit-roasting.'),
  Word('cuisine', 'achiote', 'n.', 'A reddish paste from annatto seeds', 'Achiote gives the marinade its blazing brick-red color.'),
  Word('cuisine', 'epazote', 'n.', 'A pungent Mexican herb used with beans', 'Epazote in the pot of beans is said to settle the stomach.'),
  Word('cuisine', 'masa', 'n.', 'A dough of nixtamalized corn for tortillas and tamales', 'Press the masa thin in a tortilla press lined with plastic.'),
  Word('cuisine', 'nixtamal', 'n.', 'Corn treated with alkali to make masa', 'The nixtamal soaks overnight before being ground into masa.'),
  Word('cuisine', 'nixtamalization', 'n.', 'The alkaline soak that transforms corn for masa', 'Nixtamalization unlocks niacin and gives tortillas their flavor.'),
  Word('cuisine', 'tamale', 'n.', 'A Mesoamerican dish of masa steamed in a husk', 'A Christmas Eve tamalada is family work.'),
  Word('cuisine', 'tortilla', 'n.', 'A thin round flatbread of corn or wheat', 'Warm the tortilla over the burner just until it puffs.'),
  Word('cuisine', 'queso fresco', 'n.', 'A fresh crumbly Mexican cheese', 'Sprinkle queso fresco over the elote off the grill.'),
  Word('cuisine', 'cotija', 'n.', 'An aged crumbly salty Mexican cheese', 'Cotija plays the role of parmesan in Mexican cooking.'),
  Word('cuisine', 'crema', 'n.', 'A Mexican cultured cream resembling crème fraîche', 'A zigzag of crema cools the spice of the enchiladas.'),
  Word('cuisine', 'crème fraîche', 'n.', 'A French cultured cream with a tangy flavor', 'Stir crème fraîche into the soup off the heat so it doesn\'t curdle.'),
  Word('cuisine', 'crème anglaise', 'n.', 'A pourable French vanilla custard sauce', 'Pour crème anglaise around the chocolate cake on the plate.'),
  Word('cuisine', 'crème brûlée', 'n.', 'A French custard with a brittle caramelized sugar top', 'Crack the crème brûlée top with the back of the spoon.'),
  Word('cuisine', 'crème pâtissière', 'n.', 'A thick French pastry cream', 'Fill the éclairs with crème pâtissière piped from a star tip.'),
  Word('cuisine', 'pâte à choux', 'n.', 'A French twice-cooked dough for éclairs and profiteroles', 'A good pâte à choux puffs hollow in the oven.'),
  Word('cuisine', 'pâte brisée', 'n.', 'A French short pastry dough for tarts', 'Roll the pâte brisée cold between two sheets of parchment.'),
  Word('cuisine', 'pâte sucrée', 'n.', 'A sweet French short pastry', 'Pâte sucrée is the cookie-like crust under fruit tarts.'),
  Word('cuisine', 'pâte feuilletée', 'n.', 'French puff pastry', 'Pâte feuilletée is hundreds of butter layers and not for the impatient.'),
  Word('cuisine', 'détrempe', 'n.', 'The flour-and-water base in puff pastry making', 'Wrap the détrempe around the cold butter for the first turn.'),
  Word('cuisine', 'beurrage', 'n.', 'The butter block folded into laminated dough', 'Pound the beurrage until pliable but still cold.'),
  Word('cuisine', 'laminate', 'v.', 'To fold butter into dough in alternating layers', 'Laminate the dough through three single turns for proper rise.'),
  Word('cuisine', 'tourage', 'n.', 'The folding process for laminated doughs', 'Each tourage stretches the layers thinner.'),
  Word('cuisine', 'frangipane', 'n.', 'An almond cream filling for tarts and pastries', 'Pipe the frangipane into the tart shell before layering pears.'),
  Word('cuisine', 'ganache', 'n.', 'A mixture of chocolate and warm cream', 'Whip the ganache until it holds peaks for the filling.'),
  Word('cuisine', 'meringue', 'n.', 'Whipped egg whites stabilized with sugar', 'A Swiss meringue is more stable than French and easier than Italian.'),
  Word('cuisine', 'macaron', 'n.', 'A French almond meringue cookie sandwich', 'Each macaron should have a smooth top and a delicate foot.'),
  Word('cuisine', 'macaroon', 'n.', 'A chewy coconut cookie unrelated to the macaron', 'Dip the macaroon bottoms in dark chocolate before serving.'),
  Word('cuisine', 'madeleine', 'n.', 'A small shell-shaped French sponge cake', 'A madeleine should be hot from the oven, with the hump pronounced.'),
  Word('cuisine', 'financier', 'n.', 'A small French almond butter cake', 'A buttery financier with espresso is a perfect afternoon pause.'),
  Word('cuisine', 'canelé', 'n.', 'A Bordeaux pastry with a crisp shell and custardy center', 'A canelé is hard mahogany outside and tender inside.'),
  Word('cuisine', 'kouign-amann', 'n.', 'A Breton laminated butter and sugar pastry', 'The kouign-amann shatters into salty-sweet flakes on the first bite.'),
  Word('cuisine', 'croissant', 'n.', 'A French laminated yeasted pastry', 'A real croissant pulls apart in honeycombed layers.'),
  Word('cuisine', 'pain au chocolat', 'n.', 'A French rectangular croissant with chocolate batons', 'A pain au chocolat and a coffee is the Paris breakfast.'),
  Word('cuisine', 'galette', 'n.', 'A free-form rustic French tart', 'A summer galette of stone fruit is forgiving and beautiful.'),
  Word('cuisine', 'clafoutis', 'n.', 'A French baked custard with whole fruit', 'Cherry clafoutis is summer\'s easiest dessert.'),
  Word('cuisine', 'far breton', 'n.', 'A dense Breton custard cake with prunes', 'Far breton tastes of vanilla, brandy, and grandmothers.'),
  Word('cuisine', 'mille-feuille', 'n.', 'A French pastry of layered puff pastry and pastry cream', 'A mille-feuille means a thousand leaves of impossibly thin pastry.'),
  Word('cuisine', 'opera cake', 'n.', 'A layered French almond and coffee cake with ganache', 'The opera cake stacks seven precise layers.'),
  Word('cuisine', 'tarte tatin', 'n.', 'An upside-down French caramelized apple tart', 'A tarte tatin needs apples that won\'t fall apart in the caramel.'),
  Word('cuisine', 'galette des rois', 'n.', 'A French Epiphany cake of puff pastry and frangipane', 'Whoever finds the fève in the galette des rois wears the crown.'),
  Word('cuisine', 'baguette', 'n.', 'A long thin French bread', 'A baguette is best within four hours of leaving the oven.'),
  Word('cuisine', 'pain de mie', 'n.', 'A soft white French sandwich bread', 'Slice the pain de mie thin for the tea sandwiches.'),
  Word('cuisine', 'brioche', 'n.', 'A rich French bread enriched with butter and eggs', 'A brioche bun makes a burger feel formal.'),
  Word('cuisine', 'fougasse', 'n.', 'A leaf-shaped Provençal flatbread', 'A fougasse studded with olives is a Provence pantry essential.'),
  Word('cuisine', 'pissaladière', 'n.', 'A Provençal flatbread with onions, olives, and anchovies', 'Pissaladière is Nice\'s answer to pizza.'),
  Word('cuisine', 'ratatouille', 'n.', 'A Provençal stew of summer vegetables', 'Layer the ratatouille slowly so each vegetable keeps its identity.'),
  Word('cuisine', 'bouillabaisse', 'n.', 'A Provençal fish stew with rouille and bread', 'Real Marseille bouillabaisse uses rockfish and saffron.'),
  Word('cuisine', 'rouille', 'n.', 'A Provençal saffron-garlic mayonnaise', 'Stir the rouille into the bouillabaisse for a hit of garlic and heat.'),
  Word('cuisine', 'cassoulet', 'n.', 'A French slow-cooked white bean and meat casserole', 'A real cassoulet forms seven crusts that are stirred back in.'),
  Word('cuisine', 'coq au vin', 'n.', 'A French braise of chicken in red wine', 'Coq au vin tastes better the next day.'),
  Word('cuisine', 'boeuf bourguignon', 'n.', 'A red-wine French beef stew from Burgundy', 'Boeuf bourguignon was Julia Child\'s gateway dish for America.'),
  Word('cuisine', 'pot-au-feu', 'n.', 'A French boiled beef and vegetable dinner', 'Pot-au-feu is the most humble and most royal of French dishes.'),
  Word('cuisine', 'choucroute garnie', 'n.', 'An Alsatian platter of sauerkraut and cured meats', 'Choucroute garnie is the warm hug of Alsatian winter.'),
  Word('cuisine', 'flammekueche', 'n.', 'An Alsatian thin tart with cream, onion, and lardons', 'Flammekueche is Alsatian pizza done in five minutes.'),
  Word('cuisine', 'quiche', 'n.', 'A French savory custard tart', 'A real quiche Lorraine has only lardons, cream, and eggs.'),
  Word('cuisine', 'soufflé', 'n.', 'A puffed baked egg dish, sweet or savory', 'Don\'t open the oven door or the soufflé will collapse.'),
  Word('cuisine', 'mousseline', 'n.', 'A light puréed mixture lightened with cream', 'The fish mousseline is piped into a pastry shell before poaching.'),
  Word('cuisine', 'galantine', 'n.', 'A cold deboned poultry stuffed and pressed', 'A duck galantine takes a day but feeds a dinner party.'),
  Word('cuisine', 'ballotine', 'n.', 'A boned and stuffed poultry leg, roasted or braised', 'A chicken ballotine slices into perfect rounds for the plate.'),
  Word('cuisine', 'roulade', 'n.', 'Meat or fish rolled around a filling', 'Tie the pork roulade tight before searing.'),
  Word('cuisine', 'chef de partie', 'n.', 'A station chef in a brigade kitchen', 'The fish chef de partie has been on the line for ten years.'),
  Word('cuisine', 'sous chef', 'n.', 'The second-in-command in a professional kitchen', 'The sous chef runs the line while the chef works the floor.'),
  Word('cuisine', 'garde-manger', 'n.', 'The cold-station chef or department', 'The garde-manger plates the crudités, terrines, and tartares.'),
  Word('cuisine', 'saucier', 'n.', 'The cook in charge of sauces and sautéed dishes', 'The saucier station is the hottest spot in a brigade kitchen.'),
  Word('cuisine', 'poissonnier', 'n.', 'The fish station cook in a brigade', 'The poissonnier breaks down the whole turbot at noon.'),
  Word('cuisine', 'pâtissier', 'n.', 'The pastry chef in a kitchen brigade', 'The pâtissier comes in at 4 a.m. to start the laminations.'),
  Word('cuisine', 'brigade', 'n.', 'The French hierarchical kitchen team', 'Escoffier formalized the modern kitchen brigade.'),
  Word('cuisine', 'expediter', 'n.', 'The cook who calls and coordinates tickets at the pass', 'The expediter keeps the dining room and kitchen in sync.'),
  Word('cuisine', 'the pass', 'n.', 'The counter where finished plates leave the kitchen', 'The chef stands at the pass and inspects every plate.'),
  Word('cuisine', 'the line', 'n.', 'The row of cooking stations in a professional kitchen', 'Service hits the line like a controlled storm.'),
  Word('cuisine', '86', 'v.', 'To mark a dish as unavailable', 'We 86 the halibut — the last portion just sold.'),
  Word('cuisine', 'on order', 'phr.', 'In the queue but not yet started', 'Two pasta on order, one risotto fire now.'),
  Word('cuisine', 'all day', 'phr.', 'The running total of an item across active tickets', 'Six steaks all day, three med-rare, two rare, one well.'),
  Word('cuisine', 'walk-in', 'n.', 'A large refrigerated room for kitchen storage', 'The bones are in the walk-in on the bottom shelf.'),
  Word('cuisine', 'lowboy', 'n.', 'A short refrigerator below a cooking station', 'Keep the proteins prepped in the lowboy during service.'),
  Word('cuisine', 'salamander', 'n.', 'A small intense overhead broiler', 'Hit the gratin under the salamander to glaze the top.'),
  Word('cuisine', 'plancha', 'n.', 'A flat hot griddle used for searing', 'Sear the octopus on the plancha until charred.'),
  Word('cuisine', 'mandoline', 'n.', 'A blade tool for slicing produce thin and uniform', 'Use the mandoline for paper-thin fennel — and use the guard.'),
  Word('cuisine', 'tamis', 'n.', 'A fine drum sieve for purées', 'Push the purée through a tamis for that glassy texture.'),
  Word('cuisine', 'chinois', 'n.', 'A conical fine-mesh strainer', 'Strain the sauce through a chinois for absolute silkiness.'),
  Word('cuisine', 'china cap', 'n.', 'A perforated conical strainer with larger holes', 'Press the bisque through a china cap first, then a chinois.'),
  Word('cuisine', 'cheesecloth', 'n.', 'A loosely woven cotton cloth for straining', 'Wrap the spices in cheesecloth to make a sachet.'),
  Word('cuisine', 'sachet', 'n.', 'Aromatics tied in cloth for flavoring stocks', 'Drop the sachet into the simmering bouillon for thirty minutes.'),
  Word('cuisine', 'bouquet garni', 'n.', 'A tied bundle of herbs to flavor stocks', 'Tuck the bouquet garni between the leeks before adding water.'),
  Word('cuisine', 'cocotte', 'n.', 'A small French cast-iron pot, often enameled', 'Bake the eggs en cocotte with a spoon of cream.'),
  Word('cuisine', 'Dutch oven', 'n.', 'A heavy lidded pot for slow cooking', 'Braise the short ribs in a Dutch oven for three hours.'),
  Word('cuisine', 'molcajete', 'n.', 'A Mexican mortar of volcanic stone', 'Pound the guacamole in a molcajete for authentic texture.'),
  Word('cuisine', 'suribachi', 'n.', 'A Japanese ridged mortar for grinding', 'Grind the sesame in the suribachi until oily and fragrant.'),
  Word('cuisine', 'wok', 'n.', 'A curved deep pan used in Chinese cooking', 'Season the wok hard so it goes nonstick over time.'),
  Word('cuisine', 'comal', 'n.', 'A flat Mexican griddle for tortillas', 'Char the chiles on the dry comal before grinding.'),
  Word('cuisine', 'paella pan', 'n.', 'A wide shallow Spanish pan for paella', 'A 16-inch paella pan feeds about six.'),
  Word('cuisine', 'tagine pot', 'n.', 'A Moroccan clay pot with a conical lid', 'The tagine pot captures and returns the steam to the stew.'),
  Word('cuisine', 'donabe', 'n.', 'A Japanese clay pot for tabletop cooking', 'Cook the rice in the donabe and serve it right at the table.'),
  Word('cuisine', 'bamboo steamer', 'n.', 'A stacked Chinese steaming basket', 'A bamboo steamer wicks moisture so the dumplings don\'t sweat.'),
  Word('cuisine', 'fish spatula', 'n.', 'A thin slotted flexible spatula for delicate flipping', 'Slide a fish spatula under the fillet to keep it intact.'),
  Word('cuisine', 'bench scraper', 'n.', 'A flat tool for dividing dough and clearing surfaces', 'A bench scraper is the most useful tool a baker has.'),
  Word('cuisine', 'sheet pan', 'n.', 'A rimmed flat metal baking tray', 'The sheet pan dinner has saved more weeknights than I can count.'),
  Word('cuisine', 'rondeau', 'n.', 'A wide shallow pot for browning and braising', 'Brown the chicken thighs in a rondeau before adding the wine.'),
  Word('cuisine', 'sauté pan', 'n.', 'A straight-sided pan for stovetop cooking', 'A heavy sauté pan holds heat better than a thin skillet.'),
  Word('cuisine', 'skillet', 'n.', 'A flat-bottomed frying pan', 'My grandmother\'s cast-iron skillet is still my favorite tool.'),
  Word('cuisine', 'chef\'s knife', 'n.', 'An all-purpose kitchen knife with a curved blade', 'A sharp chef\'s knife makes every kitchen task easier.'),
  Word('cuisine', 'paring knife', 'n.', 'A small knife for detailed work', 'A paring knife is perfect for peeling pearl onions.'),
  Word('cuisine', 'boning knife', 'n.', 'A thin flexible knife for separating meat from bone', 'A boning knife glides between the joint and the cartilage.'),
  Word('cuisine', 'cleaver', 'n.', 'A heavy rectangular knife for chopping bone and produce', 'The Chinese cleaver does the work of an entire knife block.'),
  Word('cuisine', 'santoku', 'n.', 'A short Japanese all-purpose knife with a flat edge', 'The santoku makes vertical chopping feel natural.'),
  Word('cuisine', 'yanagiba', 'n.', 'A long single-bevel Japanese knife for slicing fish', 'A yanagiba glides through sashimi in one long stroke.'),
  Word('cuisine', 'deba', 'n.', 'A heavy Japanese single-bevel knife for breaking down fish', 'The deba splits through the spine of a small fish cleanly.'),
  Word('cuisine', 'nakiri', 'n.', 'A rectangular Japanese vegetable knife', 'A nakiri chops scallions in a single drop.'),
  Word('cuisine', 'whetstone', 'n.', 'A stone used to sharpen knife edges', 'Soak the whetstone twenty minutes before sharpening.'),
  Word('cuisine', 'honing rod', 'n.', 'A steel rod for realigning a knife edge', 'Run the blade across the honing rod before every prep shift.'),
  Word('cuisine', 'paysanne', 'n.', 'A flat square or triangular vegetable cut', 'Cut the leeks paysanne for the rustic soup.'),
  Word('cuisine', 'macédoine', 'n.', 'A 5mm dice of vegetables', 'Cut the carrots into a tidy macédoine for the salad.'),
  Word('cuisine', 'batonnet', 'n.', 'Sticks of vegetable about a quarter inch by two inches', 'A bag of homemade carrot batonnet beats anything from the store.'),
  Word('cuisine', 'tournée', 'n.', 'A football-shaped vegetable cut with seven faces', 'A perfect tournée potato is the test of a pastry student.'),
  Word('cuisine', 'rondelle', 'n.', 'A round coin-shaped slice', 'Cut the carrots into rondelles for the chicken soup.'),
  Word('cuisine', 'concassé', 'n.', 'Coarsely chopped peeled and seeded tomato', 'Fold the tomato concassé into the pasta at the end.'),
  Word('cuisine', 'supreme', 'n.', 'A citrus segment cut free of pith and membrane', 'Garnish the salad with grapefruit supremes.'),
  Word('cuisine', 'fillet', 'v.', 'To remove the flesh of a fish from the bone', 'Fillet the fish in two clean passes along the spine.'),
  Word('cuisine', 'butcher', 'v.', 'To break down a whole animal into cuts', 'A good butcher can break down a side of beef in twenty minutes.'),
  Word('cuisine', 'spine', 'n.', 'The backbone of an animal, often removed in butchery', 'Snap the spine out before laying the chicken flat.'),
  Word('cuisine', 'silver skin', 'n.', 'A tough membrane on cuts of meat', 'Trim the silver skin off the tenderloin or it\'ll seize in the pan.'),
  Word('cuisine', 'marbling', 'n.', 'Intramuscular fat that streaks through meat', 'Heavy marbling is what makes a Wagyu ribeye unforgettable.'),
  Word('cuisine', 'tenderloin', 'n.', 'A long, lean, very tender cut of beef or pork', 'The tenderloin is the lean piece beneath the spine.'),
  Word('cuisine', 'ribeye', 'n.', 'A richly marbled steak from the rib section', 'A bone-in ribeye is the king of steakhouse cuts.'),
  Word('cuisine', 'porterhouse', 'n.', 'A large steak with both tenderloin and strip', 'A porterhouse for two is dinner and a show.'),
  Word('cuisine', 'tomahawk', 'n.', 'A ribeye with the long rib bone left attached', 'A tomahawk grills with theatrical flair.'),
  Word('cuisine', 'strip steak', 'n.', 'A boneless cut from the short loin', 'A New York strip steak cooks evenly and slices beautifully.'),
  Word('cuisine', 'hanger steak', 'n.', 'A flavorful cut from the diaphragm area', 'Hanger steak rewards a quick sear and a hard rest.'),
  Word('cuisine', 'skirt steak', 'n.', 'A long thin flavorful cut from the plate', 'Marinate the skirt steak and grill it hot and fast for fajitas.'),
  Word('cuisine', 'flank steak', 'n.', 'A lean fibrous steak from the abdomen', 'Slice the flank steak against the grain to keep it tender.'),
  Word('cuisine', 'tri-tip', 'n.', 'A triangular cut from the bottom sirloin', 'Santa Maria tri-tip is the signature Central Coast barbecue.'),
  Word('cuisine', 'brisket', 'n.', 'A tough flavorful cut from the cow\'s chest', 'Texas brisket separates the smoking patient from the impatient.'),
  Word('cuisine', 'chuck', 'n.', 'A heavily worked, flavorful cut from the shoulder', 'Chuck makes the best burger and the best pot roast.'),
  Word('cuisine', 'short rib', 'n.', 'A meaty rib cut prized for braising', 'Korean short rib gets sliced thin across the bones for galbi.'),
  Word('cuisine', 'oxtail', 'n.', 'The tail of the cow, gelatinous when braised', 'Oxtail stew is the gold standard of slow Sunday cooking.'),
  Word('cuisine', 'shank', 'n.', 'The lower leg cut, perfect for long braises', 'A braised lamb shank falls off the bone with a fork.'),
  Word('cuisine', 'cheek', 'n.', 'A muscular braising cut from the face', 'Beef cheek braised in red wine eats like the richest brisket.'),
  Word('cuisine', 'tongue', 'n.', 'A tender braising cut, often pickled or smoked', 'Beef tongue in tacos is creamier than any steak.'),
  Word('cuisine', 'sweetbreads', 'n.', 'The thymus or pancreas, prized as offal', 'Crisped sweetbreads taste like the world\'s best chicken nuggets.'),
  Word('cuisine', 'foie gras', 'n.', 'Fattened duck or goose liver', 'A torchon of foie gras is silkier than any pâté.'),
  Word('cuisine', 'pork belly', 'n.', 'The fatty cut from the underside of the pig', 'Pork belly cooks long and slow until the fat surrenders.'),
  Word('cuisine', 'spare rib', 'n.', 'A rib cut from the pig\'s belly side', 'Spare ribs need a low-and-slow smoke for hours.'),
  Word('cuisine', 'baby back', 'n.', 'A leaner rib cut from the pig\'s loin', 'Baby backs cook quicker than spare ribs but with less collagen.'),
  Word('cuisine', 'pork shoulder', 'n.', 'A tough collagen-rich cut perfect for pulling', 'Pork shoulder turns into the most forgiving roast around.'),
  Word('cuisine', 'jowl', 'n.', 'The cheek meat of the pig, often cured', 'Cure the jowl and you get guanciale.'),
  Word('cuisine', 'trotter', 'n.', 'A pig\'s foot used for body in stocks and braises', 'Slip a trotter into the broth for that gelatin pull.'),
  Word('cuisine', 'lamb saddle', 'n.', 'A cut spanning the loins on both sides of the lamb', 'A roast saddle of lamb feeds a holiday table.'),
  Word('cuisine', 'rack', 'n.', 'A roast of rib bones, often Frenched', 'A rack of lamb with herbs is a centerpiece roast.'),
  Word('cuisine', 'French', 'v.', 'To clean meat off the end of a rib bone', 'French the rack so the bones present clean on the plate.'),
  Word('cuisine', 'dry-age', 'v.', 'To age beef in cool dry conditions to concentrate flavor', 'A 45-day dry-aged ribeye tastes funky and incredible.'),
  Word('cuisine', 'wet-age', 'v.', 'To age beef sealed in its own juices', 'Most steaks are wet-aged in a vacuum bag for two weeks.'),
  Word('cuisine', 'wagyu', 'n.', 'Japanese cattle prized for marbling', 'A5 wagyu is so rich a few ounces feels like a meal.'),
  Word('cuisine', 'fond', 'n.', 'The browned bits stuck to the pan after searing', 'The fond is where the flavor lives — never waste it.'),
  Word('cuisine', 'liaison', 'n.', 'A mixture of egg yolk and cream used to finish sauces', 'Whisk a little hot broth into the liaison before adding it back.'),
  Word('cuisine', 'slurry', 'n.', 'A thickener of starch dispersed in cold liquid', 'Stir the cornstarch slurry in at the end to thicken the sauce.'),
  Word('cuisine', 'monter au beurre', 'phr.', 'To finish a sauce by whisking in cold butter', 'Monter au beurre just before plating for a glossy finish.'),
  Word('cuisine', 'emulsify', 'v.', 'To suspend one liquid in another, like oil in vinegar', 'Whisk hard to emulsify the vinaigrette until cloudy.'),
  Word('cuisine', 'lecithin', 'n.', 'A natural emulsifier found in egg yolks and soy', 'Lecithin in the yolk holds hollandaise together.'),
  Word('cuisine', 'Maillard reaction', 'n.', 'The browning of proteins and sugars with heat', 'The Maillard reaction is what makes seared steak smell so good.'),
  Word('cuisine', 'syrup stage', 'n.', 'A specific temperature point in cooked sugar', 'Cook the sugar to the soft-ball stage at 235 degrees.'),
  Word('cuisine', 'crystallize', 'v.', 'To form sugar crystals out of a syrup', 'Brush the pan sides with water so the syrup doesn\'t crystallize.'),
  Word('cuisine', 'invert sugar', 'n.', 'A liquid sugar that resists crystallization', 'A spoon of invert sugar keeps the sorbet smooth in the freezer.'),
  Word('cuisine', 'gluten', 'n.', 'A protein network formed when wheat is hydrated', 'A long autolyse builds gluten without much kneading.'),
  Word('cuisine', 'autolyse', 'n.', 'A rest period for flour and water before mixing', 'A 45-minute autolyse makes the dough silkier to work.'),
  Word('cuisine', 'levain', 'n.', 'A natural leavening of fermented flour and water', 'Feed the levain twelve hours before mixing the bread.'),
  Word('cuisine', 'poolish', 'n.', 'A wet pre-ferment used in bread baking', 'A poolish overnight gives the baguette its open crumb.'),
  Word('cuisine', 'biga', 'n.', 'A stiff Italian pre-ferment', 'Ciabatta starts with a biga left out overnight.'),
  Word('cuisine', 'crumb', 'n.', 'The interior structure of a bread loaf', 'The crumb on this loaf is open and glossy.'),
  Word('cuisine', 'crust', 'n.', 'The outer browned shell of bread', 'A crackly crust comes from steam in the first ten minutes.'),
  Word('cuisine', 'oven spring', 'n.', 'The final rise of bread in the first minutes of baking', 'A good slash on the loaf encourages oven spring.'),
  Word('cuisine', 'bulk fermentation', 'n.', 'The first long rise of bread dough', 'Watch the bulk fermentation rather than the clock.'),
  Word('cuisine', 'banneton', 'n.', 'A rattan basket for proofing bread loaves', 'Dust the banneton with rice flour so the loaf releases clean.'),
  Word('cuisine', 'lame', 'n.', 'A razor blade used to score bread', 'A sharp lame slashes the loaf without dragging the dough.'),
  Word('cuisine', 'scoring', 'n.', 'Slashing bread before baking to direct the rise', 'Scoring controls where the loaf opens up in the oven.'),
  Word('cuisine', 'docking', 'n.', 'Pricking dough to prevent puffing', 'Dock the tart shell before blind baking.'),
  Word('cuisine', 'blind bake', 'v.', 'To bake a pastry shell without filling', 'Blind bake the crust with weights so it doesn\'t shrink.'),
  Word('cuisine', 'pie weights', 'n.', 'Heavy beads used to weigh down blind-baked crusts', 'Dried beans work fine as pie weights in a pinch.'),
  Word('cuisine', 'egg wash', 'n.', 'A beaten egg brushed onto pastry for sheen', 'A second coat of egg wash gives the pie crust extra shine.'),
  Word('cuisine', 'piping bag', 'n.', 'A cone-shaped bag for shaping soft mixtures', 'Pipe the meringue rosettes through a star tip.'),
  Word('cuisine', 'plating', 'n.', 'The arrangement of food on the dish', 'The plating tells the diner what to taste first.'),
  Word('cuisine', 'fleur de sel', 'n.', 'A delicate hand-harvested sea salt', 'A pinch of fleur de sel finishes a chocolate tart beautifully.'),
  Word('cuisine', 'flaky salt', 'n.', 'A crunchy textured salt for finishing', 'Sprinkle flaky salt on the cookies right out of the oven.'),
  Word('cuisine', 'kosher salt', 'n.', 'A coarse-flaked salt favored in restaurants', 'Kosher salt is easy to pinch and to feel between your fingers.'),
  Word('cuisine', 'rock salt', 'n.', 'Large unrefined salt crystals', 'Roast the beets buried in rock salt for concentrated flavor.'),
  Word('cuisine', 'capers', 'n.', 'The pickled flower buds of a Mediterranean bush', 'Fry the capers until they crisp into salty little blossoms.'),
  Word('cuisine', 'caperberries', 'n.', 'The larger fruits of the caper bush', 'Caperberries are perfect martini garnishes.'),
  Word('cuisine', 'anchovy', 'n.', 'A small oily fish often cured', 'A pounded anchovy disappears into the sauce but lifts everything.'),
  Word('cuisine', 'sardine', 'n.', 'A small oily fish, often tinned in oil', 'Good tinned sardines on toast with lemon is lunch.'),
  Word('cuisine', 'mackerel', 'n.', 'A rich oily fish with firm flesh', 'Smoked mackerel pâté is the easiest hors d\'oeuvre I know.'),
  Word('cuisine', 'bluefin', 'n.', 'A large prized tuna species', 'Bluefin toro melts in the mouth like edible butter.'),
  Word('cuisine', 'toro', 'n.', 'The fatty belly cut of tuna', 'A single piece of o-toro can cost more than the rest of the omakase.'),
  Word('cuisine', 'halibut', 'n.', 'A large mild flatfish', 'Pan-roasted halibut with brown butter is restaurant-ready.'),
  Word('cuisine', 'turbot', 'n.', 'A prized European flatfish', 'A whole roast turbot is a celebratory plate.'),
  Word('cuisine', 'dover sole', 'n.', 'A delicate European flatfish', 'Dover sole meunière is an old-school steakhouse classic.'),
  Word('cuisine', 'monkfish', 'n.', 'A firm-fleshed fish nicknamed poor man\'s lobster', 'Monkfish stays meaty whether you grill it or braise it.'),
  Word('cuisine', 'branzino', 'n.', 'A Mediterranean sea bass', 'Roast the whole branzino on a bed of fennel and lemon.'),
  Word('cuisine', 'snapper', 'n.', 'A reddish ocean fish with firm flesh', 'Crispy-skin snapper over a tomato broth never disappoints.'),
  Word('cuisine', 'dorade', 'n.', 'A European sea bream', 'Grill the dorade whole with rosemary and sea salt.'),
  Word('cuisine', 'cod', 'n.', 'A mild white-fleshed ocean fish', 'Salt cod is the foundation of Portuguese bacalhau dishes.'),
  Word('cuisine', 'bacalao', 'n.', 'Salt-cured cod popular across the Mediterranean', 'Soak the bacalao in cold water overnight before cooking.'),
  Word('cuisine', 'mussels', 'n.', 'Bivalve mollusks cooked in shells', 'Steam the mussels with white wine and shallot for moules marinière.'),
  Word('cuisine', 'clams', 'n.', 'A bivalve mollusk eaten raw or cooked', 'Steam the clams with garlic and chili until they pop open.'),
  Word('cuisine', 'oysters', 'n.', 'Bivalve mollusks usually eaten raw', 'A dozen oysters with mignonette and a glass of muscadet.'),
  Word('cuisine', 'mignonette', 'n.', 'A vinegar-shallot sauce for raw oysters', 'A spoon of mignonette on a Kumamoto is briny perfection.'),
  Word('cuisine', 'shucking', 'n.', 'The act of opening shellfish from their shells', 'Shucking oysters fast is a bar skill worth learning.'),
  Word('cuisine', 'scallops', 'n.', 'Sweet adductor-muscle bivalves', 'Sear the scallops hard in a hot pan and don\'t move them.'),
  Word('cuisine', 'lobster roll', 'n.', 'A New England sandwich of buttered lobster on a bun', 'Maine lobster roll cold with mayo or Connecticut hot with butter — pick your side.'),
  Word('cuisine', 'langoustine', 'n.', 'A small lobster-like crustacean', 'Langoustine in butter is one of Europe\'s great luxuries.'),
  Word('cuisine', 'prawn', 'n.', 'A larger shrimp-like crustacean', 'Whole tiger prawns over wood charcoal are the pride of a Galician dinner.'),
  Word('cuisine', 'crawfish', 'n.', 'A small freshwater crustacean', 'A Louisiana crawfish boil takes a heap of newspaper and a cold beer.'),
  Word('cuisine', 'soft-shell', 'adj.', 'Of a crab during its molting season', 'Soft-shell crab dredged in flour and fried whole is summer magic.'),
  Word('cuisine', 'roe', 'n.', 'Fish or shellfish eggs', 'A spoon of trout roe pops salty on every bite.'),
  Word('cuisine', 'ikura', 'n.', 'Salmon roe seasoned for sushi', 'Ikura over rice with shiso is breakfast in Hokkaido.'),
  Word('cuisine', 'uni', 'n.', 'The edible gonads of sea urchin', 'A piece of uni nigiri tastes like the ocean itself.'),
  Word('cuisine', 'caviar', 'n.', 'Salt-cured sturgeon roe', 'Caviar belongs on a mother-of-pearl spoon, never a metal one.'),
  Word('cuisine', 'beluga', 'n.', 'A prized large sturgeon caviar', 'Beluga grains are larger and creamier than osetra.'),
  Word('cuisine', 'osetra', 'n.', 'A nutty grade of sturgeon caviar', 'Osetra has a clean briny pop and a hazelnut finish.'),
  Word('cuisine', 'sweet vermouth', 'n.', 'A reddish aromatized fortified wine', 'Sweet vermouth pulls a Manhattan together.'),
  Word('cuisine', 'champagne', 'n.', 'A sparkling wine from the French region of the same name', 'Open the champagne with a sigh, never a pop.'),
  Word('cuisine', 'prosecco', 'n.', 'An Italian sparkling wine from the Veneto', 'A glass of cold prosecco starts every Italian aperitivo.'),
  Word('cuisine', 'crémant', 'n.', 'A French sparkling wine made outside Champagne', 'Crémant de Bourgogne delivers Champagne style at a friendlier price.'),
  Word('cuisine', 'rosé', 'n.', 'A pink wine made from briefly skinned red grapes', 'A dry Provence rosé on a hot terrace is hard to beat.'),
  Word('cuisine', 'natural wine', 'n.', 'Wine made with minimal additives or filtration', 'Natural wine is funky, cloudy, and divisive.'),
  Word('cuisine', 'orange wine', 'n.', 'A white wine made on its skins', 'Orange wine drinks like a tannic, savory white.'),
  Word('cuisine', 'vintage', 'n.', 'The year of grape harvest for a wine', 'A great vintage can lift even a modest producer.'),
  Word('cuisine', 'corkage', 'n.', 'A fee for opening a wine you brought yourself', 'The corkage fee is twenty-five dollars a bottle.'),
  Word('cuisine', 'tannin', 'n.', 'A drying compound in wine and tea', 'High tannin reds want a fatty steak to soften them.'),
  Word('cuisine', 'acidity', 'n.', 'The bright sharp character of a wine or dish', 'A vinaigrette without acidity is just dressed leaves.'),
  Word('cuisine', 'nose', 'n.', 'The aroma of a wine or spirit', 'The wine has a nose of cherry and tobacco.'),
  Word('cuisine', 'legs', 'n.', 'The drips a wine leaves on the glass', 'The legs tell you only that there\'s alcohol in the glass.'),
  Word('cuisine', 'corked', 'adj.', 'Of a wine spoiled by TCA contamination', 'The wine smelled like a wet basement — definitely corked.'),
  Word('cuisine', 'mocktail', 'n.', 'A non-alcoholic cocktail', 'A serious mocktail program is finally getting the respect it deserves.'),
  Word('cuisine', 'highball', 'n.', 'A simple cocktail of spirit and a long mixer', 'A Japanese highball with sparkling water and ice is a perfect aperitif.'),
  Word('cuisine', 'shrub', 'n.', 'A vinegar-based fruit syrup for cocktails', 'A raspberry shrub in soda water cuts through a heavy meal.'),
  Word('cuisine', 'oleo saccharum', 'n.', 'A sugar-citrus oil extraction used in punches', 'Oleo saccharum is the secret behind a great punch base.'),
  Word('cuisine', 'kombucha', 'n.', 'A fermented sweetened tea', 'A glass of kombucha takes the place of beer at the table for me.'),
  Word('cuisine', 'kefir', 'n.', 'A tangy fermented milk drink', 'Kefir in the smoothie thickens it and adds gut-friendly bacteria.'),
  Word('cuisine', 'lacto-ferment', 'v.', 'To preserve by encouraging lactic-acid bacteria', 'Lacto-ferment the cucumbers in 2 percent brine for a week.'),
  Word('cuisine', 'koji', 'n.', 'A grain inoculated with Aspergillus oryzae', 'Koji breaks down protein into umami compounds.'),
  Word('cuisine', 'shio koji', 'n.', 'A Japanese marinade of koji, salt, and water', 'Marinate the fish in shio koji overnight for instant tenderness.'),
  Word('cuisine', 'natto', 'n.', 'A pungent fermented Japanese soybean dish', 'Natto is sticky, stringy, and an acquired taste.'),
  Word('cuisine', 'tempeh', 'n.', 'A firm Indonesian fermented soybean cake', 'Sear the tempeh hard so it crisps on the outside.'),
  Word('cuisine', 'sauerkraut', 'n.', 'Fermented shredded cabbage', 'A jar of sauerkraut on top of a hot dog is mandatory.'),
  Word('cuisine', 'vegan', 'adj.', 'Containing no animal products of any kind', 'The chef built a serious vegan tasting menu out of garden produce.'),
  Word('cuisine', 'vegetarian', 'adj.', 'Free of meat but possibly using dairy or eggs', 'Vegetarian Indian cooking is some of the best on earth.'),
  Word('cuisine', 'pescatarian', 'adj.', 'Vegetarian except for fish and shellfish', 'The pescatarian menu hides nothing in the broths.'),
  Word('cuisine', 'kosher', 'adj.', 'Conforming to Jewish dietary law', 'The kosher kitchen separates meat and dairy entirely.'),
  Word('cuisine', 'halal', 'adj.', 'Conforming to Islamic dietary law', 'Halal certification covers the slaughter and the handling.'),
  Word('cuisine', 'briny', 'adj.', 'Tasting of clean salty seawater', 'A briny oyster on ice tastes like the bay it came from.'),
  Word('cuisine', 'funky', 'adj.', 'Pleasantly fermented or barnyardy in flavor', 'The funky cheese stinks up the room and makes me smile.'),
  Word('cuisine', 'bracing', 'adj.', 'Sharply refreshing, often with acidity', 'A bracing gin and tonic resets the palate.'),
  Word('cuisine', 'lacquered', 'adj.', 'Glossy from a glaze of sugar or sauce', 'The lacquered duck breast caught the light like polished wood.'),
  Word('cuisine', 'blistered', 'adj.', 'Charred in patches under intense heat', 'Blistered shishito peppers with flaky salt disappear in minutes.'),
  Word('cuisine', 'silky', 'adj.', 'Smoothly textured on the tongue', 'A silky parsnip purée under the lamb is restaurant move number one.'),
  Word('cuisine', 'gamy', 'adj.', 'Tasting of wild meat with strong character', 'Venison is gamy in the best way when handled correctly.'),
  Word('cuisine', 'astringent', 'adj.', 'Drying and puckering on the palate', 'Young red wine can be astringent before it softens with age.'),
  Word('cuisine', 'bitter', 'adj.', 'Sharply unsweet, like coffee or radicchio', 'A bitter green like dandelion cuts through a rich dressing.'),
];
