import 'words_data.dart';

const kCuisineExtras2 = <Word>[
  Word('cuisine', 'curdle', 'v.', 'to cause milk or a sauce to separate into solid and liquid parts', 'High heat made the cream curdle in the pan.'),
  Word('cuisine', 'frothy', 'adj.', 'full of or covered with a light, airy foam', 'The barista poured a frothy layer over the latte.'),
  Word('cuisine', 'savor', 'v.', 'to taste and enjoy food slowly and fully', 'She paused to savor each bite of the dessert.'),
  Word('cuisine', 'palatable', 'adj.', 'pleasant enough to eat or drink', 'A pinch of salt made the broth far more palatable.'),
  Word('cuisine', 'succulent', 'adj.', 'tender, juicy, and tasty', 'The slow-roasted lamb was wonderfully succulent.'),
  Word('cuisine', 'zesty', 'adj.', 'having a fresh, sharp, lively flavor', 'A zesty lemon dressing brightened the salad.'),
  Word('cuisine', 'mellow', 'adj.', 'smooth and full in flavor, not harsh', 'Aging gave the cheese a mellow, nutty taste.'),
  Word('cuisine', 'robust', 'adj.', 'strong, rich, and full-bodied in flavor', 'The stew had a robust, meaty depth.'),
  Word('cuisine', 'delicate', 'adj.', 'subtle and easily overwhelmed in flavor', 'The fish has a delicate taste best left unspiced.'),
  Word('cuisine', 'rancid', 'adj.', 'tasting or smelling unpleasant due to spoiled fat', 'The old butter had turned rancid.'),
  Word('cuisine', 'effervescence', 'n.', 'the quality of bubbling or giving off small bubbles', 'The wine\'s effervescence tickled the palate.'),
  Word('cuisine', 'viscous', 'adj.', 'thick and sticky in consistency', 'Reduce the sauce until it becomes viscous.'),
  Word('cuisine', 'tangy', 'adj.', 'having a sharp, slightly sour taste', 'The tangy yogurt cut through the rich curry.'),
  Word('cuisine', 'smoky', 'adj.', 'having the flavor or aroma of smoke', 'Grilling gave the eggplant a smoky character.'),
  Word('cuisine', 'earthy', 'adj.', 'having a flavor reminiscent of soil or root vegetables', 'Mushrooms lend an earthy note to the risotto.'),
  Word('cuisine', 'nutty', 'adj.', 'tasting of nuts', 'Toasting brings out the grain\'s nutty flavor.'),
  Word('cuisine', 'velvet', 'n.', 'a Chinese coating technique giving meat a smooth texture', 'The chef used velvet to keep the chicken silky.'),
  Word('cuisine', 'dredge', 'v.', 'to coat food lightly with flour or another dry mixture', 'Dredge the cutlets before frying them.'),
  Word('cuisine', 'caramel', 'n.', 'sugar heated until it browns and develops a rich flavor', 'She drizzled warm caramel over the flan.'),
  Word('cuisine', 'truffle', 'n.', 'a prized aromatic fungus used to flavor dishes', 'Shaved truffle elevated the simple pasta.'),
  Word('cuisine', 'paprika', 'n.', 'a spice made from ground dried peppers', 'Smoked paprika gave the dish a deep red hue.'),
  Word('cuisine', 'coriander', 'n.', 'the seeds of the cilantro plant used as a spice', 'Toast the coriander before grinding it.'),
  Word('cuisine', 'cumin', 'n.', 'an earthy, warm spice common in many cuisines', 'Cumin is essential to a good chili.'),
  Word('cuisine', 'nutmeg', 'n.', 'a warm, sweet spice grated from a hard seed', 'A grating of nutmeg finished the béchamel.'),
  Word('cuisine', 'cinnamon', 'n.', 'a fragrant spice from tree bark', 'Cinnamon scented the simmering apples.'),
  Word('cuisine', 'clove', 'n.', 'a pungent dried flower bud used as a spice', 'Stud the ham with whole cloves.'),
  Word('cuisine', 'allspice', 'n.', 'a spice tasting of clove, cinnamon, and nutmeg combined', 'Allspice gives jerk seasoning its warmth.'),
  Word('cuisine', 'thyme', 'n.', 'an aromatic herb used in savory cooking', 'A sprig of thyme flavored the roast.'),
  Word('cuisine', 'rosemary', 'n.', 'a fragrant woody herb used with meats', 'She tucked rosemary under the lamb.'),
  Word('cuisine', 'tarragon', 'n.', 'an herb with a mild anise-like flavor', 'Tarragon brightens a classic béarnaise.'),
  Word('cuisine', 'oregano', 'n.', 'a pungent herb common in Mediterranean cooking', 'Dried oregano seasoned the tomato sauce.'),
  Word('cuisine', 'cilantro', 'n.', 'the fresh leaves of the coriander plant', 'Garnish the tacos with chopped cilantro.'),
  Word('cuisine', 'dill', 'n.', 'a feathery herb used with fish and pickles', 'Fresh dill pairs beautifully with salmon.'),
  Word('cuisine', 'sage', 'n.', 'an aromatic herb often used with pork or poultry', 'Fried sage leaves topped the gnocchi.'),
  Word('cuisine', 'marjoram', 'n.', 'a sweet, mild herb related to oregano', 'Marjoram lends a gentle floral note to sausage.'),
  Word('cuisine', 'chervil', 'n.', 'a delicate herb with a faint anise flavor', 'Chervil garnished the spring soup.'),
  Word('cuisine', 'bay leaf', 'n.', 'an aromatic leaf used to flavor simmered dishes', 'Add a bay leaf to the simmering stock.'),
  Word('cuisine', 'peppercorn', 'n.', 'the dried berry ground to make pepper', 'Crush the peppercorns coarsely for the crust.'),
  Word('cuisine', 'shallot', 'n.', 'a small, mild member of the onion family', 'Mince a shallot for the vinaigrette.'),
  Word('cuisine', 'leek', 'n.', 'a mild onion relative with a long white stalk', 'Sweat the leeks until soft.'),
  Word('cuisine', 'scallion', 'n.', 'a young onion with a small bulb and green top', 'Scatter sliced scallions over the noodles.'),
  Word('cuisine', 'chive', 'n.', 'a slender herb with a mild onion flavor', 'Snip fresh chives onto the baked potato.'),
  Word('cuisine', 'fennel', 'n.', 'a crisp bulb vegetable with an anise flavor', 'Shaved fennel added crunch to the salad.'),
  Word('cuisine', 'artichoke', 'n.', 'an edible flower bud eaten as a vegetable', 'They braised the artichoke hearts in oil.'),
  Word('cuisine', 'eggplant', 'n.', 'a glossy purple vegetable used in many cuisines', 'Salt the eggplant to draw out bitterness.'),
  Word('cuisine', 'zucchini', 'n.', 'a tender summer squash', 'She grated zucchini into the fritters.'),
  Word('cuisine', 'endive', 'n.', 'a slightly bitter leafy salad vegetable', 'Endive leaves held the savory filling.'),
  Word('cuisine', 'radicchio', 'n.', 'a bitter red-leaved chicory used in salads', 'Grilling tames the bite of radicchio.'),
  Word('cuisine', 'arugula', 'n.', 'a peppery salad green', 'Peppery arugula topped the pizza.'),
  Word('cuisine', 'watercress', 'n.', 'a peppery leafy green grown in water', 'Watercress added a sharp note to the sandwich.'),
  Word('cuisine', 'kale', 'n.', 'a hardy leafy green cabbage relative', 'Massage the kale to soften the leaves.'),
  Word('cuisine', 'chard', 'n.', 'a leafy green with edible colorful stalks', 'Sauté the chard with garlic and oil.'),
  Word('cuisine', 'okra', 'n.', 'a green pod vegetable used to thicken stews', 'Okra gives gumbo its body.'),
  Word('cuisine', 'parsnip', 'n.', 'a sweet, pale root vegetable', 'Roasted parsnips caramelize beautifully.'),
  Word('cuisine', 'turnip', 'n.', 'a round root vegetable with a mild peppery taste', 'Mash the turnips with butter.'),
  Word('cuisine', 'rutabaga', 'n.', 'a large yellow root vegetable, a turnip relative', 'Rutabaga sweetens as it roasts.'),
  Word('cuisine', 'celeriac', 'n.', 'the knobby edible root of celery', 'Celeriac makes a silky purée.'),
  Word('cuisine', 'kohlrabi', 'n.', 'a crisp, mild bulbous vegetable', 'Slice the kohlrabi thin for a slaw.'),
  Word('cuisine', 'shiitake', 'n.', 'a meaty brown Asian mushroom', 'Shiitake mushrooms deepened the broth.'),
  Word('cuisine', 'chanterelle', 'n.', 'a golden, funnel-shaped wild mushroom', 'Sautéed chanterelles topped the toast.'),
  Word('cuisine', 'porcini', 'n.', 'a prized woodland mushroom with rich flavor', 'Dried porcini intensified the sauce.'),
  Word('cuisine', 'morel', 'n.', 'a honeycombed wild spring mushroom', 'Morels are a fleeting springtime treat.'),
  Word('cuisine', 'pickling', 'n.', 'the process of preserving food in brine or vinegar', 'Pickling keeps the cucumbers crisp for weeks.'),
  Word('cuisine', 'curing', 'n.', 'preserving meat or fish with salt, smoke, or air', 'Curing the pork takes several weeks.'),
  Word('cuisine', 'smoking', 'n.', 'flavoring and preserving food with wood smoke', 'Smoking gives the brisket its bark.'),
  Word('cuisine', 'fermentation', 'n.', 'the breakdown of sugars by microbes to develop flavor', 'Fermentation gives kimchi its tang.'),
  Word('cuisine', 'proofing', 'n.', 'letting dough rise before baking', 'Proofing the dough doubled its size.'),
  Word('cuisine', 'kneading', 'n.', 'working dough to develop its gluten', 'Kneading gives bread its chewy structure.'),
  Word('cuisine', 'whisking', 'n.', 'beating ingredients rapidly to combine or aerate', 'Constant whisking prevented lumps in the gravy.'),
  Word('cuisine', 'folding', 'n.', 'gently combining a light mixture into a heavier one', 'Careful folding keeps the soufflé airy.'),
  Word('cuisine', 'searing', 'n.', 'browning a surface quickly over high heat', 'A hard searing locks in the steak\'s juices.'),
  Word('cuisine', 'roasting', 'n.', 'cooking food with dry heat in an oven', 'Slow roasting tenderized the tough cut.'),
  Word('cuisine', 'poaching', 'n.', 'cooking gently in barely simmering liquid', 'Poaching keeps the eggs soft and tender.'),
  Word('cuisine', 'steaming', 'n.', 'cooking food over boiling water with vapor', 'Steaming preserves the dumplings\' delicate skin.'),
  Word('cuisine', 'braising', 'n.', 'cooking food slowly in a little liquid in a covered pot', 'Braising melts the connective tissue.'),
  Word('cuisine', 'grilling', 'n.', 'cooking over an open flame or hot grate', 'Grilling left attractive char marks on the corn.'),
  Word('cuisine', 'frying', 'n.', 'cooking food in hot fat or oil', 'Deep frying gave the fritters a crisp shell.'),
  Word('cuisine', 'mash', 'v.', 'to crush food into a soft pulp', 'Mash the potatoes with warm milk.'),
  Word('cuisine', 'shred', 'v.', 'to cut or tear food into thin strips', 'Shred the cooked pork with two forks.'),
  Word('cuisine', 'grate', 'v.', 'to shred food against a rough surface', 'Grate the cheese over the casserole.'),
  Word('cuisine', 'peel', 'v.', 'to remove the outer skin of a fruit or vegetable', 'Peel the apples before slicing.'),
  Word('cuisine', 'core', 'v.', 'to remove the central hard part of a fruit', 'Core the pears before poaching them.'),
  Word('cuisine', 'pit', 'v.', 'to remove the stone from a fruit', 'Pit the cherries before baking the pie.'),
  Word('cuisine', 'devein', 'v.', 'to remove the dark vein from a shrimp', 'Devein the shrimp before grilling.'),
  Word('cuisine', 'debone', 'v.', 'to remove the bones from meat or fish', 'The cook deboned the chicken thigh.'),
  Word('cuisine', 'skim', 'v.', 'to remove fat or foam from a liquid\'s surface', 'Skim the stock to keep it clear.'),
  Word('cuisine', 'strain', 'v.', 'to separate liquids from solids through a sieve', 'Strain the custard for a smooth texture.'),
  Word('cuisine', 'sift', 'v.', 'to pass dry ingredients through a fine mesh', 'Sift the flour to remove lumps.'),
  Word('cuisine', 'drizzle', 'v.', 'to pour a thin stream of liquid over food', 'Drizzle olive oil over the burrata.'),
  Word('cuisine', 'garnish', 'v.', 'to decorate a dish with a small edible addition', 'Garnish the soup with a swirl of cream.'),
  Word('cuisine', 'plate', 'v.', 'to arrange food attractively on a dish', 'The chef plated each course with precision.'),
  Word('cuisine', 'season', 'v.', 'to add salt, pepper, or other flavorings', 'Season the broth to taste.'),
  Word('cuisine', 'dust', 'v.', 'to sprinkle lightly with a powder', 'Dust the cake with confectioners\' sugar.'),
  Word('cuisine', 'coat', 'v.', 'to cover food with a layer of another ingredient', 'Coat the fish in seasoned breadcrumbs.'),
  Word('cuisine', 'stuff', 'v.', 'to fill the cavity of food with a mixture', 'Stuff the peppers with rice and herbs.'),
  Word('cuisine', 'wilt', 'v.', 'to cook greens briefly until they soften', 'Wilt the spinach in the hot pan.'),
  Word('cuisine', 'toast', 'v.', 'to brown food with dry heat', 'Toast the nuts to deepen their flavor.'),
  Word('cuisine', 'roll out', 'phr.', 'to flatten dough with a rolling pin', 'Roll out the dough to a thin sheet.'),
  Word('cuisine', 'whisk in', 'phr.', 'to incorporate an ingredient by whisking', 'Whisk in the butter off the heat.'),
  Word('cuisine', 'bring to a boil', 'phr.', 'to heat a liquid until it bubbles rapidly', 'Bring to a boil, then lower the heat.'),
  Word('cuisine', 'season to taste', 'phr.', 'to adjust seasoning according to preference', 'Add salt and pepper, then season to taste.'),
  Word('cuisine', 'let rest', 'phr.', 'to allow cooked meat to sit before slicing', 'Let the roast rest for ten minutes.'),
  Word('cuisine', 'set aside', 'phr.', 'to put an ingredient apart for later use', 'Brown the onions and set aside.'),
  Word('cuisine', 'fold in', 'phr.', 'to gently mix a light ingredient into a batter', 'Fold in the egg whites at the end.'),
  Word('cuisine', 'spaetzle', 'n.', 'small soft German egg noodles or dumplings', 'She served the goulash over buttered spaetzle.'),
  Word('cuisine', 'pierogi', 'n.', 'Eastern European stuffed dumplings', 'They filled the pierogi with potato and cheese.'),
  Word('cuisine', 'gyoza', 'n.', 'Japanese pan-fried dumplings', 'The gyoza had a crisp, golden bottom.'),
  Word('cuisine', 'wonton', 'n.', 'a Chinese dumpling often served in soup', 'Each wonton was folded into a tidy purse.'),
  Word('cuisine', 'ravioli', 'n.', 'stuffed pasta pockets', 'The ravioli were filled with ricotta and spinach.'),
  Word('cuisine', 'tortellini', 'n.', 'small ring-shaped stuffed pasta', 'Tortellini floated in the clear broth.'),
  Word('cuisine', 'lasagna', 'n.', 'a baked dish of layered pasta, sauce, and cheese', 'The lasagna emerged bubbling from the oven.'),
  Word('cuisine', 'cannelloni', 'n.', 'large pasta tubes filled and baked', 'The cannelloni were stuffed with veal.'),
  Word('cuisine', 'fettuccine', 'n.', 'flat ribbon-shaped pasta', 'Toss the fettuccine in the creamy sauce.'),
  Word('cuisine', 'linguine', 'n.', 'narrow flat pasta strands', 'Linguine pairs well with clam sauce.'),
  Word('cuisine', 'penne', 'n.', 'short tube pasta cut on the diagonal', 'The penne held the spicy tomato sauce well.'),
  Word('cuisine', 'fusilli', 'n.', 'short spiral-shaped pasta', 'Fusilli traps the pesto in its twists.'),
  Word('cuisine', 'farfalle', 'n.', 'bow-tie shaped pasta', 'Farfalle suits a light vegetable sauce.'),
  Word('cuisine', 'vermicelli', 'n.', 'very thin pasta or noodle strands', 'Rice vermicelli soaked in the warm broth.'),
  Word('cuisine', 'gemelli', 'n.', 'short pasta of two strands twisted together', 'Gemelli clings nicely to a chunky ragù.'),
  Word('cuisine', 'tagliolini', 'n.', 'very thin ribbon pasta', 'Tagliolini cooks in just two minutes.'),
  Word('cuisine', 'ricotta', 'n.', 'a soft, mild fresh Italian cheese', 'Spread ricotta over the warm toast.'),
  Word('cuisine', 'halloumi', 'n.', 'a firm cheese that holds its shape when grilled', 'Grilled halloumi turned golden and squeaky.'),
  Word('cuisine', 'feta', 'n.', 'a tangy, crumbly brined cheese', 'Crumble feta over the Greek salad.'),
  Word('cuisine', 'gruyère', 'n.', 'a firm, nutty Swiss cheese', 'Gruyère melts smoothly into fondue.'),
  Word('cuisine', 'emmental', 'n.', 'a mild Swiss cheese with large holes', 'Emmental gave the sandwich a nutty melt.'),
  Word('cuisine', 'comté', 'n.', 'a rich French mountain cheese', 'Aged comté has deep, savory notes.'),
  Word('cuisine', 'brie', 'n.', 'a soft, creamy cow\'s milk cheese with a bloomy rind', 'The warm brie oozed onto the bread.'),
  Word('cuisine', 'camembert', 'n.', 'a soft, earthy French cheese', 'Baked camembert makes a luscious dip.'),
  Word('cuisine', 'roquefort', 'n.', 'a tangy French blue cheese made from sheep\'s milk', 'Roquefort crumbled over the pear salad.'),
  Word('cuisine', 'stilton', 'n.', 'a rich English blue cheese', 'Stilton paired well with the port.'),
  Word('cuisine', 'havarti', 'n.', 'a mild, buttery Danish cheese', 'Havarti melts well in a grilled sandwich.'),
  Word('cuisine', 'provolone', 'n.', 'a semi-hard Italian cheese with a smooth texture', 'Provolone topped the hot sub.'),
  Word('cuisine', 'asiago', 'n.', 'an Italian cheese ranging from mild to sharp', 'Grate aged asiago over the pasta.'),
  Word('cuisine', 'fontina', 'n.', 'a creamy, semi-soft melting cheese', 'Fontina made the gratin rich and gooey.'),
  Word('cuisine', 'reduction', 'n.', 'a sauce thickened by simmering to concentrate flavor', 'A balsamic reduction glazed the figs.'),
  Word('cuisine', 'marinade', 'n.', 'a seasoned liquid used to flavor and tenderize food', 'The chicken soaked in a citrus marinade.'),
  Word('cuisine', 'dressing', 'n.', 'a sauce used to flavor salads', 'A simple vinaigrette is the best dressing.'),
  Word('cuisine', 'batter', 'n.', 'a thin uncooked mixture of flour and liquid', 'Dip the fish in the cold batter.'),
  Word('cuisine', 'dough', 'n.', 'a thick mixture of flour and liquid for baking', 'Knead the dough until it is smooth.'),
  Word('cuisine', 'leavening', 'n.', 'an agent that makes baked goods rise', 'Baking soda acts as a leavening agent.'),
  Word('cuisine', 'curd', 'n.', 'the solid part formed when milk coagulates', 'The cheesemaker pressed the fresh curd.'),
  Word('cuisine', 'whey', 'n.', 'the watery liquid left after milk curdles', 'Drain the whey from the yogurt.'),
  Word('cuisine', 'stock', 'n.', 'a flavorful liquid made by simmering bones or vegetables', 'A good stock is the base of the soup.'),
  Word('cuisine', 'broth', 'n.', 'a savory liquid made by simmering meat or vegetables', 'Ladle the steaming broth over the noodles.'),
  Word('cuisine', 'condiment', 'n.', 'a flavoring served alongside food', 'Mustard is a classic condiment for sausage.'),
  Word('cuisine', 'relish', 'n.', 'a chopped, pickled condiment', 'Spoon some sweet relish onto the hot dog.'),
  Word('cuisine', 'rind', 'n.', 'the tough outer layer of cheese, fruit, or bacon', 'Trim the rind from the cheese.'),
  Word('cuisine', 'gristle', 'n.', 'tough cartilage in meat', 'Trim the gristle before grilling the steak.'),
  Word('cuisine', 'marrow', 'n.', 'the rich fatty tissue inside bones', 'Roasted marrow spread easily on the toast.'),
  Word('cuisine', 'crackling', 'n.', 'the crisp browned skin of roasted pork', 'The pork crackling shattered satisfyingly.'),
];
