import 'words_data.dart';

const kEmotionsExtras2 = <Word>[
  Word('emotions', 'apprehensive', 'adj.', 'anxious or fearful that something bad will happen', 'She felt apprehensive about her first day at the new job.'),
  Word('emotions', 'indignant', 'adj.', 'feeling or showing anger at something unjust', 'He was indignant when accused of cheating.'),
  Word('emotions', 'wistful', 'adj.', 'having a feeling of vague or regretful longing', 'She gave a wistful smile at the old photograph.'),
  Word('emotions', 'despondent', 'adj.', 'in low spirits from loss of hope or courage', 'He grew despondent after the third rejection letter.'),
  Word('emotions', 'jubilation', 'n.', 'a feeling of great happiness and triumph', 'The crowd erupted in jubilation at the final whistle.'),
  Word('emotions', 'trepidation', 'n.', 'a feeling of fear or agitation about something that may happen', 'She approached the interview with quiet trepidation.'),
  Word('emotions', 'elation', 'n.', 'great happiness and exhilaration', 'A wave of elation swept over him as he crossed the finish line.'),
  Word('emotions', 'disgruntled', 'adj.', 'angry or dissatisfied', 'The disgruntled customer demanded a refund.'),
  Word('emotions', 'contentment', 'n.', 'a state of peaceful happiness and satisfaction', 'She sighed with contentment beside the warm fire.'),
  Word('emotions', 'exasperated', 'adj.', 'intensely irritated and frustrated', 'He was exasperated by the endless delays.'),
  Word('emotions', 'melancholic', 'adj.', 'feeling a thoughtful or gentle sadness', 'The rainy afternoon left her in a melancholic mood.'),
  Word('emotions', 'euphoric', 'adj.', 'feeling intense excitement and happiness', 'She felt euphoric after acing the exam.'),
  Word('emotions', 'aggrieved', 'adj.', 'feeling resentment at having been treated unfairly', 'He felt aggrieved by the unfair criticism.'),
  Word('emotions', 'serene', 'adj.', 'calm, peaceful, and untroubled', 'A serene expression settled over her face.'),
  Word('emotions', 'fretful', 'adj.', 'feeling distress and irritation', 'The fretful child could not settle down for the night.'),
  Word('emotions', 'sorrowful', 'adj.', 'feeling or showing deep distress and sadness', 'She wore a sorrowful look at the farewell.'),
  Word('emotions', 'agitated', 'adj.', 'feeling troubled, nervous, or upset', 'He paced the floor in an agitated state.'),
  Word('emotions', 'disheartened', 'adj.', 'having lost determination or confidence', 'The team felt disheartened after the loss.'),
  Word('emotions', 'vexed', 'adj.', 'annoyed, frustrated, or worried', 'She was vexed by his careless remarks.'),
  Word('emotions', 'anguished', 'adj.', 'experiencing severe mental or emotional pain', 'An anguished cry escaped her lips.'),
  Word('emotions', 'jittery', 'adj.', 'nervous or unable to relax', 'He felt jittery before stepping on stage.'),
  Word('emotions', 'distraught', 'adj.', 'very worried and upset', 'The distraught parents searched for their lost child.'),
  Word('emotions', 'wary', 'adj.', 'feeling cautious about possible danger or problems', 'She was wary of strangers offering favors.'),
  Word('emotions', 'remorseful', 'adj.', 'feeling deep regret for a wrong committed', 'He was remorseful about the hurtful words.'),
  Word('emotions', 'indifferent', 'adj.', 'having no particular interest or concern', 'She seemed indifferent to the outcome.'),
  Word('emotions', 'beleaguered', 'adj.', 'feeling overwhelmed by pressure or troubles', 'The beleaguered manager faced complaints from all sides.'),
  Word('emotions', 'ecstasy', 'n.', 'an overwhelming feeling of great happiness', 'She danced in a state of pure ecstasy.'),
  Word('emotions', 'dejected', 'adj.', 'sad and dispirited', 'He looked dejected after the bad news.'),
  Word('emotions', 'buoyant', 'adj.', 'cheerful and optimistic', 'Her buoyant mood lifted the whole team.'),
  Word('emotions', 'perturbed', 'adj.', 'anxious or unsettled', 'He was perturbed by the strange noise.'),
  Word('emotions', 'rapturous', 'adj.', 'characterized by intense pleasure or enthusiasm', 'The audience gave a rapturous round of applause.'),
  Word('emotions', 'woeful', 'adj.', 'full of sorrow; very sad', 'She told a woeful tale of misfortune.'),
  Word('emotions', 'mournful', 'adj.', 'feeling or expressing sorrow', 'The mournful music suited the somber occasion.'),
  Word('emotions', 'frantic', 'adj.', 'wild with anxiety, fear, or other emotion', 'He made a frantic search for his keys.'),
  Word('emotions', 'composed', 'adj.', 'calm and in control of one\'s feelings', 'She remained composed despite the chaos.'),
  Word('emotions', 'forsaken', 'adj.', 'feeling abandoned and alone', 'He felt forsaken after his friends left.'),
  Word('emotions', 'wretched', 'adj.', 'in a very unhappy or unfortunate state', 'She felt wretched after the argument.'),
  Word('emotions', 'gratified', 'adj.', 'pleased and satisfied', 'He was gratified by their warm response.'),
  Word('emotions', 'flummoxed', 'adj.', 'bewildered or perplexed', 'The riddle left her completely flummoxed.'),
  Word('emotions', 'somber', 'adj.', 'gloomy and serious in mood', 'A somber silence filled the hall.'),
  Word('emotions', 'enraptured', 'adj.', 'filled with intense delight', 'She was enraptured by the symphony.'),
  Word('emotions', 'discontent', 'n.', 'a feeling of dissatisfaction', 'A sense of discontent spread among the workers.'),
  Word('emotions', 'spirited', 'adj.', 'full of energy, enthusiasm, and determination', 'She gave a spirited defense of her ideas.'),
  Word('emotions', 'tormented', 'adj.', 'suffering severe mental anguish', 'He was tormented by feelings of guilt.'),
  Word('emotions', 'lighthearted', 'adj.', 'cheerful and carefree', 'They shared a lighthearted joke over dinner.'),
  Word('emotions', 'queasy', 'adj.', 'feeling slightly uneasy or anxious', 'The thought of the test made her queasy.'),
  Word('emotions', 'radiant', 'adj.', 'showing great joy or happiness', 'The bride looked radiant with happiness.'),
  Word('emotions', 'forlornness', 'n.', 'the state of being lonely and sad', 'A deep forlornness settled over the empty house.'),
  Word('emotions', 'embittered', 'adj.', 'made resentful or angry by misfortune', 'Years of hardship had embittered him.'),
  Word('emotions', 'enthralled', 'adj.', 'captivated and fascinated', 'The children were enthralled by the storyteller.'),
  Word('emotions', 'crabby', 'adj.', 'bad-tempered and irritable', 'He gets crabby when he skips breakfast.'),
  Word('emotions', 'despair', 'n.', 'the complete loss of hope', 'He sank into despair after the diagnosis.'),
  Word('emotions', 'cantankerous', 'adj.', 'bad-tempered and argumentative', 'The cantankerous old man grumbled at everyone.'),
  Word('emotions', 'rejoice', 'v.', 'to feel or show great joy', 'They gathered to rejoice at the good news.'),
  Word('emotions', 'desolation', 'n.', 'a feeling of great unhappiness and loneliness', 'A wave of desolation washed over her.'),
  Word('emotions', 'jaunty', 'adj.', 'having a lively, cheerful, and self-confident manner', 'He walked with a jaunty spring in his step.'),
  Word('emotions', 'apprehension', 'n.', 'anxiety or fear that something bad will happen', 'She felt a flicker of apprehension before the call.'),
  Word('emotions', 'mellow', 'adj.', 'relaxed and free from tension', 'The music put everyone in a mellow mood.'),
  Word('emotions', 'irate', 'adj.', 'extremely angry', 'The irate driver honked at the slow traffic.'),
  Word('emotions', 'tickled', 'adj.', 'amused and pleased', 'She was tickled by his silly antics.'),
  Word('emotions', 'heartbroken', 'adj.', 'suffering from overwhelming grief', 'He was heartbroken when his dog died.'),
  Word('emotions', 'placated', 'adj.', 'made calm or less angry', 'The customer left placated after the apology.'),
  Word('emotions', 'apoplectic', 'adj.', 'overcome with extreme anger; furious', 'He was apoplectic when he saw the bill.'),
  Word('emotions', 'beatific', 'adj.', 'showing or feeling blissful happiness', 'A beatific smile lit her face.'),
  Word('emotions', 'crushed', 'adj.', 'devastated and deeply upset', 'She was crushed by the harsh review.'),
  Word('emotions', 'antsy', 'adj.', 'restless and impatient', 'The kids got antsy on the long drive.'),
  Word('emotions', 'reassured', 'adj.', 'having had doubts or fears removed', 'She felt reassured by his steady voice.'),
  Word('emotions', 'doleful', 'adj.', 'expressing sorrow; mournful', 'The dog gave a doleful whine at the door.'),
  Word('emotions', 'galled', 'adj.', 'irritated and resentful', 'He was galled by the unfair treatment.'),
  Word('emotions', 'sprightly', 'adj.', 'lively and full of energy', 'She felt sprightly after a good night\'s rest.'),
  Word('emotions', 'apprehend', 'v.', 'to anticipate something with anxiety or fear', 'They began to apprehend the worst.'),
  Word('emotions', 'glum', 'adj.', 'looking or feeling dejected; morose', 'He sat glum in the corner all evening.'),
  Word('emotions', 'rattled', 'adj.', 'made nervous or upset', 'The sudden question left her rattled.'),
  Word('emotions', 'fulfilled', 'adj.', 'satisfied through fully developing one\'s feelings', 'She felt fulfilled after years of meaningful work.'),
  Word('emotions', 'huffy', 'adj.', 'easily offended; touchy', 'He got huffy when his idea was ignored.'),
  Word('emotions', 'maudlin', 'adj.', 'self-pityingly or tearfully sentimental', 'He grew maudlin after a few drinks.'),
  Word('emotions', 'unnerved', 'adj.', 'deprived of courage or confidence', 'The eerie silence unnerved the hikers.'),
  Word('emotions', 'exhilarated', 'adj.', 'feeling very happy, animated, or elated', 'She felt exhilarated after the roller coaster.'),
  Word('emotions', 'peeved', 'adj.', 'annoyed or irritated', 'He was peeved at being kept waiting.'),
  Word('emotions', 'tearful', 'adj.', 'crying or about to cry from emotion', 'She gave a tearful goodbye at the station.'),
  Word('emotions', 'contrite', 'adj.', 'feeling remorse for wrongdoing', 'He sent a contrite apology the next day.'),
  Word('emotions', 'spellbound', 'adj.', 'captivated as if by a spell', 'The audience sat spellbound by the performance.'),
  Word('emotions', 'consoled', 'adj.', 'comforted in a time of grief or disappointment', 'She felt consoled by her friend\'s kind words.'),
  Word('emotions', 'disillusioned', 'adj.', 'disappointed in someone or something once admired', 'She grew disillusioned with politics.'),
  Word('emotions', 'rejuvenated', 'adj.', 'feeling restored and refreshed', 'He felt rejuvenated after the vacation.'),
  Word('emotions', 'crotchety', 'adj.', 'irritable and full of complaints', 'The crotchety neighbor scolded the children.'),
  Word('emotions', 'awestruck', 'adj.', 'filled with awe', 'The tourists were awestruck by the canyon.'),
  Word('emotions', 'fervor', 'n.', 'intense and passionate feeling', 'She spoke with great fervor about the cause.'),
  Word('emotions', 'crabbed', 'adj.', 'ill-tempered and sour', 'His crabbed manner put visitors off.'),
  Word('emotions', 'aglow', 'adj.', 'radiant with warmth, color, or happiness', 'Her face was aglow with excitement.'),
  Word('emotions', 'distressed', 'adj.', 'suffering from anxiety, sorrow, or pain', 'She was distressed by the bad news.'),
  Word('emotions', 'panicky', 'adj.', 'feeling or showing sudden uncontrollable fear', 'She got panicky when the lights went out.'),
  Word('emotions', 'mirth', 'n.', 'amusement expressed in laughter', 'The room filled with mirth at the joke.'),
  Word('emotions', 'cowed', 'adj.', 'intimidated and subdued by fear', 'The cowed recruits obeyed without question.'),
  Word('emotions', 'overwrought', 'adj.', 'in a state of nervous excitement or anxiety', 'She was overwrought after the long ordeal.'),
  Word('emotions', 'frazzled', 'adj.', 'exhausted and emotionally worn out', 'By Friday she felt completely frazzled.'),
  Word('emotions', 'wonderstruck', 'adj.', 'filled with wonder or amazement', 'The child stood wonderstruck before the fireworks.'),
  Word('emotions', 'grieving', 'adj.', 'feeling deep sorrow over a loss', 'The grieving widow received many letters.'),
  Word('emotions', 'spiteful', 'adj.', 'showing a desire to hurt or offend', 'She made a spiteful remark about his work.'),
  Word('emotions', 'morbid', 'adj.', 'having an abnormal preoccupation with gloom', 'He had a morbid fascination with disaster.'),
  Word('emotions', 'irked', 'adj.', 'annoyed or irritated', 'The constant noise irked the neighbors.'),
  Word('emotions', 'sprezzatura', 'n.', 'an emotional ease that conceals real effort', 'He answered the tough question with sprezzatura.'),
  Word('emotions', 'enchantment', 'n.', 'a feeling of great pleasure; delight', 'The garden held a quiet enchantment for her.'),
  Word('emotions', 'dispirited', 'adj.', 'having lost enthusiasm and hope', 'The dispirited workers trudged home.'),
  Word('emotions', 'zealous', 'adj.', 'full of energetic and passionate feeling', 'He was zealous in support of the team.'),
  Word('emotions', 'aggravated', 'adj.', 'annoyed and provoked', 'She was aggravated by the slow service.'),
  Word('emotions', 'sentimental', 'adj.', 'prompted by tender or nostalgic feelings', 'He felt sentimental looking at old letters.'),
  Word('emotions', 'rankled', 'adj.', 'caused persistent annoyance or resentment', 'The insult rankled for days.'),
  Word('emotions', 'beaming', 'adj.', 'smiling broadly out of happiness', 'She came in beaming with the good news.'),
  Word('emotions', 'desperation', 'n.', 'a state of despair leading to rash behavior', 'In desperation, he begged for help.'),
  Word('emotions', 'jocular', 'adj.', 'fond of or characterized by joking', 'His jocular mood lightened the meeting.'),
  Word('emotions', 'shaken', 'adj.', 'emotionally disturbed or upset', 'She was visibly shaken by the accident.'),
  Word('emotions', 'rhapsodic', 'adj.', 'extravagantly enthusiastic or ecstatic', 'He grew rhapsodic describing the sunset.'),
  Word('emotions', 'sulkiness', 'n.', 'a mood of silent bad temper', 'His sulkiness lasted the whole afternoon.'),
  Word('emotions', 'consternation', 'n.', 'feelings of anxiety or dismay', 'To her consternation, the door was locked.'),
  Word('emotions', 'gladness', 'n.', 'the feeling of being happy', 'A quiet gladness filled the reunion.'),
  Word('emotions', 'fuming', 'adj.', 'feeling great anger', 'He was fuming after the rude email.'),
  Word('emotions', 'tenderhearted', 'adj.', 'having a kind and gentle disposition', 'The tenderhearted nurse comforted every patient.'),
  Word('emotions', 'disquiet', 'n.', 'a feeling of anxiety or worry', 'A sense of disquiet hung over the town.'),
  Word('emotions', 'beguilement', 'n.', 'the state of being charmed or delighted', 'There was a gentle beguilement in her gaze.'),
  Word('emotions', 'enliven', 'v.', 'to make more cheerful or lively', 'The music helped to enliven the party.'),
  Word('emotions', 'mortification', 'n.', 'a feeling of great embarrassment or shame', 'To his mortification, he forgot her name.'),
  Word('emotions', 'tantalized', 'adj.', 'tormented by desire for something out of reach', 'She was tantalized by the smell of fresh bread.'),
  Word('emotions', 'agonized', 'adj.', 'expressing intense suffering', 'He gave an agonized groan.'),
  Word('emotions', 'titillated', 'adj.', 'pleasantly excited or stimulated', 'The audience was titillated by the gossip.'),
  Word('emotions', 'soothed', 'adj.', 'made calm and less distressed', 'The baby was soothed by the gentle rocking.'),
  Word('emotions', 'sheepishness', 'n.', 'embarrassment from shame or shyness', 'He admitted his error with sheepishness.'),
  Word('emotions', 'verklempt', 'adj.', 'overcome with emotion', 'She got verklempt during the toast.'),
  Word('emotions', 'fidgety', 'adj.', 'restless and uneasy', 'He grew fidgety during the long lecture.'),
  Word('emotions', 'gloating', 'adj.', 'feeling smug pleasure at another\'s misfortune', 'She wore a gloating smile after winning.'),
  Word('emotions', 'wonderment', 'n.', 'a state of awed admiration or respect', 'The night sky filled them with wonderment.'),
  Word('emotions', 'demoralized', 'adj.', 'having lost confidence or hope', 'The team felt demoralized after the defeat.'),
  Word('emotions', 'effervescent', 'adj.', 'vivacious and enthusiastic', 'Her effervescent laughter filled the room.'),
  Word('emotions', 'shuddering', 'adj.', 'trembling from fear or revulsion', 'A shuddering dread gripped him.'),
  Word('emotions', 'comforted', 'adj.', 'eased of grief or distress', 'She felt comforted by his presence.'),
  Word('emotions', 'churlish', 'adj.', 'rude and bad-tempered', 'It would be churlish to refuse such kindness.'),
  Word('emotions', 'flush', 'n.', 'a sudden rush of intense feeling', 'A flush of pride warmed her cheeks.'),
  Word('emotions', 'nervy', 'adj.', 'nervous and on edge', 'He felt nervy waiting for the results.'),
  Word('emotions', 'jocund', 'adj.', 'cheerful and lighthearted', 'A jocund spirit ran through the festival.'),
  Word('emotions', 'desolated', 'adj.', 'made to feel utterly wretched and lonely', 'She was desolated by the loss of her friend.'),
  Word('emotions', 'pique', 'n.', 'a feeling of irritation from wounded pride', 'In a fit of pique, she left the room.'),
  Word('emotions', 'careworn', 'adj.', 'showing signs of prolonged worry', 'His careworn face revealed the long ordeal.'),
  Word('emotions', 'verve', 'n.', 'vigor and spirit in feeling or expression', 'She tackled the project with great verve.'),
  Word('emotions', 'horrified', 'adj.', 'filled with horror; shocked', 'They were horrified by the news report.'),
  Word('emotions', 'lovestruck', 'adj.', 'deeply or helplessly in love', 'The lovestruck teenager wrote her poems daily.'),
  Word('emotions', 'sullenness', 'n.', 'bad-tempered silence and gloom', 'His sullenness cast a pall over dinner.'),
  Word('emotions', 'gusto', 'n.', 'enthusiastic enjoyment and vigor', 'He attacked the meal with gusto.'),
  Word('emotions', 'fearsome', 'adj.', 'inspiring fear or dread', 'The storm had a fearsome power.'),
  Word('emotions', 'mopey', 'adj.', 'gloomy, listless, and dejected', 'He felt mopey on the rainy holiday.'),
  Word('emotions', 'incredulous', 'adj.', 'unwilling to believe; amazed and skeptical', 'He gave an incredulous laugh at the claim.'),
  Word('emotions', 'pensiveness', 'n.', 'deep, often sad thoughtfulness', 'A quiet pensiveness settled over her.'),
  Word('emotions', 'rambunctious', 'adj.', 'uncontrollably exuberant and boisterous', 'The rambunctious puppies raced around the yard.'),
  Word('emotions', 'wounded', 'adj.', 'feeling hurt emotionally', 'She felt wounded by his thoughtless joke.'),
  Word('emotions', 'jingoistic', 'adj.', 'feeling aggressive patriotic pride', 'The crowd grew jingoistic during the rally.'),
  Word('emotions', 'unsettled', 'adj.', 'anxious and uneasy', 'The strange call left her unsettled.'),
  Word('emotions', 'beatitude', 'n.', 'a state of supreme blessedness or bliss', 'A look of beatitude crossed her face.'),
  Word('emotions', 'flinty', 'adj.', 'showing no emotion or warmth', 'He gave a flinty stare in reply.'),
  Word('emotions', 'gallant', 'adj.', 'brave and high-spirited in feeling', 'He made a gallant effort to cheer her up.'),
  Word('emotions', 'mope', 'v.', 'to be listless and dejected', 'He tends to mope when plans fall through.'),
  Word('emotions', 'venerate', 'v.', 'to regard with deep respect', 'They venerate the memory of their founder.'),
  Word('emotions', 'jangled', 'adj.', 'left feeling nervously irritated', 'The constant alarms left her nerves jangled.'),
  Word('emotions', 'rejuvenation', 'n.', 'a renewed feeling of energy and freshness', 'The retreat brought a sense of rejuvenation.'),
  Word('emotions', 'puzzlement', 'n.', 'a state of confusion or uncertainty', 'She frowned in puzzlement at the note.'),
  Word('emotions', 'aflutter', 'adj.', 'in a state of nervous or excited agitation', 'Her heart was aflutter before the date.'),
  Word('emotions', 'crushing', 'adj.', 'causing overwhelming sadness or pressure', 'The defeat was a crushing blow.'),
  Word('emotions', 'jadedness', 'n.', 'a worn-out lack of enthusiasm', 'Years of routine bred a deep jadedness.'),
  Word('emotions', 'rapt', 'adj.', 'completely absorbed and fascinated', 'The crowd listened with rapt attention.'),
  Word('emotions', 'galvanized', 'adj.', 'shocked into sudden emotional action', 'The speech galvanized the volunteers.'),
  Word('emotions', 'morosity', 'n.', 'a gloomy and sullen mood', 'A heavy morosity hung about him.'),
  Word('emotions', 'joviality', 'n.', 'cheerful and friendly good humor', 'His joviality made everyone feel welcome.'),
  Word('emotions', 'forsaking', 'n.', 'the act of abandoning, leaving one bereft', 'The forsaking left her feeling hollow.'),
  Word('emotions', 'aplomb', 'n.', 'self-confidence and composure under pressure', 'She handled the crisis with aplomb.'),
  Word('emotions', 'lachrymose', 'adj.', 'tearful or given to weeping', 'He became lachrymose at the farewell.'),
  Word('emotions', 'piqued', 'adj.', 'feeling irritated or resentful', 'She was piqued by the offhand dismissal.'),
  Word('emotions', 'fervency', 'n.', 'intensity of feeling or belief', 'He pleaded with surprising fervency.'),
  Word('emotions', 'gobsmack', 'v.', 'to astonish utterly', 'The result would gobsmack any expert.'),
  Word('emotions', 'reverent', 'adj.', 'feeling or showing deep respect', 'A reverent hush fell over the chapel.'),
  Word('emotions', 'crabbiness', 'n.', 'a state of irritable bad temper', 'His crabbiness faded after a nap.'),
  Word('emotions', 'tetchy', 'adj.', 'irritable and bad-tempered', 'She felt tetchy after the sleepless night.'),
  Word('emotions', 'flummox', 'v.', 'to confuse or bewilder someone', 'The trick question seemed to flummox him.'),
  Word('emotions', 'jollity', 'n.', 'lively and cheerful activity or atmosphere', 'The fair was full of music and jollity.'),
  Word('emotions', 'spleen', 'n.', 'bad temper or spiteful ill humor', 'He vented his spleen on the referee.'),
];
