import 'words_data.dart';

const kEverydayExtras = <Word>[
  Word('everyday', 'succinct', 'adj.', 'Said clearly in very few words', 'Keep the update succinct so the team can skim it before the call.'),
  Word('everyday', 'candid', 'adj.', 'Honest and direct, even when uncomfortable', 'I appreciate your candid feedback on the first draft.'),
  Word('everyday', 'pragmatic', 'adj.', 'Practical and focused on what actually works', 'Let\'s take a pragmatic approach and fix the biggest issue first.'),
  Word('everyday', 'nuance', 'n.', 'A small but important difference in meaning', 'There\'s a nuance here that the summary completely misses.'),
  Word('everyday', 'mitigate', 'v.', 'To make something bad less serious', 'We added a backup plan to mitigate the risk of delays.'),
  Word('everyday', 'leverage', 'v.', 'To use something to your advantage', 'We can leverage your contacts to get a faster reply.'),
  Word('everyday', 'tangible', 'adj.', 'Real and clearly noticeable', 'I want to see tangible progress by the end of the week.'),
  Word('everyday', 'articulate', 'v.', 'To express an idea clearly in words', 'She articulated the problem better than anyone else in the room.'),
  Word('everyday', 'concise', 'adj.', 'Short and to the point', 'Please keep the email concise; he barely reads past two lines.'),
  Word('everyday', 'prudent', 'adj.', 'Careful and sensible about the future', 'It would be prudent to save the receipt just in case.'),
  Word('everyday', 'viable', 'adj.', 'Able to work or succeed', 'That\'s the only viable option within our budget.'),
  Word('everyday', 'cohesive', 'adj.', 'Holding together as a unified whole', 'The slides need to feel more cohesive before we present them.'),
  Word('everyday', 'ambivalent', 'adj.', 'Having mixed feelings about something', 'I\'m ambivalent about moving; I love the city but hate the rent.'),
  Word('everyday', 'meticulous', 'adj.', 'Very careful about small details', 'She\'s meticulous, so the budget will add up to the penny.'),
  Word('everyday', 'caveat', 'n.', 'A warning or condition to keep in mind', 'The plan works, with one caveat: it depends on the weather.'),
  Word('everyday', 'tentative', 'adj.', 'Not final and likely to change', 'Let\'s pencil in a tentative date and confirm next week.'),
  Word('everyday', 'redundant', 'adj.', 'Repeated unnecessarily', 'Cut the second paragraph; it\'s redundant with the intro.'),
  Word('everyday', 'feasible', 'adj.', 'Possible to do without too much trouble', 'Is it feasible to finish this by Friday, or should we push it?'),
  Word('everyday', 'streamline', 'v.', 'To make a process simpler and faster', 'We streamlined the checkout so it takes two clicks instead of five.'),
  Word('everyday', 'daunting', 'adj.', 'Seeming hard enough to be discouraging', 'The reading list looked daunting until I broke it into chapters.'),
  Word('everyday', 'mundane', 'adj.', 'Ordinary and a bit dull', 'Most of my morning is just mundane admin and email.'),
  Word('everyday', 'tedious', 'adj.', 'Boring because it takes so long', 'Filling out the form was tedious but only took ten minutes.'),
  Word('everyday', 'concede', 'v.', 'To admit that something is true', 'I\'ll concede you were right about leaving early.'),
  Word('everyday', 'clarify', 'v.', 'To make something easier to understand', 'Could you clarify what time the meeting actually starts?'),
  Word('everyday', 'gist', 'n.', 'The main point of something', 'I skimmed the report, but I got the gist of it.'),
  Word('everyday', 'plausible', 'adj.', 'Believable and reasonable', 'That\'s a plausible excuse, but I\'d still double-check it.'),
  Word('everyday', 'coherent', 'adj.', 'Clear and logically connected', 'Get some sleep first; you\'re not coherent right now.'),
  Word('everyday', 'adept', 'adj.', 'Very skilled at something', 'She\'s adept at calming down upset customers.'),
  Word('everyday', 'diligent', 'adj.', 'Hardworking and careful', 'He\'s diligent about replying to messages within the hour.'),
  Word('everyday', 'frugal', 'adj.', 'Careful with money and resources', 'We stayed frugal this month to save for the trip.'),
  Word('everyday', 'versatile', 'adj.', 'Able to do many different things well', 'A good blazer is versatile enough for work or dinner.'),
  Word('everyday', 'candidly', 'adv.', 'In an honest and direct way', 'Candidly, I think we should walk away from this deal.'),
  Word('everyday', 'ambiguous', 'adj.', 'Having more than one possible meaning', 'The instructions were ambiguous, so half of us did it wrong.'),
  Word('everyday', 'deliberate', 'adj.', 'Done on purpose and with thought', 'That was a deliberate choice, not an accident.'),
  Word('everyday', 'intuitive', 'adj.', 'Easy to understand without being taught', 'The app is intuitive, so my parents figured it out fast.'),
  Word('everyday', 'resilient', 'adj.', 'Able to recover quickly from difficulty', 'Kids are resilient; she bounced back from the move in a week.'),
  Word('everyday', 'scrutinize', 'v.', 'To examine very closely', 'Scrutinize the contract before you sign anything.'),
  Word('everyday', 'advocate', 'v.', 'To publicly support an idea or person', 'I\'ll advocate for a later deadline at tomorrow\'s meeting.'),
  Word('everyday', 'delegate', 'v.', 'To give a task to someone else', 'You can\'t do it all; learn to delegate the small stuff.'),
  Word('everyday', 'prioritize', 'v.', 'To deal with the most important things first', 'Let\'s prioritize the bug fix over the new feature.'),
  Word('everyday', 'reconcile', 'v.', 'To make two things agree or fit together', 'I need to reconcile these two spreadsheets before payday.'),
  Word('everyday', 'pertinent', 'adj.', 'Directly relevant to the matter', 'Only include details that are pertinent to the request.'),
  Word('everyday', 'discreet', 'adj.', 'Careful not to attract attention or share secrets', 'Be discreet about the layoffs until it\'s announced.'),
  Word('everyday', 'rapport', 'n.', 'A friendly, trusting connection with someone', 'She built quick rapport with every new client.'),
  Word('everyday', 'amenable', 'adj.', 'Willing to agree or cooperate', 'My boss is amenable to remote work on Fridays.'),
  Word('everyday', 'forgo', 'v.', 'To choose to do without something', 'I\'ll forgo dessert tonight and save room for breakfast.'),
  Word('everyday', 'reiterate', 'v.', 'To say something again for emphasis', 'Let me reiterate: the deadline is firm.'),
  Word('everyday', 'tactful', 'adj.', 'Careful not to upset or offend people', 'She found a tactful way to decline the invitation.'),
  Word('everyday', 'astute', 'adj.', 'Quick to understand and judge well', 'That was an astute observation about the budget.'),
  Word('everyday', 'overhaul', 'v.', 'To repair or improve something thoroughly', 'We need to overhaul the onboarding process this quarter.'),
  Word('everyday', 'recurring', 'adj.', 'Happening again and again', 'Set a recurring reminder so you don\'t forget the rent.'),
  Word('everyday', 'discrepancy', 'n.', 'A difference between things that should match', 'There\'s a discrepancy between the receipt and my statement.'),
  Word('everyday', 'consolidate', 'v.', 'To combine several things into one', 'Let\'s consolidate these emails into a single thread.'),
  Word('everyday', 'imperative', 'adj.', 'Extremely important and urgent', 'It\'s imperative that we reply before noon.'),
  Word('everyday', 'inadvertent', 'adj.', 'Happening by accident, not on purpose', 'Sorry, the duplicate charge was inadvertent.'),
  Word('everyday', 'feasibly', 'adv.', 'In a way that can realistically be done', 'How much can we feasibly finish before lunch?'),
  Word('everyday', 'forthcoming', 'adj.', 'Willing to share information openly', 'He wasn\'t very forthcoming about why he quit.'),
  Word('everyday', 'allocate', 'v.', 'To set aside for a particular purpose', 'We allocated an hour each morning for deep work.'),
  Word('everyday', 'expedite', 'v.', 'To make something happen faster', 'Can you expedite the shipping so it arrives by Friday?'),
  Word('everyday', 'circumvent', 'v.', 'To find a way around a problem or rule', 'We circumvented the long line by booking online.'),
  Word('everyday', 'subsequent', 'adj.', 'Coming after something else', 'We can fix the rest in subsequent updates.'),
  Word('everyday', 'preliminary', 'adj.', 'Coming before the main part as preparation', 'These are just preliminary numbers, so don\'t quote them yet.'),
  Word('everyday', 'pragmatically', 'adv.', 'In a practical, realistic way', 'Pragmatically speaking, we can\'t afford both.'),
  Word('everyday', 'rectify', 'v.', 'To correct something that is wrong', 'We\'ll rectify the billing error on your next statement.'),
  Word('everyday', 'cumbersome', 'adj.', 'Awkward and difficult to handle', 'The old form was cumbersome, so we trimmed it.'),
  Word('everyday', 'innocuous', 'adj.', 'Harmless and unlikely to offend', 'It started as an innocuous question about the weekend.'),
  Word('everyday', 'pivotal', 'adj.', 'Very important to how things turn out', 'That meeting was pivotal to landing the account.'),
  Word('everyday', 'concur', 'v.', 'To agree with someone', 'I concur; let\'s wait until the numbers are final.'),
  Word('everyday', 'wary', 'adj.', 'Cautious because of possible danger', 'Be wary of emails asking for your password.'),
  Word('everyday', 'curtail', 'v.', 'To reduce or cut something short', 'We had to curtail the meeting when the room was booked.'),
  Word('everyday', 'gauge', 'v.', 'To estimate or judge something', 'I sent a quick poll to gauge interest in the lunch.'),
  Word('everyday', 'cordial', 'adj.', 'Warm and friendly in a polite way', 'We kept things cordial even though we disagreed.'),
  Word('everyday', 'aptly', 'adv.', 'In a fitting and suitable way', 'The new logo is aptly named after the founder.'),
  Word('everyday', 'defer', 'v.', 'To put off until a later time', 'Let\'s defer the decision until we have the data.'),
  Word('everyday', 'cursory', 'adj.', 'Quick and without attention to detail', 'A cursory glance showed the report was missing a page.'),
  Word('everyday', 'finite', 'adj.', 'Having a clear limit or end', 'We have finite time, so let\'s focus on essentials.'),
  Word('everyday', 'overt', 'adj.', 'Done openly and not hidden', 'He made no overt complaint, but you could tell he was annoyed.'),
  Word('everyday', 'judicious', 'adj.', 'Showing good, careful judgment', 'A judicious use of the budget left room for emergencies.'),
  Word('everyday', 'tenable', 'adj.', 'Able to be defended or maintained', 'That position isn\'t tenable once the costs come in.'),
  Word('everyday', 'salient', 'adj.', 'Most noticeable or important', 'Just give me the salient points before the call.'),
  Word('everyday', 'amiable', 'adj.', 'Friendly and pleasant to be around', 'Our new neighbor is amiable and always says hello.'),
  Word('everyday', 'onerous', 'adj.', 'Requiring a lot of difficult effort', 'The paperwork was onerous but unavoidable.'),
  Word('everyday', 'verbatim', 'adv.', 'In exactly the same words', 'Don\'t quote me verbatim; just share the idea.'),
  Word('everyday', 'tenuous', 'adj.', 'Weak and not well supported', 'The connection between the two reports is tenuous at best.'),
  Word('everyday', 'apprise', 'v.', 'To inform someone of something', 'Please apprise me of any changes to the schedule.'),
  Word('everyday', 'cogent', 'adj.', 'Clear, logical, and convincing', 'She made a cogent case for working from home.'),
  Word('everyday', 'mundanely', 'adv.', 'In an ordinary, unremarkable way', 'He described his weekend rather mundanely, but I knew better.'),
  Word('everyday', 'judiciously', 'adv.', 'With good and careful judgment', 'Spend the bonus judiciously rather than all at once.'),
  Word('everyday', 'ostensibly', 'adv.', 'Apparently, though perhaps not truly', 'He left early, ostensibly to catch a train.'),
  Word('everyday', 'preempt', 'v.', 'To act first to prevent something', 'I sent the FAQ to preempt the usual questions.'),
  Word('everyday', 'amicable', 'adj.', 'Friendly and without hostility', 'They reached an amicable split on who pays what.'),
  Word('everyday', 'palatable', 'adj.', 'Acceptable or pleasant enough', 'We made the news more palatable by offering a discount.'),
  Word('everyday', 'redress', 'v.', 'To set right a wrong or imbalance', 'The refund should redress the mix-up nicely.'),
  Word('everyday', 'extraneous', 'adj.', 'Not relevant or necessary', 'Trim the extraneous details and keep the ask clear.'),
  Word('everyday', 'concerted', 'adj.', 'Done together in a planned way', 'It took a concerted effort to clear the inbox.'),
  Word('everyday', 'glean', 'v.', 'To gather information bit by bit', 'I gleaned the schedule from a few scattered emails.'),
  Word('everyday', 'fastidious', 'adj.', 'Very fussy about detail and cleanliness', 'He\'s fastidious about labeling every folder.'),
  Word('everyday', 'placate', 'v.', 'To calm someone who is angry', 'A quick apology helped placate the frustrated customer.'),
  Word('everyday', 'commensurate', 'adj.', 'Matching in size or degree', 'The pay should be commensurate with the workload.'),
  Word('everyday', 'reticent', 'adj.', 'Reluctant to speak or share', 'She was reticent about the raise until it was confirmed.'),
  Word('everyday', 'forestall', 'v.', 'To prevent by acting in advance', 'We sent reminders to forestall any missed payments.'),
  Word('everyday', 'judicial', 'adj.', 'Relating to courts or careful judgment', 'The dispute moved to a judicial review after talks failed.'),
  Word('everyday', 'apt', 'adj.', 'Suitable and well-chosen', 'That was an apt comparison for explaining the delay.'),
];
