import 'words_data.dart';

const kLiteratureExtras = <Word>[
  Word('literature', 'anaphora', 'n.', 'Repetition of a word at the start of successive clauses', 'Dickens uses anaphora when he writes \'It was the best of times, it was the worst of times\'.'),
  Word('literature', 'epistrophe', 'n.', 'Repetition of a word at the end of successive clauses', 'Lincoln\'s \'of the people, by the people, for the people\' is textbook epistrophe.'),
  Word('literature', 'chiasmus', 'n.', 'A reversal of grammatical structure in two parallel phrases', 'JFK\'s \'ask not what your country can do for you\' is a famous chiasmus.'),
  Word('literature', 'antimetabole', 'n.', 'A chiasmus where the exact words are reversed', 'Antimetabole gives a sentence the snap of a closing door.'),
  Word('literature', 'asyndeton', 'n.', 'Omitting conjunctions between clauses for speed', 'Caesar\'s \'I came, I saw, I conquered\' relies on asyndeton.'),
  Word('literature', 'polysyndeton', 'n.', 'Using many conjunctions in close succession for weight', 'Hemingway leans on polysyndeton to slow the reader down.'),
  Word('literature', 'anadiplosis', 'n.', 'Repeating the last word of one clause at the start of the next', 'Yoda\'s \'Fear leads to anger, anger leads to hate\' is anadiplosis.'),
  Word('literature', 'epanalepsis', 'n.', 'Repeating a word at the beginning and end of a clause', 'Epanalepsis frames a thought between two echoes of itself.'),
  Word('literature', 'polyptoton', 'n.', 'Repeating a root word in different grammatical forms', 'Shakespeare loves polyptoton, as in \'love is not love which alters\'.'),
  Word('literature', 'antanaclasis', 'n.', 'Repeating a word with a different meaning each time', 'Antanaclasis is a favorite trick of Renaissance sonneteers.'),
  Word('literature', 'zeugma', 'n.', 'A word governing two others in different senses', 'Pope writes that the heroine may \'stain her honor or her new brocade\' — a wicked zeugma.'),
  Word('literature', 'syllepsis', 'n.', 'A zeugma where the shared word is grammatically odd in one branch', 'Syllepsis often produces a wry comic effect.'),
  Word('literature', 'hendiadys', 'n.', 'Expressing one idea with two nouns joined by a conjunction', 'Hamlet\'s \'sound and fury\' is hendiadys for furious noise.'),
  Word('literature', 'merism', 'n.', 'Naming the parts to mean the whole', 'The biblical \'heaven and earth\' is a merism for the universe.'),
  Word('literature', 'synecdoche', 'n.', 'A figure where a part stands for the whole', 'Calling sailors \'hands\' is a classic synecdoche.'),
  Word('literature', 'metonymy', 'n.', 'Substituting a related term for the thing meant', 'Saying \'the crown\' for the monarchy is metonymy.'),
  Word('literature', 'periphrasis', 'n.', 'Using many words where one would do', 'Epic poets favor periphrasis to elevate plain things.'),
  Word('literature', 'circumlocution', 'n.', 'A roundabout way of saying something', 'Bureaucratic prose drowns in circumlocution.'),
  Word('literature', 'euphemism', 'n.', 'A softer phrase used in place of a harsh one', '\'Passed away\' is a gentle euphemism for died.'),
  Word('literature', 'dysphemism', 'n.', 'A harsher phrase used in place of a neutral one', 'Calling food \'slop\' is dysphemism for effect.'),
  Word('literature', 'malapropism', 'n.', 'Comic misuse of a similar-sounding word', 'Mrs. Malaprop gave the malapropism its name.'),
  Word('literature', 'spoonerism', 'n.', 'A slip swapping initial sounds of two words', 'Reverend Spooner produced spoonerisms like \'a blushing crow\'.'),
  Word('literature', 'paronomasia', 'n.', 'The formal name for a play on words', 'Shakespeare\'s clowns thrive on paronomasia.'),
  Word('literature', 'paraprosdokian', 'n.', 'A sentence whose ending swerves from what you expected', 'Stand-up comedians live by the paraprosdokian.'),
  Word('literature', 'aporia', 'n.', 'A staged moment of doubt or impasse', 'The speaker opens with an aporia: \'where shall I even begin?\'.'),
  Word('literature', 'apophasis', 'n.', 'Mentioning something by saying you will not mention it', 'Politicians love apophasis: \'I won\'t bring up his record\'.'),
  Word('literature', 'praeteritio', 'n.', 'Another name for apophasis, drawing attention by denial', 'Cicero made praeteritio a courtroom weapon.'),
  Word('literature', 'meiosis', 'n.', 'Deliberate understatement that belittles the subject', 'Calling the Atlantic \'a bit of a puddle\' is meiosis.'),
  Word('literature', 'tautology', 'n.', 'Saying the same thing twice in different words', 'Bad prose is full of unintended tautology.'),
  Word('literature', 'pleonasm', 'n.', 'Use of more words than necessary to express an idea', '\'Free gift\' is a familiar pleonasm.'),
  Word('literature', 'anachronism', 'n.', 'Something placed in the wrong time period', 'A clock striking in Julius Caesar is a notorious anachronism.'),
  Word('literature', 'epithet', 'n.', 'A descriptive phrase regularly attached to a name', 'Homer calls the sea \'wine-dark\' as a fixed epithet.'),
  Word('literature', 'kenning', 'n.', 'A compound figurative phrase common in Old Norse verse', '\'Whale-road\' is the famous kenning for the sea.'),
  Word('literature', 'apologue', 'n.', 'A short moral tale, often with animals', 'Aesop\'s apologues teach prudence and pride.'),
  Word('literature', 'exemplum', 'n.', 'A brief illustrative story used in a sermon or essay', 'Medieval preachers stitched exempla into their homilies.'),
  Word('literature', 'aphorism', 'n.', 'A pithy saying that delivers a general truth', 'La Rochefoucauld is the great master of the aphorism.'),
  Word('literature', 'maxim', 'n.', 'A short statement expressing a general rule of conduct', 'Polonius\' speech is stuffed with worldly maxims.'),
  Word('literature', 'adage', 'n.', 'A familiar saying that has stood the test of time', 'The adage that \'still waters run deep\' is older than English itself.'),
  Word('literature', 'epigram', 'n.', 'A short, witty, often satirical poem or remark', 'Oscar Wilde could fire off an epigram before breakfast.'),
  Word('literature', 'witticism', 'n.', 'A clever or amusing remark', 'Dorothy Parker\'s witticisms still circulate online.'),
  Word('literature', 'bon mot', 'phr.', 'A neatly turned phrase or clever saying', 'Wilde sprinkled every play with a bon mot.'),
  Word('literature', 'mot juste', 'phr.', 'Exactly the right word for the occasion', 'Flaubert hunted for the mot juste like a sniper.'),
  Word('literature', 'fin de siècle', 'phr.', 'Of the late nineteenth century and its decadent mood', 'Beardsley\'s drawings are pure fin de siècle.'),
  Word('literature', 'avant-garde', 'adj.', 'Experimental and ahead of its time', 'The little magazines published avant-garde poetry no one else would touch.'),
  Word('literature', 'modernism', 'n.', 'An early twentieth-century movement of formal experiment', 'Modernism shattered the Victorian sense of a stable narrator.'),
  Word('literature', 'postmodernism', 'n.', 'A later movement marked by pastiche, irony, and self-reference', 'Pynchon\'s novels are central texts of postmodernism.'),
  Word('literature', 'romanticism', 'n.', 'A movement prizing emotion, nature, and the individual', 'Wordsworth helped launch English romanticism.'),
  Word('literature', 'naturalism', 'n.', 'A school portraying life as shaped by environment and heredity', 'Zola\'s naturalism took readers into the mines and slums.'),
  Word('literature', 'symbolism', 'n.', 'A late-nineteenth-century movement favoring suggestion over statement', 'Mallarmé led the French symbolism that fed modernist verse.'),
  Word('literature', 'imagism', 'n.', 'An early modernist movement valuing precise, hard images', 'Pound and H.D. defined imagism in three brief rules.'),
  Word('literature', 'surrealism', 'n.', 'A movement releasing the imagery of the unconscious', 'Breton\'s manifesto launched surrealism in 1924.'),
  Word('literature', 'dadaism', 'n.', 'An anti-art movement of nonsense and provocation', 'Dadaism mocked a Europe that had just shredded itself in war.'),
  Word('literature', 'futurism', 'n.', 'An early movement glorifying speed, machines, and rupture', 'Marinetti\'s futurism produced shouting typography and noisy verse.'),
  Word('literature', 'expressionism', 'n.', 'A movement projecting inner feeling onto the outside world', 'German expressionism painted streets that screamed back at the viewer.'),
  Word('literature', 'transcendentalism', 'n.', 'A New England movement valuing intuition and nature', 'Emerson\'s essays are the heart of American transcendentalism.'),
  Word('literature', 'lost generation', 'phr.', 'The disillusioned expatriate writers after World War I', 'Hemingway and Fitzgerald became faces of the lost generation.'),
  Word('literature', 'harlem renaissance', 'phr.', 'The 1920s flowering of Black art and writing in Harlem', 'Hughes\' early poems belong to the harlem renaissance.'),
  Word('literature', 'bloomsbury', 'n.', 'The London circle around Virginia Woolf and her friends', 'Bloomsbury blended novels, painting, and economics over tea.'),
  Word('literature', 'inklings', 'n.', 'The Oxford writing group around Lewis and Tolkien', 'The inklings read drafts aloud in a pub called The Eagle and Child.'),
  Word('literature', 'fugitives', 'n.', 'A southern group of poets that produced Ransom and Tate', 'The fugitives founded a poetry magazine in 1920s Nashville.'),
  Word('literature', 'oulipo', 'n.', 'A French group writing under invented constraints', 'Oulipo includes Queneau and Perec, who wrote a novel without the letter E.'),
  Word('literature', 'concrete poetry', 'phr.', 'Verse whose typography is part of its meaning', 'Concrete poetry asks you to look at a poem as much as read it.'),
  Word('literature', 'found poetry', 'phr.', 'Poems assembled from words discovered in other texts', 'A found poetry chapbook may stitch lines from old newspapers.'),
  Word('literature', 'erasure', 'n.', 'A poem made by deleting words from an existing source', 'Phillips\' \'A Humument\' is the great example of erasure.'),
  Word('literature', 'cento', 'n.', 'A poem stitched together from lines by other poets', 'A cento is part homage and part collage.'),
  Word('literature', 'ekphrasis', 'n.', 'A vivid verbal description of a work of visual art', 'Keats\' \'Ode on a Grecian Urn\' is the model of ekphrasis.'),
  Word('literature', 'pathetic fallacy', 'phr.', 'Attributing human emotion to nature', 'Ruskin coined pathetic fallacy to scold poets for weeping clouds.'),
  Word('literature', 'sublime', 'n.', 'A grand aesthetic awe mixed with terror', 'Burke distinguished the sublime from the merely beautiful.'),
  Word('literature', 'picaresque', 'adj.', 'Of an episodic tale following a roguish hero', 'Cervantes\' \'Don Quixote\' is the founding picaresque novel.'),
  Word('literature', 'epistolary', 'adj.', 'Told through letters or other documents', 'Richardson\'s \'Pamela\' established the epistolary novel in English.'),
  Word('literature', 'frame narrative', 'phr.', 'A story containing another story within it', 'The frame narrative in \'Frankenstein\' nests three voices.'),
  Word('literature', 'embedded narrative', 'phr.', 'A story told inside another story', 'Scheherazade is the ultimate embedded narrative engine.'),
  Word('literature', 'metafiction', 'n.', 'Fiction that draws attention to its own artifice', 'Italo Calvino\'s books are sly works of metafiction.'),
  Word('literature', 'autofiction', 'n.', 'Fiction that closely mirrors the author\'s real life', 'Knausgaard\'s autofiction blurs the line between memoir and novel.'),
  Word('literature', 'mise en abyme', 'phr.', 'A copy of the whole work appearing inside itself', 'The play within \'Hamlet\' is a famous mise en abyme.'),
  Word('literature', 'fourth wall', 'phr.', 'The invisible barrier between performers and audience', 'Ferris Bueller breaks the fourth wall to talk straight at us.'),
  Word('literature', 'breaking the fourth wall', 'phr.', 'Speaking directly to the audience or reader', 'Deadpool keeps breaking the fourth wall for jokes.'),
  Word('literature', 'stream of consciousness', 'phr.', 'Prose mimicking the unbroken flow of a character\'s thought', 'Molly Bloom\'s monologue is the textbook stream of consciousness.'),
  Word('literature', 'interior monologue', 'phr.', 'A character\'s thoughts presented in first person', 'Joyce\'s interior monologue feels like eavesdropping on a mind.'),
  Word('literature', 'free indirect discourse', 'phr.', 'Third-person prose colored by a character\'s voice', 'Jane Austen pioneered free indirect discourse in English.'),
  Word('literature', 'focalization', 'n.', 'The point of view through which a story is filtered', 'Shifting the focalization changes how we judge a scene.'),
  Word('literature', 'diegesis', 'n.', 'The world inside a story as opposed to its telling', 'Sound that characters can hear belongs to the diegesis.'),
  Word('literature', 'mimesis', 'n.', 'The imitation of reality in art', 'Auerbach\'s \'Mimesis\' traces mimesis from Homer to Woolf.'),
  Word('literature', 'verismo', 'n.', 'An Italian literary and operatic style of gritty realism', 'Verga led the verismo school in late nineteenth-century Italy.'),
  Word('literature', 'kitchen sink', 'adj.', 'Of postwar British art focused on working-class life', 'Kitchen sink drama dragged the stage into bedsits and pubs.'),
  Word('literature', 'social realism', 'phr.', 'Art that depicts ordinary lives with documentary honesty', 'Steinbeck\'s Dust Bowl novels are social realism.'),
  Word('literature', 'magical', 'adj.', 'Combining realistic narration with matter-of-fact wonders', 'García Márquez\'s magical style made levitation feel like weather.'),
  Word('literature', 'fabulism', 'n.', 'A mode that blends folk-tale logic into modern fiction', 'Karen Russell\'s stories sit at the heart of contemporary fabulism.'),
  Word('literature', 'science fiction', 'phr.', 'A genre extrapolating from real or imagined science', 'Le Guin used science fiction to test ideas about gender and power.'),
  Word('literature', 'speculative fiction', 'phr.', 'An umbrella term covering sci-fi, fantasy, and alt-history', 'Atwood prefers the label speculative fiction for \'The Handmaid\'s Tale\'.'),
  Word('literature', 'dystopia', 'n.', 'A grim imagined society used as warning', 'Orwell\'s \'1984\' is the canonical dystopia.'),
  Word('literature', 'utopia', 'n.', 'An ideal imagined society used to critique our own', 'More\'s \'Utopia\' gave the genre its name.'),
  Word('literature', 'cyberpunk', 'n.', 'A subgenre of high-tech, low-life near-future fiction', 'Gibson\'s \'Neuromancer\' became the bible of cyberpunk.'),
  Word('literature', 'steampunk', 'n.', 'A subgenre set in a Victorian world of steam-powered tech', 'Steampunk turns goggles and gears into a costume aesthetic.'),
  Word('literature', 'solarpunk', 'n.', 'A hopeful subgenre imagining green, post-fossil futures', 'Solarpunk stories trade dystopia for solar panels and gardens.'),
  Word('literature', 'noir', 'n.', 'A dark, morally tangled style of crime fiction', 'Chandler\'s rain-soaked Los Angeles defined American noir.'),
  Word('literature', 'hardboiled', 'adj.', 'Of tough, cynical detective fiction in plain language', 'Hammett\'s hardboiled prose hit like a punch.'),
  Word('literature', 'cozy', 'adj.', 'Of low-violence mysteries set in tidy small communities', 'Agatha Christie\'s village whodunits are the model cozy.'),
  Word('literature', 'whodunit', 'n.', 'A mystery built around the question of the killer\'s identity', 'A whodunit lives or dies by its red herrings.'),
  Word('literature', 'thriller', 'n.', 'A plot-driven novel built on suspense and danger', 'Le Carré reinvented the spy thriller with moral weight.'),
  Word('literature', 'potboiler', 'n.', 'A novel written quickly for money rather than art', 'Even Conrad turned out the occasional potboiler.'),
  Word('literature', 'page-turner', 'n.', 'A book whose plot keeps the reader flipping pages', 'Her debut became a true page-turner by the second chapter.'),
  Word('literature', 'bodice ripper', 'phr.', 'A historical romance with steamy passages', 'The bodice ripper paperbacks of the 1980s sold by the million.'),
  Word('literature', 'penny dreadful', 'phr.', 'A cheap nineteenth-century serial of lurid fiction', 'Sweeney Todd first appeared in a penny dreadful.'),
  Word('literature', 'pulp', 'n.', 'Cheap magazines printing genre fiction in mass quantities', 'Raymond Chandler cut his teeth writing for the pulps.'),
  Word('literature', 'chapbook', 'n.', 'A small inexpensive booklet of poems or stories', 'Many poets start out publishing chapbooks with tiny presses.'),
  Word('literature', 'pamphlet', 'n.', 'A short polemical work in cheap paper covers', 'Thomas Paine\'s pamphlet \'Common Sense\' helped spark a revolution.'),
  Word('literature', 'broadside', 'n.', 'A single sheet printed on one side for cheap circulation', 'Eighteenth-century ballads survived as broadsides sold on the street.'),
  Word('literature', 'serial', 'n.', 'A novel published in successive installments', 'Dickens released most of his novels as serials in magazines.'),
  Word('literature', 'page-turn', 'n.', 'A break engineered to make a reader flip the page', 'Magazine fiction lives or dies by the page-turn.'),
  Word('literature', 'feuilleton', 'n.', 'A literary supplement at the bottom of a French newspaper', 'Balzac\'s novels first reached readers in the feuilleton.'),
  Word('literature', 'roman-fleuve', 'n.', 'A long sequence of linked novels following a family or era', 'Proust\'s great roman-fleuve runs to seven volumes.'),
  Word('literature', 'tetralogy', 'n.', 'A connected series of four works', 'Updike\'s Rabbit tetralogy follows one man across four decades.'),
  Word('literature', 'trilogy', 'n.', 'A connected series of three works', 'Tolkien\'s ring trilogy made fantasy a market category.'),
  Word('literature', 'diptych', 'n.', 'A work made of two paired parts', 'Her novel reads as a diptych: childhood, then aftermath.'),
  Word('literature', 'triptych', 'n.', 'A work made of three paired parts', 'McEwan structured the book as a triptych of decades.'),
  Word('literature', 'omnibus', 'n.', 'A volume collecting several works by the same author', 'The omnibus edition gathers all four short novels.'),
  Word('literature', 'anthology', 'n.', 'A collection of selected works by various authors', 'The Norton anthology has shaped American literary taste for decades.'),
  Word('literature', 'compendium', 'n.', 'A concise but comprehensive collection of a subject', 'The compendium covers every Shakespeare play in one volume.'),
  Word('literature', 'folio', 'n.', 'A large book made of sheets folded once', 'Shakespeare\'s First Folio collected his plays in 1623.'),
  Word('literature', 'quarto', 'n.', 'A book size with sheets folded into quarters', 'Several Shakespeare plays survive only in early quarto editions.'),
  Word('literature', 'octavo', 'n.', 'A book size with sheets folded three times', 'Victorian novels often appeared as three-decker octavo sets.'),
  Word('literature', 'incunabula', 'n.', 'Books printed before 1501, the cradle of European printing', 'The library\'s incunabula are kept under glass.'),
  Word('literature', 'colophon', 'n.', 'A note at the end of a book giving printing details', 'A fine private press still includes a hand-set colophon.'),
  Word('literature', 'frontispiece', 'n.', 'An illustration facing the title page of a book', 'The frontispiece showed the author at his writing desk.'),
  Word('literature', 'flyleaf', 'n.', 'A blank page at the front or back of a book', 'She always wrote her name on the flyleaf in fountain pen.'),
  Word('literature', 'endpaper', 'n.', 'The decorative sheet glued to a book\'s inside cover', 'The endpaper showed a map of Middle-earth.'),
  Word('literature', 'dust jacket', 'phr.', 'The paper cover protecting a hardback book', 'A pristine dust jacket can double the price of a first edition.'),
  Word('literature', 'imprimatur', 'n.', 'An official sign of approval to print', 'Once the censor granted the imprimatur, the book could go to press.'),
  Word('literature', 'paratext', 'n.', 'Everything around the main text — titles, blurbs, prefaces', 'Genette argued that paratext frames how we read the work.'),
  Word('literature', 'dedication', 'n.', 'A printed inscription offering the book to someone', 'The dedication reads simply \'For my mother\'.'),
  Word('literature', 'colportage', 'n.', 'The peddling of cheap books and pamphlets door to door', 'Before bookshops spread, colportage put novels in farm kitchens.'),
  Word('literature', 'samizdat', 'n.', 'Self-published texts circulated in defiance of state censors', 'Solzhenitsyn\'s prison memoir reached Russians through samizdat.'),
  Word('literature', 'tamizdat', 'n.', 'Banned books smuggled abroad and printed there', 'Nabokov\'s early Russian novels appeared as tamizdat from Paris.'),
  Word('literature', 'codex', 'n.', 'A bound book of pages, the modern format', 'The codex replaced the scroll across the late Roman empire.'),
  Word('literature', 'palimpsest', 'n.', 'A manuscript scraped clean and reused, with traces still showing', 'Critics call a layered novel a kind of palimpsest.'),
  Word('literature', 'manuscript', 'n.', 'A handwritten or unpublished text', 'The British Library houses the manuscript of \'Beowulf\'.'),
  Word('literature', 'autograph', 'n.', 'A manuscript in the author\'s own hand', 'The autograph of \'Ulysses\' is split between several institutions.'),
  Word('literature', 'holograph', 'n.', 'A document written entirely by the person whose name it bears', 'Emily Dickinson\'s holograph fascicles preserve her own sewing.'),
  Word('literature', 'marginalia', 'n.', 'Notes scribbled in the margins of a book', 'Coleridge\'s marginalia have been published as a separate volume.'),
  Word('literature', 'apocrypha', 'n.', 'Writings of doubtful authorship or authority', 'The Shakespeare apocrypha collects plays only loosely tied to him.'),
  Word('literature', 'juvenilia', 'n.', 'A writer\'s very early work, usually from youth', 'The Brontës\' juvenilia describe a kingdom called Angria.'),
  Word('literature', 'oeuvre', 'n.', 'The complete body of work by an artist', 'Her oeuvre spans three novels and a hundred poems.'),
  Word('literature', 'corpus', 'n.', 'A collected body of texts treated as one whole', 'Linguists study the entire corpus of Old English verse.'),
  Word('literature', 'incipit', 'n.', 'The opening words of a text, used to identify it', 'Medieval manuscripts list works by their incipit.'),
  Word('literature', 'envoi', 'n.', 'A short closing stanza addressing a poem to its dedicatee', 'Chaucer ends \'Troilus\' with a tender envoi to his book.'),
  Word('literature', 'coda', 'n.', 'A passage that concludes a work after the main action', 'The coda jumps forward twenty years to a reunion.'),
  Word('literature', 'peroration', 'n.', 'The grand concluding section of a speech', 'Cicero\'s peroration urges the jury with rising rhythm.'),
  Word('literature', 'exordium', 'n.', 'The opening section of a classical speech', 'The exordium aims to win the audience\'s goodwill.'),
  Word('literature', 'narratio', 'n.', 'The factual statement of the case in classical oratory', 'A clear narratio sets up the argument that follows.'),
  Word('literature', 'rhetoric', 'n.', 'The art of effective speaking and writing', 'Aristotle\'s \'Rhetoric\' is still the foundation of the field.'),
  Word('literature', 'logos', 'n.', 'Rhetorical appeal through logic and evidence', 'A strong essay leans on logos as much as feeling.'),
  Word('literature', 'ethos', 'n.', 'Rhetorical appeal based on the speaker\'s character', 'A doctor citing her credentials is establishing ethos.'),
  Word('literature', 'kairos', 'n.', 'The right and timely moment for a rhetorical move', 'A good speech reads the kairos of the room.'),
  Word('literature', 'enthymeme', 'n.', 'A truncated syllogism that leaves a premise implied', 'Most advertising slogans run on enthymeme.'),
  Word('literature', 'syllogism', 'n.', 'A three-part logical argument with two premises', 'The famous syllogism about Socrates ends in mortality.'),
  Word('literature', 'commonplace', 'n.', 'A familiar quotation or idea kept on hand for reuse', 'Renaissance students copied a commonplace into a notebook.'),
  Word('literature', 'commonplace book', 'phr.', 'A personal notebook of memorable passages', 'Locke\'s commonplace book mixed sermons and recipes.'),
  Word('literature', 'florilegium', 'n.', 'An anthology of choice passages from various authors', 'Monks circulated a florilegium of patristic wisdom.'),
  Word('literature', 'gloss', 'n.', 'A brief explanation of a difficult word in a margin', 'Old English manuscripts often carry a Latin gloss.'),
  Word('literature', 'scholium', 'n.', 'A marginal note by an ancient or medieval commentator', 'A scholium on the Iliad clarifies a Homeric idiom.'),
  Word('literature', 'pericope', 'n.', 'A self-contained passage carved out for study', 'The sermon focused on one short pericope from Luke.'),
  Word('literature', 'hagiography', 'n.', 'A biography that idealizes its subject', 'Critics complained the new memoir was pure hagiography.'),
  Word('literature', 'panegyric', 'n.', 'A formal speech of high praise', 'Pliny\'s panegyric on Trajan flatters him for pages.'),
  Word('literature', 'eulogy', 'n.', 'A speech praising someone, often at a funeral', 'The eulogy treated his father as a quiet hero.'),
  Word('literature', 'jeremiad', 'n.', 'A long, mournful complaint or denunciation', 'The Sunday op-ed was a jeremiad against modern manners.'),
  Word('literature', 'philippic', 'n.', 'A bitter denunciation aimed at a person or policy', 'Demosthenes\' philippics warned Athens against Philip of Macedon.'),
  Word('literature', 'lampoon', 'n.', 'A coarse satirical attack on a person', 'Pope\'s \'Dunciad\' is a sprawling lampoon of bad writers.'),
  Word('literature', 'invective', 'n.', 'Vehement, insulting language', 'Renaissance preachers loved a good blast of invective.'),
  Word('literature', 'diatribe', 'n.', 'A forceful, unbroken verbal attack', 'His Twitter feed reads like one long diatribe.'),
  Word('literature', 'screed', 'n.', 'A long, often ranting written argument', 'The pamphlet turned out to be an anti-tax screed.'),
  Word('literature', 'manifesto', 'n.', 'A public declaration of principles or aims', 'Marinetti\'s futurist manifesto was printed on the front page of Le Figaro.'),
  Word('literature', 'treatise', 'n.', 'A formal written work on a subject', 'Locke\'s treatise on government changed political thought.'),
  Word('literature', 'tract', 'n.', 'A short polemical pamphlet, often religious', 'The Methodist tract was thrust into every passing hand.'),
  Word('literature', 'familiar essay', 'phr.', 'A relaxed, personal essay in the Montaigne tradition', 'Hazlitt\'s familiar essays still feel like a conversation.'),
  Word('literature', 'lyric', 'n.', 'A short personal poem voicing feeling', 'Sappho\'s lyric fragments still strike like fresh arrows.'),
  Word('literature', 'lyric essay', 'phr.', 'An essay that borrows the compression and music of poetry', 'Anne Carson is a master of the lyric essay.'),
  Word('literature', 'prose poem', 'phr.', 'A short prose work with the density of a poem', 'Baudelaire\'s \'Paris Spleen\' is the great book of prose poems.'),
  Word('literature', 'flash fiction', 'phr.', 'Very short stories, often under a thousand words', 'Lydia Davis built a career on flash fiction.'),
  Word('literature', 'short story', 'phr.', 'A brief work of prose fiction with a single effect', 'Chekhov refined the modern short story.'),
  Word('literature', 'novelette', 'n.', 'A fiction longer than a story but shorter than a novella', 'Many science fiction awards single out the novelette length.'),
  Word('literature', 'sketch', 'n.', 'A brief, lightly drawn prose piece about a place or person', 'Dickens began as a writer of London sketches.'),
  Word('literature', 'vignette', 'n.', 'A short, evocative scene that catches a moment', 'Cisneros\' \'House on Mango Street\' is built from vignettes.'),
  Word('literature', 'tableau', 'n.', 'A static, vivid scene like a painting', 'The chapter ends in a tableau of guests frozen at dinner.'),
  Word('literature', 'set piece', 'phr.', 'A grand passage written for impact', 'The storm at sea is the set piece of the novel.'),
  Word('literature', 'purple prose', 'phr.', 'Overwritten, gaudy passages of fiction', 'The romance novel slips into purple prose every bedroom scene.'),
  Word('literature', 'pulp prose', 'phr.', 'Cheap, gaudy writing styled after old pulps', 'The thriller leans into pulp prose with a wink.'),
  Word('literature', 'plain style', 'phr.', 'A prose style stripped of ornament', 'Hemingway championed a plain style of short sentences.'),
  Word('literature', 'grand style', 'phr.', 'An elevated, formal style suited to weighty subjects', 'Milton\'s grand style turns syntax into music.'),
  Word('literature', 'middle style', 'phr.', 'A balanced prose register between plain and grand', 'A good newspaper column lives in the middle style.'),
  Word('literature', 'sermo humilis', 'phr.', 'The humble style favored by early Christian writers', 'Augustine\'s sermo humilis brought scripture to ordinary ears.'),
  Word('literature', 'register', 'n.', 'A style of language fitted to a setting', 'The narrator shifts register from courtroom to bedroom.'),
  Word('literature', 'diction', 'n.', 'The author\'s choice of words and phrasing', 'Her diction is precise without ever sounding stiff.'),
  Word('literature', 'syntax', 'n.', 'The arrangement of words into sentences', 'Faulkner\'s syntax winds for pages before it lands.'),
  Word('literature', 'cadence', 'n.', 'The rhythmic flow of a sentence or line', 'Listen for the cadence at the end of each paragraph.'),
  Word('literature', 'sentence rhythm', 'phr.', 'The beat and pacing of prose sentences', 'Good revision attends to sentence rhythm above all.'),
  Word('literature', 'periodic sentence', 'phr.', 'A sentence that withholds its main clause until the end', 'A periodic sentence keeps the reader leaning forward.'),
  Word('literature', 'loose sentence', 'phr.', 'A sentence that delivers its main clause early', 'A loose sentence sprawls comfortably after its point.'),
  Word('literature', 'parallelism', 'n.', 'Matching grammatical structure in successive phrases', 'Parallelism gives a sentence the swing of a pendulum.'),
  Word('literature', 'isocolon', 'n.', 'A series of clauses of equal length and form', 'Caesar\'s tricolon is also a perfect isocolon.'),
  Word('literature', 'tricolon', 'n.', 'A series of three parallel clauses or phrases', '\'Friends, Romans, countrymen\' is a famous tricolon.'),
  Word('literature', 'tetracolon', 'n.', 'A series of four parallel clauses or phrases', 'A tetracolon stretches the rhythm a beat longer.'),
  Word('literature', 'auxesis', 'n.', 'A rhetorical climb where each item escalates the last', 'Caesar\'s veni, vidi, vici is a textbook auxesis.'),
  Word('literature', 'anticlimax', 'n.', 'A descent from grand to trivial within a phrase', 'Pope uses anticlimax to puncture his heroine\'s pride.'),
  Word('literature', 'parataxis', 'n.', 'Placing clauses side by side without conjunctions', 'Hemingway\'s parataxis lets each fact stand on its own.'),
  Word('literature', 'hypotaxis', 'n.', 'Subordinating clauses inside larger structures', 'James\'s hypotaxis nests qualifications inside qualifications.'),
  Word('literature', 'sprung rhythm', 'phr.', 'A meter Hopkins built on stressed syllables alone', 'Hopkins claimed sprung rhythm matched the muscle of English speech.'),
  Word('literature', 'iamb', 'n.', 'A metrical foot of one unstressed and one stressed syllable', 'The iamb is the engine of most English verse.'),
  Word('literature', 'trochee', 'n.', 'A metrical foot of one stressed and one unstressed syllable', 'Blake\'s \'Tyger Tyger\' opens with a trochee.'),
  Word('literature', 'anapest', 'n.', 'A metrical foot of two unstressed and one stressed syllable', 'The anapest gallops, as in \'twas the night before Christmas\'.'),
  Word('literature', 'dactyl', 'n.', 'A metrical foot of one stressed and two unstressed syllables', 'Hexameter rolls along on the dactyl.'),
  Word('literature', 'spondee', 'n.', 'A metrical foot of two stressed syllables', 'A spondee makes a line stamp its feet.'),
  Word('literature', 'foot', 'n.', 'A unit of meter made of stressed and unstressed syllables', 'Most English meters describe how many feet fit in a line.'),
  Word('literature', 'dimeter', 'n.', 'A line of verse with two metrical feet', 'Skelton\'s sermons in dimeter rattle along briskly.'),
  Word('literature', 'trimeter', 'n.', 'A line of verse with three metrical feet', 'Many hymns alternate tetrameter and trimeter.'),
  Word('literature', 'tetrameter', 'n.', 'A line of verse with four metrical feet', 'Tetrameter is the ballad and nursery rhyme staple.'),
  Word('literature', 'pentameter', 'n.', 'A line of verse with five metrical feet', 'Iambic pentameter is the backbone of Shakespeare\'s plays.'),
  Word('literature', 'hexameter', 'n.', 'A line of verse with six metrical feet', 'The Iliad rolls in dactylic hexameter for tens of thousands of lines.'),
  Word('literature', 'heptameter', 'n.', 'A line of verse with seven metrical feet', 'Macaulay\'s ballads boom along in heptameter.'),
  Word('literature', 'alexandrine', 'n.', 'A twelve-syllable iambic line, common in French verse', 'Racine\'s tragedies march in alexandrine couplets.'),
  Word('literature', 'fourteener', 'n.', 'A line of fourteen syllables in iambic heptameter', 'Chapman translated Homer into thumping fourteeners.'),
  Word('literature', 'blank verse', 'phr.', 'Unrhymed iambic pentameter', 'Milton\'s \'Paradise Lost\' is written entirely in blank verse.'),
  Word('literature', 'free verse', 'phr.', 'Verse without fixed meter or rhyme', 'Whitman\'s free verse opened a new continent of poetry.'),
  Word('literature', 'heroic couplet', 'phr.', 'A pair of rhyming iambic pentameter lines', 'Pope perfected the heroic couplet to surgical sharpness.'),
  Word('literature', 'couplet', 'n.', 'Two consecutive lines that rhyme', 'A Shakespearean sonnet closes with a turning couplet.'),
  Word('literature', 'tercet', 'n.', 'A stanza or group of three lines', 'A tercet is the smallest stanza that lets a rhyme breathe.'),
  Word('literature', 'terza rima', 'phr.', 'A chained tercet form invented by Dante', 'Dante\'s \'Commedia\' rolls in terza rima for fourteen thousand lines.'),
  Word('literature', 'quatrain', 'n.', 'A stanza of four lines', 'Most hymns and ballads are built from quatrains.'),
  Word('literature', 'quintain', 'n.', 'A stanza of five lines', 'A quintain gives a poem a small surplus to play with.'),
  Word('literature', 'sestet', 'n.', 'A stanza of six lines or the final six of a sonnet', 'The Italian sonnet turns from octave to sestet.'),
  Word('literature', 'septet', 'n.', 'A stanza of seven lines', 'Chaucer\'s \'Troilus\' uses a septet known as rhyme royal.'),
  Word('literature', 'octave', 'n.', 'A stanza of eight lines or the first eight of a sonnet', 'The octave sets up the problem the sestet must answer.'),
  Word('literature', 'rhyme royal', 'phr.', 'A seven-line stanza rhyming ababbcc', 'Chaucer brought rhyme royal into English verse.'),
  Word('literature', 'ottava rima', 'phr.', 'An eight-line stanza rhyming abababcc', 'Byron\'s \'Don Juan\' bounces along in ottava rima.'),
  Word('literature', 'spenserian stanza', 'phr.', 'A nine-line stanza Spenser built for \'The Faerie Queene\'', 'The Spenserian stanza closes on a long alexandrine.'),
  Word('literature', 'ballad stanza', 'phr.', 'A quatrain of alternating tetrameter and trimeter', 'The ballad stanza powers everything from folk songs to Dickinson.'),
  Word('literature', 'common meter', 'phr.', 'A hymn meter of 8-6-8-6 syllables', 'Many of Dickinson\'s poems fit the common meter of Protestant hymns.'),
  Word('literature', 'fixed form', 'phr.', 'A poetic shape with set rules of length and rhyme', 'The villanelle is a fixed form with two recurring lines.'),
  Word('literature', 'villanelle', 'n.', 'A nineteen-line fixed form with two refrains', 'Dylan Thomas\'s \'Do Not Go Gentle\' is the great modern villanelle.'),
  Word('literature', 'sestina', 'n.', 'A fixed form of six six-line stanzas rotating six end-words', 'A sestina makes the same six words feel new each time.'),
  Word('literature', 'pantoum', 'n.', 'A poem of quatrains where lines repeat in a sliding pattern', 'The pantoum came into French verse from Malay.'),
  Word('literature', 'ghazal', 'n.', 'A fixed form of couplets sharing a refrain and rhyme', 'Agha Shahid Ali championed the ghazal in English.'),
  Word('literature', 'rondeau', 'n.', 'A short fixed form built on two rhymes and a refrain', 'A rondeau opens and closes on the same phrase.'),
  Word('literature', 'triolet', 'n.', 'An eight-line poem with two refrain lines', 'A triolet packs a lot of return into very little space.'),
  Word('literature', 'rondel', 'n.', 'A short fixed form of thirteen or fourteen lines with refrains', 'Medieval French poets favored the rondel.'),
  Word('literature', 'ballade', 'n.', 'A French fixed form of three stanzas and an envoi', 'Villon\'s most famous ballade asks where the snows of yesteryear are.'),
  Word('literature', 'aubade', 'n.', 'A dawn poem of lovers parting at sunrise', 'Donne\'s \'The Sun Rising\' is a witty aubade.'),
  Word('literature', 'epithalamion', 'n.', 'A wedding poem celebrating bride and groom', 'Spenser wrote his own epithalamion on his marriage day.'),
  Word('literature', 'bucolic', 'adj.', 'Of country life and pastoral scenes', 'Virgil\'s bucolic poems set shepherds in a soft-edged Italy.'),
  Word('literature', 'georgic', 'n.', 'A poem about agriculture and rural labor', 'Virgil\'s georgics treat beekeeping with epic seriousness.'),
  Word('literature', 'eclogue', 'n.', 'A short pastoral poem, often a dialogue between shepherds', 'Each eclogue stages a different rural conversation.'),
  Word('literature', 'idyll', 'n.', 'A short poem evoking a charming rural scene', 'Tennyson\'s \'Idylls of the King\' borrow the name for Arthurian tales.'),
  Word('literature', 'dirge', 'n.', 'A short mournful song for the dead', 'The chorus closes the play with a dirge.'),
  Word('literature', 'threnody', 'n.', 'A song or poem of grieving', 'Emerson\'s \'Threnody\' mourns his lost son.'),
  Word('literature', 'lament', 'n.', 'A poem or song expressing grief', 'The medieval Welsh tradition is rich in laments.'),
  Word('literature', 'paean', 'n.', 'A song of praise or triumph', 'The newspaper review was a paean to her new collection.'),
  Word('literature', 'hymn', 'n.', 'A religious song of praise', 'Charles Wesley wrote thousands of hymns.'),
  Word('literature', 'psalm', 'n.', 'A sacred song or poem, especially from the biblical book', 'Coverdale\'s psalm translations entered the Book of Common Prayer.'),
  Word('literature', 'canticle', 'n.', 'A hymn or chant taken from biblical text', 'The Magnificat is the most famous canticle.'),
  Word('literature', 'epistle', 'n.', 'A formal letter, sometimes used as a literary form', 'Horace\'s verse epistles set a template for centuries.'),
  Word('literature', 'meditation', 'n.', 'A reflective devotional poem or essay', 'Donne\'s prose meditations move from sickbed to cosmos.'),
  Word('literature', 'devotional', 'adj.', 'Concerned with religious feeling and practice', 'The devotional poems of Herbert still speak across centuries.'),
  Word('literature', 'metaphysical', 'adj.', 'Of seventeenth-century poets fond of intellectual conceits', 'Donne and Herbert are the heart of the metaphysical school.'),
  Word('literature', 'cavalier', 'adj.', 'Of Royalist seventeenth-century poets writing on love and loyalty', 'The cavalier poets prized elegance and a light touch.'),
  Word('literature', 'augustan', 'adj.', 'Of the early eighteenth-century English poets of polish and wit', 'Pope and Swift are the great augustan satirists.'),
  Word('literature', 'graveyard', 'adj.', 'Of an eighteenth-century school musing on death in churchyards', 'Gray\'s elegy is the masterpiece of the graveyard school.'),
  Word('literature', 'sentimental', 'adj.', 'Of an eighteenth-century fashion for tender feeling', 'The sentimental novel taught readers to cry on cue.'),
  Word('literature', 'bluestocking', 'n.', 'An intellectual woman of the eighteenth-century London salons', 'The bluestocking circle pioneered women\'s public learning.'),
  Word('literature', 'salon', 'n.', 'A regular literary gathering at a private home', 'Madame de Staël\'s salon hosted half of Europe\'s writers.'),
  Word('literature', 'coterie', 'n.', 'A close circle of writers sharing taste and influence', 'The coterie around Pound rebuilt modern poetry from within.'),
  Word('literature', 'symposium', 'n.', 'A gathering for serious talk, modeled on Plato\'s dialogue', 'The annual symposium gathers translators of medieval verse.'),
  Word('literature', 'discourse', 'n.', 'Extended verbal exchange or talk in a work', 'Plato turned philosophical discourse into an art form.'),
  Word('literature', 'colloquy', 'n.', 'A formal conversation, often staged', 'Erasmus\' colloquies were classroom plays for Latin students.'),
  Word('literature', 'masque', 'n.', 'A courtly entertainment of music, dance, and verse', 'Ben Jonson wrote masques for the Stuart court.'),
  Word('literature', 'mystery play', 'phr.', 'A medieval drama staging biblical episodes', 'The York mystery plays were performed on wagons in the street.'),
  Word('literature', 'morality play', 'phr.', 'A medieval drama in which characters personify virtues and vices', '\'Everyman\' is the most famous morality play.'),
  Word('literature', 'miracle play', 'phr.', 'A medieval drama dramatizing the life of a saint', 'A miracle play might depict the trials of Saint Nicholas.'),
  Word('literature', 'commedia dell\'arte', 'phr.', 'An improvised Italian comedy of stock masked roles', 'Harlequin and Pantalone come from the commedia dell\'arte.'),
  Word('literature', 'closet drama', 'phr.', 'A play meant to be read rather than staged', 'Shelley\'s \'Prometheus Unbound\' is a great closet drama.'),
  Word('literature', 'tragicomedy', 'n.', 'A play mixing tragic and comic elements', 'Beaumont and Fletcher specialized in tragicomedy.'),
  Word('literature', 'kabuki', 'n.', 'A stylized Japanese form of dance-drama', 'Kabuki actors wear bold makeup and exaggerated costumes.'),
  Word('literature', 'noh', 'n.', 'A formal Japanese masked theater drawing on myth', 'Yeats studied noh and let it shape his late plays.'),
  Word('literature', 'kyogen', 'n.', 'Short comic Japanese plays performed between noh acts', 'Kyogen lifts the mood after a heavy noh drama.'),
  Word('literature', 'sanskrit drama', 'phr.', 'Classical Indian theater in Sanskrit', 'Kalidasa\'s \'Shakuntala\' is the jewel of Sanskrit drama.'),
  Word('literature', 'kathakali', 'n.', 'A classical Indian dance-drama of southern Kerala', 'Kathakali dancers train for years in eye movements alone.'),
  Word('literature', 'shadow play', 'phr.', 'A drama performed with cut-out figures behind a lit screen', 'Indonesian wayang is the most famous shadow play tradition.'),
  Word('literature', 'wayang', 'n.', 'Indonesian shadow puppet theater drawing on epic stories', 'A wayang performance can last all night.'),
  Word('literature', 'tragic flaw', 'phr.', 'A defect of character that brings about a hero\'s downfall', 'Othello\'s tragic flaw is jealousy.'),
  Word('literature', 'hamartia', 'n.', 'The Greek term for a tragic error or flaw', 'Aristotle places hamartia at the center of tragedy.'),
  Word('literature', 'peripeteia', 'n.', 'The sudden reversal of fortune in a drama', 'Oedipus\'s peripeteia falls when the messenger speaks.'),
  Word('literature', 'anagnorisis', 'n.', 'A character\'s decisive moment of recognition', 'Aristotle pairs anagnorisis with peripeteia for maximum effect.'),
  Word('literature', 'stichomythia', 'n.', 'Rapid line-for-line exchange between two characters', 'Greek tragedy crackles when it slides into stichomythia.'),
  Word('literature', 'parabasis', 'n.', 'A passage where the chorus addresses the audience directly', 'Aristophanes uses the parabasis to roast Athenian politics.'),
  Word('literature', 'parodos', 'n.', 'The entrance song of the chorus in Greek drama', 'The parodos sets the tone before the action begins.'),
  Word('literature', 'stasimon', 'n.', 'A choral ode sung between episodes of Greek tragedy', 'Each stasimon comments on what just happened on stage.'),
  Word('literature', 'agon', 'n.', 'A formal contest of words between two characters', 'The central agon of \'Antigone\' pits law against family.'),
  Word('literature', 'episode', 'n.', 'A scene in Greek drama between choral odes', 'An ancient tragedy alternates episode and stasimon.'),
  Word('literature', 'prologos', 'n.', 'The opening scene of a Greek play before the chorus enters', 'The prologos lays out the situation in a single voice.'),
  Word('literature', 'exodos', 'n.', 'The closing scene of a Greek play after the last ode', 'The exodos clears the stage and the chorus.'),
  Word('literature', 'three unities', 'phr.', 'The neoclassical rules of one action, one place, one day', 'French tragedy clung to the three unities longer than English.'),
  Word('literature', 'unity of action', 'phr.', 'The rule that a play\'s plot should be single and whole', 'Aristotle prizes unity of action above all else.'),
  Word('literature', 'unity of place', 'phr.', 'The rule that a play should stay in one location', 'Neoclassical critics insisted on strict unity of place.'),
  Word('literature', 'unity of time', 'phr.', 'The rule that a play\'s action should fit within a day', 'Racine respects unity of time to claustrophobic effect.'),
  Word('literature', 'theatre of cruelty', 'phr.', 'Artaud\'s vision of a primal, shocking stage', 'The theatre of cruelty aimed to assault audience habit.'),
  Word('literature', 'theatre of the absurd', 'phr.', 'Postwar drama showing existence as senseless and bleakly funny', 'Beckett and Ionesco lead the theatre of the absurd.'),
  Word('literature', 'epic theatre', 'phr.', 'Brecht\'s style designed to provoke thought rather than empathy', 'Epic theatre breaks illusion with songs and placards.'),
  Word('literature', 'verfremdungseffekt', 'n.', 'Brecht\'s alienation effect that keeps audiences thinking', 'A spotlight aimed at the audience is classic verfremdungseffekt.'),
  Word('literature', 'method', 'n.', 'A school of acting drawing on inner emotional memory', 'Strasberg taught the method to a generation of American stars.'),
  Word('literature', 'staging', 'n.', 'The way a play is arranged in performance', 'The new staging set the whole production inside a kitchen.'),
  Word('literature', 'mise-en-scène', 'n.', 'Everything visible on stage or in a film frame', 'Her mise-en-scène loaded the room with telling props.'),
  Word('literature', 'blocking', 'n.', 'The pattern of actors\' movements on a stage', 'A director sketches the blocking before the first rehearsal.'),
  Word('literature', 'stage direction', 'phr.', 'An instruction in a script about action or setting', 'Beckett\'s stage directions can be more haunting than his dialogue.'),
  Word('literature', 'story beat', 'phr.', 'A small unit of action within a scene', 'Each story beat shifts the relationship between the two characters.'),
  Word('literature', 'intermission', 'n.', 'A break between the acts of a play', 'The intermission gave everyone time to debate the ending so far.'),
  Word('literature', 'curtain', 'n.', 'The drop of fabric ending a play or act', 'The curtain falls on a single lit chair.'),
  Word('literature', 'tagline', 'n.', 'A short memorable phrase associated with a work', 'The novel\'s tagline appeared on every bus shelter.'),
  Word('literature', 'logline', 'n.', 'A one-sentence summary of a story\'s premise', 'A good logline sells a script in a single breath.'),
  Word('literature', 'premise', 'n.', 'The central situation a story sets up', 'The premise is simple: a man wakes up as a beetle.'),
  Word('literature', 'inciting incident', 'phr.', 'The event that sets the main story in motion', 'The inciting incident in \'Hamlet\' is the ghost\'s appearance.'),
  Word('literature', 'rising action', 'phr.', 'The building complications after the inciting incident', 'The rising action keeps tightening until the third act.'),
  Word('literature', 'falling action', 'phr.', 'The unwinding tension after the climax', 'The falling action eases the reader into the ending.'),
  Word('literature', 'turning point', 'phr.', 'The moment a story\'s direction shifts decisively', 'The turning point comes when she opens the letter.'),
  Word('literature', 'plot point', 'phr.', 'A specific event that reshapes the plot', 'Screenwriters often pin a plot point at the end of act one.'),
  Word('literature', 'midpoint', 'n.', 'The structural pivot at the middle of a screenplay', 'The midpoint reversal sends the hero into deeper water.'),
  Word('literature', 'beat sheet', 'phr.', 'A one-page outline of a story\'s structural beats', 'Many screenwriters draft a beat sheet before the script.'),
  Word('literature', 'three-act structure', 'phr.', 'The standard screenplay shape of setup, conflict, and resolution', 'Hollywood films lean hard on three-act structure.'),
  Word('literature', 'five-act structure', 'phr.', 'A classical play structure of five linked sections', 'Shakespeare typically uses a flexible five-act structure.'),
  Word('literature', 'freytag\'s pyramid', 'phr.', 'A diagram of dramatic shape with five rising and falling stages', 'Freytag\'s pyramid is still taught in introductory drama classes.'),
  Word('literature', 'hero\'s journey', 'phr.', 'A mythic story pattern of departure, ordeal, and return', 'Star Wars famously follows the hero\'s journey.'),
  Word('literature', 'monomyth', 'n.', 'Campbell\'s name for the universal hero\'s journey', 'The monomyth lifts its bones from comparative mythology.'),
  Word('literature', 'save the cat', 'phr.', 'A screenwriting beat-sheet method popularized by Blake Snyder', 'Save the cat advises planting a likable moment up front.'),
  Word('literature', 'snowflake method', 'phr.', 'A way of outlining a novel by expanding a one-line idea', 'The snowflake method grows scope step by patient step.'),
  Word('literature', 'pantser', 'n.', 'A writer who drafts without an outline', 'Stephen King is a famous pantser.'),
  Word('literature', 'plotter', 'n.', 'A writer who outlines a story before drafting', 'She\'s a plotter who knows the ending before chapter one.'),
  Word('literature', 'discovery draft', 'phr.', 'A first draft used to find out what the story is', 'Most novelists need a discovery draft before they really start.'),
  Word('literature', 'shitty first draft', 'phr.', 'Anne Lamott\'s permission to write a bad first attempt', 'The shitty first draft is where the real book starts.'),
  Word('literature', 'revision', 'n.', 'The process of rewriting and refining a draft', 'Most writers think their book is born in revision.'),
  Word('literature', 'line edit', 'phr.', 'Editing focused on word choice and sentence rhythm', 'A good line edit lifts the prose without changing the story.'),
  Word('literature', 'copyedit', 'n.', 'Editing focused on grammar and consistency', 'A copyedit catches the comma splices and continuity slips.'),
  Word('literature', 'proofread', 'v.', 'To check a final text for small errors', 'She proofread the galleys with a sharp pencil.'),
  Word('literature', 'galley', 'n.', 'An advance printed proof of a forthcoming book', 'Reviewers received the galleys six months before pub date.'),
  Word('literature', 'reader copy', 'phr.', 'An advance printed copy sent out for early publicity', 'Booksellers pass a reader copy around the staff room.'),
  Word('literature', 'blurb', 'n.', 'A short promotional quote on a book\'s jacket', 'A blurb from a famous novelist can sell tens of thousands of copies.'),
  Word('literature', 'jacket copy', 'phr.', 'The descriptive text on a book\'s dust jacket', 'Strong jacket copy is half the work of selling a literary novel.'),
  Word('literature', 'pitch', 'n.', 'A brief sell of a story\'s premise to an editor or agent', 'Her pitch was a sentence long and the room laughed.'),
  Word('literature', 'query letter', 'phr.', 'A short letter sent to agents proposing a book', 'A good query letter opens with the hook and ends with credentials.'),
  Word('literature', 'submission', 'n.', 'A manuscript sent for consideration to a publisher', 'The submission spent six weeks in the slush pile.'),
  Word('literature', 'slush pile', 'phr.', 'The stack of unsolicited submissions at a publisher', 'A famous novel was once plucked from a slush pile.'),
  Word('literature', 'midlist', 'n.', 'Books that sell modestly without becoming bestsellers', 'Most working novelists make a living on the midlist.'),
  Word('literature', 'remainder', 'n.', 'An unsold book offered at a deep discount', 'A remainder bin can yield surprising literary finds.'),
  Word('literature', 'backlist', 'n.', 'A publisher\'s books from previous seasons still in print', 'A strong backlist pays a publisher\'s bills for years.'),
  Word('literature', 'frontlist', 'n.', 'A publisher\'s newly released titles', 'The frontlist gets all the marketing budget.'),
  Word('literature', 'imprint', 'n.', 'A publishing brand within a larger company', 'Knopf is the prestige imprint inside Random House.'),
  Word('literature', 'copyright', 'n.', 'A legal right to control reproduction of a work', 'Her contract granted the publisher the copyright for ten years.'),
  Word('literature', 'royalties', 'n.', 'A share of revenue paid to authors per copy sold', 'Most novelists earn their royalties only after the advance earns out.'),
  Word('literature', 'advance', 'n.', 'A sum paid to an author before publication', 'The advance was generous but had to last three years of writing.'),
  Word('literature', 'agent', 'n.', 'A literary representative who sells work for the author', 'Her agent sold the novel in three days.'),
  Word('literature', 'editor', 'n.', 'A publishing professional who shapes a book for press', 'Maxwell Perkins was the editor of Fitzgerald and Hemingway.'),
  Word('literature', 'amanuensis', 'n.', 'A scribe who writes from another\'s dictation', 'Milton dictated \'Paradise Lost\' to a series of amanuenses.'),
  Word('literature', 'ghostwriter', 'n.', 'A writer who pens a book credited to someone else', 'Many celebrity memoirs are shaped by a discreet ghostwriter.'),
  Word('literature', 'collaboration', 'n.', 'A work written by two or more authors together', 'Their collaboration produced a play neither could have written alone.'),
  Word('literature', 'translation', 'n.', 'A version of a work in a different language', 'The new translation finally lets English readers hear the music.'),
  Word('literature', 'translator', 'n.', 'A person who renders a text from one language into another', 'The translator\'s name is finally on the cover this time.'),
  Word('literature', 'adaptation', 'n.', 'A work remade in a new medium or form', 'The screen adaptation cuts two of the novel\'s subplots.'),
  Word('literature', 'novelization', 'n.', 'A novel based on a film, game, or other source', 'A novelization can sell as well as the movie it follows.'),
  Word('literature', 'fan fiction', 'phr.', 'Stories written by fans using existing characters and worlds', 'Many bestsellers started life as fan fiction.'),
  Word('literature', 'retelling', 'n.', 'A new version of a classic story', 'Margaret Atwood\'s retelling of the Odyssey gives Penelope a voice.'),
  Word('literature', 'mash-up', 'n.', 'A novel splicing a classic with new genre elements', 'The Jane Austen mash-up added zombies to the Bennet ball.'),
  Word('literature', 'imitation', 'n.', 'A work copying the style of another author in tribute', 'Pope\'s \'Imitations of Horace\' update the Roman satirist for London.'),
  Word('literature', 'burlesque', 'n.', 'A comic imitation that mocks a serious source', 'Cervantes wrote one of the world\'s great burlesques of chivalric romance.'),
  Word('literature', 'lampoonery', 'n.', 'The practice of ridiculing folly or vice in writing', 'Swift\'s \'A Modest Proposal\' is the gold standard of lampoonery.'),
  Word('literature', 'horatian satire', 'phr.', 'A gentle, urbane form of satire', 'Horatian satire winks where Juvenalian satire snarls.'),
  Word('literature', 'juvenalian satire', 'phr.', 'A bitter, harsh form of satire named after Juvenal', 'Swift\'s \'A Modest Proposal\' is juvenalian satire at full volume.'),
  Word('literature', 'menippean satire', 'phr.', 'A satire mixing prose, verse, and digression to attack ideas', 'Burton\'s \'Anatomy of Melancholy\' is sprawling menippean satire.'),
  Word('literature', 'mock epic', 'phr.', 'A poem applying epic grandeur to a trivial subject', 'Pope\'s \'The Rape of the Lock\' is the great English mock epic.'),
  Word('literature', 'mock heroic', 'adj.', 'Of writing that treats trivial matters in heroic style', 'The mock heroic tone turns a card game into a battle.'),
  Word('literature', 'travesty', 'n.', 'A grotesque imitation of a serious work', 'The pantomime version was a travesty of the original tragedy.'),
  Word('literature', 'spoof', 'n.', 'A light comic parody', 'The film is a spoof of every haunted-house cliché.'),
  Word('literature', 'send-up', 'n.', 'A mocking imitation of someone or something', 'The novel is a wicked send-up of Manhattan publishing.'),
  Word('literature', 'roman policier', 'phr.', 'A French term for the detective novel', 'Simenon\'s Maigret books defined the modern roman policier.'),
  Word('literature', 'kunstlerroman', 'n.', 'A novel about the development of an artist', 'Joyce\'s \'Portrait of the Artist\' is the model kunstlerroman.'),
  Word('literature', 'erziehungsroman', 'n.', 'A novel of education and moral training', 'The erziehungsroman tracks a hero through teachers and trials.'),
  Word('literature', 'gesamtkunstwerk', 'n.', 'A total artwork uniting music, text, and stage', 'Wagner aimed at the gesamtkunstwerk in his Bayreuth festival.'),
  Word('literature', 'leitmotif', 'n.', 'A recurring image or phrase tied to a theme or character', 'A wilting rose is the leitmotif of the protagonist\'s decline.'),
  Word('literature', 'doppelganger', 'n.', 'A ghostly or fictional double of a living person', 'Poe loved a good doppelganger.'),
  Word('literature', 'confidant', 'n.', 'A trusted character to whom another reveals secrets', 'Horatio is Hamlet\'s confidant from the first scene.'),
  Word('literature', 'flat character', 'phr.', 'A character defined by a single trait', 'Most minor villains are deliberately flat characters.'),
  Word('literature', 'round character', 'phr.', 'A character of complex and developing traits', 'A good protagonist is always a round character.'),
  Word('literature', 'static character', 'phr.', 'A character who does not change over the story', 'The wise neighbor often stays a static character.'),
  Word('literature', 'dynamic character', 'phr.', 'A character whose inner life changes across the story', 'The heroine\'s shift from naivety to insight makes her dynamic.'),
  Word('literature', 'characterization', 'n.', 'The craft of creating and revealing characters', 'Strong characterization makes the reader hear a voice from page one.'),
  Word('literature', 'interiority', 'n.', 'The depicted inner life of a character', 'Henry James perfected the art of rendering interiority.'),
  Word('literature', 'point of view', 'phr.', 'The position from which a story is told', 'A shift in point of view can transform the same scene.'),
  Word('literature', 'first person', 'phr.', 'A narrative told by an \'I\' character', 'Holden Caulfield narrates \'Catcher in the Rye\' in first person.'),
  Word('literature', 'second person', 'phr.', 'A narrative addressed to a \'you\'', 'Bright Lights, Big City sustains second person for the whole novel.'),
  Word('literature', 'third person', 'phr.', 'A narrative told from outside the characters using \'he\' or \'she\'', 'Most nineteenth-century novels stay in steady third person.'),
  Word('literature', 'limited', 'adj.', 'Of a third-person view confined to one character\'s mind', 'A limited point of view stays inside one consciousness at a time.'),
  Word('literature', 'objective', 'adj.', 'Of a narration showing only what an observer could see', 'Hemingway\'s objective style refuses to enter anyone\'s head.'),
  Word('literature', 'narrative distance', 'phr.', 'How close or remote the prose feels from a character\'s mind', 'The chapter pulls the narrative distance back to a long historical shot.'),
  Word('literature', 'showing', 'n.', 'Conveying meaning through scene and image rather than statement', 'Workshops always preach showing over telling.'),
  Word('literature', 'telling', 'n.', 'Conveying meaning through direct statement rather than scene', 'A summary chapter relies on telling to leap over years.'),
  Word('literature', 'pacing', 'n.', 'The speed at which a story unfolds', 'The middle chapters need tighter pacing.'),
  Word('literature', 'tension', 'n.', 'The pull of unresolved force in a scene or sentence', 'A good page keeps tension humming under the surface.'),
  Word('literature', 'stakes', 'n.', 'What a character stands to gain or lose', 'Without clear stakes, even chases turn dull.'),
  Word('literature', 'world-building', 'n.', 'The craft of inventing a story\'s setting and rules', 'Tolkien set the standard for world-building in fantasy.'),
  Word('literature', 'milieu', 'n.', 'The social environment in which a story takes place', 'Wharton brings Old New York milieu to life.'),
  Word('literature', 'atmosphere', 'n.', 'The pervading feeling of a literary work', 'Poe\'s tales drip with claustrophobic atmosphere.'),
  Word('literature', 'ambience', 'n.', 'The mood and character of a place or scene', 'The opening chapter sets a misty London ambience.'),
  Word('literature', 'sense of place', 'phr.', 'A vivid feel for the geography of a story', 'Eudora Welty had a sense of place that you could smell.'),
  Word('literature', 'local color', 'phr.', 'Vivid regional detail evoked in fiction', 'Bret Harte\'s mining tales are thick with local color.'),
  Word('literature', 'regionalism', 'n.', 'Writing focused on a particular geographic area', 'Sarah Orne Jewett\'s Maine sketches are central to American regionalism.'),
  Word('literature', 'urban', 'adj.', 'Of writing rooted in city life and rhythm', 'Dickens turned urban London into a literary subject.'),
  Word('literature', 'flaneur', 'n.', 'A wandering observer of city streets', 'Baudelaire celebrated the flaneur as the modern poet.'),
  Word('literature', 'psychogeography', 'n.', 'Writing about how places shape feeling and thought', 'Iain Sinclair walks London in his books of psychogeography.'),
  Word('literature', 'nature writing', 'phr.', 'A genre of careful prose about wild places', 'Annie Dillard\'s \'Pilgrim at Tinker Creek\' is a classic of nature writing.'),
  Word('literature', 'travel writing', 'phr.', 'A genre describing journeys and foreign places', 'Bruce Chatwin reshaped modern travel writing.'),
  Word('literature', 'reportage', 'n.', 'Detailed factual writing based on direct observation', 'Hersey\'s \'Hiroshima\' set the bar for postwar reportage.'),
  Word('literature', 'new journalism', 'phr.', 'A 1960s movement applying novelistic technique to reporting', 'Tom Wolfe championed the new journalism in the magazines.'),
  Word('literature', 'gonzo', 'adj.', 'Of immersive first-person journalism in the Thompson mode', 'Hunter S. Thompson invented gonzo reporting on the campaign trail.'),
  Word('literature', 'literary journalism', 'phr.', 'Nonfiction that uses the techniques of fiction', 'Joan Didion\'s essays are a high-water mark of literary journalism.'),
  Word('literature', 'creative nonfiction', 'phr.', 'True writing crafted with the tools of fiction', 'Creative nonfiction lets memoirists shape memory like scene.'),
  Word('literature', 'nonfiction novel', 'phr.', 'A genre that reports real events with novelistic technique', 'Capote called \'In Cold Blood\' a nonfiction novel.'),
  Word('literature', 'documentary poetry', 'phr.', 'Poetry built from documents and primary records', 'Muriel Rukeyser pioneered modern documentary poetry.'),
  Word('literature', 'oral history', 'phr.', 'A record of past events told in the voices of participants', 'Svetlana Alexievich won the Nobel for her oral histories.'),
  Word('literature', 'testimonio', 'n.', 'A first-person account bearing witness to oppression', 'Rigoberta Menchú\'s testimonio sparked a wide ethical debate.'),
  Word('literature', 'lyric I', 'phr.', 'The speaking voice of a lyric poem', 'The lyric I is never quite the poet, but never quite a stranger.'),
  Word('literature', 'persona', 'n.', 'A fictional speaker the writer adopts in a poem or story', 'Browning\'s \'My Last Duchess\' is voiced by a chilling persona.'),
  Word('literature', 'dramatic monologue', 'phr.', 'A poem in which a single speaker reveals himself in a setting', 'Browning perfected the dramatic monologue in Victorian England.'),
  Word('literature', 'apostrophic', 'adj.', 'Of poetry that addresses absent persons or abstractions', 'Shelley\'s apostrophic odes call out to wind and skylark.'),
  Word('literature', 'invocation', 'n.', 'A formal opening call to a muse or deity', 'Milton begins \'Paradise Lost\' with a long invocation.'),
  Word('literature', 'muse', 'n.', 'A source or goddess of inspiration', 'Homer asks the muse to sing the wrath of Achilles.'),
  Word('literature', 'epic simile', 'phr.', 'An elaborate extended comparison in Homeric verse', 'An epic simile can spiral on for ten lines before returning to the action.'),
  Word('literature', 'homeric epithet', 'phr.', 'A stock descriptive phrase attached to a Homeric figure', 'Achilles is the swift-footed of the homeric epithet.'),
  Word('literature', 'formula', 'n.', 'A repeated phrase that helps an oral poet improvise', 'Milman Parry showed Homer was built from formulas.'),
  Word('literature', 'oral tradition', 'phr.', 'The body of stories carried by memory and performance', 'African griots preserve epic in oral tradition.'),
  Word('literature', 'griot', 'n.', 'A West African storyteller and oral historian', 'A griot might recite a clan\'s genealogy for hours.'),
  Word('literature', 'bard', 'n.', 'A poet who sings tales of heroes, often to music', 'Welsh tradition still honors the bard at the Eisteddfod.'),
  Word('literature', 'skald', 'n.', 'A Norse court poet performing praise verse', 'The skald composed elaborate metaphors for sword and ship.'),
  Word('literature', 'scop', 'n.', 'An Anglo-Saxon court poet and entertainer', 'The scop in \'Beowulf\' sings of older heroes between battles.'),
  Word('literature', 'troubadour', 'n.', 'A medieval Provençal lyric poet of courtly love', 'The troubadour tradition shaped European poetry for centuries.'),
  Word('literature', 'trouvere', 'n.', 'A medieval lyric poet of northern France', 'A trouvere sang of love and chivalry at noble courts.'),
  Word('literature', 'minnesinger', 'n.', 'A medieval German lyric poet of courtly love', 'Walther von der Vogelweide is the most famous minnesinger.'),
  Word('literature', 'jongleur', 'n.', 'A medieval traveling entertainer reciting verse', 'The jongleur could juggle, sing, and recite a chanson de geste.'),
  Word('literature', 'chanson de geste', 'phr.', 'An Old French epic of heroic deeds', 'The Song of Roland is the great surviving chanson de geste.'),
  Word('literature', 'matière', 'n.', 'A traditional cycle of subject matter in medieval romance', 'The matière de Bretagne supplied Arthurian stories to all Europe.'),
  Word('literature', 'lai', 'n.', 'A short narrative poem in the medieval French tradition', 'Marie de France\'s lais are jewels of twelfth-century verse.'),
  Word('literature', 'fabliau', 'n.', 'A short, bawdy medieval comic tale', 'Chaucer reworked the fabliau in his bawdier Canterbury tales.'),
  Word('literature', 'bestiary', 'n.', 'A medieval book of moralized animal lore', 'A bestiary tells you what a lion or unicorn means as much as is.'),
  Word('literature', 'iconography', 'n.', 'A system of visual symbols carrying meaning', 'Christian iconography assigns each saint a recognizable attribute.'),
  Word('literature', 'iconology', 'n.', 'The study of meaning in visual images and symbols', 'Panofsky\'s iconology shaped how we read Renaissance paintings.'),
  Word('literature', 'mythopoeia', 'n.', 'The making of myth, or invented mythological writing', 'Tolkien\'s legendarium is a feat of modern mythopoeia.'),
  Word('literature', 'legendarium', 'n.', 'A body of legendary writings linked into one mythology', 'Tolkien\'s legendarium fills more volumes than the trilogy.'),
  Word('literature', 'cosmogony', 'n.', 'A myth or theory of how the universe began', 'Hesiod\'s Theogony lays out a Greek cosmogony.'),
  Word('literature', 'apocalyptic', 'adj.', 'Of writing about catastrophic ends and revelations', 'Cormac McCarthy\'s \'The Road\' is an apocalyptic masterpiece.'),
  Word('literature', 'eschatology', 'n.', 'Doctrine of the last things, often used in literary criticism', 'Milton\'s late work circles around eschatology.'),
  Word('literature', 'theodicy', 'n.', 'A writing defending divine justice in a suffering world', '\'Paradise Lost\' is in part a theodicy in verse.'),
  Word('literature', 'intertextuality', 'n.', 'The web of references and echoes between texts', 'Modernist poems are dense with intertextuality.'),
  Word('literature', 'hypertext', 'n.', 'Text linked nonlinearly to other texts', 'Early electronic hypertext novels asked readers to choose a path.'),
  Word('literature', 'ergodic', 'adj.', 'Of literature requiring nontrivial effort to traverse', 'Pavić\'s dictionary novel is a celebrated ergodic work.'),
  Word('literature', 'liminality', 'n.', 'A state of being on the threshold between two conditions', 'Coming-of-age novels live in liminality.'),
  Word('literature', 'uncanny', 'n.', 'Freud\'s name for the strangely familiar in fiction', 'A doll that almost looks alive is the uncanny in miniature.'),
  Word('literature', 'sublimation', 'n.', 'The redirecting of impulse into creative work', 'Freud read art as the sublimation of forbidden wishes.'),
  Word('literature', 'objet petit a', 'phr.', 'Lacan\'s unattainable object of desire in narrative', 'A novel\'s longed-for letter often plays the role of objet petit a.'),
  Word('literature', 'gaze', 'n.', 'The directing of looking that structures viewing or reading', 'Feminist critics famously analyze the male gaze.'),
  Word('literature', 'subject position', 'phr.', 'The stance a text invites the reader to occupy', 'Each chapter opens a different subject position to the reader.'),
  Word('literature', 'reader response', 'phr.', 'A criticism focused on how readers make meaning', 'Reader response shifted attention from the text alone to its audience.'),
  Word('literature', 'horizon of expectations', 'phr.', 'Jauss\'s name for the conventions readers bring to a text', 'A novel that breaks the horizon of expectations often gets read as new.'),
  Word('literature', 'implied reader', 'phr.', 'The reader a text seems to imagine and address', 'Iser argues every text builds its own implied reader.'),
  Word('literature', 'formalism', 'n.', 'A criticism focused on form rather than context', 'Russian formalism gave us the very vocabulary of literary device.'),
  Word('literature', 'new criticism', 'phr.', 'A mid-century school treating poems as self-contained objects', 'New criticism trained students to read closely line by line.'),
  Word('literature', 'close reading', 'phr.', 'Careful attention to a text\'s every word and figure', 'Close reading still anchors most literature classrooms.'),
  Word('literature', 'distant reading', 'phr.', 'Analysis of literature using large-scale data', 'Franco Moretti coined distant reading for studying thousands of novels.'),
  Word('literature', 'structuralism', 'n.', 'A criticism mapping literature\'s underlying patterns', 'Saussure\'s linguistics gave structuralism its starting tools.'),
  Word('literature', 'poststructuralism', 'n.', 'A criticism questioning fixed structures and meanings', 'Poststructuralism unsettled the certainties of an earlier French criticism.'),
  Word('literature', 'deconstruction', 'n.', 'Derrida\'s practice of unsettling textual oppositions', 'Deconstruction finds the moment a binary collapses under itself.'),
  Word('literature', 'différance', 'n.', 'Derrida\'s play on difference and deferral of meaning', 'Différance is famously hard to translate without losing the pun.'),
  Word('literature', 'logocentrism', 'n.', 'A bias toward speech and presence over writing', 'Derrida critiques the logocentrism of Western philosophy.'),
  Word('literature', 'phallogocentrism', 'n.', 'A logocentrism marked by masculine bias', 'Feminist theorists adopted phallogocentrism as a critical term.'),
  Word('literature', 'écriture féminine', 'phr.', 'A mode of writing tied to women\'s bodies and rhythms', 'Cixous called for écriture féminine as a way out of patriarchal language.'),
  Word('literature', 'gynocriticism', 'n.', 'A criticism focused on women writers as a tradition', 'Elaine Showalter coined gynocriticism for studying women\'s literary history.'),
  Word('literature', 'postcolonial', 'adj.', 'Of literature and theory analyzing colonial aftermath', 'Postcolonial readings explore power, language, and empire.'),
  Word('literature', 'subaltern', 'n.', 'A person outside the structures of dominant power', 'Spivak\'s essay asks whether the subaltern can speak.'),
  Word('literature', 'orientalism', 'n.', 'A Western mode of constructing the East as exotic other', 'Said\'s \'Orientalism\' is a foundational postcolonial work.'),
  Word('literature', 'hybridity', 'n.', 'A mixing of cultural forms across colonial boundaries', 'Bhabha placed hybridity at the heart of postcolonial theory.'),
  Word('literature', 'mimicry', 'n.', 'The colonized subject\'s imitation that subtly destabilizes power', 'Bhabha reads colonial mimicry as both flattering and threatening.'),
  Word('literature', 'creolization', 'n.', 'The blending of languages and cultures, especially in the Caribbean', 'Glissant celebrates creolization as a model for world culture.'),
  Word('literature', 'negritude', 'n.', 'A literary movement affirming Black identity and pride', 'Césaire and Senghor founded negritude in 1930s Paris.'),
  Word('literature', 'queer theory', 'phr.', 'A criticism unsettling fixed categories of sex and desire', 'Eve Sedgwick is central to the queer theory of the early 1990s.'),
  Word('literature', 'ecocriticism', 'n.', 'A criticism reading literature through ecological lenses', 'Ecocriticism asks what our books say about the land.'),
  Word('literature', 'biofiction', 'n.', 'A novel that imagines a real person\'s inner life', 'Colm Tóibín\'s \'The Master\' is biofiction about Henry James.'),
  Word('literature', 'docupoetics', 'n.', 'A poetics built on archival and documentary materials', 'Claudia Rankine\'s \'Citizen\' draws on docupoetics.'),
  Word('literature', 'litfic', 'n.', 'A casual industry term for literary fiction', 'Booksellers distinguish litfic from genre on the shelf.'),
];
