import 'words_data.dart';

const kLiteratureExtras2 = <Word>[
  Word('literature', 'antihero', 'n.', 'a central character who lacks conventional heroic qualities such as courage or morality', 'The brooding antihero of the novel cheats and lies yet still wins our sympathy.'),
  Word('literature', 'foil character', 'n.', 'a character whose contrasting traits highlight those of another', 'The cheerful sidekick acts as a foil character to the grim detective.'),
  Word('literature', 'archetypal', 'adj.', 'relating to a recurring symbol or character type found across many stories', 'The wise old mentor is an archetypal figure in fantasy fiction.'),
  Word('literature', 'epiphany', 'n.', 'a sudden moment of insight or revelation experienced by a character', 'In a quiet epiphany, she realized her whole life had been a performance.'),
  Word('literature', 'motivation', 'n.', 'the underlying reason driving a character\'s actions', 'The villain\'s motivation is revealed to be a childhood betrayal.'),
  Word('literature', 'subtext', 'n.', 'meaning that lies beneath the literal words of a text', 'Their polite conversation carried a subtext of simmering resentment.'),
  Word('literature', 'pretext', 'n.', 'an ostensible reason masking a character\'s true purpose', 'He visited under the pretext of returning a book.'),
  Word('literature', 'backstory', 'n.', 'the history of a character or situation preceding the main narrative', 'A few flashbacks fill in the hero\'s tragic backstory.'),
  Word('literature', 'flashforward', 'n.', 'a scene that jumps ahead to events later than the present narrative', 'A brief flashforward shows the protagonist as an old man.'),
  Word('literature', 'analepsis', 'n.', 'a narrative device that recounts events from an earlier time', 'The chapter uses analepsis to return to the night of the murder.'),
  Word('literature', 'prolepsis', 'n.', 'the narration of a future event as if it had already occurred', 'Through prolepsis the narrator hints at the disaster to come.'),
  Word('literature', 'framing device', 'n.', 'a story-within-a-story structure that surrounds the main narrative', 'The diary serves as a framing device for the entire tale.'),
  Word('literature', 'vignette sketch', 'n.', 'a brief evocative scene capturing a single moment or mood', 'The book is built from dozens of small vignette sketches of city life.'),
  Word('literature', 'denotation', 'n.', 'the literal dictionary meaning of a word', 'The denotation of \'home\' is simply a dwelling place.'),
  Word('literature', 'connotation', 'n.', 'the emotional or cultural associations a word carries beyond its literal meaning', 'The word \'home\' has warm connotations of safety and belonging.'),
  Word('literature', 'figurative', 'adj.', 'using language in a non-literal, metaphorical sense', 'Her figurative description of the storm gave it a human rage.'),
  Word('literature', 'literal', 'adj.', 'taking words in their basic factual sense without metaphor', 'A literal reading misses the poem\'s deeper symbolism.'),
  Word('literature', 'trope', 'n.', 'a commonly recurring theme, device, or convention', 'The chosen-one trope appears in countless adventure stories.'),
  Word('literature', 'cliché', 'n.', 'an overused expression or idea that has lost its freshness', 'Avoid the cliché of a dark and stormy night opening.'),
  Word('literature', 'idiom', 'n.', 'a fixed phrase whose meaning differs from its literal words', 'The dialogue is peppered with regional idiom.'),
  Word('literature', 'vernacular', 'n.', 'the everyday spoken language of a particular region or group', 'The author renders the rural vernacular with great care.'),
  Word('literature', 'dialect', 'n.', 'a regional or social variety of a language with distinct features', 'Each character speaks in a recognizable dialect.'),
  Word('literature', 'idiolect', 'n.', 'the speech habits peculiar to a single individual', 'The detective\'s clipped idiolect makes him instantly identifiable.'),
  Word('literature', 'cant', 'n.', 'the specialized jargon of a particular group, often a secretive one', 'The thieves communicate in an impenetrable cant.'),
  Word('literature', 'argot', 'n.', 'the slang or coded vocabulary of a closed group', 'The prison scenes are thick with criminal argot.'),
  Word('literature', 'malaprop', 'n.', 'a comic misuse of a word in place of a similar-sounding one', 'His every malaprop sets the audience laughing.'),
  Word('literature', 'neologism', 'n.', 'a newly coined word or expression', 'The science-fiction novel bristles with futuristic neologisms.'),
  Word('literature', 'portmanteau', 'n.', 'a word blending the sounds and meanings of two others', 'Carroll invented the portmanteau \'chortle\' from chuckle and snort.'),
  Word('literature', 'coinage', 'n.', 'a word or phrase newly invented by a writer', 'The term \'cyberspace\' is a famous literary coinage.'),
  Word('literature', 'archaism', 'n.', 'a word or style that is deliberately old-fashioned', 'The poet uses archaism like \'thee\' to evoke a bygone age.'),
  Word('literature', 'anachronistic', 'adj.', 'belonging to a period other than the one depicted', 'A wristwatch in a medieval scene is jarringly anachronistic.'),
  Word('literature', 'paradox', 'n.', 'a statement that seems contradictory yet reveals a truth', 'The poem turns on the paradox that loss can be a kind of gain.'),
  Word('literature', 'epigrammatic', 'adj.', 'expressed in a witty, terse, memorable form', 'Wilde\'s epigrammatic wit fills every page.'),
  Word('literature', 'aphoristic', 'adj.', 'composed of concise statements of general truth', 'The essay\'s aphoristic style packs wisdom into single lines.'),
  Word('literature', 'gnomic', 'adj.', 'expressed in short, cryptic, proverb-like statements', 'The oracle speaks in gnomic riddles.'),
  Word('literature', 'sententious', 'adj.', 'given to pompous moralizing in a terse, preachy way', 'The narrator\'s sententious tone grows tiresome.'),
  Word('literature', 'didactic', 'adj.', 'intended to instruct or convey a moral lesson', 'The fable is openly didactic in its closing line.'),
  Word('literature', 'polemic', 'n.', 'a fierce written attack on or defense of an opinion', 'The pamphlet is a blistering polemic against censorship.'),
  Word('literature', 'apologia', 'n.', 'a formal written defense of one\'s beliefs or conduct', 'The memoir reads as an apologia for his controversial career.'),
  Word('literature', 'manifesto art', 'n.', 'a public declaration of a movement\'s aims and principles', 'The Futurists announced their break with the past in a fiery manifesto art.'),
  Word('literature', 'credo', 'n.', 'a statement of an author\'s guiding beliefs', 'The preface lays out the writer\'s artistic credo.'),
  Word('literature', 'verse drama', 'n.', 'a play written in metrical or rhymed lines', 'Shakespeare\'s histories are masterpieces of verse drama.'),
  Word('literature', 'prose drama', 'n.', 'a play written in ordinary, non-metrical language', 'Ibsen helped popularize realistic prose drama.'),
  Word('literature', 'one-act', 'n.', 'a short play consisting of a single act', 'Her one-act unfolds in real time in a single room.'),
  Word('literature', 'monodrama', 'n.', 'a dramatic piece performed by a single actor', 'The monodrama gives the lone performer the whole stage.'),
  Word('literature', 'pageant', 'n.', 'an elaborate public dramatic spectacle, often historical', 'The town staged a pageant retelling its founding.'),
  Word('literature', 'interlude', 'n.', 'a short dramatic or musical piece between larger sections', 'A comic interlude relieves the tragedy\'s tension.'),
  Word('literature', 'unmasking', 'n.', 'the moment a character\'s true identity or nature is revealed', 'The villain\'s unmasking comes in the final act.'),
  Word('literature', 'catastrophe', 'n.', 'the final disastrous turn of events in a tragedy', 'The catastrophe leaves the stage strewn with the dead.'),
  Word('literature', 'recognition', 'n.', 'the moment a character grasps a crucial truth, shifting the plot', 'Oedipus\'s recognition of his crimes is the play\'s pivot.'),
  Word('literature', 'reversal', 'n.', 'a sudden change in a character\'s fortunes', 'The hero\'s sudden reversal plunges the story into darkness.'),
  Word('literature', 'complication', 'n.', 'the part of a plot in which conflicts build and entangle', 'The complication thickens as new rivals appear.'),
  Word('literature', 'exposition dump', 'n.', 'a clumsy passage delivering background information all at once', 'The opening chapter sags under an exposition dump.'),
  Word('literature', 'foreshadowing', 'n.', 'hints planted early about events to come', 'The broken clock is subtle foreshadowing of the tragedy.'),
  Word('literature', 'flashback', 'n.', 'a scene that interrupts the present to depict the past', 'A flashback reveals how the friendship began.'),
  Word('literature', 'plant and payoff', 'phr.', 'the technique of seeding a detail early that matters later', 'The hidden key is a textbook plant and payoff.'),
  Word('literature', 'callback', 'n.', 'a later reference to an earlier moment in the text', 'The final line is a poignant callback to chapter one.'),
  Word('literature', 'throughline', 'n.', 'the central thread connecting a story\'s events', 'Grief is the emotional throughline of the whole novel.'),
  Word('literature', 'arc of change', 'phr.', 'the trajectory of a character\'s inner transformation', 'Her arc of change carries her from fear to courage.'),
  Word('literature', 'static', 'adj.', 'describing a character who does not change over the story', 'The butler remains a static figure throughout.'),
  Word('literature', 'rounded', 'adj.', 'describing a fully developed, complex character', 'Even minor figures feel rounded and alive.'),
  Word('literature', 'stock character', 'n.', 'a conventional, easily recognized character type', 'The miser is a stock character of comedy.'),
  Word('literature', 'caricature', 'n.', 'an exaggerated portrayal emphasizing a few traits for effect', 'The pompous lord is drawn as broad caricature.'),
  Word('literature', 'composite character', 'n.', 'a single figure created by merging several real people', 'The memoirist used a composite character to protect identities.'),
  Word('literature', 'everyman', 'n.', 'an ordinary character meant to represent humanity at large', 'The clerk functions as an everyman caught in vast events.'),
  Word('literature', 'ingenue', 'n.', 'a naive, innocent young female character', 'The plot turns on the ingenue\'s loss of innocence.'),
  Word('literature', 'raisonneur', 'n.', 'a character who voices the author\'s own viewpoint', 'The old doctor serves as the play\'s raisonneur.'),
  Word('literature', 'choral character', 'n.', 'a figure who comments on the action like a Greek chorus', 'The gossiping neighbor acts as a choral character.'),
  Word('literature', 'doubling', 'n.', 'the pairing of characters who mirror one another', 'The doubling of twins underscores the theme of fate.'),
  Word('literature', 'shadow self', 'n.', 'a character embodying the repressed darker side of another', 'The villain is the hero\'s shadow self made flesh.'),
  Word('literature', 'characterology', 'n.', 'the study or systematic creation of fictional characters', 'The seminar focused on the characterology of the realist novel.'),
  Word('literature', 'omniscience', 'n.', 'the all-knowing perspective of a narrator with total access', 'The narrator\'s omniscience reveals every character\'s thoughts.'),
  Word('literature', 'focalizer', 'n.', 'the character through whose perspective events are presented', 'The child becomes the focalizer for the war\'s horrors.'),
  Word('literature', 'narratee', 'n.', 'the implied listener to whom a narrator addresses the story', 'The confessional tone implies an intimate narratee.'),
  Word('literature', 'narratology', 'n.', 'the theoretical study of narrative structure', 'Her thesis applies narratology to graphic novels.'),
  Word('literature', 'diegetic', 'adj.', 'belonging to the world of the story itself', 'The song is diegetic because the characters can hear it.'),
  Word('literature', 'extradiegetic', 'adj.', 'existing outside the narrated story world', 'The narrator\'s asides are extradiegetic comments to the reader.'),
  Word('literature', 'metadiegetic', 'adj.', 'belonging to a story told within the main story', 'The traveler\'s tale forms a metadiegetic layer.'),
  Word('literature', 'unreliability', 'n.', 'the quality of a narrator whose account cannot be trusted', 'The novel\'s power lies in the narrator\'s growing unreliability.'),
  Word('literature', 'free direct discourse', 'phr.', 'a character\'s unmarked thoughts presented without tags', 'Free direct discourse drops us straight into his panic.'),
  Word('literature', 'reported speech', 'n.', 'the indirect relaying of what a character said', 'Most dialogue here is filtered through reported speech.'),
  Word('literature', 'narrative voice', 'n.', 'the distinctive personality and style of the storyteller', 'The wry narrative voice carries the otherwise grim plot.'),
  Word('literature', 'tense shift', 'n.', 'a deliberate change of verb tense for narrative effect', 'A sudden tense shift to the present makes the scene vivid.'),
  Word('literature', 'in situ', 'phr.', 'describing narration set within the immediate scene', 'The crisis is rendered in situ rather than recalled.'),
  Word('literature', 'scansion', 'n.', 'the analysis of a line\'s metrical pattern', 'Careful scansion reveals the poem\'s shifting rhythm.'),
  Word('literature', 'prosody', 'n.', 'the study of versification, meter, and rhythm', 'A grasp of prosody helps one hear a poem\'s music.'),
  Word('literature', 'syllabic verse', 'n.', 'poetry organized by counting syllables per line', 'Haiku is a form of syllabic verse.'),
  Word('literature', 'accentual verse', 'n.', 'poetry measured by the number of stressed syllables', 'Old English poetry uses accentual verse.'),
  Word('literature', 'quantitative verse', 'n.', 'poetry based on the length of syllables rather than stress', 'Classical Latin poets wrote in quantitative verse.'),
  Word('literature', 'metrical foot', 'n.', 'a basic repeating unit of stressed and unstressed syllables', 'The iamb is the most common metrical foot in English.'),
  Word('literature', 'pyrrhic', 'n.', 'a metrical foot of two unstressed syllables', 'A pyrrhic lightens the rhythm of the line.'),
  Word('literature', 'amphibrach', 'n.', 'a metrical foot of an unstressed, stressed, unstressed syllable', 'Limericks often lilt with the amphibrach.'),
  Word('literature', 'anacrusis', 'n.', 'an extra unstressed syllable at the start of a line', 'The anacrusis gives the verse a running start.'),
  Word('literature', 'catalexis', 'n.', 'the omission of a syllable from the end of a metrical line', 'Catalexis clips the final foot for emphasis.'),
  Word('literature', 'feminine ending', 'n.', 'a line ending on an unstressed syllable', 'The feminine ending softens the closing of each verse.'),
  Word('literature', 'masculine rhyme', 'n.', 'a rhyme on a single final stressed syllable', 'The couplet closes with a crisp masculine rhyme.'),
  Word('literature', 'feminine rhyme', 'n.', 'a rhyme on two syllables, the last unstressed', 'Comic verse delights in feminine rhyme.'),
  Word('literature', 'slant rhyme', 'n.', 'an approximate rhyme using similar but not identical sounds', 'Dickinson favored the unsettling effect of slant rhyme.'),
  Word('literature', 'eye rhyme', 'n.', 'words that look alike but do not sound alike', 'Love and move form an eye rhyme.'),
  Word('literature', 'internal rhyme', 'n.', 'rhyme occurring within a single line of verse', 'The ballad sparkles with internal rhyme.'),
  Word('literature', 'end rhyme', 'n.', 'rhyme that falls at the ends of lines', 'The sonnet relies on a strict pattern of end rhyme.'),
  Word('literature', 'half rhyme', 'n.', 'a partial rhyme matching consonants but not vowels', 'The half rhyme leaves the ear faintly unsettled.'),
  Word('literature', 'rhyme scheme', 'n.', 'the ordered pattern of rhymes in a poem', 'The stanza follows an ABAB rhyme scheme.'),
  Word('literature', 'refrain', 'n.', 'a repeated line or group of lines in a poem or song', 'The mournful refrain returns at each stanza\'s close.'),
  Word('literature', 'burden', 'n.', 'a recurring refrain or chorus in a song or poem', 'Each verse ends with the same haunting burden.'),
  Word('literature', 'strophe', 'n.', 'the first section of a choral ode or a stanza of irregular form', 'The strophe is answered by the antistrophe.'),
  Word('literature', 'antistrophe', 'n.', 'the second section answering the strophe in a Greek ode', 'In the antistrophe the chorus moves back across the stage.'),
  Word('literature', 'epode', 'n.', 'the concluding part of a classical ode after strophe and antistrophe', 'The epode resolves the ode\'s argument.'),
  Word('literature', 'pindaric', 'adj.', 'relating to a grand, irregular ode in the manner of Pindar', 'The poet attempted a soaring pindaric ode.'),
  Word('literature', 'monostich', 'n.', 'a poem or stanza consisting of a single line', 'The whole poem is a startling monostich.'),
  Word('literature', 'distich', 'n.', 'a pair of verse lines, especially a self-contained couplet', 'Each proverb is cast as a neat distich.'),
  Word('literature', 'tristich', 'n.', 'a group of three verse lines', 'The poem is built from linked tristich units.'),
  Word('literature', 'cinquain', 'n.', 'a five-line stanza or poem, often with a fixed syllable pattern', 'She composed a delicate cinquain about autumn.'),
  Word('literature', 'sextain', 'n.', 'a six-line stanza', 'Each section is a tightly rhymed sextain.'),
  Word('literature', 'tanka', 'n.', 'a Japanese verse form of five lines in a 5-7-5-7-7 pattern', 'The tanka extends the haiku with two further lines.'),
  Word('literature', 'renga', 'n.', 'a collaborative Japanese linked-verse form', 'Several poets composed the renga in turn.'),
  Word('literature', 'rubai', 'n.', 'a Persian quatrain with a characteristic rhyme scheme', 'Each rubai distills a whole philosophy into four lines.'),
  Word('literature', 'qasida', 'n.', 'a long, monorhymed ode in classical Arabic and Persian poetry', 'The court poet recited a qasida praising the king.'),
  Word('literature', 'kyrielle', 'n.', 'a French verse form with a recurring refrain line', 'The kyrielle\'s refrain tolls like a bell.'),
  Word('literature', 'roundelay', 'n.', 'a short poem with a recurring refrain', 'The shepherds sang a simple roundelay.'),
  Word('literature', 'madrigal', 'n.', 'a short lyric poem, often pastoral, suitable for setting to music', 'The madrigal celebrates a spring meadow.'),
  Word('literature', 'carol', 'n.', 'a joyful song or poem, traditionally with a burden', 'The medieval carol praises the turning seasons.'),
  Word('literature', 'roundel', 'n.', 'an English variation of the rondeau with refrains', 'Swinburne perfected the delicate roundel.'),
  Word('literature', 'clerihew', 'n.', 'a comic four-line biographical verse with irregular meter', 'He dashed off a clerihew about a famous chemist.'),
  Word('literature', 'doggerel', 'n.', 'crude, irregular verse, often comic or trivial', 'The greeting card was filled with cheerful doggerel.'),
  Word('literature', 'nonsense verse', 'n.', 'playful poetry featuring absurd or invented language', 'Lear\'s nonsense verse delights children and adults alike.'),
  Word('literature', 'macaronic', 'adj.', 'mixing words from two or more languages, often for comic effect', 'The macaronic poem weaves Latin into English lines.'),
  Word('literature', 'shaped poem', 'n.', 'a poem whose layout forms a visual image of its subject', 'Herbert\'s shaped poem takes the form of an altar.'),
  Word('literature', 'caudate sonnet', 'n.', 'a sonnet with additional lines, or tail, appended', 'Milton experimented with the caudate sonnet.'),
  Word('literature', 'crown of sonnets', 'phr.', 'a sequence of sonnets linked by repeated lines', 'The crown of sonnets binds seven poems into one.'),
  Word('literature', 'sonnet sequence', 'n.', 'a connected series of sonnets exploring a single theme', 'The sonnet sequence traces a doomed love affair.'),
  Word('literature', 'petrarchan', 'adj.', 'relating to the Italian sonnet form divided into octave and sestet', 'The petrarchan sonnet poses a problem then resolves it.'),
  Word('literature', 'shakespearean', 'adj.', 'relating to the English sonnet of three quatrains and a couplet', 'The shakespearean sonnet ends with an epigrammatic couplet.'),
  Word('literature', 'volta', 'n.', 'the turn of thought or feeling in a sonnet', 'The volta arrives at the ninth line with a change of heart.'),
  Word('literature', 'lyricism', 'n.', 'an expressive, songlike quality in writing', 'The prose is celebrated for its quiet lyricism.'),
  Word('literature', 'sublimity', 'n.', 'a quality of grandeur that inspires awe in literature', 'The mountain passages reach genuine sublimity.'),
  Word('literature', 'picturesque', 'adj.', 'visually charming in a way reminiscent of a painting', 'The novel lingers over picturesque country scenes.'),
  Word('literature', 'grotesque', 'n.', 'a style mingling the comic and the horrifying or distorted', 'The carnival scene is pure grotesque.'),
  Word('literature', 'macabre', 'adj.', 'disturbingly concerned with death and decay', 'The story\'s macabre humor unsettles the reader.'),
  Word('literature', 'gothic mode', 'n.', 'a style of fiction featuring gloom, dread, and the supernatural', 'The ruined abbey signals the gothic mode at once.'),
  Word('literature', 'sensibility', 'n.', 'a refined emotional responsiveness valued in eighteenth-century writing', 'The heroine\'s acute sensibility drives the plot.'),
  Word('literature', 'pathos appeal', 'phr.', 'a passage designed to evoke pity or sorrow', 'The deathbed scene is a deliberate pathos appeal.'),
  Word('literature', 'bathetic', 'adj.', 'sinking absurdly from the lofty to the trivial', 'The grand speech ends on a bathetic note.'),
  Word('literature', 'mawkish', 'adj.', 'excessively and falsely sentimental', 'The reunion scene grows mawkish and overwrought.'),
  Word('literature', 'maudlin', 'adj.', 'tearfully or weakly emotional', 'The ballad is maudlin but oddly affecting.'),
  Word('literature', 'lugubrious', 'adj.', 'mournful, dismal, often exaggeratedly so', 'The narrator\'s lugubrious tone suits the funeral setting.'),
  Word('literature', 'somber', 'adj.', 'dark, grave, and serious in mood', 'A somber atmosphere pervades the prison chapters.'),
  Word('literature', 'ominous', 'adj.', 'suggesting that something bad is about to happen', 'The ominous opening line warns of disaster.'),
  Word('literature', 'foreboding', 'n.', 'a feeling of impending evil or misfortune in a text', 'A sense of foreboding hangs over the wedding feast.'),
  Word('literature', 'wistful', 'adj.', 'tinged with gentle longing or melancholy', 'The poem casts a wistful glance at lost youth.'),
  Word('literature', 'elegiac', 'adj.', 'expressing sorrow, especially for something lost', 'The novel closes on an elegiac note for a vanished world.'),
  Word('literature', 'plaintive', 'adj.', 'sounding sad and mournful', 'The shepherd\'s plaintive song echoes the poem\'s grief.'),
  Word('literature', 'jocular', 'adj.', 'fond of joking; humorous in tone', 'The jocular narrator keeps the satire light.'),
  Word('literature', 'wry', 'adj.', 'dryly and cleverly humorous, often with irony', 'Her wry asides puncture every pretension.'),
  Word('literature', 'droll', 'adj.', 'amusing in an odd or whimsical way', 'The novel is full of droll provincial characters.'),
  Word('literature', 'whimsical', 'adj.', 'playfully fanciful or quaint', 'The whimsical fairy tale charms with its odd logic.'),
  Word('literature', 'facetious', 'adj.', 'treating serious matters with inappropriate humor', 'His facetious footnotes mock the solemn subject.'),
  Word('literature', 'tongue-in-cheek', 'adj.', 'intended humorously and not to be taken seriously', 'The mock-heroic tone is entirely tongue-in-cheek.'),
  Word('literature', 'deadpan', 'adj.', 'delivered with a flat, expressionless manner for comic effect', 'The narrator\'s deadpan style heightens the absurdity.'),
  Word('literature', 'caustic', 'adj.', 'bitingly sarcastic or critical', 'The reviewer\'s caustic wit spares no one.'),
  Word('literature', 'acerbic', 'adj.', 'sharp and biting in tone', 'The essay\'s acerbic style made many enemies.'),
  Word('literature', 'mordant', 'adj.', 'cruelly or sharply critical in a witty way', 'Her mordant humor exposes society\'s hypocrisies.'),
  Word('literature', 'trenchant', 'adj.', 'vigorous, incisive, and effective in expression', 'The critic offered a trenchant analysis of the novel.'),
  Word('literature', 'incisive', 'adj.', 'sharply and clearly analytical', 'The biography is praised for its incisive portrait.'),
  Word('literature', 'lapidary', 'adj.', 'elegant, precise, and polished, as if carved in stone', 'The poet\'s lapidary style wastes not a syllable.'),
  Word('literature', 'ornate', 'adj.', 'elaborately and heavily decorated in style', 'The ornate prose drips with adjectives.'),
  Word('literature', 'florid', 'adj.', 'excessively flowery or elaborate in style', 'The florid descriptions slow the narrative.'),
  Word('literature', 'baroque', 'adj.', 'extravagantly ornate and complex in style', 'The baroque sentences coil through whole pages.'),
  Word('literature', 'euphuism', 'n.', 'an artificial, highly elaborate prose style of balanced phrases', 'Lyly\'s euphuism set a fashion at the Elizabethan court.'),
  Word('literature', 'gongorism', 'n.', 'an ornate, learned Spanish poetic style full of allusion', 'The sonnet shows the dense gongorism of its age.'),
  Word('literature', 'preciosity', 'n.', 'affected refinement or over-elegance in writing', 'The salon poetry collapsed into mere preciosity.'),
  Word('literature', 'terseness', 'n.', 'brevity and economy of expression', 'Hemingway\'s terseness leaves much unsaid.'),
  Word('literature', 'laconic', 'adj.', 'using very few words; concise to the point of bluntness', 'The hero\'s laconic replies hint at hidden depths.'),
  Word('literature', 'spare', 'adj.', 'stripped of ornament; plain and economical', 'The spare style mirrors the bleak landscape.'),
  Word('literature', 'minimalist', 'adj.', 'using the fewest and simplest elements for effect', 'Carver\'s minimalist stories leave wide silences.'),
  Word('literature', 'maximalist', 'adj.', 'embracing abundance, excess, and dense detail', 'The maximalist novel crams in dozens of subplots.'),
  Word('literature', 'discursive', 'adj.', 'digressive; ranging widely from the main subject', 'The discursive essay wanders charmingly from topic to topic.'),
  Word('literature', 'digression', 'n.', 'a temporary departure from the main subject', 'A long digression on whaling interrupts the chase.'),
  Word('literature', 'excursus', 'n.', 'a detailed discussion appended to or inserted in a work', 'The excursus on geology fills an entire chapter.'),
  Word('literature', 'aside remark', 'n.', 'a brief comment directed past the main line of thought', 'The narrator drops an aside remark to the reader.'),
  Word('literature', 'parenthesis', 'n.', 'an inserted phrase set apart from the main statement', 'A witty parenthesis undercuts the solemn claim.'),
  Word('literature', 'antiphrasis', 'n.', 'the use of a word to mean its opposite, often ironically', 'Calling the storm a gentle breeze is antiphrasis.'),
  Word('literature', 'hyperbaton', 'n.', 'the inversion of the normal order of words for effect', 'The poet uses hyperbaton to delay the key noun.'),
  Word('literature', 'anastrophe', 'n.', 'the reversal of the usual order of words', 'Yoda\'s speech is built on playful anastrophe.'),
  Word('literature', 'epizeuxis', 'n.', 'the immediate repetition of a word for emphasis', 'Lear\'s cry of \'never, never, never\' is epizeuxis.'),
  Word('literature', 'symploce', 'n.', 'the combined repetition of words at the start and end of clauses', 'The speech\'s symploce hammers home its plea.'),
  Word('literature', 'anaphoric', 'adj.', 'involving repetition at the beginnings of successive clauses', 'The anaphoric \'I have a dream\' lifts the whole oration.'),
  Word('literature', 'epanorthosis', 'n.', 'the immediate correction of a word just used, for emphasis', 'Through epanorthosis he says \'a thousand, no, a million times.\''),
  Word('literature', 'aposiopesis', 'n.', 'a sudden breaking off of speech as if unable to continue', 'The threat ends in aposiopesis: \'Why, I will—.\''),
  Word('literature', 'occupatio', 'n.', 'mentioning something by claiming one will not mention it', 'By occupatio he lists the crimes he says he\'ll ignore.'),
  Word('literature', 'adynaton', 'n.', 'hyperbole expressing impossibility', 'When pigs fly is a familiar adynaton.'),
  Word('literature', 'hypallage', 'n.', 'the transfer of an attribute from its proper noun to another', 'The phrase \'sleepless night\' is a small hypallage.'),
  Word('literature', 'enallage', 'n.', 'the deliberate substitution of one grammatical form for another', 'The poem\'s enallage swaps singular for plural for effect.'),
  Word('literature', 'catachresis', 'n.', 'the strained or mixed use of a word in an unusual way', 'The bold catachresis speaks of a blind mouth.'),
  Word('literature', 'synesthesia', 'n.', 'describing one sense in terms of another', 'The synesthesia of a loud color startles the reader.'),
  Word('literature', 'transferred epithet', 'phr.', 'an adjective shifted from the noun it logically modifies', 'A weary road is a transferred epithet for a weary traveler.'),
  Word('literature', 'periphrastic', 'adj.', 'expressed in a roundabout or wordy way', 'The periphrastic style avoids naming death directly.'),
  Word('literature', 'paralipsis', 'n.', 'drawing attention to something by professing to omit it', 'By paralipsis he says he won\'t mention his rival\'s lies.'),
  Word('literature', 'antiphon', 'n.', 'a verse sung or recited in response to another', 'The poem alternates voices like an antiphon.'),
];
