import 'words_data.dart';

const kLoveExtras2 = <Word>[
  Word('love', 'ardor', 'n.', 'intense feelings of love or passion', 'His ardor for her grew with every letter they exchanged.'),
  Word('love', 'ardent', 'adj.', 'characterized by intense feeling or passion', 'She was an ardent admirer who never missed his performances.'),
  Word('love', 'affection', 'n.', 'a gentle feeling of fondness or liking', 'She showed her affection with small thoughtful gestures.'),
  Word('love', 'affectionate', 'adj.', 'showing or feeling fondness or tenderness', 'He gave her an affectionate squeeze of the hand.'),
  Word('love', 'fondness', 'n.', 'tender affection or liking for someone', 'A deep fondness for each other grew over the years.'),
  Word('love', 'endearment', 'n.', 'a word or phrase expressing love', '"Darling" was the endearment he used most often.'),
  Word('love', 'endearing', 'adj.', 'inspiring love or affection', 'Her clumsy laugh was one of her most endearing traits.'),
  Word('love', 'intimacy', 'n.', 'close familiarity or emotional closeness', 'The intimacy between them deepened over many quiet evenings.'),
  Word('love', 'intimate', 'adj.', 'closely connected in a personal or private way', 'They shared an intimate dinner by candlelight.'),
  Word('love', 'passion', 'n.', 'strong and barely controllable emotion or desire', 'Their passion for one another never seemed to fade.'),
  Word('love', 'passionate', 'adj.', 'showing or caused by strong feelings of love', 'He wrote her a passionate declaration of his love.'),
  Word('love', 'desire', 'n.', 'a strong feeling of wanting someone', 'A quiet desire stirred whenever she entered the room.'),
  Word('love', 'attraction', 'n.', 'the quality of arousing interest or romantic interest', 'There was an undeniable attraction between the two of them.'),
  Word('love', 'attract', 'v.', 'to draw someone toward oneself by appeal', 'Her warmth seemed to attract everyone she met.'),
  Word('love', 'alluring', 'adj.', 'powerfully and mysteriously attractive', 'She gave him an alluring smile across the crowded room.'),
  Word('love', 'fancy', 'v.', 'to feel romantic attraction toward someone', 'He had fancied her since their first day at college.'),
  Word('love', 'admire', 'v.', 'to regard with respect, warmth, or approval', 'He admired her from afar for months before speaking.'),
  Word('love', 'admirer', 'n.', 'a person who is romantically attracted to another', 'A secret admirer left flowers on her doorstep.'),
  Word('love', 'suitor', 'n.', 'a man who pursues a woman romantically', 'She had many suitors but favored none of them.'),
  Word('love', 'wooing', 'n.', 'the act of trying to win someone\'s love', 'His patient wooing finally won her heart.'),
  Word('love', 'courtship', 'n.', 'the period of developing a romantic relationship', 'Their courtship lasted two years before they married.'),
  Word('love', 'romance', 'n.', 'a love affair or feeling of excitement in love', 'A whirlwind romance swept the two of them away.'),
  Word('love', 'dalliance', 'n.', 'a casual romantic or sexual relationship', 'It was a brief dalliance she soon came to regret.'),
  Word('love', 'dote', 'v.', 'to show excessive fondness for someone', 'He would dote on her endlessly, fulfilling every wish.'),
  Word('love', 'cuddle', 'v.', 'to hold close in one\'s arms affectionately', 'They liked to cuddle on the sofa during the rain.'),
  Word('love', 'embrace', 'n.', 'an act of holding someone closely in one\'s arms', 'She melted into his warm embrace at the airport.'),
  Word('love', 'caress', 'v.', 'to touch or stroke gently and lovingly', 'He gently caressed her cheek as she fell asleep.'),
  Word('love', 'nuzzle', 'v.', 'to rub or push against gently with affection', 'She liked to nuzzle against his shoulder while reading.'),
  Word('love', 'snuggle', 'v.', 'to settle into a warm, comfortable position close to someone', 'They would snuggle under the blanket on cold nights.'),
  Word('love', 'companionship', 'n.', 'the comfort of having someone to share life with', 'After years alone, she craved gentle companionship.'),
  Word('love', 'companion', 'n.', 'a person one spends time with or shares life with', 'He became her constant companion through every season.'),
  Word('love', 'partner', 'n.', 'a person with whom one shares a romantic relationship', 'She introduced him as her partner of five years.'),
  Word('love', 'belonging', 'n.', 'a feeling of being accepted as part of something', 'With him she finally felt a deep sense of belonging.'),
  Word('love', 'commitment', 'n.', 'dedication to a long-term relationship', 'Their marriage was built on mutual love and commitment.'),
  Word('love', 'committed', 'adj.', 'dedicated to a cause or relationship', 'They were fully committed to one another for life.'),
  Word('love', 'faithful', 'adj.', 'loyal and true to a partner', 'He remained faithful to her through every hardship.'),
  Word('love', 'loyalty', 'n.', 'a strong feeling of allegiance and devotion', 'Her loyalty to him never wavered, even in doubt.'),
  Word('love', 'devoted', 'adj.', 'very loving or loyal to someone', 'He was a devoted husband who adored his wife.'),
  Word('love', 'steadfast', 'adj.', 'firmly loyal and unwavering in love', 'Her steadfast love carried them through the dark years.'),
  Word('love', 'cherished', 'adj.', 'protected and cared for lovingly', 'She kept his letters as cherished mementos.'),
  Word('love', 'treasure', 'v.', 'to value and care for deeply', 'He would treasure every moment they spent together.'),
  Word('love', 'adoration', 'n.', 'deep love and respect', 'The way he looked at her was pure adoration.'),
  Word('love', 'adoring', 'adj.', 'showing deep love and admiration', 'She gave him an adoring glance across the table.'),
  Word('love', 'idolize', 'v.', 'to admire or love to excess', 'He seemed to idolize her, hanging on her every word.'),
  Word('love', 'enamor', 'v.', 'to fill with intense love or fascination', 'Her wit and grace soon enamored everyone around her.'),
  Word('love', 'infatuation', 'n.', 'an intense but short-lived passion for someone', 'His infatuation faded once he truly got to know her.'),
  Word('love', 'fascination', 'n.', 'an irresistible attraction or interest', 'She held a quiet fascination for the mysterious stranger.'),
  Word('love', 'captivation', 'n.', 'the state of being charmed or held by fascination', 'His captivation with her grew stronger each day.'),
  Word('love', 'bewitch', 'v.', 'to enchant and delight someone completely', 'Her dark eyes seemed to bewitch every man she met.'),
  Word('love', 'spellbound', 'adj.', 'held as if by a spell, entranced', 'He stood spellbound the moment she walked in.'),
  Word('love', 'mesmerize', 'v.', 'to hold the attention as if by a spell', 'Her singing voice mesmerized the entire room.'),
  Word('love', 'dazzle', 'v.', 'to impress deeply with brilliance or charm', 'He set out to dazzle her with poetry and roses.'),
  Word('love', 'charming', 'adj.', 'pleasant and attractive in a winning way', 'He was charming, and she found him hard to resist.'),
  Word('love', 'flirtation', 'n.', 'playful romantic behavior with someone', 'Their flirtation at the party turned into a first date.'),
  Word('love', 'flirtatious', 'adj.', 'behaving in a playfully romantic way', 'She shot him a flirtatious wink from across the bar.'),
  Word('love', 'coy', 'adj.', 'making a show of shy or modest reluctance to attract', 'She gave a coy smile when he asked for her number.'),
  Word('love', 'bashful', 'adj.', 'shy or easily embarrassed, especially in romance', 'He grew bashful whenever she complimented him.'),
  Word('love', 'demure', 'adj.', 'reserved, modest, and shy in a charming way', 'She lowered her eyes with a demure little laugh.'),
  Word('love', 'wink', 'v.', 'to close and open one eye as a flirtatious gesture', 'He gave her a playful wink as she passed by.'),
  Word('love', 'blush', 'v.', 'to redden in the face from emotion or shyness', 'She began to blush the moment he held her hand.'),
  Word('love', 'twinkle', 'n.', 'a sparkle in the eye suggesting affection', 'There was a tender twinkle in his eye as he proposed.'),
  Word('love', 'butterflies', 'n.', 'a fluttery feeling of nervous excitement in love', 'She got butterflies every time he texted her.'),
  Word('love', 'giddy', 'adj.', 'excited and lightheaded with happiness', 'The new couple felt giddy with newfound love.'),
  Word('love', 'lovesick', 'adj.', 'so in love that one is unable to act normally', 'He moped around the house, hopelessly lovesick.'),
  Word('love', 'heartfelt', 'adj.', 'deeply and sincerely felt', 'She wrote him a heartfelt note before he left.'),
  Word('love', 'devote', 'v.', 'to give all of one\'s attention or love to someone', 'He chose to devote his life to making her happy.'),
  Word('love', 'cherishing', 'n.', 'the act of holding dear with great affection', 'Their love was built on a daily cherishing of one another.'),
  Word('love', 'reciprocate', 'v.', 'to respond to a gesture or feeling in kind', 'She was overjoyed when he reciprocated her affection.'),
  Word('love', 'requite', 'v.', 'to return love or affection', 'At last he learned that she requited his love.'),
  Word('love', 'mutual', 'adj.', 'felt or shared equally by two people', 'Their attraction was instant and entirely mutual.'),
  Word('love', 'tenderness', 'n.', 'gentleness and kindness in love', 'He treated her with a tenderness she had never known.'),
  Word('love', 'gentleness', 'n.', 'the quality of being kind and tender', 'His gentleness toward her revealed how much he cared.'),
  Word('love', 'warmth', 'n.', 'kindness and affection in feeling', 'There was a comforting warmth in the way she spoke to him.'),
  Word('love', 'comfort', 'n.', 'a state of ease found in a loving presence', 'She found great comfort in his steady, loving arms.'),
  Word('love', 'soothe', 'v.', 'to gently calm or comfort someone', 'He would soothe her worries with a soft embrace.'),
  Word('love', 'cuddly', 'adj.', 'pleasant to hold close and embrace', 'He was warm and cuddly, perfect for cold evenings.'),
  Word('love', 'sweetness', 'n.', 'the quality of being kind and loving', 'The sweetness of his words made her heart flutter.'),
  Word('love', 'whisper', 'v.', 'to speak softly and intimately', 'He leaned in to whisper that he loved her.'),
  Word('love', 'flutter', 'v.', 'to feel a rapid stir of excitement in love', 'Her heart began to flutter the moment he arrived.'),
  Word('love', 'pang', 'n.', 'a sudden sharp feeling of longing or love', 'A pang of longing struck her when he said goodbye.'),
  Word('love', 'ache', 'n.', 'a dull, persistent emotional pain from love', 'The ache of missing him grew with every passing day.'),
  Word('love', 'heartstrings', 'n.', 'one\'s deepest feelings of love or sympathy', 'The old love song tugged at her heartstrings.'),
  Word('love', 'sweetnothings', 'phr.', 'tender words of affection murmured to a lover', 'He whispered sweet nothings into her ear all night.'),
  Word('love', 'amorousness', 'n.', 'the state of being full of romantic feeling', 'There was an amorousness in the air that summer evening.'),
  Word('love', 'romanticize', 'v.', 'to make something seem more loving or ideal', 'She tended to romanticize their early days together.'),
  Word('love', 'sentimentality', 'n.', 'tender emotion, sometimes excessive', 'Their anniversary was filled with happy sentimentality.'),
  Word('love', 'nostalgia', 'n.', 'a wistful affection for the past, often of a romance', 'A wave of nostalgia hit her when she found his old letters.'),
  Word('love', 'keepsake', 'n.', 'a small item kept in memory of a loved one', 'She wore his ring as a keepsake long after he left.'),
  Word('love', 'memento', 'n.', 'an object kept as a reminder of someone loved', 'He kept the ticket stub as a memento of their first date.'),
  Word('love', 'token', 'n.', 'a small thing given as a sign of love', 'He gave her a locket as a token of his devotion.'),
  Word('love', 'canoodle', 'v.', 'to kiss and cuddle amorously', 'The young couple would canoodle on the park bench for hours.'),
  Word('love', 'entwine', 'v.', 'to twist together, as lives or hands in love', 'Their fingers would entwine as they walked along the shore.'),
  Word('love', 'intertwine', 'v.', 'to closely connect two lives or people', 'Marriage would forever intertwine their two families.'),
  Word('love', 'inseparable', 'adj.', 'unable to be parted, as devoted lovers', 'The couple was inseparable from the day they met.'),
  Word('love', 'union', 'n.', 'the joining together of two people in love', 'Their union was blessed by both of their families.'),
  Word('love', 'engaged', 'adj.', 'having formally agreed to marry', 'They got engaged after a romantic trip to Paris.'),
  Word('love', 'engagement', 'n.', 'a formal agreement to get married', 'Their engagement was announced at the family dinner.'),
  Word('love', 'vow', 'n.', 'a solemn promise, often of love or marriage', 'They exchanged heartfelt vows beneath the old oak tree.'),
  Word('love', 'cohabit', 'v.', 'to live together in a romantic relationship', 'They decided to cohabit before getting married.'),
  Word('love', 'winsome', 'adj.', 'attractive or appealing in a charming way', 'Her winsome charm made him fall a little harder each day.'),
];
