import 'words_data.dart';

const kLoveExtras2 = <Word>[
  Word('love', 'ardor', 'n.', 'intense feelings of love or passion', 'His ardor for her grew with every letter they exchanged.'),
  Word('love', 'ardent', 'adj.', 'characterized by intense feeling or passion', 'She was an ardent admirer who never missed his performances.'),
  Word('love', 'endearment', 'n.', 'a word or phrase expressing love', '"Darling" was the endearment he used most often.'),
  Word('love', 'endearing', 'adj.', 'inspiring love or affection', 'Her clumsy laugh was one of her most endearing traits.'),
  Word('love', 'alluring', 'adj.', 'powerfully and mysteriously attractive', 'She gave him an alluring smile across the crowded room.'),
  Word('love', 'suitor', 'n.', 'a man who pursues a woman romantically', 'She had many suitors but favored none of them.'),
  Word('love', 'wooing', 'n.', 'the act of trying to win someone\'s love', 'His patient wooing finally won her heart.'),
  Word('love', 'courtship', 'n.', 'the period of developing a romantic relationship', 'Their courtship lasted two years before they married.'),
  Word('love', 'dalliance', 'n.', 'a casual romantic or sexual relationship', 'It was a brief dalliance she soon came to regret.'),
  Word('love', 'dote', 'v.', 'to show excessive fondness for someone', 'He would dote on her endlessly, fulfilling every wish.'),
  Word('love', 'caress', 'v.', 'to touch or stroke gently and lovingly', 'He gently caressed her cheek as she fell asleep.'),
  Word('love', 'nuzzle', 'v.', 'to rub or push against gently with affection', 'She liked to nuzzle against his shoulder while reading.'),
  Word('love', 'snuggle', 'v.', 'to settle into a warm, comfortable position close to someone', 'They would snuggle under the blanket on cold nights.'),
  Word('love', 'steadfast', 'adj.', 'firmly loyal and unwavering in love', 'Her steadfast love carried them through the dark years.'),
  Word('love', 'cherished', 'adj.', 'protected and cared for lovingly', 'She kept his letters as cherished mementos.'),
  Word('love', 'adoration', 'n.', 'deep love and respect', 'The way he looked at her was pure adoration.'),
  Word('love', 'adoring', 'adj.', 'showing deep love and admiration', 'She gave him an adoring glance across the table.'),
  Word('love', 'idolize', 'v.', 'to admire or love to excess', 'He seemed to idolize her, hanging on her every word.'),
  Word('love', 'enamor', 'v.', 'to fill with intense love or fascination', 'Her wit and grace soon enamored everyone around her.'),
  Word('love', 'infatuation', 'n.', 'an intense but short-lived passion for someone', 'His infatuation faded once he truly got to know her.'),
  Word('love', 'fascination', 'n.', 'an irresistible attraction or interest', 'She held a quiet fascination for the mysterious stranger.'),
  Word('love', 'captivation', 'n.', 'the state of being charmed or held by fascination', 'His captivation with her grew stronger each day.'),
  Word('love', 'bewitch', 'v.', 'to enchant and delight someone completely', 'Her dark eyes seemed to bewitch every man she met.'),
  Word('love', 'spellbound', 'adj.', 'held as if by a spell, entranced', 'He stood spellbound the moment she walked in.'),
  Word('love', 'mesmerize', 'v.', 'to hold the attention as if by a spell', 'Her singing voice mesmerized the entire room.'),
  Word('love', 'dazzle', 'v.', 'to impress deeply with brilliance or charm', 'He set out to dazzle her with poetry and roses.'),
  Word('love', 'flirtation', 'n.', 'playful romantic behavior with someone', 'Their flirtation at the party turned into a first date.'),
  Word('love', 'flirtatious', 'adj.', 'behaving in a playfully romantic way', 'She shot him a flirtatious wink from across the bar.'),
  Word('love', 'coy', 'adj.', 'making a show of shy or modest reluctance to attract', 'She gave a coy smile when he asked for her number.'),
  Word('love', 'bashful', 'adj.', 'shy or easily embarrassed, especially in romance', 'He grew bashful whenever she complimented him.'),
  Word('love', 'demure', 'adj.', 'reserved, modest, and shy in a charming way', 'She lowered her eyes with a demure little laugh.'),
  Word('love', 'butterflies', 'n.', 'a fluttery feeling of nervous excitement in love', 'She got butterflies every time he texted her.'),
  Word('love', 'lovesick', 'adj.', 'so in love that one is unable to act normally', 'He moped around the house, hopelessly lovesick.'),
  Word('love', 'cherishing', 'n.', 'the act of holding dear with great affection', 'Their love was built on a daily cherishing of one another.'),
  Word('love', 'reciprocate', 'v.', 'to respond to a gesture or feeling in kind', 'She was overjoyed when he reciprocated her affection.'),
  Word('love', 'requite', 'v.', 'to return love or affection', 'At last he learned that she requited his love.'),
  Word('love', 'tenderness', 'n.', 'gentleness and kindness in love', 'He treated her with a tenderness she had never known.'),
  Word('love', 'gentleness', 'n.', 'the quality of being kind and tender', 'His gentleness toward her revealed how much he cared.'),
  Word('love', 'cuddly', 'adj.', 'pleasant to hold close and embrace', 'He was warm and cuddly, perfect for cold evenings.'),
  Word('love', 'pang', 'n.', 'a sudden sharp feeling of longing or love', 'A pang of longing struck her when he said goodbye.'),
  Word('love', 'heartstrings', 'n.', 'one\'s deepest feelings of love or sympathy', 'The old love song tugged at her heartstrings.'),
  Word('love', 'sweetnothings', 'phr.', 'tender words of affection murmured to a lover', 'He whispered sweet nothings into her ear all night.'),
  Word('love', 'amorousness', 'n.', 'the state of being full of romantic feeling', 'There was an amorousness in the air that summer evening.'),
  Word('love', 'romanticize', 'v.', 'to make something seem more loving or ideal', 'She tended to romanticize their early days together.'),
  Word('love', 'sentimentality', 'n.', 'tender emotion, sometimes excessive', 'Their anniversary was filled with happy sentimentality.'),
  Word('love', 'keepsake', 'n.', 'a small item kept in memory of a loved one', 'She wore his ring as a keepsake long after he left.'),
  Word('love', 'memento', 'n.', 'an object kept as a reminder of someone loved', 'He kept the ticket stub as a memento of their first date.'),
  Word('love', 'canoodle', 'v.', 'to kiss and cuddle amorously', 'The young couple would canoodle on the park bench for hours.'),
  Word('love', 'entwine', 'v.', 'to twist together, as lives or hands in love', 'Their fingers would entwine as they walked along the shore.'),
  Word('love', 'intertwine', 'v.', 'to closely connect two lives or people', 'Marriage would forever intertwine their two families.'),
  Word('love', 'inseparable', 'adj.', 'unable to be parted, as devoted lovers', 'The couple was inseparable from the day they met.'),
  Word('love', 'engagement', 'n.', 'a formal agreement to get married', 'Their engagement was announced at the family dinner.'),
  Word('love', 'cohabit', 'v.', 'to live together in a romantic relationship', 'They decided to cohabit before getting married.'),
  Word('love', 'winsome', 'adj.', 'attractive or appealing in a charming way', 'Her winsome charm made him fall a little harder each day.'),
];
