import 'words_data.dart';

const kMusicExtras = <Word>[
  Word('music', 'treble', 'n.', 'The higher range of musical pitches', 'Boost the treble a little so the cymbals cut through.'),
  Word('music', 'bassline', 'n.', 'The lowest melodic line in a song', 'That funk track lives or dies by its bassline.'),
  Word('music', 'hi-hat', 'n.', 'A pair of cymbals on a pedal-operated stand', 'She tapped the hi-hat on every eighth note.'),
  Word('music', 'snare', 'n.', 'A drum with wires stretched across the bottom head', 'The snare hits on beats two and four in most rock songs.'),
  Word('music', 'kick', 'n.', 'The large bass drum played with a foot pedal', 'The kick was too boomy until we cut some low mids.'),
  Word('music', 'tom', 'n.', 'A tuned drum without a snare on the bottom', 'He rolled across the toms going into the chorus.'),
  Word('music', 'cymbal', 'n.', 'A round brass plate struck to make a shimmering sound', 'A crash cymbal punctuates the start of the next section.'),
  Word('music', 'ride', 'n.', 'A large sustaining cymbal used for steady rhythm', 'The drummer switched from hi-hat to ride for the solo.'),
  Word('music', 'modal', 'adj.', 'Based on church modes rather than major-minor scales', 'Miles Davis pushed jazz toward a modal approach in 1959.'),
  Word('music', 'dorian', 'n.', 'A minor mode with a raised sixth degree', 'Try playing dorian over that minor seventh chord.'),
  Word('music', 'phrygian', 'n.', 'A minor mode with a lowered second degree', 'Phrygian gives the riff a Spanish flavor.'),
  Word('music', 'lydian', 'n.', 'A major mode with a raised fourth degree', 'The bridge floats on a dreamy lydian scale.'),
  Word('music', 'mixolydian', 'n.', 'A major mode with a lowered seventh degree', 'Most blues-rock solos rely on mixolydian.'),
  Word('music', 'locrian', 'n.', 'A diminished-feeling mode rarely used in tonal music', 'Locrian sounds unstable because the tonic chord is diminished.'),
  Word('music', 'ionian', 'n.', 'The major scale used as a mode', 'Ionian is just a fancy name for plain old major.'),
  Word('music', 'aeolian', 'n.', 'The natural minor scale used as a mode', 'Folk tunes often sit comfortably in aeolian.'),
  Word('music', 'hemiola', 'n.', 'A rhythmic pattern crossing two against three', 'The waltz suddenly slips into a hemiola before the cadence.'),
  Word('music', 'polytonality', 'n.', 'The use of two or more keys at once', 'Stravinsky stacked C major over F-sharp major for icy polytonality.'),
  Word('music', 'atonal', 'adj.', 'Lacking a clear tonal center', 'Schoenberg pioneered an atonal approach to composition.'),
  Word('music', 'serialism', 'n.', 'Composing using ordered rows of pitches', 'Webern took serialism to its sparest extreme.'),
  Word('music', 'twelve-tone', 'adj.', 'Built on a row containing all twelve pitches', 'A twelve-tone row gave the piece its angular character.'),
  Word('music', 'microtonal', 'adj.', 'Using intervals smaller than a semitone', 'Microtonal tuning can make a Western ear feel disoriented.'),
  Word('music', 'spectralism', 'n.', 'A style derived from analyzing the overtones of sounds', 'Grisey is the household name in French spectralism.'),
  Word('music', 'minimalism', 'n.', 'A style built from short repeated patterns', 'Steve Reich brought phase-shifting minimalism to the concert hall.'),
  Word('music', 'aleatoric', 'adj.', 'Involving chance or performer choice', 'Cage wrote aleatoric pieces decided by coin tosses.'),
  Word('music', 'idiophone', 'n.', 'An instrument that sounds by vibrating itself', 'A triangle is the simplest idiophone in the orchestra.'),
  Word('music', 'chordophone', 'n.', 'An instrument that makes sound from a vibrating string', 'Guitars and violins are both chordophones.'),
  Word('music', 'aerophone', 'n.', 'An instrument that sounds by vibrating a column of air', 'Flutes, trumpets, and accordions all count as aerophones.'),
  Word('music', 'membranophone', 'n.', 'An instrument that sounds by a vibrating skin', 'Most drums fall under the membranophone label.'),
  Word('music', 'electrophone', 'n.', 'An instrument that generates sound electronically', 'Synthesizers are the textbook electrophone.'),
  Word('music', 'fretboard', 'n.', 'The strip on a guitar where notes are pressed', 'She slid her finger up the fretboard for the high note.'),
  Word('music', 'capo', 'n.', 'A clamp that raises the pitch of a guitar', 'Put a capo on the third fret to match her vocal range.'),
  Word('music', 'plectrum', 'n.', 'A small piece used to pluck strings', 'I dropped my plectrum into the soundhole mid-song.'),
  Word('music', 'distortion', 'n.', 'A clipped, overdriven guitar tone', 'Crank the distortion for the metal section.'),
  Word('music', 'overdrive', 'n.', 'A warm, slightly clipped amplifier tone', 'Blues players love that creamy overdrive sound.'),
  Word('music', 'fuzz', 'n.', 'A heavily clipped, woolly guitar effect', 'The riff has that classic 60s fuzz texture.'),
  Word('music', 'wah', 'n.', 'A foot-controlled filter sweep on a guitar', 'Hendrix made the wah pedal famous.'),
  Word('music', 'reverb', 'n.', 'A simulation of reflections in a space', 'Drown the vocal in reverb for a dreamy effect.'),
  Word('music', 'delay', 'n.', 'An echo effect set to a chosen time', 'A dotted-eighth delay gives The Edge his signature sound.'),
  Word('music', 'chorusing', 'n.', 'A modulation effect that thickens a sound', 'A bit of chorusing makes the clean guitar sparkle.'),
  Word('music', 'flanger', 'n.', 'A sweeping comb-filter modulation effect', 'The flanger gave the snare a jet-engine whoosh.'),
  Word('music', 'phaser', 'n.', 'A modulation effect that sweeps notches in frequency', 'The keys have a subtle phaser on them.'),
  Word('music', 'compressor', 'n.', 'A processor that evens out loud and soft', 'Slap a compressor on the vocal to keep it level.'),
  Word('music', 'limiter', 'n.', 'A compressor that prevents signal from exceeding a level', 'The limiter on the master bus catches any stray peaks.'),
  Word('music', 'sidechain', 'n.', 'Triggering compression from a separate signal', 'The classic house pump comes from sidechaining the bass to the kick.'),
  Word('music', 'eq', 'n.', 'Tools that adjust the balance of frequencies', 'A little eq below 200 Hz cleaned up the mix.'),
  Word('music', 'mastering', 'n.', 'The final polish stage of a record', 'Mastering glued the album together across all twelve tracks.'),
  Word('music', 'daw', 'n.', 'A digital audio workstation for recording and editing', 'Most bedroom producers swear by their favorite daw.'),
  Word('music', 'plugin', 'n.', 'A software module that processes audio', 'I added a tape plugin to warm up the drum bus.'),
  Word('music', 'midi', 'n.', 'A protocol for sending musical performance data', 'Send the midi out of the keyboard into the synth module.'),
  Word('music', 'quantize', 'v.', 'To snap recorded notes to a grid', 'Quantize the hi-hat but leave the snare alone for feel.'),
  Word('music', 'arpeggiator', 'n.', 'A device that plays chord notes one at a time', 'Run the pad through the arpeggiator for movement.'),
  Word('music', 'sequencer', 'n.', 'A device or program that triggers notes in order', 'The sequencer fires off the bassline while you play keys.'),
  Word('music', 'sampler', 'n.', 'A device that plays back recorded sounds as notes', 'He loaded an orchestra hit into the sampler.'),
  Word('music', 'looper', 'n.', 'A pedal or app that records and repeats audio', 'She built the whole song live on a looper.'),
  Word('music', 'oscillator', 'n.', 'The waveform generator in a synth', 'Detune the second oscillator for a fatter sound.'),
  Word('music', 'envelope', 'n.', 'A shape controlling how a sound rises and falls', 'A snappy envelope makes the pluck pop.'),
  Word('music', 'filter', 'n.', 'A circuit that shapes frequencies of a sound', 'Sweep the filter open during the build-up.'),
  Word('music', 'lfo', 'n.', 'A low-frequency oscillator that modulates a parameter', 'An lfo on the filter gives the pad some wobble.'),
  Word('music', 'patch', 'n.', 'A saved sound on a synthesizer', 'Save that patch — we might use it again on track three.'),
  Word('music', 'preset', 'n.', 'A factory-stored sound on a synth or plugin', 'I tweaked the preset until it didn\'t sound like every other song.'),
  Word('music', 'synthesizer', 'n.', 'An electronic instrument that generates sound', 'Vintage analog synthesizers are back in fashion.'),
  Word('music', 'subtractive', 'adj.', 'Synthesizing sound by filtering a rich waveform', 'Most classic synths use subtractive design.'),
  Word('music', 'additive', 'adj.', 'Synthesizing sound by stacking pure tones', 'Additive synthesis is powerful but CPU-hungry.'),
  Word('music', 'wavetable', 'n.', 'A synthesis method scanning through stored waveforms', 'Wavetable synths excel at morphing textures.'),
  Word('music', 'granular', 'adj.', 'Built from many tiny grains of sound', 'A granular processor turned the violin into a shimmering cloud.'),
  Word('music', 'fm', 'n.', 'Synthesis using one oscillator to modulate another', 'The DX7 made fm synthesis a household staple in the 80s.'),
  Word('music', 'monophonic', 'adj.', 'Capable of playing only one note at a time', 'The old Moog was strictly monophonic.'),
  Word('music', 'polyphonic', 'adj.', 'Capable of playing many notes at once', 'You need a polyphonic synth for those lush pads.'),
  Word('music', 'tutti', 'n.', 'A passage played by the whole ensemble', 'The tutti entrance shook the rafters.'),
  Word('music', 'solo', 'n.', 'A passage played alone by one performer', 'His sax solo brought the crowd to its feet.'),
  Word('music', 'trio', 'n.', 'A group of three musicians', 'The piano trio took the stage after intermission.'),
  Word('music', 'quintet', 'n.', 'A group of five musicians', 'A brass quintet opened the wedding.'),
  Word('music', 'sextet', 'n.', 'A group of six performers', 'The string sextet recorded in a converted barn.'),
  Word('music', 'septet', 'n.', 'A group of seven performers', 'Beethoven\'s septet remains a charming chamber piece.'),
  Word('music', 'octet', 'n.', 'A group of eight performers', 'Mendelssohn wrote his string octet as a teenager.'),
  Word('music', 'orchestra', 'n.', 'A large ensemble of strings, winds, and percussion', 'The orchestra tuned to an oboe\'s A.'),
  Word('music', 'conductor', 'n.', 'The person who directs an ensemble in performance', 'A good conductor barely needs to speak.'),
  Word('music', 'baton', 'n.', 'The stick a conductor uses to mark the beat', 'She tapped the baton on the stand to call the orchestra to order.'),
  Word('music', 'podium', 'n.', 'The raised platform a conductor stands on', 'He stepped onto the podium and the hall fell silent.'),
  Word('music', 'pit', 'n.', 'The sunken area for musicians at an opera or musical', 'The orchestra plays from the pit beneath the stage.'),
  Word('music', 'baroque', 'adj.', 'Of the elaborate style of music roughly 1600 to 1750', 'Bach is the towering figure of the baroque era.'),
  Word('music', 'rococo', 'adj.', 'Of a light, ornate style following the baroque', 'The rococo flourishes feel almost decorative.'),
  Word('music', 'classical', 'adj.', 'Of the balanced style roughly 1750 to 1820', 'Haydn and Mozart shaped the classical period.'),
  Word('music', 'romantic', 'adj.', 'Of the emotionally expansive style of the 19th century', 'Romantic composers pushed the symphony to enormous lengths.'),
  Word('music', 'impressionism', 'n.', 'A style evoking mood through color and texture', 'Debussy stands at the heart of musical impressionism.'),
  Word('music', 'expressionism', 'n.', 'A style of extreme emotional intensity and dissonance', 'Schoenberg\'s early expressionism shocked Vienna.'),
  Word('music', 'neoclassicism', 'n.', 'A 20th-century return to classical forms and clarity', 'Stravinsky\'s neoclassicism leaned on 18th-century models.'),
  Word('music', 'bebop', 'n.', 'A fast, virtuosic style of 1940s jazz', 'Charlie Parker tore through bebop changes at impossible tempos.'),
  Word('music', 'swing', 'n.', 'A jazz style with a lilting eighth-note feel', 'You can\'t play swing without a strong walking bass.'),
  Word('music', 'fusion', 'n.', 'A blend of jazz with rock and other styles', 'Weather Report defined 70s fusion.'),
  Word('music', 'bossa nova', 'n.', 'A gentle Brazilian jazz-influenced style', 'A bossa nova feel suits the song much better.'),
  Word('music', 'samba', 'n.', 'An upbeat Brazilian dance style with strong percussion', 'Samba schools spend all year preparing for Carnival.'),
  Word('music', 'salsa', 'n.', 'An Afro-Cuban dance music style', 'The salsa band kept the dance floor packed all night.'),
  Word('music', 'reggae', 'n.', 'A Jamaican style with offbeat guitar and bass-heavy groove', 'Reggae taught the world to sit back on the offbeat.'),
  Word('music', 'ska', 'n.', 'An upbeat Jamaican precursor to reggae', 'Ska bands love a tight horn section.'),
  Word('music', 'dub', 'n.', 'A reggae offshoot built from heavy effects and dropouts', 'King Tubby invented dub at the mixing desk.'),
  Word('music', 'dancehall', 'n.', 'A Jamaican style of toasting over digital riddims', 'Dancehall took over Kingston soundsystems in the 80s.'),
  Word('music', 'afrobeat', 'n.', 'A West African style mixing funk and traditional rhythm', 'Fela Kuti is the founding father of afrobeat.'),
  Word('music', 'highlife', 'n.', 'A West African popular style with jazzy guitar lines', 'Ghanaian highlife is full of brass and palm-wine guitar.'),
  Word('music', 'soukous', 'n.', 'A fast Congolese dance style with shimmering guitars', 'Soukous guitarists pioneered the sebene section.'),
  Word('music', 'cumbia', 'n.', 'A Colombian dance style now popular across Latin America', 'A cumbia rhythm got the whole party moving.'),
  Word('music', 'tango', 'n.', 'An Argentine dance style of passionate phrasing', 'A tango orchestra typically features a bandoneon.'),
  Word('music', 'flamenco', 'n.', 'A Spanish style of guitar, song, and dance', 'The flamenco guitarist tapped out a fierce rasgueado.'),
  Word('music', 'fado', 'n.', 'A Portuguese style of melancholy song', 'Fado singers tell stories of longing and the sea.'),
  Word('music', 'klezmer', 'n.', 'An Eastern European Jewish folk style', 'A klezmer clarinet wails over a fast freylekh.'),
  Word('music', 'qawwali', 'n.', 'A devotional South Asian Sufi vocal style', 'Nusrat Fateh Ali Khan brought qawwali to global stages.'),
  Word('music', 'raga', 'n.', 'A melodic framework in Indian classical music', 'Each raga is tied to a season or time of day.'),
  Word('music', 'tala', 'n.', 'A rhythmic cycle in Indian classical music', 'The tabla player keeps the tala steady for the soloist.'),
  Word('music', 'gamelan', 'n.', 'An Indonesian ensemble of tuned percussion', 'A gamelan rehearsal can rattle the walls of a village.'),
  Word('music', 'koto', 'n.', 'A Japanese long zither with thirteen silk strings', 'The koto solo evoked a quiet temple garden.'),
  Word('music', 'shamisen', 'n.', 'A three-stringed Japanese lute played with a plectrum', 'A shamisen punctuates the kabuki narration.'),
  Word('music', 'sitar', 'n.', 'A long-necked Indian lute with sympathetic strings', 'Ravi Shankar made the sitar famous in the West.'),
  Word('music', 'tabla', 'n.', 'A pair of hand drums used in Indian classical music', 'The tabla solo unraveled into impossible cross-rhythms.'),
  Word('music', 'oud', 'n.', 'A short-necked Middle Eastern lute', 'The oud player improvised a long taqsim.'),
  Word('music', 'bouzouki', 'n.', 'A long-necked Greek lute with a sharp tone', 'A bouzouki line drove the rebetiko number.'),
  Word('music', 'balalaika', 'n.', 'A triangular Russian folk lute', 'The balalaika ensemble plucked through a quick dance tune.'),
  Word('music', 'didgeridoo', 'n.', 'An Aboriginal Australian drone instrument', 'A didgeridoo opened the festival with circular breathing.'),
  Word('music', 'kalimba', 'n.', 'An African thumb piano with metal tines', 'She plucked a soothing pattern on the kalimba.'),
  Word('music', 'mbira', 'n.', 'A Zimbabwean thumb piano used in spiritual music', 'Mbira music repeats short cycles with subtle shifts.'),
  Word('music', 'djembe', 'n.', 'A West African goblet drum played with bare hands', 'The djembe circle warmed up with a steady three-against-two.'),
  Word('music', 'conga', 'n.', 'A tall single-headed drum from Cuba', 'The conga player anchored the groove from stage left.'),
  Word('music', 'bongos', 'n.', 'A pair of small Cuban hand drums', 'He slapped out an offbeat on the bongos.'),
  Word('music', 'cajon', 'n.', 'A box-shaped percussion instrument from Peru', 'A cajon makes acoustic gigs feel like full band shows.'),
  Word('music', 'maracas', 'n.', 'Filled rattles shaken to give a percussive shimmer', 'A simple pair of maracas pushed the song along.'),
  Word('music', 'tambourine', 'n.', 'A small frame drum with jingles', 'Shake the tambourine on every chorus.'),
  Word('music', 'cowbell', 'n.', 'A clapperless bell played as a percussion instrument', 'More cowbell, the producer insisted.'),
  Word('music', 'timpani', 'n.', 'Large tunable kettledrums used in orchestras', 'The timpani rolled in for the finale.'),
  Word('music', 'xylophone', 'n.', 'A tuned percussion instrument with wooden bars', 'The xylophone added a bright clatter to the bridge.'),
  Word('music', 'marimba', 'n.', 'A large mellow-toned wooden bar percussion instrument', 'Four mallets gave the marimba a rich chordal sound.'),
  Word('music', 'vibraphone', 'n.', 'A metal-bar percussion with motor-driven vibrato', 'Milt Jackson made the vibraphone a jazz mainstay.'),
  Word('music', 'glockenspiel', 'n.', 'A small set of tuned metal bars', 'A glockenspiel sparkles above the strings.'),
  Word('music', 'celesta', 'n.', 'A keyboard instrument with tuned metal bars', 'Tchaikovsky\'s sugar-plum theme rides on a celesta.'),
  Word('music', 'harpsichord', 'n.', 'A plucked keyboard instrument predating the piano', 'The harpsichord ticks along under the baroque concerto.'),
  Word('music', 'clavichord', 'n.', 'A quiet early keyboard instrument with tangents', 'A clavichord is barely audible from across a room.'),
  Word('music', 'fortepiano', 'n.', 'The early lighter version of the piano', 'Mozart\'s sonatas were written for the fortepiano.'),
  Word('music', 'spinet', 'n.', 'A small upright piano or harpsichord', 'There\'s an old spinet piano in the corner of the studio.'),
  Word('music', 'organ', 'n.', 'A keyboard instrument that sounds with pipes or electronics', 'The pipe organ shook the cathedral floor.'),
  Word('music', 'hammond', 'n.', 'An electromechanical organ favored in jazz and rock', 'The Hammond growled through a Leslie cabinet.'),
  Word('music', 'leslie', 'n.', 'A rotating speaker cabinet usually paired with a Hammond', 'Switching the Leslie to fast gave the solo a swirl.'),
  Word('music', 'accordion', 'n.', 'A bellows-driven reed instrument with keys or buttons', 'The accordion gives Parisian café music its soul.'),
  Word('music', 'concertina', 'n.', 'A small hexagonal accordion-like instrument', 'A concertina led the sea shanty sing-along.'),
  Word('music', 'harmonica', 'n.', 'A small free-reed instrument played by mouth', 'A bluesy harmonica wailed over the slow shuffle.'),
  Word('music', 'bagpipes', 'n.', 'A reed instrument fed by a bag of air', 'The bagpipes droned at the head of the parade.'),
  Word('music', 'piccolo', 'n.', 'A small flute pitched an octave above', 'A piccolo cuts through the loudest orchestra.'),
  Word('music', 'flute', 'n.', 'A side-blown woodwind instrument with no reed', 'The flute solo floated over the strings.'),
  Word('music', 'oboe', 'n.', 'A double-reed woodwind with a piercing tone', 'The oboe gives the orchestra its tuning note.'),
  Word('music', 'clarinet', 'n.', 'A single-reed woodwind with a cylindrical bore', 'The clarinet glide opens Gershwin\'s Rhapsody in Blue.'),
  Word('music', 'bassoon', 'n.', 'A double-reed woodwind with a low woody sound', 'The bassoon plays the spooky opening of The Rite of Spring.'),
  Word('music', 'saxophone', 'n.', 'A single-reed instrument made of metal', 'A breathy saxophone took over the chorus.'),
  Word('music', 'cornet', 'n.', 'A trumpet-like brass instrument with a mellower tone', 'British brass bands rely on the cornet section.'),
  Word('music', 'trumpet', 'n.', 'A high brass instrument with three valves', 'The trumpet hit the high C cleanly.'),
  Word('music', 'flugelhorn', 'n.', 'A wide-bore brass instrument with a soft sound', 'A flugelhorn solo gave the ballad a velvety warmth.'),
  Word('music', 'trombone', 'n.', 'A brass instrument played with a slide', 'The trombone section punched in for the shout chorus.'),
  Word('music', 'tuba', 'n.', 'The lowest brass instrument', 'The tuba anchored the marching band\'s low end.'),
  Word('music', 'euphonium', 'n.', 'A small tuba-like brass instrument with a smooth tone', 'The euphonium carried the melody in the brass band.'),
  Word('music', 'french horn', 'n.', 'A circular brass instrument with a mellow blended tone', 'The french horn slid through a long lyrical line.'),
  Word('music', 'violin', 'n.', 'The smallest and highest standard bowed string', 'She tucked the violin under her chin and began.'),
  Word('music', 'viola', 'n.', 'A bowed string slightly larger than a violin', 'The viola sits in the alto range of the string section.'),
  Word('music', 'cello', 'n.', 'A large bowed string instrument played seated', 'The cello carried the heartbreak of the second movement.'),
  Word('music', 'contrabass', 'n.', 'The largest and lowest bowed string instrument', 'A bowed contrabass rumbled beneath the orchestra.'),
  Word('music', 'harp', 'n.', 'A large plucked string instrument with pedals', 'A harp glissando opened the dream sequence.'),
  Word('music', 'lute', 'n.', 'A pear-shaped plucked string instrument from the Renaissance', 'The lute player tuned for half an hour before the recital.'),
  Word('music', 'mandolin', 'n.', 'A small double-strung plucked instrument', 'A mandolin tremolo gave the bluegrass tune its bounce.'),
  Word('music', 'banjo', 'n.', 'A drum-bodied string instrument central to old-time music', 'The banjo rolled through three-finger patterns.'),
  Word('music', 'ukulele', 'n.', 'A small Hawaiian four-string instrument', 'A ukulele strum brightened the porch jam.'),
  Word('music', 'dulcimer', 'n.', 'A folk instrument with strings stretched across a soundbox', 'A hammered dulcimer chimed through the Appalachian set.'),
  Word('music', 'zither', 'n.', 'A flat string instrument with many strings', 'The zither gave The Third Man its haunting theme.'),
  Word('music', 'slide', 'n.', 'A continuous movement between pitches on an instrument', 'The trombone slide is a marching band classic.'),
  Word('music', 'portamento', 'n.', 'A subtle slide between two pitches', 'A touch of portamento makes the violin line sing.'),
  Word('music', 'tessitura', 'n.', 'The most comfortable pitch range for a voice', 'Her tessitura sits surprisingly low for a soprano.'),
  Word('music', 'melisma', 'n.', 'Many notes sung on one syllable', 'Mariah Carey made melisma a pop staple.'),
  Word('music', 'belting', 'n.', 'A powerful chest-voice singing style', 'Broadway belting can blow out an untrained voice.'),
  Word('music', 'yodel', 'n.', 'A vocal style flipping rapidly between registers', 'A Swiss yodel rang through the alpine meadow.'),
  Word('music', 'throat singing', 'n.', 'A style producing two pitches in one voice', 'Tuvan throat singing creates an eerie overtone melody.'),
  Word('music', 'scat', 'n.', 'Improvised singing using nonsense syllables', 'Ella Fitzgerald could scat over the wildest changes.'),
  Word('music', 'chanteuse', 'n.', 'A female singer of cabaret or popular songs', 'The set list paid tribute to mid-century French chanteuses.'),
  Word('music', 'countertenor', 'n.', 'A male singer with a very high range', 'The countertenor floated above the early-music ensemble.'),
  Word('music', 'mezzo', 'n.', 'A female voice between soprano and contralto', 'A mezzo sang the role of Carmen.'),
  Word('music', 'contralto', 'n.', 'The lowest female voice type', 'A true contralto is a rare instrument.'),
  Word('music', 'bass-baritone', 'n.', 'A voice between bass and baritone', 'The bass-baritone took the role of Wotan.'),
  Word('music', 'larynx', 'n.', 'The voice box that produces vocal pitch', 'Singers learn to relax the larynx for a free tone.'),
  Word('music', 'diaphragm', 'n.', 'The muscle that supports the breath', 'Engage your diaphragm so the long phrase doesn\'t collapse.'),
  Word('music', 'phrasing', 'n.', 'How a performer shapes a musical line', 'Her phrasing made even simple melodies feel new.'),
  Word('music', 'articulation', 'n.', 'How a note is attacked and released', 'Cleaner articulation will fix that messy run.'),
  Word('music', 'dynamics', 'n.', 'The loud-and-soft markings or behavior of a piece', 'Watch the dynamics in the second movement.'),
  Word('music', 'mezzo forte', 'n.', 'Moderately loud as a dynamic marking', 'Play the chorale mezzo forte from the start.'),
  Word('music', 'pianissimo', 'n.', 'Very soft as a dynamic marking', 'The strings drop to pianissimo at letter G.'),
  Word('music', 'fortissimo', 'n.', 'Very loud as a dynamic marking', 'The brass blast a fortissimo at the climax.'),
  Word('music', 'sforzando', 'n.', 'A sudden strong accent on a note', 'Hit that downbeat with a real sforzando.'),
  Word('music', 'rubato', 'n.', 'Flexible timing for expressive effect', 'Chopin\'s nocturnes beg for tasteful rubato.'),
  Word('music', 'accelerando', 'n.', 'A gradual increase in tempo', 'Build a slow accelerando into the recapitulation.'),
  Word('music', 'ritardando', 'n.', 'A gradual slowing of tempo', 'A long ritardando set up the final chord.'),
  Word('music', 'fermata', 'n.', 'A hold lengthening a note beyond its written value', 'The conductor cued a long fermata over the rest.'),
  Word('music', 'caesura', 'n.', 'A pronounced pause in the flow of music', 'A dramatic caesura cut the piece in two.'),
  Word('music', 'attacca', 'n.', 'A direction to move to the next section without pause', 'The movements run attacca into one another.'),
  Word('music', 'da capo', 'n.', 'A direction to return to the beginning', 'A da capo aria repeats the opening section with ornaments.'),
  Word('music', 'segno', 'n.', 'A sign marking a point to return to', 'Jump back to the segno after the bridge.'),
  Word('music', 'coda sign', 'n.', 'A notation symbol marking the final section', 'Skip to the coda sign on the third pass.'),
  Word('music', 'tablature', 'n.', 'A notation showing finger positions on strings', 'Beginners often start by reading tablature.'),
  Word('music', 'clef', 'n.', 'A symbol fixing the pitch range on a staff', 'The viola reads from an alto clef.'),
  Word('music', 'staff', 'n.', 'The five lines used to notate pitches', 'Pencil the dynamics in below the staff.'),
  Word('music', 'ledger line', 'n.', 'A short line extending the staff for high or low notes', 'The high note sits three ledger lines above the staff.'),
  Word('music', 'sharp', 'n.', 'A sign raising a note by a semitone', 'Don\'t forget the sharp in measure twelve.'),
  Word('music', 'flat', 'n.', 'A sign lowering a note by a semitone', 'That accidental is a flat, not a natural.'),
  Word('music', 'natural', 'n.', 'A sign cancelling a sharp or flat', 'Pencil in a natural to remind yourself.'),
  Word('music', 'accidental', 'n.', 'A pitch alteration that lasts only the measure', 'Watch the accidental on beat three.'),
  Word('music', 'enharmonic', 'adj.', 'Sounding the same but spelled differently', 'C sharp and D flat are enharmonic equivalents.'),
  Word('music', 'tonic', 'n.', 'The home note or chord of a key', 'The phrase finally lands on the tonic.'),
  Word('music', 'dominant', 'n.', 'The fifth scale degree or its chord', 'The dominant pulls strongly toward the tonic.'),
  Word('music', 'subdominant', 'n.', 'The fourth scale degree or its chord', 'A move to the subdominant softens the harmony.'),
  Word('music', 'leading tone', 'n.', 'The seventh note that pulls up to the tonic', 'A raised leading tone gives the cadence its bite.'),
  Word('music', 'mediant', 'n.', 'The third scale degree', 'A mediant chord shares two notes with the tonic.'),
  Word('music', 'submediant', 'n.', 'The sixth scale degree', 'A deceptive cadence often lands on the submediant.'),
  Word('music', 'supertonic', 'n.', 'The second scale degree', 'The supertonic seventh is a classic predominant chord.'),
  Word('music', 'authentic', 'adj.', 'Of a cadence moving from dominant to tonic', 'The piece closes with an emphatic authentic cadence.'),
  Word('music', 'plagal', 'adj.', 'Of a cadence moving from subdominant to tonic', 'The amen at the end of a hymn is a plagal cadence.'),
  Word('music', 'deceptive', 'adj.', 'Of a cadence that avoids the expected tonic', 'A deceptive cadence keeps the phrase from settling.'),
  Word('music', 'half cadence', 'n.', 'A pause on the dominant chord', 'A half cadence leaves the listener hanging.'),
  Word('music', 'picardy third', 'n.', 'Ending a minor piece on a major chord', 'Bach often ends a minor fugue with a picardy third.'),
  Word('music', 'neapolitan', 'n.', 'A flattened supertonic major chord', 'A neapolitan chord adds a touch of drama.'),
  Word('music', 'tritone', 'n.', 'An interval of three whole tones', 'Medieval theorists called the tritone the devil in music.'),
  Word('music', 'perfect fifth', 'n.', 'A consonant interval of seven semitones', 'The opening fanfare leaps a perfect fifth.'),
  Word('music', 'minor third', 'n.', 'An interval of three semitones', 'A minor third gives the chord its sad color.'),
  Word('music', 'major third', 'n.', 'An interval of four semitones', 'A major third brightens the harmony.'),
  Word('music', 'minor seventh', 'n.', 'An interval of ten semitones', 'A minor seventh adds bluesy color to the dominant.'),
  Word('music', 'major seventh', 'n.', 'An interval of eleven semitones', 'A major seventh chord has that dreamy jazz sound.'),
  Word('music', 'diminished', 'adj.', 'Of an interval or chord smaller than minor', 'A diminished seventh chord screams unresolved tension.'),
  Word('music', 'augmented', 'adj.', 'Of an interval or chord larger than major', 'An augmented chord climbs in three equal leaps.'),
  Word('music', 'voicing', 'n.', 'How the notes of a chord are arranged in pitch', 'A drop-two voicing keeps the harmony clear.'),
  Word('music', 'inversion', 'n.', 'A chord arranged with a non-root in the bass', 'Use a first inversion to smooth out the bassline.'),
  Word('music', 'figured bass', 'n.', 'A shorthand notation for baroque keyboard harmony', 'Continuo players read from figured bass at sight.'),
  Word('music', 'continuo', 'n.', 'The baroque accompanying group of bass and keyboard', 'The continuo includes cello and harpsichord on this recording.'),
  Word('music', 'tutti passage', 'n.', 'A section played by the entire ensemble', 'The orchestra came in for the tutti passage after the cadenza.'),
  Word('music', 'concertante', 'adj.', 'Featuring a soloist or small group against the ensemble', 'A concertante section gave the oboist the spotlight.'),
  Word('music', 'ripieno', 'n.', 'The accompanying group in a baroque concerto', 'The ripieno fills out the texture behind the soloists.'),
  Word('music', 'obbligato', 'n.', 'An essential instrumental line accompanying a singer', 'The aria features a violin obbligato weaving around the voice.'),
  Word('music', 'recitative', 'n.', 'Speech-like singing used to advance opera plot', 'A long recitative sets up the famous aria.'),
  Word('music', 'arioso', 'n.', 'A lyrical passage between recitative and aria', 'The arioso lets the character muse before the aria proper.'),
  Word('music', 'verismo', 'n.', 'A realistic, gritty style of Italian opera', 'Puccini\'s operas carry the verismo torch.'),
  Word('music', 'bel canto', 'n.', 'A florid Italian vocal style of the early 19th century', 'Bel canto requires breath control and clean coloratura.'),
  Word('music', 'coloratura', 'n.', 'Highly elaborate vocal ornamentation', 'A coloratura soprano can rattle off rapid scales.'),
  Word('music', 'fioritura', 'n.', 'Decorative ornamental flourishes in a vocal line', 'The cadenza ended with a tumbling fioritura.'),
  Word('music', 'mordent', 'n.', 'A quick alternation with a neighboring note', 'A mordent on the downbeat sharpens the rhythm.'),
  Word('music', 'turn', 'n.', 'An ornament circling around a main note', 'A graceful turn ornamented the long sustained note.'),
  Word('music', 'trill', 'n.', 'A rapid alternation between two adjacent notes', 'Hold the trill for two full bars.'),
  Word('music', 'appoggiatura', 'n.', 'A leaning dissonant note resolving stepwise', 'An appoggiatura adds yearning to the melody.'),
  Word('music', 'acciaccatura', 'n.', 'A very short crushed grace note', 'An acciaccatura barely touches the beat before the main note.'),
  Word('music', 'grace note', 'n.', 'A small ornamental note before a main note', 'A quick grace note gave the melody a fiddle-style lift.'),
  Word('music', 'tonality', 'n.', 'The system of organizing music around a key', 'Late Romantic composers stretched tonality almost to breaking.'),
  Word('music', 'chromatic', 'adj.', 'Using all twelve pitches of the scale', 'A chromatic line slides between the two chords.'),
  Word('music', 'diatonic', 'adj.', 'Using only the notes of one major or minor scale', 'The hymn melody is strictly diatonic.'),
  Word('music', 'pentatonic', 'adj.', 'Of a five-note scale common in folk music', 'The pentatonic scale works over almost any rock riff.'),
  Word('music', 'whole tone', 'adj.', 'Of a scale built entirely from whole steps', 'A whole tone scale sounds floaty and unresolved.'),
  Word('music', 'octatonic', 'adj.', 'Of an eight-note scale alternating half and whole steps', 'Stravinsky loved the octatonic scale.'),
  Word('music', 'blue note', 'n.', 'A flatted scale degree giving blues its flavor', 'Bend the third up to the major to milk that blue note.'),
  Word('music', 'shuffle', 'n.', 'A swung blues rhythm with a triplet feel', 'A slow shuffle suits this twelve-bar blues.'),
  Word('music', 'boogie', 'n.', 'A rolling left-hand piano blues style', 'Pinetop Smith made boogie piano a household sound.'),
  Word('music', 'stride', 'n.', 'A piano style alternating bass notes and chords', 'Fats Waller could play stride for hours.'),
  Word('music', 'ragtime', 'n.', 'A syncopated piano style around 1900', 'Scott Joplin\'s ragtime tunes are still everywhere.'),
  Word('music', 'dixieland', 'n.', 'An early New Orleans jazz style with collective improvisation', 'A dixieland band marched ahead of the parade.'),
  Word('music', 'big band', 'n.', 'A large jazz ensemble of brass, reeds, and rhythm', 'Glenn Miller led one of the most famous big bands.'),
  Word('music', 'hard bop', 'n.', 'A funky and bluesy 50s offshoot of bebop', 'Art Blakey championed hard bop with the Messengers.'),
  Word('music', 'cool jazz', 'n.', 'A relaxed introspective post-bebop style', 'Chet Baker became the face of cool jazz.'),
  Word('music', 'free jazz', 'n.', 'A jazz style abandoning fixed forms and chord changes', 'Ornette Coleman ushered in free jazz with quiet fury.'),
  Word('music', 'avant-garde', 'adj.', 'Boldly experimental in style and form', 'The avant-garde quartet abandoned bar lines entirely.'),
  Word('music', 'noise', 'n.', 'A genre using abrasive, non-pitched sound', 'The noise set lasted twenty minutes of pure walls of static.'),
  Word('music', 'drone', 'n.', 'A sustained tone or pitch underlying music', 'A bagpipe drone fills out the low end.'),
  Word('music', 'ambient', 'adj.', 'Of slow, atmospheric music meant to fill a space', 'Brian Eno coined the term for ambient music.'),
  Word('music', 'shoegaze', 'n.', 'A swirling guitar-rock style with washes of reverb', 'My Bloody Valentine defined shoegaze with Loveless.'),
  Word('music', 'post-rock', 'n.', 'An instrumental rock style of long building arcs', 'Mogwai built post-rock songs on quiet-loud dynamics.'),
  Word('music', 'math rock', 'n.', 'A rock style with complex meters and angular riffs', 'The math rock band counted off in eleven.'),
  Word('music', 'prog', 'n.', 'A rock style of long forms and virtuoso playing', 'Yes and King Crimson defined classic prog.'),
  Word('music', 'glam', 'n.', 'A flamboyant 70s rock style of high theatricality', 'Bowie\'s glam phase reshaped rock fashion.'),
  Word('music', 'punk', 'n.', 'A fast, raw, anti-establishment rock style', 'The Clash showed punk could be musically adventurous.'),
  Word('music', 'hardcore', 'n.', 'A faster, harsher offshoot of punk', 'Black Flag pushed hardcore into longer formats.'),
  Word('music', 'grunge', 'n.', 'A sludgy, distorted 90s rock style from the Pacific Northwest', 'Nirvana put grunge in every suburban bedroom.'),
  Word('music', 'emo', 'n.', 'An emotionally vulnerable offshoot of punk rock', 'Mid-90s emo had a quieter, more confessional sound.'),
  Word('music', 'metalcore', 'n.', 'A blend of hardcore and metal', 'Metalcore vocals jump between screams and clean choruses.'),
  Word('music', 'death metal', 'n.', 'An extreme metal style with growled vocals', 'A blast beat drove the death metal riff forward.'),
  Word('music', 'black metal', 'n.', 'A frostbitten, lo-fi extreme metal subgenre', 'Norwegian black metal has its own visual aesthetic.'),
  Word('music', 'doom', 'n.', 'A slow, heavy metal style with crushing riffs', 'Doom bands prefer half the tempo and twice the fuzz.'),
  Word('music', 'sludge', 'n.', 'A grimy, slow style mixing doom and hardcore', 'Sludge guitarists drown everything in low-end distortion.'),
  Word('music', 'thrash', 'n.', 'A fast, aggressive 80s metal style', 'Metallica\'s early albums were defining thrash records.'),
  Word('music', 'grindcore', 'n.', 'A blistering metal-punk hybrid with very short songs', 'A grindcore set might pack fifteen songs into ten minutes.'),
  Word('music', 'industrial', 'adj.', 'Of music built from metallic, machine-like textures', 'Industrial bands love to sample factory noise.'),
  Word('music', 'goth', 'n.', 'A dark, atmospheric post-punk style', 'The Cure shaped a generation of goth rock.'),
  Word('music', 'darkwave', 'n.', 'A moody, synthesizer-driven goth-adjacent style', 'Darkwave acts thrive in basement venues and online niches.'),
  Word('music', 'synthwave', 'n.', 'A retro 80s-inspired electronic style', 'Synthwave producers chase a Miami-Vice cinematic glow.'),
  Word('music', 'vaporwave', 'n.', 'A slowed-down, ironic 80s nostalgia style', 'Vaporwave samples mall jazz and warps it into something dreamy.'),
  Word('music', 'house', 'n.', 'A four-on-the-floor electronic dance style from Chicago', 'A deep house set kept the dance floor hypnotized.'),
  Word('music', 'techno', 'n.', 'A futuristic electronic dance style from Detroit', 'Detroit techno mixed Kraftwerk with funk.'),
  Word('music', 'trance', 'n.', 'A euphoric electronic dance style with long builds', 'A trance breakdown drops out everything except the lead.'),
  Word('music', 'dubstep', 'n.', 'An electronic style of heavy bass wobbles and halftime beats', 'Dubstep producers chase the perfect wobble bass.'),
  Word('music', 'drum and bass', 'n.', 'A fast electronic style built on breakbeats and deep bass', 'Drum and bass tracks usually hover around 170 bpm.'),
  Word('music', 'jungle', 'n.', 'An early breakbeat-driven precursor to drum and bass', 'Jungle producers chopped the Amen break to pieces.'),
  Word('music', 'breakbeat', 'n.', 'A genre and rhythm built from chopped drum breaks', 'A breakbeat groove keeps the dancers off the four.'),
  Word('music', 'idm', 'n.', 'A cerebral, glitchy strand of electronic music', 'Aphex Twin\'s early records helped define idm.'),
  Word('music', 'glitch', 'n.', 'An aesthetic built from digital errors and artifacts', 'A glitch break tore the smooth pad to ribbons.'),
  Word('music', 'lo-fi', 'adj.', 'Of music with intentional low-fidelity production', 'Lo-fi hip-hop study streams blew up on YouTube.'),
  Word('music', 'chillwave', 'n.', 'A hazy, nostalgic indie-electronic style', 'Chillwave artists love saturated tape echo.'),
  Word('music', 'trap', 'n.', 'A Southern hip-hop style with skittering hi-hats', 'A trap beat under the verse changed the whole feel.'),
  Word('music', 'drill', 'n.', 'A dark, aggressive offshoot of trap from Chicago and the UK', 'Drill producers favor sliding 808s and sparse melodies.'),
  Word('music', 'boom bap', 'n.', 'A 90s East-Coast hip-hop sound of crunchy drums', 'A boom bap loop has that classic dusty feel.'),
  Word('music', 'g-funk', 'n.', 'A West Coast hip-hop style of laid-back synths', 'Dr. Dre defined g-funk with The Chronic.'),
  Word('music', 'conscious rap', 'n.', 'Hip-hop focused on social and political themes', 'Conscious rap pushes the listener to think.'),
  Word('music', 'mumble rap', 'n.', 'A slurred, melodic style of modern rap', 'Critics dismissed mumble rap until it dominated the charts.'),
  Word('music', 'r&b', 'n.', 'Rhythm and blues, a soulful African-American pop genre', 'Modern r&b borrows freely from electronic music.'),
  Word('music', 'motown', 'n.', 'A polished soul style from Detroit\'s Motown label', 'Motown grooves are still the gold standard for pop bass.'),
  Word('music', 'doo-wop', 'n.', 'A 1950s style of close harmony vocal groups', 'A doo-wop bridge gave the song its retro charm.'),
  Word('music', 'gospel', 'n.', 'A Christian vocal genre rooted in African American churches', 'Aretha Franklin\'s gospel roots powered every record she made.'),
  Word('music', 'spiritual', 'n.', 'A religious folk song from the African American tradition', 'The choir opened with a haunting spiritual.'),
  Word('music', 'sea shanty', 'n.', 'A working song sung by sailors', 'A sea shanty viral trend swept TikTok in 2021.'),
  Word('music', 'work song', 'n.', 'A rhythmic song that paces manual labor', 'Field hollers and work songs fed early blues.'),
  Word('music', 'lullaby', 'n.', 'A gentle song sung to soothe a child to sleep', 'She hummed a lullaby until the baby drifted off.'),
  Word('music', 'anthem', 'n.', 'A celebratory or stirring song for a group or nation', 'The crowd belted out the team anthem.'),
  Word('music', 'hymn', 'n.', 'A song of religious praise or devotion', 'The congregation sang an old hymn in four-part harmony.'),
  Word('music', 'chant', 'n.', 'A repetitive sung or spoken vocal pattern', 'The monastery rang with Gregorian chant at dawn.'),
  Word('music', 'plainchant', 'n.', 'Unaccompanied liturgical chant of the early church', 'Medieval plainchant has a meditative, unmetered flow.'),
  Word('music', 'organum', 'n.', 'An early form of polyphony with parallel voices', 'Notre-Dame composers expanded organum into vast arches of sound.'),
  Word('music', 'madrigal', 'n.', 'A Renaissance secular vocal piece for several voices', 'The madrigal painted each word with a different texture.'),
  Word('music', 'chanson', 'n.', 'A French song, especially of the Renaissance or 20th century', 'Edith Piaf made the chanson into national heritage.'),
  Word('music', 'cantata', 'n.', 'A short vocal work with instrumental accompaniment', 'Bach wrote a new cantata for nearly every Sunday.'),
  Word('music', 'oratorio', 'n.', 'A large religious work for soloists, choir, and orchestra', 'Handel\'s Messiah is the most beloved oratorio in English.'),
  Word('music', 'passion', 'n.', 'A musical setting of the suffering of Christ', 'Bach\'s St. Matthew Passion takes three hours to perform.'),
  Word('music', 'magnificat', 'n.', 'A setting of Mary\'s song of praise', 'Bach\'s Magnificat opens with trumpets blazing.'),
  Word('music', 'te deum', 'n.', 'A setting of an early Christian hymn of praise', 'A Te Deum often marks a public celebration.'),
  Word('music', 'partita', 'n.', 'A baroque suite of stylized dance movements', 'Bach\'s violin partitas are a Mount Everest for any soloist.'),
  Word('music', 'suite', 'n.', 'A multi-movement work, often built from dances', 'The orchestral suite included a stately sarabande.'),
  Word('music', 'sarabande', 'n.', 'A slow baroque dance in triple meter', 'A sarabande leans heavily on the second beat.'),
  Word('music', 'gigue', 'n.', 'A lively baroque dance in compound meter', 'The gigue closes the suite with a sprint.'),
  Word('music', 'allemande', 'n.', 'A moderate baroque dance in duple meter', 'An allemande opens most baroque keyboard suites.'),
  Word('music', 'courante', 'n.', 'A flowing baroque dance in triple meter', 'A French courante moves in stately triplets.'),
  Word('music', 'gavotte', 'n.', 'A moderate French dance with a half-bar upbeat', 'The gavotte starts on beat three of the bar.'),
  Word('music', 'minuet', 'n.', 'A graceful triple-meter dance from the baroque court', 'A minuet often sits at the third movement of a classical symphony.'),
  Word('music', 'scherzo', 'n.', 'A fast, playful triple-meter movement', 'Beethoven replaced the minuet with a scherzo.'),
  Word('music', 'rondo', 'n.', 'A form with a recurring main theme', 'The rondo finale dances back to the theme three times.'),
  Word('music', 'sonata form', 'n.', 'A classical structure of exposition, development, and recapitulation', 'A textbook first movement uses sonata form.'),
  Word('music', 'theme', 'n.', 'A clear melodic idea developed through a piece', 'The cello introduces the second theme of the movement.'),
  Word('music', 'motif', 'n.', 'A short recurring musical idea', 'Beethoven built the entire fifth symphony from one four-note motif.'),
  Word('music', 'phrase', 'n.', 'A short, complete-feeling unit of melody', 'Each phrase ends with a tiny breath.'),
  Word('music', 'antecedent', 'n.', 'The opening phrase of a question-answer pair', 'The antecedent ends on a half cadence.'),
  Word('music', 'consequent', 'n.', 'The closing phrase that answers the antecedent', 'The consequent rounds off the period with a full cadence.'),
  Word('music', 'period', 'n.', 'A pair of phrases forming a balanced musical sentence', 'The opening period is an eight-bar question and answer.'),
  Word('music', 'cadenced', 'adj.', 'Marked by rhythmic flow or accent', 'Her cadenced phrasing made the lyrics land harder.'),
  Word('music', 'cadential', 'adj.', 'Functioning at or near a cadence', 'A cadential six-four chord delays the dominant.'),
  Word('music', 'tonicization', 'n.', 'Briefly treating a non-tonic chord as a temporary tonic', 'A quick tonicization darkened the bridge.'),
  Word('music', 'secondary dominant', 'n.', 'A dominant chord aimed at a non-tonic chord', 'A secondary dominant pushes the harmony toward the relative minor.'),
  Word('music', 'pedal point', 'n.', 'A sustained bass note held under shifting chords', 'A long pedal point built tension under the final fugue.'),
  Word('music', 'counterpoint', 'n.', 'The art of weaving independent melodic lines', 'Bach\'s counterpoint feels both inevitable and surprising.'),
  Word('music', 'invertible counterpoint', 'n.', 'Counterpoint designed to swap voices', 'Bach uses invertible counterpoint in nearly every fugue.'),
  Word('music', 'stretto', 'n.', 'Overlapping entries of a fugue subject', 'The fugue tightens into a dramatic stretto near the end.'),
  Word('music', 'subject', 'n.', 'The main theme of a fugue', 'The subject enters first in the alto voice.'),
  Word('music', 'countersubject', 'n.', 'A second melodic line that accompanies a fugue subject', 'The countersubject sneaks in beneath the answer.'),
  Word('music', 'imitation', 'n.', 'One voice copying another a beat or bar later', 'A bit of imitation tightens the texture in the middle section.'),
  Word('music', 'homophonic', 'adj.', 'Of music with one melody and chordal accompaniment', 'A homophonic hymn moves all voices together.'),
  Word('music', 'polyphonic style', 'adj.', 'Of music with several independent melodic lines', 'Renaissance motets are densely polyphonic.'),
  Word('music', 'heterophonic', 'adj.', 'Of music where voices vary the same melody simultaneously', 'A heterophonic texture is common in Middle Eastern music.'),
  Word('music', 'monophonic line', 'adj.', 'Of music with a single melodic line', 'Gregorian chant is monophonic by definition.'),
  Word('music', 'texture', 'n.', 'How the layers of sound fit together', 'The texture thins out for the slow movement.'),
  Word('music', 'voicing leading', 'n.', 'How individual voices move from chord to chord', 'Smooth voice leading hides the chord changes.'),
  Word('music', 'parallel fifths', 'n.', 'Two voices moving in fifths simultaneously', 'Classical theory frowns on parallel fifths.'),
  Word('music', 'reharm', 'n.', 'Reworking the chords under an existing melody', 'A jazz reharm turned the standard inside out.'),
  Word('music', 'changes', 'n.', 'The chord progression of a tune', 'Most jazz musicians can play rhythm changes in their sleep.'),
  Word('music', 'comping', 'n.', 'Accompanying a soloist with chords', 'The pianist\'s comping pushed the soloist forward.'),
  Word('music', 'walking bass', 'n.', 'A steady stepwise bass line moving on every beat', 'A walking bass line gave the swing tune its forward motion.'),
  Word('music', 'slap bass', 'n.', 'A funk technique of slapping and popping bass strings', 'His slap bass solo brought the whole room to its feet.'),
  Word('music', 'fingerstyle', 'n.', 'A guitar technique using the fingers instead of a pick', 'Fingerstyle players often borrow ideas from classical guitar.'),
  Word('music', 'flatpicking', 'n.', 'Playing guitar with a flat pick, often in folk styles', 'Doc Watson made flatpicking a virtuoso art.'),
  Word('music', 'tapping', 'n.', 'A guitar technique of striking strings with the fretting hand', 'Van Halen turned two-handed tapping into a rock standard.'),
  Word('music', 'bottleneck', 'n.', 'A slide used on guitar strings for swooping pitch', 'A bottleneck slide gave the blues its mournful slide.'),
  Word('music', 'hammer-on', 'n.', 'Sounding a higher note by tapping a fretting finger down', 'Add a hammer-on to make the lick smoother.'),
  Word('music', 'pull-off', 'n.', 'Sounding a lower note by snapping a finger off the string', 'A clean pull-off finishes the descending phrase.'),
  Word('music', 'palm mute', 'n.', 'Damping strings with the picking-hand palm', 'Palm mute the verses for a chunkier feel.'),
  Word('music', 'tremolo picking', 'n.', 'Picking a single note rapidly back and forth', 'Surf guitarists love tremolo picking for that twangy buzz.'),
  Word('music', 'bowing', 'n.', 'The art and technique of using a bow on strings', 'Her bowing made the runs sound effortless.'),
  Word('music', 'spiccato', 'n.', 'A light, bouncing bow stroke on a string instrument', 'Use spiccato for the dancing eighth notes.'),
  Word('music', 'martele', 'n.', 'A sharply attacked detached bow stroke', 'Hit each note with a clean martele.'),
  Word('music', 'sul ponticello', 'n.', 'Playing close to the bridge for a glassy tone', 'Sul ponticello gives the passage a haunted edge.'),
  Word('music', 'sul tasto', 'n.', 'Playing over the fingerboard for a soft tone', 'A sul tasto effect mutes the violins beautifully.'),
  Word('music', 'col legno', 'n.', 'Striking the strings with the wood of the bow', 'Col legno taps add a percussive crackle to the section.'),
  Word('music', 'double stop', 'n.', 'Playing two notes at once on a string instrument', 'A double stop gives the violin a richer sound.'),
  Word('music', 'harmonic', 'n.', 'A pure overtone produced by lightly touching a string', 'A glassy harmonic ended the cello phrase.'),
  Word('music', 'overtones', 'n.', 'Pitches above a fundamental that color a sound', 'Rich overtones make a Steinway sound different from an upright.'),
  Word('music', 'partial', 'n.', 'A single component of an overtone series', 'The fifth partial is roughly a major third above the third octave.'),
  Word('music', 'fundamental', 'n.', 'The lowest pitch component of a note', 'A subwoofer reproduces the fundamental of low notes.'),
  Word('music', 'formant', 'n.', 'A resonance that shapes the character of a sound or vowel', 'Vocal formants tell your ear which vowel is being sung.'),
  Word('music', 'resonance', 'n.', 'The amplifying response of a body or space to certain frequencies', 'The hall\'s natural resonance flatters string quartets.'),
  Word('music', 'attack', 'n.', 'The way a note begins in time', 'Plucked instruments have a quick attack.'),
  Word('music', 'sustain', 'n.', 'How long a note holds at full volume', 'A piano has a long sustain compared to a harpsichord.'),
  Word('music', 'decay', 'n.', 'How a note fades after the attack', 'Adjust the decay to fit the tempo of the song.'),
  Word('music', 'release', 'n.', 'How a note ends after the key or finger lifts', 'A short release keeps the pluck tight.'),
  Word('music', 'noise floor', 'n.', 'The background level of unwanted sound', 'A high noise floor ruined the quiet take.'),
  Word('music', 'gain staging', 'n.', 'Setting levels through a signal chain', 'Good gain staging keeps each stage clean and headroom-rich.'),
  Word('music', 'headroom', 'n.', 'How much louder a signal can get before clipping', 'Leave a few dB of headroom for the mastering engineer.'),
  Word('music', 'mix bus', 'n.', 'The combined output channel of a mix', 'A gentle compressor on the mix bus glued the song together.'),
  Word('music', 'mix down', 'v.', 'To combine multitrack recordings into a final mix', 'They\'ll mix down the album over the next two weeks.'),
  Word('music', 'overdub', 'n.', 'A part recorded over an existing take', 'She added a tambourine overdub on the second chorus.'),
  Word('music', 'punch in', 'v.', 'To re-record a small section over an existing take', 'Let\'s punch in just the second verse vocal.'),
  Word('music', 'tracking', 'n.', 'The phase of recording instrumental and vocal parts', 'They spent three days tracking drums for the album.'),
  Word('music', 'click track', 'n.', 'A metronome played in headphones during recording', 'The drummer hated playing to a click track at first.'),
  Word('music', 'pre-roll', 'n.', 'A count-in before recording begins', 'Give me two bars of pre-roll before the take.'),
  Word('music', 'multitrack', 'n.', 'A recording with multiple independent layers', 'A modern multitrack can hold hundreds of channels.'),
  Word('music', 'stem', 'n.', 'A submix of related tracks within a song', 'They sent over the vocal stem for a remix.'),
  Word('music', 'bounce', 'v.', 'To render a session down to a single audio file', 'Bounce the mix and email it to the band tonight.'),
  Word('music', 'render', 'v.', 'To process and export a final audio file', 'Render the master at 24-bit, 96 kHz.'),
  Word('music', 'dither', 'n.', 'Low-level noise added when reducing bit depth', 'Apply dither only at the very last stage.'),
  Word('music', 'normalize', 'v.', 'To raise a track to a target peak level', 'Normalize the file before sending it to the mastering engineer.'),
  Word('music', 'lufs', 'n.', 'A loudness unit used to measure perceived volume', 'Streaming platforms target around minus fourteen lufs.'),
  Word('music', 'phantom power', 'n.', 'Power sent through a cable to condenser microphones', 'Engage phantom power before the singer steps up.'),
  Word('music', 'condenser', 'n.', 'A sensitive studio microphone needing phantom power', 'A large-diaphragm condenser captured every breath.'),
  Word('music', 'dynamic mic', 'n.', 'A rugged microphone good for loud sources', 'A dynamic mic handles the guitar amp without distorting.'),
  Word('music', 'ribbon mic', 'n.', 'A microphone with a thin metal ribbon for a warm sound', 'A ribbon mic flattered the brass section nicely.'),
  Word('music', 'cardioid', 'adj.', 'Of a microphone pattern that rejects sound from behind', 'Use a cardioid mic to reject the bleed from the drums.'),
  Word('music', 'omnidirectional', 'adj.', 'Picking up sound equally from every direction', 'An omnidirectional mic captured the room nicely.'),
  Word('music', 'figure-eight', 'adj.', 'Of a microphone pattern that picks up front and back', 'A figure-eight ribbon gave the duet a great stereo image.'),
  Word('music', 'room tone', 'n.', 'The natural sound of an empty space', 'Capture a minute of room tone before tearing down.'),
  Word('music', 'reverb tail', 'n.', 'The fading echo of a reverb effect', 'Cut the reverb tail before the next downbeat.'),
  Word('music', 'pre-delay', 'n.', 'A short gap before reverb kicks in', 'A bit of pre-delay keeps the vocal clear.'),
  Word('music', 'shimmer', 'n.', 'A reverb effect with octave-pitched feedback', 'A shimmer reverb gave the pad an angelic glow.'),
  Word('music', 'plate', 'n.', 'A classic reverb made by vibrating a metal plate', 'A plate reverb adds a vintage smear to vocals.'),
  Word('music', 'spring reverb', 'n.', 'A reverb built around vibrating coiled springs', 'Surf guitarists swear by the splash of spring reverb.'),
  Word('music', 'convolution', 'n.', 'A digital reverb based on real-world impulse responses', 'A convolution reverb can drop you inside Carnegie Hall.'),
  Word('music', 'autotune', 'n.', 'A pitch-correction tool widely used on vocals', 'A subtle autotune kept the vocal in tune without erasing character.'),
  Word('music', 'pitch shift', 'n.', 'A process that raises or lowers pitch without changing speed', 'A pitch shift dropped the chorus down an octave.'),
  Word('music', 'time stretch', 'n.', 'A process that changes length without changing pitch', 'Time stretch the drum loop to fit the new tempo.'),
  Word('music', 'vocoder', 'n.', 'A device that imposes a voice on a synthesizer', 'A vocoder turned the spoken intro into robotic harmony.'),
  Word('music', 'talkbox', 'n.', 'A pedal that shapes a guitar tone through a singer\'s mouth', 'Peter Frampton made the talkbox famous in the 70s.'),
  Word('music', 'looping', 'n.', 'Building a performance by stacking live recorded layers', 'Live looping let her sound like a whole choir.'),
  Word('music', 'turntablism', 'n.', 'The art of manipulating vinyl as an instrument', 'Turntablism grew up alongside early hip-hop.'),
  Word('music', 'scratching', 'n.', 'Moving a record back and forth under the needle', 'A quick scratch fill led into the verse.'),
  Word('music', 'crossfader', 'n.', 'A slider that blends between two channels on a DJ mixer', 'Slam the crossfader for a chirp scratch.'),
  Word('music', 'beatmatching', 'n.', 'Aligning the tempos of two records for mixing', 'Good beatmatching is invisible to the dance floor.'),
  Word('music', 'cueing', 'n.', 'Previewing the next track in headphones', 'Quick cueing lets the DJ find the drop on the fly.'),
  Word('music', 'mashup creation', 'adj.', 'Combining elements from multiple songs into one', 'The mashup creation crowd loves a clever a cappella over a fresh beat.'),
  Word('music', 'flip', 'n.', 'A creative reworking of a sampled song', 'That bassline flip turned the old soul tune into a banger.'),
  Word('music', 'chop', 'v.', 'To slice a sample into rearranged pieces', 'Chop the vocal hook and rebuild it on the pads.'),
  Word('music', 'loop point', 'n.', 'The spot where audio repeats seamlessly', 'Set the loop point on the upbeat to avoid a click.'),
  Word('music', 'metronomic', 'adj.', 'Steady and mechanical, like a metronome', 'Her timing is metronomic from start to finish.'),
  Word('music', 'rushing', 'n.', 'Speeding up a tempo accidentally', 'The drummer is rushing into the chorus.'),
  Word('music', 'dragging', 'n.', 'Slowing a tempo accidentally', 'The band is dragging by the end of the bridge.'),
  Word('music', 'pocket groove', 'adj.', 'Of a rhythm sitting deeply in the time feel', 'The bassist and drummer locked into a deep pocket groove.'),
  Word('music', 'feel', 'n.', 'The intangible character of a rhythmic performance', 'You can\'t quantize feel onto a grid.'),
  Word('music', 'shuffle feel', 'n.', 'A swung rhythmic feel rooted in blues', 'Set the shuffle feel to about sixty-five percent.'),
  Word('music', 'straight eighths', 'n.', 'Even subdivisions without swing', 'Rock tunes usually call for straight eighths.'),
  Word('music', 'triplet', 'n.', 'Three notes played in the space of two', 'Sneak a triplet fill in before the final chorus.'),
  Word('music', 'sextuplet', 'n.', 'Six notes played in the space of four', 'A flashing sextuplet run closed the solo.'),
  Word('music', 'polymeter', 'n.', 'Two meters happening at the same time', 'A polymeter of three over four threads through the piece.'),
  Word('music', 'odd meter', 'n.', 'A time signature with an irregular grouping', 'Take Five is the textbook odd meter tune.'),
  Word('music', 'clave', 'n.', 'A foundational rhythmic pattern in Afro-Cuban music', 'Every part has to lock to the clave.'),
  Word('music', 'tresillo', 'n.', 'A common Afro-Cuban three-stroke rhythm', 'A tresillo pattern underpins half of modern pop.'),
  Word('music', 'son clave', 'n.', 'A specific Cuban version of the clave pattern', 'The pianist anchored everything to the son clave.'),
  Word('music', 'rumba clave', 'n.', 'A clave variant with a delayed third stroke', 'Switch to rumba clave for the next chorus.'),
  Word('music', 'montuno', 'n.', 'A repeating syncopated piano figure in salsa', 'The pianist locked into a hypnotic montuno.'),
  Word('music', 'tumbao', 'n.', 'A repeating Afro-Cuban bass or conga pattern', 'The bassist drove the song with a steady tumbao.'),
  Word('music', 'compositional', 'adj.', 'Relating to the craft of writing music', 'Her compositional voice is unmistakable.'),
  Word('music', 'orchestration', 'n.', 'Assigning notes to specific instruments', 'Ravel\'s orchestration of Pictures at an Exhibition is dazzling.'),
  Word('music', 'arrangement', 'n.', 'A version of a song shaped for a particular ensemble', 'The big band arrangement was tighter than the original.'),
  Word('music', 'transcription', 'n.', 'A written version of a heard performance', 'A transcription of Coltrane\'s solo took her two weeks.'),
  Word('music', 'sight-reading', 'n.', 'Performing music at first encounter from notation', 'Session players have to be killer sight-readers.'),
  Word('music', 'ear training', 'n.', 'Developing the ability to identify pitches and intervals', 'Daily ear training will sharpen your improvising.'),
  Word('music', 'solfege', 'n.', 'A system of syllables for singing pitches', 'Solfege made the intervals click for her.'),
  Word('music', 'movable do', 'n.', 'A solfege system where do shifts with the key', 'Movable do is great for hearing function within a key.'),
  Word('music', 'fixed do', 'n.', 'A solfege system where do always names C', 'European conservatories often teach fixed do.'),
  Word('music', 'transposing', 'adj.', 'Of an instrument that sounds at a different pitch than written', 'The B-flat clarinet is a transposing instrument.'),
  Word('music', 'concert pitch', 'n.', 'The actual sounding pitch of a note', 'Tell me the chord in concert pitch, not transposed.'),
  Word('music', 'a440', 'n.', 'The reference pitch for tuning, A above middle C at 440 Hz', 'Most modern orchestras tune to a440 or a touch higher.'),
  Word('music', 'temperament', 'n.', 'A system of tuning intervals across all keys', 'Equal temperament makes every key playable but slightly impure.'),
  Word('music', 'just intonation', 'n.', 'Tuning based on pure whole-number ratios', 'Just intonation glows on a sustained chord.'),
  Word('music', 'cents', 'n.', 'Hundredths of a semitone used to measure tuning', 'The note was twenty cents flat.'),
  Word('music', 'pitch wheel', 'n.', 'A synth control for bending notes up or down', 'Use the pitch wheel for a vocal-like scoop.'),
  Word('music', 'mod wheel', 'n.', 'A synth control that adds expression like vibrato', 'Push the mod wheel for a bit of breath on the flute patch.'),
  Word('music', 'aftertouch', 'n.', 'A keyboard\'s response to pressure after a key is down', 'Aftertouch opens the filter as you lean in.'),
  Word('music', 'velocity', 'n.', 'How hard a note is struck on a keyboard', 'A high velocity triggers a brighter sample.'),
  Word('music', 'voice leading', 'n.', 'The smooth movement of independent melodic lines', 'Tight voice leading makes the chorale flow.'),
  Word('music', 'genre-bending', 'adj.', 'Crossing or mixing styles in unexpected ways', 'Her genre-bending album felt like five records in one.'),
  Word('music', 'crossover', 'n.', 'A track or artist appealing across genres', 'The crossover hit reached pop and country charts at once.'),
  Word('music', 'frontwoman', 'n.', 'A female lead performer in a band', 'The frontwoman commanded the festival stage.'),
  Word('music', 'sideman', 'n.', 'A supporting musician who plays in others\' bands', 'He spent decades as a respected sideman before going solo.'),
  Word('music', 'roadie', 'n.', 'A crew member who handles touring gear', 'A roadie wheeled the amps back into the truck.'),
  Word('music', 'merch', 'n.', 'Branded items a band sells at shows', 'They paid the rent with merch sales on the last tour.'),
  Word('music', 'rider', 'n.', 'A contract clause listing artists\' requirements', 'The rider asked for warm tea and clean towels.'),
  Word('music', 'soundcheck', 'n.', 'A pre-show test of instruments and the PA', 'A long soundcheck saved them from feedback issues later.'),
  Word('music', 'monitor', 'n.', 'A stage speaker letting performers hear themselves', 'Turn the vocal up in my monitor.'),
  Word('music', 'in-ears', 'n.', 'Headphone-style stage monitors worn by performers', 'In-ears protect a singer\'s hearing on tour.'),
  Word('music', 'foh', 'n.', 'The front-of-house mixing position at a show', 'The foh engineer dialed in the kick from across the room.'),
  Word('music', 'lighting cue', 'n.', 'A scripted change of stage lights during a song', 'A lighting cue hit perfectly on the final chorus.'),
  Word('music', 'setlist', 'n.', 'A planned order of songs for a show', 'They tweaked the setlist after the first song flopped.'),
  Word('music', 'rehearsal', 'n.', 'A practice session preparing for a performance', 'Tomorrow\'s rehearsal is at the drummer\'s loft.'),
  Word('music', 'workshop', 'n.', 'An exploratory development session for new material', 'They workshopped the song for weeks before recording.'),
  Word('music', 'session musician', 'n.', 'A pro hired to play on recordings', 'Top session musicians can sight-read anything.'),
  Word('music', 'royalty', 'n.', 'A payment to a rights holder when music is used', 'Streaming royalties come in pennies per play.'),
  Word('music', 'mechanical', 'n.', 'A royalty earned when music is reproduced', 'Mechanical royalties go to songwriters.'),
  Word('music', 'sync license', 'n.', 'Permission to use a song with visual media', 'A sync license in a hit show can change a writer\'s life.'),
  Word('music', 'publishing', 'n.', 'The business of administering songwriting rights', 'Strong publishing deals can outearn a record deal.'),
  Word('music', 'a&r', 'n.', 'The label staff who scout and develop artists', 'An a&r rep flew out to see them headline.'),
  Word('music', 'demo', 'n.', 'A rough recording made to pitch a song', 'They sent the demo to every label in town.'),
  Word('music', 'press release', 'n.', 'A document announcing a release or tour', 'The press release leaked a day early.'),
  Word('music', 'streaming', 'n.', 'On-demand online playback of music', 'Streaming changed how every band thinks about singles.'),
  Word('music', 'vinyl', 'n.', 'Records pressed on grooved discs', 'Vinyl sales have outpaced CDs for years.'),
];
