import 'words_data.dart';

const kMusicExtras2 = <Word>[
  Word('music', 'antiphony', 'n.', 'Alternating singing or playing between two groups', 'The choir split into two halves to perform the ancient hymn in antiphony.'),
  Word('music', 'plainsong', 'n.', 'Unaccompanied medieval church melody in free rhythm', 'The monks chanted the plainsong as candlelight flickered across the nave.'),
  Word('music', 'descant', 'n.', 'A high melody sung above the main tune', 'A soprano floated a delicate descant over the final verse of the carol.'),
  Word('music', 'roulade', 'n.', 'A florid run of notes sung on one syllable', 'The diva tossed off a dazzling roulade at the climax of the aria.'),
  Word('music', 'portato', 'n.', 'Playing notes slightly detached yet smoothly connected', 'The cellist used portato to give the phrase a gentle pulsing feel.'),
  Word('music', 'detache', 'n.', 'A broad, separate bow stroke for each note', 'She practiced the scale with a firm detache to even out her tone.'),
  Word('music', 'ricochet', 'n.', 'A bouncing bow stroke that produces rapid notes', 'The violinist dazzled the crowd with a flurry of ricochet bowing.'),
  Word('music', 'sautille', 'n.', 'A fast bouncing bow stroke played at the middle of the bow', 'The lively passage demanded a crisp sautille from every string player.'),
  Word('music', 'flautando', 'adv.', 'Bowing lightly near the fingerboard for a flute-like tone', 'The composer marked the passage flautando to evoke a misty dawn.'),
  Word('music', 'tasto', 'n.', 'A direction to bow over the fingerboard for a soft sound', 'Playing sul tasto requires the bow to drift toward the fingerboard for tasto color.'),
  Word('music', 'ponticello', 'n.', 'The bridge of a string instrument, near which bowing gives a glassy tone', 'Bowing close to the ponticello produced an eerie, metallic shimmer.'),
  Word('music', 'arco', 'adv.', 'A direction to resume bowing after plucking', 'After the pizzicato section the score returns to arco for the broad melody.'),
  Word('music', 'sordino', 'n.', 'A mute placed on a string or brass instrument', 'The violins played con sordino, each fitting a tiny sordino on the bridge.'),
  Word('music', 'embouchure', 'n.', 'The way a player shapes the lips on a wind instrument', 'Years of practice gave the flutist a relaxed, reliable embouchure.'),
  Word('music', 'tonguing', 'n.', 'Using the tongue to articulate notes on a wind instrument', 'Clean double tonguing let the clarinetist nail the rapid sixteenths.'),
  Word('music', 'fingering', 'n.', 'The choice of which fingers to use for each note', 'The editor printed a suggested fingering above the trickiest run.'),
  Word('music', 'sostenuto', 'adj.', 'Played in a sustained, drawn-out manner', 'The pianist held the sostenuto chords until they nearly faded.'),
  Word('music', 'marcato', 'adj.', 'Played with marked, emphatic accents', 'The brass attacked the theme marcato, each note punched and proud.'),
  Word('music', 'pesante', 'adj.', 'Played heavily and with weight', 'The march grew pesante as the full orchestra leaned into the beat.'),
  Word('music', 'leggiero', 'adj.', 'Played lightly and nimbly', 'Her fingers danced leggiero across the upper keys of the piano.'),
  Word('music', 'dolce', 'adj.', 'Played sweetly and softly', 'The oboe entered dolce, like a whispered secret over the strings.'),
  Word('music', 'cantabile', 'adj.', 'Played in a smooth, singing style', 'He shaped the cantabile line as if the cello were truly breathing.'),
  Word('music', 'grazioso', 'adj.', 'Played gracefully and elegantly', 'The minuet unfolded grazioso, every phrase poised and unhurried.'),
  Word('music', 'agitato', 'adj.', 'Played in an agitated, restless manner', 'The accompaniment turned agitato as the drama on stage intensified.'),
  Word('music', 'maestoso', 'adj.', 'Played majestically and with dignity', 'The hymn\'s final verse swelled maestoso beneath the organ.'),
  Word('music', 'giocoso', 'adj.', 'Played in a playful, jolly manner', 'The finale bounced along giocoso, drawing smiles from the audience.'),
  Word('music', 'espressivo', 'adv.', 'Played with heightened expression and feeling', 'She marked the solo espressivo and let the melody ache.'),
  Word('music', 'risoluto', 'adj.', 'Played in a resolute, determined manner', 'The trumpet announced the theme risoluto, bold and unwavering.'),
  Word('music', 'tranquillo', 'adj.', 'Played in a calm, tranquil manner', 'After the storm of sound the strings settled into a tranquillo close.'),
  Word('music', 'morendo', 'adv.', 'Gradually dying away in volume and tempo', 'The piece ended morendo, the last chord barely a breath.'),
  Word('music', 'smorzando', 'adv.', 'Dying away and growing softer', 'The cellos played smorzando until the note dissolved into silence.'),
  Word('music', 'calando', 'adv.', 'Growing softer and slower at once', 'The lullaby drifted calando as the infant finally slept.'),
  Word('music', 'allargando', 'adv.', 'Broadening by slowing and growing louder', 'The brass came in allargando to crown the symphony\'s last bars.'),
  Word('music', 'stringendo', 'adv.', 'Pressing forward and quickening the tempo', 'The chase music went stringendo, the pulse racing toward the climax.'),
  Word('music', 'affrettando', 'adv.', 'Hurrying the tempo with growing urgency', 'The conductor urged the players affrettando into the frantic coda.'),
  Word('music', 'ritenuto', 'adv.', 'Holding back the tempo suddenly', 'A brief ritenuto let the soloist savor the high note.'),
  Word('music', 'meno', 'adv.', 'A direction meaning less, as in less fast', 'The middle section is marked meno mosso for a gentler flow.'),
  Word('music', 'mosso', 'adj.', 'Moved, lively, with motion in the tempo', 'The dance grew piu mosso, sweeping the couples faster around the floor.'),
  Word('music', 'andantino', 'n.', 'A tempo slightly faster than a walking pace', 'The second movement, an easy andantino, gave the listeners a rest.'),
  Word('music', 'larghetto', 'n.', 'A tempo slightly faster than very slow', 'The larghetto theme breathed slowly beneath the soloist.'),
  Word('music', 'grave', 'n.', 'A very slow and solemn tempo', 'The funeral march opened grave, each beat weighted with grief.'),
  Word('music', 'vivace', 'adj.', 'Played in a bright, lively tempo', 'The closing rondo sparkled vivace from the first bar.'),
  Word('music', 'presto', 'adj.', 'Played at a very fast tempo', 'The pianist tore through the presto finale to thunderous applause.'),
  Word('music', 'prestissimo', 'adj.', 'Played at the fastest possible tempo', 'The encore was a prestissimo blur of cascading notes.'),
  Word('music', 'larghissimo', 'n.', 'The slowest of the slow tempos', 'The meditation unfolded larghissimo, time itself seeming to stretch.'),
  Word('music', 'doloroso', 'adj.', 'Played in a sorrowful, grieving manner', 'The viola sang doloroso, mourning over the muted accompaniment.'),
  Word('music', 'lacrimoso', 'adj.', 'Played in a tearful, mournful manner', 'The requiem turned lacrimoso, weeping in long descending lines.'),
  Word('music', 'scherzando', 'adv.', 'Played in a light, joking manner', 'The woodwinds tossed the tune around scherzando, almost teasing.'),
  Word('music', 'capriccioso', 'adj.', 'Played in a whimsical, capricious manner', 'The solo darted capriccioso between moods within a single page.'),
  Word('music', 'brillante', 'adj.', 'Played in a brilliant, showy manner', 'The variations grew ever more brillante, sparkling with virtuosity.'),
  Word('music', 'bravura', 'n.', 'A display of dazzling technical skill', 'The cadenza was pure bravura, daring and full of fire.'),
  Word('music', 'ossia', 'n.', 'An alternative, often easier, version of a passage', 'She chose the ossia to make the leap less risky in performance.'),
  Word('music', 'volta', 'n.', 'A bracketed ending marking a repeat alternative', 'On the repeat they skipped the first volta and took the second.'),
  Word('music', 'incipit', 'n.', 'The opening notes or words that identify a piece', 'Scholars catalog medieval songs by their Latin incipit.'),
  Word('music', 'ritornello', 'n.', 'A recurring instrumental refrain in a larger work', 'The orchestra returned to the cheerful ritornello between each solo.'),
  Word('music', 'divisi', 'adj.', 'Direction for a section to split into separate parts', 'The violins went divisi, half soaring high while half held the chord.'),
  Word('music', 'unison', 'n.', 'Two or more parts sounding the same pitch', 'The whole choir landed on the final note in perfect unison.'),
  Word('music', 'doubling', 'n.', 'Reinforcing a line by playing it on another instrument', 'The flute doubling the violins gave the melody a silvery edge.'),
  Word('music', 'codetta', 'n.', 'A short closing passage rounding off a section', 'A brief codetta tied up the exposition before the development began.'),
  Word('music', 'vamp', 'n.', 'A short repeated figure used to fill time', 'The band held a vamp while the singer waited for her cue.'),
  Word('music', 'turnaround', 'n.', 'A chord sequence leading back to the start of a progression', 'The jazz pianist sneaked in a clever turnaround before the next chorus.'),
  Word('music', 'breakdown', 'n.', 'A stripped-back, intense section of a song', 'The crowd surged when the metal track dropped into its breakdown.'),
  Word('music', 'outro', 'n.', 'The concluding section of a song', 'The track faded out over a dreamy four-bar outro.'),
  Word('music', 'intro', 'n.', 'The opening section that begins a song', 'A lone guitar riff served as the intro before the band kicked in.'),
  Word('music', 'fill', 'n.', 'A short flourish filling a gap between phrases', 'The drummer dropped a quick fill before the chorus exploded.'),
  Word('music', 'lead-in', 'n.', 'A few notes that set up the first downbeat', 'A two-note lead-in pulled the band into the opening bar.'),
  Word('music', 'pickup', 'n.', 'A note or notes before the first full measure', 'The melody starts on a pickup, sneaking in before the downbeat.'),
  Word('music', 'downbeat', 'n.', 'The strong first beat of a measure', 'The conductor\'s arm fell sharply to signal the downbeat.'),
  Word('music', 'backbeat', 'n.', 'The strong accent on beats two and four', 'The snare cracked on the backbeat, driving the whole groove.'),
  Word('music', 'offbeat', 'n.', 'A weak beat or the space between main beats', 'The reggae guitar chops fall squarely on the offbeat.'),
  Word('music', 'anacrusis', 'n.', 'A note or notes leading into the first downbeat', 'The hymn opens with a gentle anacrusis on the word amen.'),
  Word('music', 'cross-rhythm', 'n.', 'Conflicting rhythms layered against each other', 'The drummers wove a dizzying cross-rhythm over the steady pulse.'),
  Word('music', 'tuplet', 'n.', 'A grouping of notes that divides a beat irregularly', 'A nested tuplet made the passage notoriously hard to count.'),
  Word('music', 'quintuplet', 'n.', 'A group of five notes played in one beat', 'The harpist sprinkled a glittering quintuplet across the chord.'),
  Word('music', 'duplet', 'n.', 'Two notes played in the time of three', 'A duplet smoothed the swirling passage into an even pair.'),
  Word('music', 'syncopate', 'v.', 'To stress beats that are normally weak', 'The pianist loved to syncopate the melody to keep it bouncing.'),
  Word('music', 'transpose', 'v.', 'To move music to a different key', 'He had to transpose the song down a third for the singer.'),
  Word('music', 'harmonize', 'v.', 'To add notes that complement a melody', 'The backing singers harmonize beautifully on the final chorus.'),
  Word('music', 'orchestrate', 'v.', 'To arrange music for an orchestra', 'It took weeks to orchestrate the demo for full strings and brass.'),
  Word('music', 'improvise', 'v.', 'To create music spontaneously while performing', 'The saxophonist began to improvise over the simple two-chord vamp.'),
  Word('music', 'noodle', 'v.', 'To play casual, aimless musical phrases', 'He liked to noodle on the guitar while waiting for the others.'),
  Word('music', 'busk', 'v.', 'To perform music in a public place for tips', 'They would busk outside the station every Friday evening.'),
  Word('music', 'conduct', 'v.', 'To direct an ensemble\'s performance', 'She raised the baton to conduct the overture from memory.'),
  Word('music', 'arpeggiate', 'v.', 'To play the notes of a chord one after another', 'The harpist would arpeggiate each chord to make it shimmer.'),
  Word('music', 'detune', 'v.', 'To deliberately move a pitch away from true', 'The producer chose to detune the synth for a woozy texture.'),
  Word('music', 'comp', 'v.', 'To accompany a soloist with chords', 'The pianist would comp lightly while the trumpet took the lead.'),
  Word('music', 'segue', 'v.', 'To move smoothly from one piece into the next', 'The DJ let one track segue seamlessly into another.'),
  Word('music', 'attenuate', 'v.', 'To reduce the strength of a signal or frequency', 'The engineer used the filter to attenuate the harsh high end.'),
  Word('music', 'consonant', 'adj.', 'Describing harmonious, restful combinations of notes', 'The final chord was warmly consonant, releasing all the tension.'),
  Word('music', 'dissonant', 'adj.', 'Describing clashing, unstable combinations of notes', 'The dissonant cluster set everyone\'s teeth on edge.'),
  Word('music', 'syncopated', 'adj.', 'Marked by accents on normally weak beats', 'The funky bass line was thoroughly syncopated.'),
  Word('music', 'percussive', 'adj.', 'Sounding sharp and rhythmic like a struck drum', 'The pianist\'s percussive attack drove the dance number forward.'),
  Word('music', 'melodic', 'adj.', 'Rich in tuneful, singable melody', 'The album was praised for its melodic, hummable choruses.'),
  Word('music', 'rhythmic', 'adj.', 'Strongly governed by rhythm and pulse', 'The track was relentlessly rhythmic, built for the dance floor.'),
  Word('music', 'harmonious', 'adj.', 'Pleasingly combined in sound', 'The two voices blended into a harmonious whole.'),
  Word('music', 'contrapuntal', 'adj.', 'Relating to interwoven independent melodies', 'Bach\'s contrapuntal writing keeps every voice singing on its own.'),
  Word('music', 'syllabic', 'adj.', 'Setting one note to each syllable of text', 'The folk song\'s syllabic style made the lyrics easy to follow.'),
  Word('music', 'strophic', 'adj.', 'Repeating the same music for each verse', 'Most hymns are strophic, reusing one tune for every stanza.'),
  Word('music', 'tonal', 'adj.', 'Organized around a central key or tonic', 'The symphony stayed firmly tonal, anchored in D major.'),
  Word('music', 'passaggio', 'n.', 'The transition zone between vocal registers', 'The teacher helped her smooth the break in her passaggio.'),
  Word('music', 'glottal', 'adj.', 'Relating to the sharp closure of the vocal cords', 'He added a glottal attack to punch the start of the phrase.'),
  Word('music', 'diction', 'n.', 'The clarity with which words are sung or spoken', 'Her crisp diction let every lyric reach the back row.'),
  Word('music', 'projection', 'n.', 'The ability to carry sound to a distant listener', 'Years of training gave the tenor effortless projection.'),
  Word('music', 'resonate', 'v.', 'To vibrate sympathetically and amplify sound', 'The wooden body lets the strings resonate richly.'),
  Word('music', 'overtone', 'n.', 'A higher frequency sounding above a fundamental pitch', 'A faint overtone shimmered above the bowed string.'),
  Word('music', 'sympathetic', 'adj.', 'Describing strings that vibrate in response to others', 'The sitar\'s sympathetic strings shimmer when the main string is plucked.'),
  Word('music', 'fret', 'n.', 'A raised strip on a fingerboard marking pitches', 'He slid his finger up to the seventh fret for the high note.'),
  Word('music', 'nut', 'n.', 'The ridge guiding strings at the top of a neck', 'A worn nut was causing the open string to buzz.'),
  Word('music', 'soundboard', 'n.', 'The vibrating surface that amplifies an instrument', 'The piano\'s spruce soundboard gives it a warm, full voice.'),
  Word('music', 'reed', 'n.', 'A thin strip that vibrates to make a wind instrument sound', 'The oboist soaked a fresh reed before the rehearsal.'),
  Word('music', 'mouthpiece', 'n.', 'The part of a wind instrument placed against the lips', 'He swapped to a wider mouthpiece for a darker trumpet sound.'),
  Word('music', 'valve', 'n.', 'A button that redirects air to change pitch on brass', 'A sticky valve made the third note sputter.'),
  Word('music', 'pedal', 'n.', 'A foot-operated lever that alters an instrument\'s sound', 'She pressed the sustain pedal to let the chord ring out.'),
  Word('music', 'damper', 'n.', 'A felt pad that stops a piano string from sounding', 'Lifting the damper lets the note continue to ring.'),
  Word('music', 'capodastro', 'n.', 'A clamp that raises a guitar\'s pitch across all strings', 'She fitted a capodastro on the third fret to match her voice.'),
  Word('music', 'amplitude', 'n.', 'The size of a sound wave, heard as loudness', 'Turning up the gain increased the signal\'s amplitude.'),
  Word('music', 'waveform', 'n.', 'The visual shape of a sound\'s vibration', 'A square waveform gives the synth its buzzy, hollow tone.'),
  Word('music', 'timpanist', 'n.', 'A musician who plays the kettledrums', 'The timpanist retuned between movements with a quick tap.'),
  Word('music', 'percussionist', 'n.', 'A musician who plays drums and struck instruments', 'The percussionist juggled four instruments during the finale.'),
  Word('music', 'accompanist', 'n.', 'A musician who supports a soloist on piano', 'A sensitive accompanist follows the singer\'s every breath.'),
  Word('music', 'soloist', 'n.', 'The featured performer in a piece', 'The young soloist drew a standing ovation for the concerto.'),
  Word('music', 'chorister', 'n.', 'A singer in a choir', 'Each chorister wore a crimson robe for the festival.'),
  Word('music', 'composition', 'n.', 'A piece of music that has been written', 'Her latest composition blends strings with electronic textures.'),
  Word('music', 'movement', 'n.', 'A self-contained section of a larger work', 'The slow movement of the symphony moved many to tears.'),
  Word('music', 'medley', 'n.', 'A piece stringing several tunes together', 'The band closed with a medley of their early hits.'),
];
