import 'words_data.dart';

const kPhilosophyExtras2 = <Word>[
  Word('philosophy', 'virtue', 'n.', 'A trait of moral excellence in a person\'s character', 'Courage was counted among the cardinal virtues.'),
  Word('philosophy', 'vice', 'n.', 'A morally bad habit or character trait', 'For Aristotle, each vice was an excess or deficiency.'),
  Word('philosophy', 'cognition', 'n.', 'The mental process of acquiring knowledge', 'Cognition involves perception, memory, and judgment.'),
  Word('philosophy', 'falsity', 'n.', 'The quality of being contrary to fact', 'A valid argument can still rest on falsity.'),
  Word('philosophy', 'validity', 'n.', 'The property of an argument whose conclusion follows from its premises', 'Validity concerns form, not the truth of premises.'),
  Word('philosophy', 'soundness', 'n.', 'The quality of an argument that is valid with true premises', 'Soundness guarantees a true conclusion.'),
  Word('philosophy', 'premise', 'n.', 'A statement offered as support for a conclusion', 'The argument fails because its premise is false.'),
  Word('philosophy', 'conclusion', 'n.', 'The statement an argument aims to establish', 'The conclusion does not follow from those premises.'),
  Word('philosophy', 'proposition', 'n.', 'A statement that can be true or false', 'A proposition is the content expressed by a sentence.'),
  Word('philosophy', 'predicate', 'n.', 'A term that ascribes a property to a subject', 'In logic, the predicate is applied to a subject.'),
  Word('philosophy', 'quantifier', 'n.', 'A logical term specifying how many things a claim concerns', 'The quantifier \'all\' makes the statement universal.'),
  Word('philosophy', 'negation', 'n.', 'The logical operation of denying a proposition', 'The negation of a true statement is false.'),
  Word('philosophy', 'conjunction', 'n.', 'A compound statement true only when both parts are true', 'A conjunction joins two claims with \'and\'.'),
  Word('philosophy', 'disjunction', 'n.', 'A compound statement true when at least one part is true', 'The disjunction holds if either option obtains.'),
  Word('philosophy', 'implication', 'n.', 'A logical relation where one statement follows from another', 'Material implication troubles many logic students.'),
  Word('philosophy', 'inference', 'n.', 'The act of deriving a conclusion from premises', 'A faulty inference led him to the wrong belief.'),
  Word('philosophy', 'deduction', 'n.', 'Reasoning from general premises to a certain conclusion', 'Deduction guarantees its conclusion if premises hold.'),
  Word('philosophy', 'entailment', 'n.', 'The relation in which one proposition logically necessitates another', 'Entailment means the conclusion cannot be false if the premises are true.'),
  Word('philosophy', 'contradiction', 'n.', 'A pair of statements that cannot both be true', 'A contradiction signals a flaw in the reasoning.'),
  Word('philosophy', 'consistency', 'n.', 'The property of statements that can all be true together', 'Logical consistency is a minimal demand on any theory.'),
  Word('philosophy', 'coherence', 'n.', 'The mutual support of beliefs within a system', 'Coherence binds his views into a unified whole.'),
  Word('philosophy', 'argumentation', 'n.', 'The practice of giving reasons to support claims', 'Sound argumentation is the heart of philosophy.'),
  Word('philosophy', 'dialectical', 'adj.', 'Relating to reasoning through opposing arguments', 'Their dialectical exchange sharpened both positions.'),
  Word('philosophy', 'discursive', 'adj.', 'Proceeding by reasoning rather than intuition', 'Discursive thought moves step by step.'),
  Word('philosophy', 'speculative', 'adj.', 'Concerned with theory rather than practical knowledge', 'His speculative metaphysics resists empirical test.'),
  Word('philosophy', 'normative', 'adj.', 'Concerned with how things ought to be', 'Ethics is a largely normative discipline.'),
  Word('philosophy', 'descriptive', 'adj.', 'Concerned with how things actually are', 'Descriptive claims report facts without judging them.'),
  Word('philosophy', 'prescriptive', 'adj.', 'Recommending how one ought to act', 'A prescriptive rule tells us what to do.'),
  Word('philosophy', 'axiomatic', 'adj.', 'Taken as self-evidently true without proof', 'Euclid built geometry on axiomatic foundations.'),
  Word('philosophy', 'apodictic', 'adj.', 'Necessarily and demonstrably true', 'Kant called mathematical truths apodictic.'),
  Word('philosophy', 'contingency', 'n.', 'The state of being possible but not necessary', 'The contingency of the world raises the question of why it exists.'),
  Word('philosophy', 'necessity', 'n.', 'The state of being such that it could not be otherwise', 'Logical necessity admits no exceptions.'),
  Word('philosophy', 'possibility', 'n.', 'The state of being able to occur or be true', 'Modal logic studies possibility and necessity.'),
  Word('philosophy', 'actuality', 'n.', 'The state of being real rather than merely possible', 'Aristotle distinguished potentiality from actuality.'),
  Word('philosophy', 'potentiality', 'n.', 'The capacity to become something not yet actual', 'An acorn has the potentiality to become an oak.'),
  Word('philosophy', 'causation', 'n.', 'The relation between a cause and its effect', 'Hume questioned our knowledge of causation.'),
  Word('philosophy', 'causality', 'n.', 'The principle that events have causes', 'Modern science presupposes universal causality.'),
  Word('philosophy', 'temporality', 'n.', 'The condition of existing within time', 'Heidegger explored the temporality of human existence.'),
  Word('philosophy', 'spatiality', 'n.', 'The condition of existing within space', 'Kant treated spatiality as a form of intuition.'),
  Word('philosophy', 'infinitude', 'n.', 'The quality of being boundless or endless', 'The infinitude of space puzzled ancient thinkers.'),
  Word('philosophy', 'finitude', 'n.', 'The condition of being limited or bounded', 'Human finitude shapes existentialist thought.'),
  Word('philosophy', 'immortality', 'n.', 'The condition of living forever', 'Plato argued for the soul\'s immortality.'),
  Word('philosophy', 'persistence', 'n.', 'The continued existence of a thing over time', 'Persistence raises questions about change and sameness.'),
  Word('philosophy', 'individuation', 'n.', 'What makes one thing distinct from another of the same kind', 'Scholastics debated the principle of individuation.'),
  Word('philosophy', 'particularity', 'n.', 'The quality of being a specific individual thing', 'The particularity of each case resists general rules.'),
  Word('philosophy', 'universality', 'n.', 'The quality of applying to all cases', 'Kant tested maxims by their universality.'),
  Word('philosophy', 'generality', 'n.', 'The quality of covering many instances', 'Scientific laws aim at generality.'),
  Word('philosophy', 'abstraction', 'n.', 'The process of forming general ideas from particulars', 'Concepts arise through abstraction from experience.'),
  Word('philosophy', 'concept', 'n.', 'A general idea grouping similar things', 'The concept of justice underlies many disputes.'),
  Word('philosophy', 'category', 'n.', 'A fundamental class under which things fall', 'Aristotle listed ten categories of being.'),
  Word('philosophy', 'attribute', 'n.', 'A property or quality belonging to a thing', 'Spinoza ascribed infinite attributes to substance.'),
  Word('philosophy', 'predication', 'n.', 'The act of asserting a property of a subject', 'Predication links a subject to its attributes.'),
  Word('philosophy', 'instantiation', 'n.', 'The relation of a particular to the universal it exemplifies', 'A red ball is an instantiation of redness.'),
  Word('philosophy', 'exemplification', 'n.', 'The relation in which a thing displays a property', 'The statue\'s exemplification of beauty moved her.'),
  Word('philosophy', 'reductionism', 'n.', 'The view that complex things reduce to simpler parts', 'Reductionism explains the mental in physical terms.'),
  Word('philosophy', 'holism', 'n.', 'The view that wholes are more than their parts', 'Holism resists analyzing systems piecemeal.'),
  Word('philosophy', 'atomism', 'n.', 'The doctrine that reality consists of indivisible units', 'Ancient atomism anticipated modern physics.'),
  Word('philosophy', 'mechanism', 'n.', 'The view that nature operates like a machine', 'Mechanism explains motion by contact and impact.'),
  Word('philosophy', 'vitalism', 'n.', 'The doctrine that life involves a non-physical force', 'Vitalism posited a vital spark beyond chemistry.'),
  Word('philosophy', 'organicism', 'n.', 'The view that reality resembles a living organism', 'Romantic organicism saw nature as a whole.'),
  Word('philosophy', 'pantheism', 'n.', 'The belief that God and the universe are identical', 'Spinoza\'s pantheism equated God with nature.'),
  Word('philosophy', 'panentheism', 'n.', 'The belief that the world exists within God', 'Panentheism keeps God both immanent and transcendent.'),
  Word('philosophy', 'theism', 'n.', 'Belief in a personal creator God', 'Classical theism attributes omnipotence to God.'),
  Word('philosophy', 'deism', 'n.', 'Belief in a creator who does not intervene in the world', 'Deism was popular among Enlightenment thinkers.'),
  Word('philosophy', 'atheism', 'n.', 'The position that no god exists', 'He defended atheism on evidential grounds.'),
  Word('philosophy', 'agnosticism', 'n.', 'The view that the existence of God is unknowable', 'Agnosticism withholds judgment on the divine.'),
  Word('philosophy', 'monotheism', 'n.', 'Belief in a single god', 'Monotheism shaped much of Western philosophy.'),
  Word('philosophy', 'polytheism', 'n.', 'Belief in many gods', 'Greek polytheism populated the world with deities.'),
  Word('philosophy', 'secularism', 'n.', 'The principle of separating belief from public life', 'Secularism keeps the state neutral on religion.'),
  Word('philosophy', 'humanism', 'n.', 'A worldview centering on human value and reason', 'Renaissance humanism revived classical learning.'),
  Word('philosophy', 'naturalism', 'n.', 'The view that only natural causes and laws exist', 'Naturalism rejects appeals to the supernatural.'),
  Word('philosophy', 'supernaturalism', 'n.', 'The view that realities exist beyond nature', 'Supernaturalism admits miracles and spirits.'),
  Word('philosophy', 'transcendentalism', 'n.', 'A philosophy emphasizing intuition and the spiritual', 'American transcendentalism celebrated nature and self.'),
  Word('philosophy', 'absolutism', 'n.', 'The view that some principles hold without exception', 'Moral absolutism forbids lying in all cases.'),
  Word('philosophy', 'relativism', 'n.', 'The view that truth or value depends on perspective', 'Cultural relativism denies universal moral norms.'),
  Word('philosophy', 'subjectivism', 'n.', 'The view that truth depends on the individual subject', 'Ethical subjectivism roots morality in feeling.'),
  Word('philosophy', 'objectivism', 'n.', 'The view that truths hold independently of minds', 'Moral objectivism affirms mind-independent values.'),
  Word('philosophy', 'perspectivism', 'n.', 'The view that all knowledge reflects a viewpoint', 'Nietzsche\'s perspectivism denies a view from nowhere.'),
  Word('philosophy', 'foundation', 'n.', 'A basic belief on which others rest', 'Empiricists seek a foundation in sense experience.'),
  Word('philosophy', 'justification', 'n.', 'The grounds that make a belief reasonable', 'Knowledge requires justification, not just truth.'),
  Word('philosophy', 'warrant', 'n.', 'The entitlement that turns true belief into knowledge', 'Plantinga analyzed warrant as proper function.'),
  Word('philosophy', 'verification', 'n.', 'The process of confirming a claim by experience', 'Positivists demanded verification of meaningful claims.'),
  Word('philosophy', 'confirmation', 'n.', 'The support evidence lends to a hypothesis', 'Confirmation raises a hypothesis\'s probability.'),
  Word('philosophy', 'corroboration', 'n.', 'The strengthening of a theory by passing tests', 'Popper preferred corroboration to confirmation.'),
  Word('philosophy', 'refutation', 'n.', 'The act of proving a claim false', 'A single counterexample can serve as refutation.'),
  Word('philosophy', 'counterexample', 'n.', 'A case that disproves a general claim', 'Her counterexample sank the proposed definition.'),
  Word('philosophy', 'presupposition', 'n.', 'Something assumed beforehand by a claim or question', 'The question carries a hidden presupposition.'),
  Word('philosophy', 'postulate', 'n.', 'A principle assumed as a basis for reasoning', 'Kant treated freedom as a practical postulate.'),
  Word('philosophy', 'corollary', 'n.', 'A claim that follows readily from another', 'This theorem yields a useful corollary.'),
  Word('philosophy', 'lemma', 'n.', 'A subsidiary proposition used to prove a larger one', 'He proved a lemma before the main theorem.'),
  Word('philosophy', 'theorem', 'n.', 'A proposition proved from accepted premises', 'The theorem follows from the axioms.'),
  Word('philosophy', 'conjecture', 'n.', 'An opinion formed on incomplete evidence', 'The conjecture remained unproven for decades.'),
  Word('philosophy', 'thought-experiment', 'n.', 'An imagined scenario used to test an idea', 'A famous thought-experiment imagines a brain in a vat.'),
  Word('philosophy', 'introspection', 'n.', 'The examination of one\'s own mental states', 'Introspection reveals the contents of consciousness.'),
  Word('philosophy', 'speculation', 'n.', 'Reasoning about matters beyond direct evidence', 'Cosmological speculation outran the available data.'),
  Word('philosophy', 'discourse', 'n.', 'Reasoned communication of ideas', 'Public discourse depends on shared norms of reason.'),
  Word('philosophy', 'treatise', 'n.', 'A systematic written work on a subject', 'Hume\'s treatise laid out his entire system.'),
  Word('philosophy', 'doctrine', 'n.', 'A set of principles held by a school or thinker', 'The doctrine of forms is central to Plato.'),
  Word('philosophy', 'dogma', 'n.', 'A principle laid down as unquestionably true', 'He rejected the dogma without argument.'),
  Word('philosophy', 'tenet', 'n.', 'A principle held as part of a belief system', 'Free will is a core tenet of his ethics.'),
  Word('philosophy', 'creed', 'n.', 'A formal statement of held beliefs', 'Their philosophical creed valued simplicity.'),
  Word('philosophy', 'maximalism', 'n.', 'The tendency to multiply principles or entities', 'Critics charged the theory with needless maximalism.'),
  Word('philosophy', 'parsimony', 'n.', 'The principle of preferring simpler explanations', 'Parsimony favors the theory with fewer assumptions.'),
  Word('philosophy', 'elegance', 'n.', 'Pleasing economy and clarity in a theory', 'Mathematicians prize the elegance of a proof.'),
  Word('philosophy', 'rigor', 'n.', 'Strict precision in reasoning or proof', 'Logical rigor leaves no step unjustified.'),
  Word('philosophy', 'precision', 'n.', 'Exactness in concepts or definitions', 'Philosophy demands precision in defining terms.'),
  Word('philosophy', 'obscurity', 'n.', 'The quality of being unclear or hard to understand', 'Critics complained of the text\'s obscurity.'),
  Word('philosophy', 'clarity', 'n.', 'The quality of being clear and intelligible', 'Analytic philosophy prizes clarity above all.'),
  Word('philosophy', 'definition', 'n.', 'A statement of the exact meaning of a term', 'Socrates pressed his friends for a definition.'),
  Word('philosophy', 'demarcation', 'n.', 'The drawing of a line between distinct kinds', 'The demarcation of science from pseudoscience is contested.'),
  Word('philosophy', 'distinction', 'n.', 'A recognized difference between two things', 'He drew a sharp distinction between cause and reason.'),
  Word('philosophy', 'analysis', 'n.', 'The breaking of a concept into its components', 'Conceptual analysis clarifies what we mean.'),
  Word('philosophy', 'systematize', 'v.', 'To arrange beliefs into an ordered system', 'Kant tried to systematize the whole of knowledge.'),
  Word('philosophy', 'theorize', 'v.', 'To form explanatory ideas about something', 'Greeks began to theorize about the cosmos.'),
  Word('philosophy', 'conceptualize', 'v.', 'To form a general idea of something', 'We struggle to conceptualize infinity.'),
  Word('philosophy', 'problematize', 'v.', 'To treat something as a problem worth questioning', 'She set out to problematize the very notion of progress.'),
  Word('philosophy', 'interrogate', 'v.', 'To examine an idea critically and closely', 'Critical theory interrogates hidden assumptions.'),
  Word('philosophy', 'derive', 'v.', 'To obtain a conclusion by reasoning', 'From these axioms we derive the rest.'),
  Word('philosophy', 'posit', 'v.', 'To assume or assert the existence of something', 'Dualists posit a non-physical mind.'),
  Word('philosophy', 'affirm', 'v.', 'To assert that something is true', 'He affirmed the reality of the external world.'),
  Word('philosophy', 'negate', 'v.', 'To deny or render void a proposition', 'To negate the claim is to assert its opposite.'),
  Word('philosophy', 'refute', 'v.', 'To prove a statement or argument false', 'A single case can refute a universal claim.'),
  Word('philosophy', 'rebut', 'v.', 'To offer reasons against an argument', 'She rose to rebut the objection point by point.'),
  Word('philosophy', 'concede', 'v.', 'To admit a point as true in argument', 'He conceded the premise but denied the conclusion.'),
  Word('philosophy', 'equivocate', 'v.', 'To use a term ambiguously to mislead', 'The sophist equivocated on the word \'good\'.'),
  Word('philosophy', 'reify', 'v.', 'To treat an abstraction as a concrete thing', 'Critics warned against reify-ing the market as an agent.'),
  Word('philosophy', 'essentialize', 'v.', 'To treat a feature as a fixed essence', 'It is a mistake to essentialize human nature.'),
  Word('philosophy', 'transcend', 'v.', 'To go beyond the limits of something', 'Mystics claim to transcend ordinary experience.'),
  Word('philosophy', 'apprehend', 'v.', 'To grasp something with the mind', 'We apprehend mathematical truths directly.'),
  Word('philosophy', 'cogitate', 'v.', 'To think deeply and carefully about something', 'He would cogitate for hours on a single question.'),
  Word('philosophy', 'ratiocinate', 'v.', 'To reason methodically and logically', 'The detective ratiocinated from clue to conclusion.'),
  Word('philosophy', 'sophisticated', 'adj.', 'Showing refined and subtle reasoning', 'Her argument was philosophically sophisticated.'),
  Word('philosophy', 'cogent', 'adj.', 'Clear, logical, and convincing', 'He made a cogent case for moral realism.'),
  Word('philosophy', 'tenable', 'adj.', 'Able to be defended against objection', 'The position is no longer tenable after that critique.'),
  Word('philosophy', 'untenable', 'adj.', 'Unable to be defended or maintained', 'Naive realism proved untenable.'),
  Word('philosophy', 'fallacious', 'adj.', 'Based on faulty reasoning', 'The appeal to popularity is fallacious.'),
  Word('philosophy', 'specious', 'adj.', 'Superficially plausible but actually wrong', 'His specious argument fooled the audience.'),
  Word('philosophy', 'spurious', 'adj.', 'False or not genuine despite appearances', 'The correlation turned out to be spurious.'),
  Word('philosophy', 'vacuous', 'adj.', 'Empty of meaning or genuine content', 'The slogan was philosophically vacuous.'),
  Word('philosophy', 'profound', 'adj.', 'Showing deep insight or significance', 'It was a profound question about being itself.'),
  Word('philosophy', 'ineffable', 'adj.', 'Too great to be expressed in words', 'Mystics call the divine ineffable.'),
  Word('philosophy', 'inexorable', 'adj.', 'Impossible to stop or resist', 'The logic led to an inexorable conclusion.'),
  Word('philosophy', 'self-evident', 'adj.', 'Obviously true without need of proof', 'They held certain truths to be self-evident.'),
  Word('philosophy', 'indubitable', 'adj.', 'Impossible to doubt', 'Descartes sought an indubitable first truth.'),
  Word('philosophy', 'incorrigible', 'adj.', 'Not capable of being corrected or doubted', 'Some hold that pain reports are incorrigible.'),
  Word('philosophy', 'defeasible', 'adj.', 'Capable of being defeated by further evidence', 'Most everyday justification is defeasible.'),
  Word('philosophy', 'fallible', 'adj.', 'Capable of being mistaken', 'Even careful reasoners are fallible.'),
  Word('philosophy', 'infallible', 'adj.', 'Incapable of being wrong', 'No human source of knowledge is infallible.'),
  Word('philosophy', 'fallibilism', 'n.', 'The view that no belief is beyond revision', 'Fallibilism keeps inquiry permanently open.'),
  Word('philosophy', 'dogmatism', 'n.', 'The tendency to assert claims without argument', 'Skeptics opposed the dogmatism of their rivals.'),
  Word('philosophy', 'quietism', 'n.', 'The view that philosophy should dissolve, not solve, problems', 'Wittgensteinian quietism abandons grand theories.'),
  Word('philosophy', 'scientism', 'n.', 'The belief that science alone yields knowledge', 'Critics charge scientism with overreach.'),
  Word('philosophy', 'historicism', 'n.', 'The view that ideas must be understood in historical context', 'Historicism denies timeless philosophical truths.'),
  Word('philosophy', 'structuralism', 'n.', 'The view that meaning arises from underlying structures', 'Structuralism analyzed culture as a system of signs.'),
  Word('philosophy', 'postmodernism', 'n.', 'A movement skeptical of grand unifying narratives', 'Postmodernism distrusts claims to universal truth.'),
  Word('philosophy', 'romanticism', 'n.', 'A movement exalting feeling, nature, and individuality', 'Romanticism reacted against cold rationalism.'),
  Word('philosophy', 'enlightenment', 'n.', 'An era championing reason and individual liberty', 'The Enlightenment reshaped European thought.'),
  Word('philosophy', 'irrationality', 'n.', 'The state of acting against reason', 'Weakness of will is a form of irrationality.'),
  Word('philosophy', 'prudence', 'n.', 'Practical wisdom in choosing means to ends', 'Prudence guides action toward the good.'),
  Word('philosophy', 'benevolence', 'n.', 'The disposition to seek the good of others', 'Hume grounded morality partly in benevolence.'),
  Word('philosophy', 'malevolence', 'n.', 'The disposition to wish harm to others', 'The problem of evil concerns apparent malevolence.'),
  Word('philosophy', 'beneficence', 'n.', 'The duty to act for the benefit of others', 'Medical ethics stresses the principle of beneficence.'),
  Word('philosophy', 'altruism', 'n.', 'Concern for the welfare of others over oneself', 'Whether genuine altruism exists is debated.'),
  Word('philosophy', 'egoism', 'n.', 'The view that self-interest guides or should guide action', 'Psychological egoism claims all acts are selfish.'),
  Word('philosophy', 'obligation', 'n.', 'A binding moral or social requirement', 'We feel an obligation to keep our promises.'),
  Word('philosophy', 'culpability', 'n.', 'The state of deserving blame', 'Intent affects an agent\'s culpability.'),
  Word('philosophy', 'blameworthy', 'adj.', 'Deserving of moral blame', 'A coerced act may not be blameworthy.'),
  Word('philosophy', 'permissible', 'adj.', 'Allowed within moral or logical rules', 'Self-defense makes the act morally permissible.'),
  Word('philosophy', 'flourishing', 'n.', 'A life of complete well-being and excellence', 'Virtue ethics centers on human flourishing.'),
  Word('philosophy', 'wellbeing', 'n.', 'The state of being healthy, happy, and fulfilled', 'Utilitarians measure acts by their effect on wellbeing.'),
];
