import 'words_data.dart';

const kPhilosophyExtras = <Word>[
  Word('philosophy', 'aporia', 'n.', 'A state of puzzlement where reasoning hits a dead end', 'Socrates loved leading his interlocutors into aporia before any answer.'),
  Word('philosophy', 'elenchus', 'n.', 'The Socratic method of refutation through questioning', 'The elenchus exposed contradictions hiding inside confident definitions.'),
  Word('philosophy', 'maieutic', 'adj.', 'Drawing latent ideas out of someone like a midwife', 'His maieutic style coaxed beliefs from students rather than imposing them.'),
  Word('philosophy', 'forms', 'n.', 'Plato\'s eternal perfect templates behind worldly things', 'For Plato, every chair is a shadow of the form of the chair itself.'),
  Word('philosophy', 'allegory', 'n.', 'A story whose surface meaning points to a deeper one', 'The allegory of the cave illustrates the painful climb toward truth.'),
  Word('philosophy', 'cave', 'n.', 'Plato\'s image of prisoners mistaking shadows for reality', 'Most of us, Plato says, live in the cave without ever turning around.'),
  Word('philosophy', 'philosopher-king', 'n.', 'Plato\'s ideal ruler trained in wisdom and virtue', 'The philosopher-king would govern reluctantly, not out of ambition.'),
  Word('philosophy', 'kallipolis', 'n.', 'Plato\'s name for the ideal just city', 'In the kallipolis each class does its proper work and nothing else.'),
  Word('philosophy', 'demiurge', 'n.', 'A craftsman god who shapes matter according to forms', 'Plato\'s demiurge orders chaos but does not create from nothing.'),
  Word('philosophy', 'chora', 'n.', 'The receptacle in which becoming takes place', 'The chora has no character of its own yet hosts every appearance.'),
  Word('philosophy', 'anamnesis', 'n.', 'Learning understood as recollecting eternal truths', 'In the Meno a slave boy proves geometry through anamnesis.'),
  Word('philosophy', 'mimesis', 'n.', 'Art understood as imitation of nature or ideas', 'Aristotle defended mimesis where Plato suspected it of lying.'),
  Word('philosophy', 'catharsis', 'n.', 'The purging of emotions through tragic spectacle', 'A good tragedy delivers catharsis without leaving the audience numb.'),
  Word('philosophy', 'hylomorphism', 'n.', 'The view that things are compounds of matter and form', 'Aristotle\'s hylomorphism treats the soul as the form of a living body.'),
  Word('philosophy', 'entelechy', 'n.', 'The actualization of a thing\'s inner potential', 'An acorn\'s entelechy is the mature oak it grows into.'),
  Word('philosophy', 'substance', 'n.', 'What underlies properties and persists through change', 'For Aristotle, an individual horse is a primary substance.'),
  Word('philosophy', 'accident', 'n.', 'A property a thing has but could lose without ceasing to be', 'A man\'s pallor is an accident; his rationality is not.'),
  Word('philosophy', 'essence', 'n.', 'What a thing fundamentally is, its defining nature', 'To grasp the essence of a triangle is to grasp why its angles sum as they do.'),
  Word('philosophy', 'haecceity', 'n.', 'The thisness that makes an individual uniquely itself', 'Duns Scotus coined haecceity to capture irreducible individuality.'),
  Word('philosophy', 'universal', 'n.', 'A property or kind shared by many particular things', 'The redness of two apples raises the old problem of universals.'),
  Word('philosophy', 'particular', 'n.', 'A single concrete instance, not a kind or property', 'Each particular cat instantiates the universal feline nature.'),
  Word('philosophy', 'nominalism', 'n.', 'The view that only particulars exist, names are mere labels', 'A strict nominalism denies that humanity is anything beyond individual humans.'),
  Word('philosophy', 'realism', 'n.', 'The view that universals or external things genuinely exist', 'Medieval realism took kinds like horse to be as real as Bucephalus.'),
  Word('philosophy', 'conceptualism', 'n.', 'A middle path: universals exist only in minds', 'Abelard\'s conceptualism placed kinds in thought rather than the world.'),
  Word('philosophy', 'four-causes', 'n.', 'Aristotle\'s material, formal, efficient, and final causes', 'Asking why a statue exists invites all four causes at once.'),
  Word('philosophy', 'final-cause', 'n.', 'The end or purpose for which something exists', 'A knife\'s final cause is cutting, not the steel it is made from.'),
  Word('philosophy', 'efficient-cause', 'n.', 'The agent that brings something about', 'The sculptor is the efficient cause of the marble bust.'),
  Word('philosophy', 'unmoved-mover', 'n.', 'A first cause that moves others without being moved', 'Aristotle\'s unmoved mover draws the cosmos toward itself by attraction.'),
  Word('philosophy', 'prime-matter', 'n.', 'Featureless stuff that takes on form to become a thing', 'Prime matter is never encountered alone, only as informed substance.'),
  Word('philosophy', 'potency', 'n.', 'A capacity to become or do something not yet actual', 'Water has the potency to freeze given the right conditions.'),
  Word('philosophy', 'analogia-entis', 'n.', 'The analogical likeness between creatures and God', 'The analogia entis lets us speak of divine goodness without flattening it.'),
  Word('philosophy', 'natural-law', 'n.', 'Moral norms held to follow from human nature itself', 'Aquinas grounded natural law in reason participating in eternal law.'),
  Word('philosophy', 'divine-command', 'n.', 'The view that morality depends on God\'s will', 'Divine command theory faces the old Euthyphro question.'),
  Word('philosophy', 'euthyphro', 'n.', 'The dilemma whether goodness is loved by gods or made by them', 'The Euthyphro forces a choice between arbitrary or independent goodness.'),
  Word('philosophy', 'ontological-argument', 'n.', 'Anselm\'s proof that God\'s essence entails existence', 'The ontological argument moves from a concept to a reality in one bold step.'),
  Word('philosophy', 'cosmological-argument', 'n.', 'An argument from the world\'s existence to a first cause', 'The cosmological argument asks why there is something rather than nothing.'),
  Word('philosophy', 'teleological-argument', 'n.', 'An argument from apparent design to a designer', 'Paley\'s watch is the classic teleological argument for a creator.'),
  Word('philosophy', 'problem-of-evil', 'n.', 'The challenge of squaring suffering with a good God', 'The problem of evil has driven theodicies for two thousand years.'),
  Word('philosophy', 'free-will-defense', 'n.', 'A reply to evil that blames misuse of human freedom', 'Plantinga\'s free will defense seeks logical consistency, not comfort.'),
  Word('philosophy', 'pascals-wager', 'n.', 'A bet that belief in God minimizes expected loss', 'Pascal\'s wager treats faith as a prudential gamble worth taking.'),
  Word('philosophy', 'fideism', 'n.', 'The view that faith stands above or against reason', 'Tertullian\'s fideism declared he believed because it was absurd.'),
  Word('philosophy', 'occams-razor', 'n.', 'A preference for the simpler of competing explanations', 'Occam\'s razor warns us not to multiply entities beyond necessity.'),
  Word('philosophy', 'haecceitas', 'n.', 'Scotus\'s technical term for individuating thisness', 'Scotus introduced haecceitas to fix what universals could not.'),
  Word('philosophy', 'via-negativa', 'n.', 'A way of speaking of God only by what God is not', 'Negative theology travels the via negativa to avoid idolizing concepts.'),
  Word('philosophy', 'beatific-vision', 'n.', 'The direct knowledge of God enjoyed in heaven', 'For Aquinas the beatific vision is the final end of human life.'),
  Word('philosophy', 'scholasticism', 'n.', 'Medieval philosophy organized around disputation and authority', 'Scholasticism prized careful distinctions over flashy rhetoric.'),
  Word('philosophy', 'quaestio', 'n.', 'A formal scholastic question with arguments on each side', 'Each quaestio in the Summa weighs objections before deciding.'),
  Word('philosophy', 'cogito', 'n.', 'Descartes\'s claim that thinking proves one exists', 'The cogito stops doubt by turning it on itself.'),
  Word('philosophy', 'meditation', 'n.', 'A reflective philosophical exercise in the first person', 'Descartes\'s Meditations stage doubt as a six-day journey.'),
  Word('philosophy', 'method-of-doubt', 'n.', 'Suspending every belief that could possibly be false', 'The method of doubt clears the ground for a firm foundation.'),
  Word('philosophy', 'evil-demon', 'n.', 'Descartes\'s hypothetical deceiver who could fake all experience', 'The evil demon scenario anticipates today\'s brain-in-a-vat worries.'),
  Word('philosophy', 'res-cogitans', 'n.', 'The thinking thing that for Descartes is the self', 'Res cogitans is defined entirely by acts of thought.'),
  Word('philosophy', 'res-extensa', 'n.', 'Extended matter, the physical substance for Descartes', 'Res extensa fills space and obeys mechanical laws.'),
  Word('philosophy', 'pineal-gland', 'n.', 'Descartes\'s guess at where mind and body interact', 'The pineal gland was his attempt to fix dualism\'s plumbing.'),
  Word('philosophy', 'interactionism', 'n.', 'The view that mental and physical genuinely affect each other', 'Interactionism keeps dualism honest at the cost of mystery.'),
  Word('philosophy', 'occasionalism', 'n.', 'God produces every match between mind and body', 'Malebranche\'s occasionalism made God the only true cause.'),
  Word('philosophy', 'parallelism', 'n.', 'Mind and body run on separate tracks that always align', 'Leibniz\'s parallelism likens them to two perfectly tuned clocks.'),
  Word('philosophy', 'monad', 'n.', 'Leibniz\'s windowless simple substance with its own perceptions', 'Each monad mirrors the whole universe from its own perspective.'),
  Word('philosophy', 'pre-established-harmony', 'n.', 'God\'s arrangement that all monads agree without interaction', 'Pre-established harmony explains coordination without causation.'),
  Word('philosophy', 'best-of-all-possible-worlds', 'n.', 'Leibniz\'s claim that this world is the optimal one God could make', 'Voltaire mocked the best of all possible worlds in Candide.'),
  Word('philosophy', 'principle-of-sufficient-reason', 'n.', 'Nothing is without a reason why it is so', 'The principle of sufficient reason drives Leibniz\'s rationalism.'),
  Word('philosophy', 'identity-of-indiscernibles', 'n.', 'Two things sharing every property are the same thing', 'The identity of indiscernibles trims Leibniz\'s ontology severely.'),
  Word('philosophy', 'substance-monism', 'n.', 'The view that reality is one single substance', 'Spinoza\'s substance monism identifies God with Nature itself.'),
  Word('philosophy', 'conatus', 'n.', 'A thing\'s striving to persist in its own being', 'Spinoza grounds desire and life in this fundamental conatus.'),
  Word('philosophy', 'sub-specie-aeternitatis', 'phr.', 'Under the aspect of eternity, as a timeless view', 'Spinoza urges seeing one\'s troubles sub specie aeternitatis.'),
  Word('philosophy', 'intellectus', 'n.', 'Intellect as an active power of grasping truth', 'Medieval thinkers distinguished intellectus from mere reasoning.'),
  Word('philosophy', 'idea-of-reflection', 'n.', 'Locke\'s ideas formed by the mind observing itself', 'Memory and willing become objects of an idea of reflection.'),
  Word('philosophy', 'simple-idea', 'n.', 'A basic mental atom received passively in experience', 'Coldness is a simple idea the mind cannot manufacture from scratch.'),
  Word('philosophy', 'complex-idea', 'n.', 'An idea built up by combining simpler ones', 'Our idea of gold is a complex idea bundling yellow, heavy, and malleable.'),
  Word('philosophy', 'primary-quality', 'n.', 'A quality genuinely belonging to objects, like shape or size', 'Primary qualities resemble what they cause in us, Locke argued.'),
  Word('philosophy', 'secondary-quality', 'n.', 'A power in objects to produce sensations like color or taste', 'A secondary quality is not in the object the way redness seems to be.'),
  Word('philosophy', 'social-contract', 'n.', 'A founding agreement that legitimates political authority', 'Social contract theory replaces divine right with mutual consent.'),
  Word('philosophy', 'state-of-nature', 'n.', 'A hypothetical condition without organized government', 'Hobbes\'s state of nature is famously solitary, poor, and short.'),
  Word('philosophy', 'leviathan', 'n.', 'Hobbes\'s name for the sovereign power that ends war of all on all', 'Only a Leviathan, he thought, could secure peace among equals.'),
  Word('philosophy', 'general-will', 'n.', 'Rousseau\'s idea of what a community wills for its common good', 'The general will is not just a majority vote but a directed purpose.'),
  Word('philosophy', 'amour-propre', 'n.', 'A self-love measured against the regard of others', 'Rousseau worried that amour propre corrupts authentic feeling.'),
  Word('philosophy', 'noble-savage', 'n.', 'A pre-civilized human imagined as naturally good', 'The noble savage is more a rhetorical foil than a literal claim.'),
  Word('philosophy', 'tabula', 'n.', 'A slate or surface, often used as shorthand for the blank mind', 'The empiricist tabula is written on by experience alone.'),
  Word('philosophy', 'impression', 'n.', 'Hume\'s vivid original perception, as in sensation or feeling', 'Every idea, Hume said, traces back to an antecedent impression.'),
  Word('philosophy', 'constant-conjunction', 'n.', 'A repeated pairing that we mistake for necessary causation', 'Hume reduced causation to constant conjunction plus mental habit.'),
  Word('philosophy', 'is-ought', 'n.', 'The gap between descriptive facts and prescriptive duties', 'Hume\'s is-ought warning still trips up confident moralists.'),
  Word('philosophy', 'naturalistic-fallacy', 'n.', 'Inferring moral conclusions from purely natural premises', 'Moore charged hedonists with the naturalistic fallacy.'),
  Word('philosophy', 'bundle-theory', 'n.', 'The self is a bundle of perceptions, not a substance', 'Hume\'s bundle theory dissolves the soul into a stream.'),
  Word('philosophy', 'induction', 'n.', 'Reasoning from observed cases to general conclusions', 'Hume questioned whether induction has any rational ground.'),
  Word('philosophy', 'problem-of-induction', 'n.', 'The puzzle of justifying inferences from past to future', 'The problem of induction haunts every empirical generalization.'),
  Word('philosophy', 'fork', 'n.', 'Hume\'s split between relations of ideas and matters of fact', 'Hume\'s fork sorts every meaningful claim into one of two boxes.'),
  Word('philosophy', 'categorical-imperative', 'n.', 'Kant\'s rule to act only on maxims one could will as universal law', 'The categorical imperative judges actions without weighing outcomes.'),
  Word('philosophy', 'hypothetical-imperative', 'n.', 'A command that binds only given some desired end', 'Brush your teeth is hypothetical; do not lie is categorical.'),
  Word('philosophy', 'autonomy', 'n.', 'Self-rule by reason giving itself moral law', 'Kant treats autonomy as the very ground of human dignity.'),
  Word('philosophy', 'heteronomy', 'n.', 'Being governed by impulses or external authority', 'Heteronomy taints any choice driven by inclination alone.'),
  Word('philosophy', 'kingdom-of-ends', 'n.', 'Kant\'s ideal community of rational beings treating each other as ends', 'In the kingdom of ends, no one is ever a mere means.'),
  Word('philosophy', 'noumenon', 'n.', 'The thing as it is in itself, beyond experience', 'Kant denies any positive knowledge of the noumenon.'),
  Word('philosophy', 'phenomenon', 'n.', 'The thing as it appears within experience', 'Science studies phenomena, not noumena, Kant insisted.'),
  Word('philosophy', 'synthetic-a-priori', 'n.', 'A judgment that is informative yet knowable without experience', 'Kant tried to make synthetic a priori knowledge respectable again.'),
  Word('philosophy', 'analytic', 'adj.', 'True by virtue of meaning, like bachelors are unmarried', 'Analytic truths add nothing new to the predicate.'),
  Word('philosophy', 'synthetic', 'adj.', 'True by going beyond what the subject contains', 'Synthetic claims tell us something the concepts alone did not.'),
  Word('philosophy', 'transcendental', 'adj.', 'Concerning conditions that make experience possible', 'Kant\'s transcendental inquiry asks how knowledge is possible at all.'),
  Word('philosophy', 'transcendental-idealism', 'n.', 'Kant\'s view that the mind structures the world we know', 'Transcendental idealism keeps the world real and the mind active.'),
  Word('philosophy', 'antinomy', 'n.', 'A pair of contradictory conclusions both seeming proven', 'Kant\'s antinomies showed pure reason colliding with itself.'),
  Word('philosophy', 'schematism', 'n.', 'Kant\'s procedure linking concepts to sensible intuitions', 'The schematism lets categories apply to actual experiences.'),
  Word('philosophy', 'sublime', 'n.', 'An aesthetic response mixing awe and overwhelm at vast power', 'Kant placed the sublime above the beautiful in moral weight.'),
  Word('philosophy', 'disinterestedness', 'n.', 'Aesthetic appreciation free of personal stake', 'Kant insisted that disinterestedness is what makes beauty universal.'),
  Word('philosophy', 'absolute', 'n.', 'The unconditioned whole that idealists made central', 'Hegel sought to grasp the Absolute through its self-development.'),
  Word('philosophy', 'spirit', 'n.', 'Hegel\'s self-knowing rational reality unfolding in history', 'World history is the biography of Spirit coming to itself.'),
  Word('philosophy', 'geist', 'n.', 'The German word for spirit or mind in idealist thought', 'Hegel\'s Geist is communal as much as individual.'),
  Word('philosophy', 'aufhebung', 'n.', 'Hegelian sublation that cancels, preserves, and elevates', 'Each stage undergoes aufhebung into a richer next stage.'),
  Word('philosophy', 'thesis', 'n.', 'An initial position in a dialectical movement', 'The thesis already harbors the seed of its own opposite.'),
  Word('philosophy', 'antithesis', 'n.', 'The opposing position that confronts a thesis', 'Tension between thesis and antithesis drives thought forward.'),
  Word('philosophy', 'synthesis', 'n.', 'A higher unity that absorbs and surpasses earlier opposites', 'A genuine synthesis is not a compromise but a transformation.'),
  Word('philosophy', 'master-slave', 'n.', 'Hegel\'s dialectic of mutual recognition through struggle', 'The master-slave passage explains why domination undermines itself.'),
  Word('philosophy', 'recognition', 'n.', 'Being acknowledged by another as a free self-conscious being', 'For Hegel, identity is impossible without recognition.'),
  Word('philosophy', 'alienation', 'n.', 'Estrangement from work, others, or one\'s own essence', 'Marx repurposed Hegelian alienation for industrial labor.'),
  Word('philosophy', 'reification', 'n.', 'Treating social relations as if they were natural things', 'Lukács argued capitalism produces a thoroughgoing reification.'),
  Word('philosophy', 'commodity-fetishism', 'n.', 'Mistaking values created by labor for properties of goods', 'Commodity fetishism hides workers behind the gleam of products.'),
  Word('philosophy', 'base', 'n.', 'The economic foundation that conditions a society', 'In classical Marxism the base shapes the ideological superstructure.'),
  Word('philosophy', 'superstructure', 'n.', 'The legal, cultural, and ideological layer above the economic base', 'Religion and law belong to the superstructure for Marx.'),
  Word('philosophy', 'ideology', 'n.', 'A system of ideas that masks or justifies power relations', 'Critique of ideology asks whose interests an obvious truth serves.'),
  Word('philosophy', 'false-consciousness', 'n.', 'A misperception of one\'s real social conditions', 'False consciousness keeps workers identifying with their employers.'),
  Word('philosophy', 'praxis-philosophy', 'n.', 'A view that transforming the world is part of understanding it', 'Marxist praxis philosophy refuses the divorce of theory and life.'),
  Word('philosophy', 'historical-materialism', 'n.', 'A theory of history driven by material productive forces', 'Historical materialism reads ideas as outgrowths of social labor.'),
  Word('philosophy', 'dialectical-materialism', 'n.', 'A materialist account of change through contradiction', 'Dialectical materialism became the official Soviet philosophy.'),
  Word('philosophy', 'class-struggle', 'n.', 'Conflict between social classes over economic interests', 'For Marx, all history so far is the history of class struggle.'),
  Word('philosophy', 'proletariat', 'n.', 'The working class that sells its labor to survive', 'The proletariat, Marx predicted, would eventually overturn capital.'),
  Word('philosophy', 'bourgeoisie', 'n.', 'The class that owns the means of production', 'The bourgeoisie revolutionizes production yet undermines itself.'),
  Word('philosophy', 'species-being', 'n.', 'The shared human nature realized through conscious labor', 'Alienation, Marx wrote, severs us from our species-being.'),
  Word('philosophy', 'use-value', 'n.', 'The usefulness a good has for someone\'s purposes', 'A coat\'s use value is to warm a body, not to fetch a price.'),
  Word('philosophy', 'exchange-value', 'n.', 'The ratio at which goods trade against one another', 'Exchange value abstracts away every concrete need.'),
  Word('philosophy', 'surplus-value', 'n.', 'The extra value extracted from labor beyond wages paid', 'Profit, Marx argued, is congealed surplus value.'),
  Word('philosophy', 'genealogy', 'n.', 'Tracing concepts through their contingent historical origins', 'Nietzsche\'s genealogy debunks the supposed naturalness of morality.'),
  Word('philosophy', 'ressentiment', 'n.', 'A repressed envy that inverts values to favor the weak', 'Slave morality, Nietzsche claimed, is born of ressentiment.'),
  Word('philosophy', 'slave-morality', 'n.', 'A value system framing weakness as virtue and strength as vice', 'Christian humility, on Nietzsche\'s read, exemplifies slave morality.'),
  Word('philosophy', 'master-morality', 'n.', 'A morality of self-affirming nobility and active power', 'Master morality calls strength good rather than evil.'),
  Word('philosophy', 'last-man', 'n.', 'Nietzsche\'s figure of complacent comfort without aspiration', 'The last man blinks and asks what is love.'),
  Word('philosophy', 'transvaluation', 'n.', 'A radical revaluation of inherited moral values', 'Nietzsche called for the transvaluation of all values.'),
  Word('philosophy', 'apollonian', 'adj.', 'Of measured form, clarity, and individuation', 'Greek sculpture exemplifies the Apollonian impulse.'),
  Word('philosophy', 'dionysian', 'adj.', 'Of ecstatic chaos, intoxication, and dissolution of the self', 'Tragedy fuses Apollonian form with Dionysian frenzy.'),
  Word('philosophy', 'noble-lie', 'n.', 'A useful myth told to bind a community together', 'Plato\'s guardians teach a noble lie about citizens\' origins.'),
  Word('philosophy', 'pessimism', 'n.', 'A view that suffering or futility outweighs goods in life', 'Schopenhauer\'s pessimism made willing itself the root of misery.'),
  Word('philosophy', 'will', 'n.', 'A blind striving force that, for Schopenhauer, underlies all reality', 'Music, he thought, expresses the will more directly than other arts.'),
  Word('philosophy', 'representation', 'n.', 'The world as it appears to a knowing subject', 'For Schopenhauer the world is both will and representation.'),
  Word('philosophy', 'principium-individuationis', 'n.', 'The principle that explains why there are many things rather than one', 'Compassion sees through the principium individuationis.'),
  Word('philosophy', 'compassion-ethics', 'n.', 'A morality grounded in fellow-feeling for suffering beings', 'Schopenhauer based compassion ethics on shared suffering.'),
  Word('philosophy', 'existence-precedes-essence', 'phr.', 'Sartre\'s claim that humans first exist and then define themselves', 'Existence precedes essence makes human nature a project, not a fact.'),
  Word('philosophy', 'facticity', 'n.', 'The unchosen features of one\'s situation, body, and past', 'Freedom always works against the resistance of facticity.'),
  Word('philosophy', 'transcendence-existential', 'n.', 'The capacity to surpass given conditions through projects', 'Sartre pairs facticity with transcendence as the two faces of being.'),
  Word('philosophy', 'being-in-itself', 'n.', 'Sartre\'s name for non-conscious solid being', 'A rock has being-in-itself, full and without lack.'),
  Word('philosophy', 'being-for-itself', 'n.', 'Sartre\'s consciousness, defined by lack and possibility', 'Being-for-itself is what it is not and is not what it is.'),
  Word('philosophy', 'being-for-others', 'n.', 'How one exists under the gaze of other consciousnesses', 'Shame reveals being-for-others most sharply.'),
  Word('philosophy', 'the-look', 'n.', 'Sartre\'s phenomenon of becoming an object to another\'s gaze', 'The look catches the voyeur and turns him into the seen.'),
  Word('philosophy', 'nausea', 'n.', 'Sartre\'s queasy sense of contingency in raw existence', 'Roquentin\'s nausea hits him on a park bench staring at a chestnut root.'),
  Word('philosophy', 'absurd', 'n.', 'The clash between human demand for meaning and a silent world', 'Camus called the absurd the only philosophical problem worth solving.'),
  Word('philosophy', 'sisyphean', 'adj.', 'Of an endless and futile labor like rolling a boulder uphill', 'A Sisyphean revision cycle on the same paragraph drained the morning.'),
  Word('philosophy', 'revolt', 'n.', 'Camus\'s defiant continuation of life in the face of absurdity', 'Revolt, not suicide, is the absurd hero\'s answer.'),
  Word('philosophy', 'leap-of-faith', 'n.', 'Kierkegaard\'s plunge into commitment beyond reason', 'A leap of faith makes religious life a passionate venture.'),
  Word('philosophy', 'either-or', 'n.', 'Kierkegaard\'s framing of decisive existential choice', 'In Either/Or the aesthetic and ethical lives confront each other.'),
  Word('philosophy', 'teleological-suspension', 'n.', 'Kierkegaard\'s claim that faith may suspend ethical norms', 'Abraham\'s knife illustrates the teleological suspension of the ethical.'),
  Word('philosophy', 'fear-and-trembling', 'n.', 'The dread that accompanies absolute religious responsibility', 'Faith for Kierkegaard is no comfort but fear and trembling.'),
  Word('philosophy', 'sickness-unto-death', 'n.', 'Despair, the soul\'s deepest spiritual malady', 'The sickness unto death is despair refusing to be itself.'),
  Word('philosophy', 'inwardness', 'n.', 'The passionate subjective relation that Kierkegaard prized', 'Truth as inwardness puts how before what.'),
  Word('philosophy', 'subjectivity-is-truth', 'phr.', 'Kierkegaard\'s slogan for passionate personal commitment', 'Subjectivity is truth means the believer\'s how can outweigh proofs.'),
  Word('philosophy', 'aesthete', 'n.', 'One devoted to a life of immediate pleasure and refined taste', 'Kierkegaard\'s aesthete flees boredom by chasing variation.'),
  Word('philosophy', 'ethical-stage', 'n.', 'A life shaped by duty, commitment, and universal norms', 'Marriage exemplifies the ethical stage of existence.'),
  Word('philosophy', 'religious-stage', 'n.', 'A life answering to an absolute beyond ethics', 'The religious stage cannot be argued, only entered.'),
  Word('philosophy', 'angst-existential', 'n.', 'A specific dread before one\'s own freedom and possibility', 'Existential angst is anxiety with no particular object.'),
  Word('philosophy', 'being-toward-death', 'n.', 'Heidegger\'s authentic confrontation with one\'s mortality', 'Being-toward-death individuates Dasein from the crowd.'),
  Word('philosophy', 'das-man', 'n.', 'The anonymous they whose opinions one drifts into following', 'Das Man reassures us that one does what one does.'),
  Word('philosophy', 'fallenness', 'n.', 'Heidegger\'s tendency of Dasein to lose itself in everyday concerns', 'Fallenness is not a sin but a structural feature of being-in-the-world.'),
  Word('philosophy', 'being-in-the-world', 'n.', 'Heidegger\'s unified structure of self engaged with world', 'Being-in-the-world resists splitting subject from object.'),
  Word('philosophy', 'ready-to-hand', 'adj.', 'Of equipment used smoothly without explicit attention', 'A hammer is ready-to-hand until it breaks.'),
  Word('philosophy', 'present-at-hand', 'adj.', 'Of an object considered as a mere thing with properties', 'Theory turns the hammer present-at-hand by detaching it from use.'),
  Word('philosophy', 'enframing', 'n.', 'Heidegger\'s name for the technological way of revealing', 'Enframing reduces forests to standing reserves of timber.'),
  Word('philosophy', 'standing-reserve', 'n.', 'Resources stockpiled for technological ordering', 'A river becomes standing reserve once dammed for power.'),
  Word('philosophy', 'aletheia', 'n.', 'Truth understood as unconcealment rather than mere correctness', 'Heidegger revived aletheia from the pre-Socratic Greeks.'),
  Word('philosophy', 'ereignis', 'n.', 'A primordial event of appropriation in later Heidegger', 'Ereignis names how being and human belong together.'),
  Word('philosophy', 'epoche', 'n.', 'The phenomenological bracketing of naive assumptions', 'Husserl\'s epoche suspends judgment so phenomena can speak.'),
  Word('philosophy', 'intentionality', 'n.', 'The directedness of consciousness toward objects', 'Every thought, on Husserl\'s view, has intentionality.'),
  Word('philosophy', 'noesis', 'n.', 'The mental act of intending an object', 'Each noesis aims at its correlate, the noema.'),
  Word('philosophy', 'noema', 'n.', 'The intended content of a conscious act', 'The noema of perception is the object as meant.'),
  Word('philosophy', 'lifeworld', 'n.', 'The pre-theoretical world of shared everyday meanings', 'Husserl insisted that even science presupposes the lifeworld.'),
  Word('philosophy', 'flesh', 'n.', 'Merleau-Ponty\'s name for the shared sensuous fabric of perceiver and world', 'The flesh dissolves the partition between body and things.'),
  Word('philosophy', 'embodiment', 'n.', 'The bodily condition that shapes thought and perception', 'Embodiment is central in feminist and phenomenological ethics.'),
  Word('philosophy', 'lived-body', 'n.', 'The body as experienced from the inside, not as a biological object', 'Pain belongs to the lived body, not the body of anatomy.'),
  Word('philosophy', 'horizon', 'n.', 'The implicit background that frames any explicit content', 'A perception always carries a horizon of further possible perceptions.'),
  Word('philosophy', 'eidos', 'n.', 'The essential structure grasped through eidetic intuition', 'Husserl sought the eidos of memory by varying examples in imagination.'),
  Word('philosophy', 'eidetic-reduction', 'n.', 'Stripping away particulars to reach an essence', 'The eidetic reduction works by free variation in fantasy.'),
  Word('philosophy', 'gadamerian', 'adj.', 'Of Gadamer\'s view that understanding fuses horizons of interpreter and text', 'A Gadamerian reading prizes dialogue with tradition.'),
  Word('philosophy', 'fusion-of-horizons', 'n.', 'The merging of an interpreter\'s and text\'s contexts in understanding', 'Translation aims at a fusion of horizons, not a transparent copy.'),
  Word('philosophy', 'hermeneutic-circle', 'n.', 'The reciprocal interpretation of parts in light of the whole', 'You cannot escape the hermeneutic circle, only enter it well.'),
  Word('philosophy', 'prejudice', 'n.', 'A pre-judgment that, for Gadamer, makes understanding possible', 'Prejudice in this sense is not a bias to overcome but a condition to recognize.'),
  Word('philosophy', 'effective-history', 'n.', 'The way past events keep shaping later understandings', 'Effective history saturates the questions we bring to a text.'),
  Word('philosophy', 'tradition', 'n.', 'A living transmission of meanings that an interpreter inhabits', 'Tradition is not a museum but a conversation in progress.'),
  Word('philosophy', 'critical-theory', 'n.', 'A school combining philosophy and social critique to emancipate', 'Critical theory traces the irrationalities behind apparently rational systems.'),
  Word('philosophy', 'culture-industry', 'n.', 'Adorno\'s name for mass culture as a standardized commodity', 'The culture industry sells false individuation by the unit.'),
  Word('philosophy', 'instrumental-reason', 'n.', 'Reason narrowed to efficient means-ends calculation', 'Instrumental reason can optimize anything while questioning nothing.'),
  Word('philosophy', 'communicative-action', 'n.', 'Habermas\'s reason oriented to mutual understanding', 'Communicative action grounds legitimacy in unforced argument.'),
  Word('philosophy', 'discourse-ethics', 'n.', 'A norm is valid if all affected could consent in fair discourse', 'Discourse ethics ties morality to ideal communication.'),
  Word('philosophy', 'ideal-speech-situation', 'n.', 'Habermas\'s thought experiment of perfectly open dialogue', 'In the ideal speech situation only the better argument wins.'),
  Word('philosophy', 'public-sphere', 'n.', 'A space of citizen reasoning between state and private life', 'Habermas charted the rise and decline of the bourgeois public sphere.'),
  Word('philosophy', 'biopolitics', 'n.', 'Power that takes biological life as its target and instrument', 'Foucault\'s biopolitics studies how populations are governed as living masses.'),
  Word('philosophy', 'discipline', 'n.', 'Foucault\'s power that trains bodies through routine and surveillance', 'Schools and prisons share the technologies of discipline.'),
  Word('philosophy', 'panopticon', 'n.', 'Bentham\'s ring-prison turned by Foucault into a figure of constant gaze', 'Modern surveillance generalizes the panopticon to everyday life.'),
  Word('philosophy', 'episteme', 'n.', 'The historical framework that defines what counts as knowledge', 'A shift in episteme reorganizes every science at once.'),
  Word('philosophy', 'governmentality', 'n.', 'The rationality through which states conduct conduct', 'Liberal governmentality acts at a distance through freedom itself.'),
  Word('philosophy', 'subjectivation', 'n.', 'The process by which power produces particular kinds of selves', 'Subjectivation makes us subjects of our own scrutiny.'),
  Word('philosophy', 'power-knowledge', 'n.', 'Foucault\'s thesis that knowledge and power constitute each other', 'There is no neutral diagnosis: every power-knowledge classifies and rules.'),
  Word('philosophy', 'deconstruction', 'n.', 'Derrida\'s reading practice that exposes hidden hierarchies in texts', 'Deconstruction is not destruction but loosening from within.'),
  Word('philosophy', 'differance', 'n.', 'Derrida\'s coinage for difference plus deferral of meaning', 'Differance shows that no sign stands fully present to itself.'),
  Word('philosophy', 'logocentrism', 'n.', 'A privileging of speech and presence over writing and absence', 'Western metaphysics, Derrida argued, has been logocentric for millennia.'),
  Word('philosophy', 'trace', 'n.', 'The mark of an absent other within any sign or presence', 'Every present moment carries the trace of past and future.'),
  Word('philosophy', 'pharmakon', 'n.', 'Derrida\'s term for something both remedy and poison', 'Writing functions as a pharmakon in Plato\'s Phaedrus.'),
  Word('philosophy', 'supplement', 'n.', 'An addition that turns out to be necessary to what it merely supplements', 'Derrida shows how each supplement undermines the supposed original.'),
  Word('philosophy', 'iterability', 'n.', 'The repeatability that makes any sign a sign at all', 'Iterability lets meaning travel beyond its original context.'),
  Word('philosophy', 'simulacrum', 'n.', 'A copy that has no original to which it refers', 'Baudrillard\'s simulacrum precedes and produces the real.'),
  Word('philosophy', 'hyperreal', 'n.', 'A condition where simulations seem realer than reality', 'A theme-park kingdom can feel more hyperreal than the actual country.'),
  Word('philosophy', 'rhizome', 'n.', 'Deleuze and Guattari\'s image of nonhierarchical connection', 'A rhizome spreads sideways without a central root.'),
  Word('philosophy', 'territorialization', 'n.', 'Capturing flows into stable codes and identities', 'Marketing territorializes desire into demographic boxes.'),
  Word('philosophy', 'body-without-organs', 'n.', 'A surface of unstructured intensities prior to organization', 'The body without organs resists being settled into a working system.'),
  Word('philosophy', 'becoming', 'n.', 'A process of differential transformation rather than fixed identity', 'Deleuze prefers becoming to being as a metaphysical category.'),
  Word('philosophy', 'difference-philosophy', 'n.', 'Deleuze\'s primacy of difference over identity and resemblance', 'A philosophy of difference reverses Platonism from within.'),
  Word('philosophy', 'event', 'n.', 'In Badiou and others, an irruption that breaks the established situation', 'A genuine event creates new subjects faithful to it.'),
  Word('philosophy', 'situation', 'n.', 'Badiou\'s structured set of what counts as existing', 'Truth procedures supplement a situation with its own excess.'),
  Word('philosophy', 'fidelity', 'n.', 'Sustained loyalty to the implications of a transforming event', 'Political fidelity binds militants long after the rally ends.'),
  Word('philosophy', 'meta-ethics', 'n.', 'The study of the nature of moral language and facts', 'Meta-ethics asks what good means before asking which actions are good.'),
  Word('philosophy', 'normative-ethics', 'n.', 'The study of which actions or characters are morally required', 'Normative ethics builds and tests principles for living well.'),
  Word('philosophy', 'applied-ethics', 'n.', 'The use of ethical theory on concrete practical issues', 'Applied ethics tackles cases like triage, war, and AI.'),
  Word('philosophy', 'moral-realism', 'n.', 'The view that moral facts exist independently of beliefs', 'Moral realism holds that cruelty is wrong, full stop.'),
  Word('philosophy', 'moral-anti-realism', 'n.', 'A denial of mind-independent moral facts', 'Moral anti-realism need not collapse into anything goes.'),
  Word('philosophy', 'error-theory', 'n.', 'Mackie\'s claim that moral statements are systematically false', 'Error theory keeps moral talk meaningful while denying its truth.'),
  Word('philosophy', 'expressivism', 'n.', 'A view that moral claims express attitudes rather than facts', 'Expressivism sidesteps queerness worries about moral entities.'),
  Word('philosophy', 'emotivism', 'n.', 'A simple expressivism: moral talk just vents approval or disgust', 'Ayer\'s emotivism reduced ethics to hurrahs and boos.'),
  Word('philosophy', 'prescriptivism', 'n.', 'A view that moral judgments are universalizable commands', 'Hare\'s prescriptivism made consistency the heart of moral talk.'),
  Word('philosophy', 'constructivism-ethics', 'n.', 'A view that moral truths follow from idealized agreement', 'Korsgaard\'s constructivism roots obligation in self-legislation.'),
  Word('philosophy', 'reflective-equilibrium', 'n.', 'Adjusting principles and judgments until they cohere', 'Rawls reaches his principles by reflective equilibrium.'),
  Word('philosophy', 'overlapping-consensus', 'n.', 'Agreement on principles for political reasons from different worldviews', 'An overlapping consensus stabilizes a pluralist liberal order.'),
  Word('philosophy', 'public-reason', 'n.', 'Reasons citizens can offer each other across deep disagreement', 'Public reason restricts the kinds of grounds invoked in legitimation.'),
  Word('philosophy', 'veil', 'n.', 'A device that hides facts about oneself to ensure impartial choice', 'Behind a veil, no one knows their station or talents.'),
  Word('philosophy', 'original-position', 'n.', 'Rawls\'s imagined setup for choosing principles of justice', 'In the original position, fairness comes from ignorance of one\'s lot.'),
  Word('philosophy', 'difference-principle', 'n.', 'A rule allowing inequalities only if they help the worst off', 'Rawls\'s difference principle is famously demanding in practice.'),
  Word('philosophy', 'primary-goods', 'n.', 'Resources any rational person wants whatever their plan of life', 'Income and rights count as primary goods in Rawls\'s scheme.'),
  Word('philosophy', 'capabilities', 'n.', 'Sen and Nussbaum\'s real freedoms to be and do various things', 'Capabilities focus on what people can actually achieve.'),
  Word('philosophy', 'libertarianism', 'n.', 'A view giving wide priority to individual liberty and property', 'Nozick\'s libertarianism rejects redistributive taxation as forced labor.'),
  Word('philosophy', 'entitlement-theory', 'n.', 'Justice as just acquisition, transfer, and rectification', 'Entitlement theory traces holdings rather than judging end states.'),
  Word('philosophy', 'communitarianism', 'n.', 'A view emphasizing situated identity and shared traditions', 'Communitarians criticize the abstract self of liberal theory.'),
  Word('philosophy', 'liberalism', 'n.', 'A political tradition centered on liberty, rights, and toleration', 'Liberalism today wrestles with its old commitments under new pressures.'),
  Word('philosophy', 'republicanism', 'n.', 'A view valuing freedom as non-domination by arbitrary power', 'Civic republicanism stresses participation and the rule of law.'),
  Word('philosophy', 'non-domination', 'n.', 'Freedom as the absence of being subject to another\'s arbitrary will', 'Non-domination protects more than the absence of interference.'),
  Word('philosophy', 'negative-liberty', 'n.', 'Freedom from external interference by others', 'Berlin\'s negative liberty asks how many doors stand open to you.'),
  Word('philosophy', 'positive-liberty', 'n.', 'Freedom as self-mastery and the capacity to realize ends', 'Positive liberty can shade into telling people what their true self wants.'),
  Word('philosophy', 'sovereignty', 'n.', 'Supreme political authority over a territory and people', 'Sovereignty has been contested since the wars of religion.'),
  Word('philosophy', 'state-of-exception', 'n.', 'A suspension of normal law claimed in emergency', 'Schmitt and Agamben analyze how the state of exception becomes the rule.'),
  Word('philosophy', 'biopower', 'n.', 'Power exercised over populations as biological entities', 'Public health policy operates squarely in the field of biopower.'),
  Word('philosophy', 'hegemony', 'n.', 'Gramsci\'s rule by cultural consent more than by force', 'Hegemony makes the rulers\' worldview seem like common sense.'),
  Word('philosophy', 'organic-intellectual', 'n.', 'A thinker tied to and arising from a social class', 'Every group, Gramsci wrote, generates its own organic intellectuals.'),
  Word('philosophy', 'subaltern', 'n.', 'Those positioned outside dominant structures of representation', 'Spivak asked whether the subaltern can speak in their own voice.'),
  Word('philosophy', 'postcolonial', 'adj.', 'Concerning the legacies of colonialism in thought and politics', 'Postcolonial critique unsettles the universals of European philosophy.'),
  Word('philosophy', 'orientalism', 'n.', 'Said\'s name for the West\'s framing of the East as exotic other', 'Orientalism shapes scholarship even when it claims neutrality.'),
  Word('philosophy', 'feminist-epistemology', 'n.', 'A study of how gender shapes what counts as knowledge', 'Feminist epistemology probes the supposed view from nowhere.'),
  Word('philosophy', 'standpoint', 'n.', 'A view that some social positions afford special epistemic access', 'Standpoint theory grants situated knowers a critical edge.'),
  Word('philosophy', 'situated-knowledge', 'n.', 'Knowledge tied to a particular embodied, social location', 'Haraway\'s situated knowledge rejects the god trick of objectivity.'),
  Word('philosophy', 'care-ethics', 'n.', 'A morality centered on relationships of responsiveness and need', 'Care ethics arose from feminist critique of impartial principles.'),
  Word('philosophy', 'consequentialism', 'n.', 'A family of theories judging acts by their outcomes', 'Consequentialism asks not what you did but what came of it.'),
  Word('philosophy', 'act-utilitarianism', 'n.', 'A view that the right act maximizes utility on each occasion', 'Act-utilitarianism can recommend disturbing individual choices.'),
  Word('philosophy', 'rule-utilitarianism', 'n.', 'A view that the right act follows rules whose general use maximizes utility', 'Rule-utilitarianism reins in some of its act-version\'s wilder verdicts.'),
  Word('philosophy', 'utility', 'n.', 'A measure of welfare, often glossed as pleasure minus pain', 'Bentham\'s utility was meant to be calculated like a budget.'),
  Word('philosophy', 'felicific-calculus', 'n.', 'Bentham\'s scheme for weighing pleasures and pains', 'The felicific calculus reads like accounting for happiness.'),
  Word('philosophy', 'higher-and-lower-pleasures', 'n.', 'Mill\'s distinction between intellectual and bodily satisfactions', 'Mill thought higher and lower pleasures could not be set on the same scale.'),
  Word('philosophy', 'trolley-problem', 'n.', 'A thought experiment about diverting harm onto fewer people', 'The trolley problem stress-tests intuitions about doing and allowing.'),
  Word('philosophy', 'doctrine-of-double-effect', 'n.', 'Permitting foreseen harms that are not intended as means', 'The doctrine of double effect plays a role in just war ethics.'),
  Word('philosophy', 'doing-allowing', 'n.', 'A distinction between actively causing and letting harm happen', 'Doing-allowing distinctions complicate utilitarian symmetries.'),
  Word('philosophy', 'agent-relative', 'adj.', 'Concerning reasons or duties tied to a specific agent\'s perspective', 'Special obligations to one\'s family are agent-relative.'),
  Word('philosophy', 'agent-neutral', 'adj.', 'Concerning reasons valid for any agent impartially', 'Maximizing total welfare is an agent-neutral aim.'),
  Word('philosophy', 'supererogation', 'n.', 'Acts of moral excellence beyond what duty requires', 'Supererogation lets us praise heroes without condemning ordinary people.'),
  Word('philosophy', 'supererogatory', 'adj.', 'Above and beyond the call of moral duty', 'A supererogatory rescue is admirable rather than obligatory.'),
  Word('philosophy', 'prima-facie-duty', 'n.', 'A duty that holds unless overridden by another duty', 'Ross built ethics from a plurality of prima facie duties.'),
  Word('philosophy', 'moral-luck', 'n.', 'The role of chance in shaping a person\'s moral standing', 'Moral luck unsettles the idea that responsibility lies solely with the will.'),
  Word('philosophy', 'akrasia-extended', 'n.', 'Acting against one\'s own better judgment', 'Akrasia is the philosopher\'s name for weakness of will.'),
  Word('philosophy', 'continence', 'n.', 'Acting rightly despite contrary desires', 'Continence is good behavior won against the grain.'),
  Word('philosophy', 'temperance', 'n.', 'Moderation in pleasures and appetites', 'Temperance keeps appetite in service of the good life.'),
  Word('philosophy', 'magnanimity', 'n.', 'Greatness of soul in pursuing honor and noble ends', 'Aristotle\'s magnanimity sits uncomfortably with modern egalitarianism.'),
  Word('philosophy', 'mean', 'n.', 'Aristotle\'s virtuous middle between deficiency and excess', 'Courage is the mean between cowardice and recklessness.'),
  Word('philosophy', 'practical-wisdom', 'n.', 'The capacity to deliberate well about what to do', 'Practical wisdom cannot be reduced to rules.'),
  Word('philosophy', 'natural-rights', 'n.', 'Rights claimed to belong to humans by nature, not convention', 'The Declaration of Independence appeals to natural rights.'),
  Word('philosophy', 'rights-claim', 'n.', 'A justified entitlement to act or be treated in some way', 'A rights-claim gives shape to political demands.'),
  Word('philosophy', 'positive-right', 'n.', 'A right that obliges others to provide goods or services', 'A positive right to healthcare imposes burdens of provision.'),
  Word('philosophy', 'negative-right', 'n.', 'A right that obliges others not to interfere', 'A negative right of free speech demands restraint, not subsidy.'),
  Word('philosophy', 'human-dignity', 'n.', 'An inherent worth attributed to every person', 'Human dignity grounds many international human rights documents.'),
  Word('philosophy', 'cosmopolitanism', 'n.', 'A view that moral concern extends to all humans equally', 'Stoic cosmopolitanism imagined a city of the world.'),
  Word('philosophy', 'patriotism', 'n.', 'Love of one\'s country, often defended as a moral allegiance', 'Liberal patriotism tries to combine attachment with critique.'),
  Word('philosophy', 'just-war', 'n.', 'A tradition assessing the morality of going to and conducting war', 'Just war theory weighs both jus ad bellum and jus in bello.'),
  Word('philosophy', 'jus-ad-bellum', 'phr.', 'Right to wage war, the conditions making war justified', 'Jus ad bellum demands legitimate authority and just cause.'),
  Word('philosophy', 'jus-in-bello', 'phr.', 'Right within war, the rules of moral conduct in fighting', 'Jus in bello forbids targeting noncombatants.'),
  Word('philosophy', 'proportionality', 'n.', 'A constraint that harms inflicted must not outweigh goods sought', 'Proportionality is a perennial check in ethics of force.'),
  Word('philosophy', 'noncombatant-immunity', 'n.', 'A norm protecting civilians from being directly attacked', 'Noncombatant immunity gives just war its sharpest moral edge.'),
  Word('philosophy', 'pacifism', 'n.', 'A view opposing the use of war or violent force', 'Pacifism ranges from absolute to strategic varieties.'),
  Word('philosophy', 'civil-disobedience', 'n.', 'Public, nonviolent breaking of law to protest injustice', 'Civil disobedience accepts punishment to dramatize wrong.'),
  Word('philosophy', 'political-obligation', 'n.', 'A duty to obey the laws of one\'s political community', 'Political obligation is harder to ground than most assume.'),
  Word('philosophy', 'consent-theory', 'n.', 'Authority is legitimate only with the consent of the governed', 'Tacit consent theories try to plug obvious gaps in consent theory.'),
  Word('philosophy', 'fair-play', 'n.', 'A duty arising from accepting benefits of cooperative schemes', 'Fair play theory grounds obligation in benefits already enjoyed.'),
  Word('philosophy', 'gratitude-theory', 'n.', 'Political duty grounded in benefits received from the state', 'Gratitude theory faces hard cases of unwanted benefits.'),
  Word('philosophy', 'paternalism', 'n.', 'Restricting a person\'s liberty for their own supposed good', 'Mill mostly opposed paternalism over competent adults.'),
  Word('philosophy', 'harm-principle', 'n.', 'A principle restricting liberty only to prevent harm to others', 'The harm principle anchors a liberal account of state coercion.'),
  Word('philosophy', 'perfectionism', 'n.', 'A view that the state may promote some conceptions of the good life', 'Perfectionism challenges strict liberal neutrality.'),
  Word('philosophy', 'neutrality-political', 'n.', 'A liberal demand that the state not favor any one conception of the good', 'Political neutrality is harder to achieve than to define.'),
  Word('philosophy', 'gettier', 'n.', 'A counterexample showing justified true belief can fail to be knowledge', 'A Gettier case has a lucky truth disconnected from its justification.'),
  Word('philosophy', 'justified-true-belief', 'n.', 'A classical analysis of knowledge as belief that is true and warranted', 'Justified true belief survived twenty centuries before Gettier shook it.'),
  Word('philosophy', 'reliabilism', 'n.', 'A theory taking knowledge to issue from reliable belief-forming processes', 'Reliabilism handles perception cases well but stumbles on demons.'),
  Word('philosophy', 'foundationalism', 'n.', 'A view that justified belief rests on basic non-inferential beliefs', 'Foundationalism aims to stop the regress of reasons.'),
  Word('philosophy', 'coherentism', 'n.', 'A view that beliefs are justified by mutual support within a web', 'Coherentism trades foundations for a self-supporting net.'),
  Word('philosophy', 'infinitism', 'n.', 'A view that justification comes from an endless chain of reasons', 'Infinitism is rare but harder to refute than it sounds.'),
  Word('philosophy', 'closure', 'n.', 'A principle that knowledge extends across known entailments', 'Closure is invoked and resisted in debates over skepticism.'),
  Word('philosophy', 'brain-in-a-vat', 'n.', 'A modern skeptical scenario of a deceived envatted mind', 'The brain-in-a-vat updates Descartes\'s evil demon for neuroscience.'),
  Word('philosophy', 'simulation-argument', 'n.', 'An argument suggesting we may live inside a computer simulation', 'Bostrom\'s simulation argument leans on probability not metaphysics.'),
  Word('philosophy', 'transcendental-argument', 'n.', 'An argument that some condition must hold for experience to be possible', 'A transcendental argument tries to silence skepticism from within.'),
  Word('philosophy', 'private-language-argument', 'n.', 'Wittgenstein\'s case against a language only the speaker could understand', 'The private language argument targets a tempting Cartesian picture.'),
  Word('philosophy', 'family-resemblance', 'n.', 'Wittgenstein\'s image of overlapping similarities without one shared feature', 'Game shows family resemblance, not a tidy essence.'),
  Word('philosophy', 'language-game', 'n.', 'A patterned activity in which words gain their use', 'Different language games carry different criteria of correctness.'),
  Word('philosophy', 'form-of-life', 'n.', 'A shared human practice that makes language games intelligible', 'A form of life is what we ultimately have to accept.'),
  Word('philosophy', 'meaning-as-use', 'n.', 'A view tying a word\'s meaning to its role in practice', 'Meaning as use shifts attention from definitions to deployments.'),
  Word('philosophy', 'rule-following', 'n.', 'Wittgenstein\'s puzzle about what fixes the correct extension of a rule', 'Rule-following considerations refuse a hidden act of meaning.'),
  Word('philosophy', 'picture-theory', 'n.', 'The early Wittgenstein\'s account of propositions as pictures of facts', 'The picture theory tied meaning to logical isomorphism.'),
  Word('philosophy', 'verification-principle', 'n.', 'A claim that meaning is exhausted by methods of verification', 'The verification principle famously failed to verify itself.'),
  Word('philosophy', 'logical-positivism', 'n.', 'An early-twentieth-century movement uniting science and logic against metaphysics', 'Logical positivism tried to put philosophy on a strict diet.'),
  Word('philosophy', 'protocol-sentence', 'n.', 'A basic observation report meant to anchor scientific knowledge', 'Neurath worried that even protocol sentences are theory-laden.'),
  Word('philosophy', 'unity-of-science', 'n.', 'A program to translate all sciences into one common language', 'The unity of science movement aimed at a shared physical idiom.'),
  Word('philosophy', 'physicalism', 'n.', 'The view that everything that exists is physical in nature', 'Modern physicalism asks how the mental relates to the physical.'),
  Word('philosophy', 'token-physicalism', 'n.', 'A view that each mental event is identical to some physical event', 'Token physicalism allows different physical realizers across minds.'),
  Word('philosophy', 'type-physicalism', 'n.', 'A stronger view identifying mental types with physical types', 'Type physicalism faces the multiple realizability objection.'),
  Word('philosophy', 'multiple-realizability', 'n.', 'A property realized by many distinct physical structures', 'Multiple realizability suggests pain need not be one brain state.'),
  Word('philosophy', 'functionalism', 'n.', 'A view that mental states are defined by their functional roles', 'Functionalism treats mind as software running on neural hardware.'),
  Word('philosophy', 'behaviorism', 'n.', 'A view reducing mental states to dispositions to behave', 'Logical behaviorism stumbled on the felt quality of experience.'),
  Word('philosophy', 'eliminativism', 'n.', 'A claim that folk psychological categories may not exist', 'Eliminativism predicts neuroscience will replace belief and desire.'),
  Word('philosophy', 'folk-psychology', 'n.', 'Our everyday framework of beliefs, desires, and intentions', 'Folk psychology gets daily life surprisingly right.'),
  Word('philosophy', 'qualia-thought-experiment', 'n.', 'A scenario probing what subjective experience consists in', 'Mary the color scientist is a famous qualia thought experiment.'),
  Word('philosophy', 'inverted-spectrum', 'n.', 'A hypothetical with swapped color qualia behaving identically', 'The inverted spectrum makes functional sameness diverge from experience.'),
  Word('philosophy', 'zombie', 'n.', 'A hypothetical creature physically identical to a person but without experience', 'Philosophical zombies probe whether consciousness is conceptually distinct.'),
  Word('philosophy', 'hard-problem', 'n.', 'Chalmers\'s problem of explaining why physical processes feel like anything', 'The hard problem cleaves consciousness from easy functional puzzles.'),
  Word('philosophy', 'panpsychism', 'n.', 'A view that some form of mind pervades all matter', 'Panpsychism is no longer the fringe position it once was.'),
  Word('philosophy', 'emergence', 'n.', 'A property that arises from but is not reducible to its parts', 'Emergence is invoked to explain consciousness, life, and culture.'),
  Word('philosophy', 'supervenience', 'n.', 'A relation where no change in one level occurs without change below', 'The mental supervenes on the physical, many philosophers grant.'),
  Word('philosophy', 'extended-mind', 'n.', 'A view that cognition can include tools and environment', 'Clark and Chalmers argued for an extended mind that crosses the skull.'),
  Word('philosophy', 'embodied-cognition', 'n.', 'A view that thinking depends on bodily form and action', 'Embodied cognition reads abstractions out of sensorimotor schemas.'),
  Word('philosophy', 'enactivism', 'n.', 'A view that cognition emerges from active engagement with the world', 'Enactivism brings phenomenology together with biology.'),
  Word('philosophy', 'chinese-room', 'n.', 'Searle\'s thought experiment against pure symbol manipulation as understanding', 'The Chinese room asks whether running a program could be enough for meaning.'),
  Word('philosophy', 'turing-test', 'n.', 'A proposal for assessing machine intelligence by indistinguishable conversation', 'The Turing test prioritized behavior over inner experience.'),
  Word('philosophy', 'frame-problem', 'n.', 'The challenge of representing what does and does not change with an action', 'The frame problem haunts both classic AI and philosophy of mind.'),
  Word('philosophy', 'mental-causation', 'n.', 'The question of how mental events bring about physical effects', 'Mental causation worries any view that treats minds as separate.'),
  Word('philosophy', 'epiphenomenalism', 'n.', 'A view that mental states are caused but have no causal effect', 'Epiphenomenalism makes consciousness a passenger on the brain.'),
  Word('philosophy', 'sense', 'n.', 'Frege\'s mode of presentation of a reference', 'Hesperus and Phosphorus share a reference but differ in sense.'),
  Word('philosophy', 'reference', 'n.', 'What a term picks out in the world', 'A definite description fixes reference through a uniqueness condition.'),
  Word('philosophy', 'rigid-designator', 'n.', 'A term that refers to the same thing in every possible world', 'Kripke argued that names are rigid designators.'),
  Word('philosophy', 'possible-world', 'n.', 'A way the world could have been, used to model modality', 'Necessity is truth in every possible world.'),
  Word('philosophy', 'modal-realism', 'n.', 'Lewis\'s view that all possible worlds exist as concretely as ours', 'Modal realism explains modality at the price of an enormous ontology.'),
  Word('philosophy', 'counterpart', 'n.', 'A similar individual in another possible world used in place of identity across worlds', 'Counterpart theory replaces transworld identity with similarity relations.'),
  Word('philosophy', 'identity-of-truth', 'n.', 'The view that truth is correspondence to fact', 'A correspondence theory of truth is the simplest folk picture.'),
  Word('philosophy', 'correspondence', 'n.', 'A relation between a true statement and an answering fact', 'Correspondence theories prosper or struggle with what facts are.'),
  Word('philosophy', 'coherence-truth', 'n.', 'Truth as fitting within an integrated set of beliefs', 'A coherence theory of truth ties truth to systemic consistency.'),
  Word('philosophy', 'deflationism', 'n.', 'A view that truth is not a substantive property worth analyzing', 'Deflationism takes saying it is true to add nothing of importance.'),
  Word('philosophy', 'minimalism-truth', 'n.', 'A version of deflationism centered on the equivalence schema', 'Minimalism captures truth with instances of the schema p is true iff p.'),
  Word('philosophy', 'pragmatic-truth', 'n.', 'Truth understood by its workability or fruitfulness in inquiry', 'A pragmatic truth is what inquiry would converge upon.'),
  Word('philosophy', 'inference-to-best-explanation', 'phr.', 'Reasoning that infers a hypothesis as the likeliest explanation', 'Detective work and theoretical science share inference to best explanation.'),
  Word('philosophy', 'abduction', 'n.', 'Peirce\'s name for generating explanatory hypotheses', 'Abduction proposes; deduction and induction test.'),
  Word('philosophy', 'falsifiability', 'n.', 'Popper\'s mark of a scientific theory: it forbids some observations', 'Falsifiability separates science from pseudo-science for Popper.'),
  Word('philosophy', 'paradigm', 'n.', 'Kuhn\'s framework of assumptions guiding normal science', 'A reigning paradigm sets the puzzles that scientists work on.'),
  Word('philosophy', 'paradigm-shift', 'n.', 'A revolutionary change in scientific worldview', 'Quantum mechanics produced a wrenching paradigm shift.'),
  Word('philosophy', 'incommensurability', 'n.', 'A claim that rival paradigms lack a shared neutral measure', 'Incommensurability complicates clean victories between theories.'),
  Word('philosophy', 'duhem-quine-thesis', 'n.', 'A claim that theories face evidence as wholes, not piecewise', 'The Duhem-Quine thesis lets us save hypotheses by adjusting auxiliaries.'),
  Word('philosophy', 'underdetermination', 'n.', 'Multiple theories fitting the same data equally well', 'Underdetermination is a perennial worry for scientific realism.'),
  Word('philosophy', 'scientific-realism', 'n.', 'A view that successful science describes a mind-independent reality', 'Scientific realism takes electrons to be more than convenient fictions.'),
  Word('philosophy', 'instrumentalism', 'n.', 'A view that theories are instruments for prediction rather than truth', 'Instrumentalism sees laws as tools, not portraits.'),
  Word('philosophy', 'constructive-empiricism', 'n.', 'Van Fraassen\'s view aiming science at empirical adequacy', 'Constructive empiricism trims realism without slipping into pure tools talk.'),
  Word('philosophy', 'no-miracles', 'n.', 'An argument that scientific success would be miraculous if science were not roughly true', 'The no-miracles argument is realism\'s favorite line.'),
  Word('philosophy', 'pessimistic-induction', 'n.', 'An argument from past failed theories to skepticism about current ones', 'The pessimistic induction warns realists of historical hubris.'),
  Word('philosophy', 'natural-kind', 'n.', 'A category carving nature at its joints', 'Gold is a natural kind in a way that brunches are not.'),
  Word('philosophy', 'essentialism', 'n.', 'A view that things have necessary defining properties', 'Kripkean essentialism revived essentialism for water and tigers.'),
  Word('philosophy', 'anti-essentialism', 'n.', 'A denial that categories have necessary defining properties', 'Anti-essentialism aligns with much social construction theory.'),
  Word('philosophy', 'social-construction', 'n.', 'The making of categories or facts through social practice', 'Social construction of race rejects biological essentialism.'),
  Word('philosophy', 'institutional-fact', 'n.', 'A fact existing only because we collectively accept it', 'Money is an institutional fact resting on shared recognition.'),
  Word('philosophy', 'collective-intentionality', 'n.', 'The shared intentions that constitute group actions', 'Collective intentionality underlies promises, marches, and orchestras.'),
  Word('philosophy', 'speech-act', 'n.', 'An utterance that performs an action, not merely reports', 'Promising is a paradigmatic speech act.'),
  Word('philosophy', 'illocutionary', 'adj.', 'Of the act performed in saying something', 'An illocutionary force can be assertion, command, or apology.'),
  Word('philosophy', 'perlocutionary', 'adj.', 'Of the effects produced in others by saying something', 'A perlocutionary outcome of a warning is fear.'),
  Word('philosophy', 'performative', 'adj.', 'Of an utterance that does what it says in saying it', 'I now pronounce you married is performative, not descriptive.'),
  Word('philosophy', 'use-mention', 'n.', 'A distinction between using a word and talking about it', 'Mixing up use and mention generates classic confusions.'),
  Word('philosophy', 'extension', 'n.', 'The set of things to which a term applies', 'The extension of red includes every red object.'),
  Word('philosophy', 'intension', 'n.', 'The conceptual content that determines extension', 'Two terms can share extension but differ in intension.'),
  Word('philosophy', 'de-dicto', 'phr.', 'Of an attitude attached to the way a thing is described', 'A de dicto belief depends on the description used.'),
  Word('philosophy', 'de-re', 'phr.', 'Of an attitude directed at a thing however described', 'A de re belief tracks the object across rephrasings.'),
  Word('philosophy', 'twin-earth', 'n.', 'Putnam\'s thought experiment showing meanings depend on the world', 'On Twin Earth the watery liquid is XYZ, not H2O.'),
  Word('philosophy', 'externalism', 'n.', 'A view that mental content depends on factors outside the head', 'Externalism is the lesson of Twin Earth for many readers.'),
  Word('philosophy', 'internalism', 'n.', 'A view that mental content depends only on internal facts about the agent', 'Internalism keeps meaning narrow and personal.'),
  Word('philosophy', 'a-priori-knowledge', 'n.', 'Knowledge gained independently of experience', 'Mathematical knowledge has long been a paradigm of a priori knowledge.'),
  Word('philosophy', 'a-posteriori-knowledge', 'n.', 'Knowledge gained through experience', 'That the kettle is boiling is a posteriori knowledge.'),
  Word('philosophy', 'necessary-truth', 'n.', 'A truth that could not have been otherwise', 'Mathematical theorems express necessary truths.'),
  Word('philosophy', 'contingent-truth', 'n.', 'A truth that could have been otherwise', 'Most political facts are contingent truths.'),
  Word('philosophy', 'analytic-synthetic-distinction', 'n.', 'A contrast between truths by meaning and truths by fact', 'Quine attacked the analytic-synthetic distinction as a dogma of empiricism.'),
  Word('philosophy', 'two-dogmas', 'n.', 'Quine\'s critique of analyticity and reductionism', 'Two Dogmas of Empiricism reshaped midcentury philosophy.'),
  Word('philosophy', 'web-of-belief', 'n.', 'Quine\'s image of beliefs as a connected fabric meeting experience at the edges', 'In the web of belief no single sentence faces the world alone.'),
  Word('philosophy', 'naturalized-epistemology', 'n.', 'Quine\'s proposal that epistemology become a chapter of science', 'Naturalized epistemology blurs philosophy with empirical psychology.'),
  Word('philosophy', 'ontological-commitment', 'n.', 'Quine\'s test for what a theory says exists by its quantifiers', 'To be is to be the value of a bound variable, Quine quipped.'),
  Word('philosophy', 'sortal', 'n.', 'A noun that supplies a principle of counting and identity', 'A sortal answers questions like how many of this kind are present.'),
  Word('philosophy', 'mereology', 'n.', 'The formal study of parts and wholes', 'Mereology offers cleaner tools than vague talk of parthood.'),
  Word('philosophy', 'composition-as-identity', 'n.', 'A view that a whole is nothing over and above its parts taken together', 'Composition as identity is parsimonious but counterintuitive.'),
  Word('philosophy', 'four-dimensionalism', 'n.', 'A view that objects extend through time as they do through space', 'Four-dimensionalism treats persons as long worms in spacetime.'),
  Word('philosophy', 'endurantism', 'n.', 'A view that objects are wholly present at each time they exist', 'Endurantism honors the everyday sense of being one thing over time.'),
  Word('philosophy', 'perdurantism', 'n.', 'A view that objects persist by having temporal parts', 'Perdurantism dovetails with relativistic physics for some metaphysicians.'),
  Word('philosophy', 'presentism', 'n.', 'A view that only present things exist', 'Presentism makes time pass, but strains relativity.'),
  Word('philosophy', 'eternalism', 'n.', 'A view that past, present, and future are equally real', 'Eternalism sees the universe as a block of spacetime.'),
  Word('philosophy', 'a-series', 'n.', 'McTaggart\'s temporal series of past, present, and future', 'The A-series locates events relative to now.'),
  Word('philosophy', 'unreality-of-time', 'n.', 'McTaggart\'s controversial argument that time does not really exist', 'The unreality of time argument still divides metaphysicians.'),
  Word('philosophy', 'ship-of-theseus', 'n.', 'A puzzle about identity when every part is gradually replaced', 'The ship of Theseus crops up whenever we restore an old building.'),
  Word('philosophy', 'sorites', 'n.', 'A paradox about vague predicates and small differences', 'The sorites asks when a heap of sand stops being a heap.'),
  Word('philosophy', 'vagueness', 'n.', 'A property of terms admitting borderline cases', 'Vagueness is no minor language quirk but a deep semantic issue.'),
  Word('philosophy', 'epistemicism', 'n.', 'A view that vague terms have sharp boundaries we cannot know', 'Epistemicism is bold but rescues classical logic from vagueness.'),
  Word('philosophy', 'supervaluation', 'n.', 'A technique handling vagueness by considering all admissible sharpenings', 'Supervaluation keeps borderline cases neither true nor false.'),
  Word('philosophy', 'liar-paradox', 'n.', 'A self-referential sentence that resists consistent truth-value assignment', 'The liar paradox motivates hierarchical theories of truth.'),
  Word('philosophy', 'russells-paradox', 'n.', 'A paradox about the set of all sets that do not contain themselves', 'Russell\'s paradox shook the foundations of early set theory.'),
  Word('philosophy', 'type-theory', 'n.', 'Russell\'s stratification of objects, sets, and higher levels', 'Type theory was invented to block self-referential paradoxes.'),
  Word('philosophy', 'logicism', 'n.', 'A program to reduce mathematics to logic alone', 'Logicism inspired Frege, Russell, and a century of fallout.'),
  Word('philosophy', 'formalism-math', 'n.', 'A view of mathematics as manipulation of symbols by rules', 'Hilbert\'s formalism sought consistency proofs for all of mathematics.'),
  Word('philosophy', 'platonism-math', 'n.', 'A view that mathematical objects exist abstractly and mind-independently', 'Mathematical platonism explains agreement but puzzles over access.'),
  Word('philosophy', 'incompleteness', 'n.', 'Gödel\'s result that consistent formal systems have unprovable truths', 'The incompleteness theorems ended the Hilbert program as originally conceived.'),
  Word('philosophy', 'truthmaker', 'n.', 'An entity in virtue of which a true proposition is true', 'Truthmaker theory ties truths to specific worldly grounds.'),
  Word('philosophy', 'grounding', 'n.', 'A metaphysical relation of being more fundamental than', 'Grounding is the new fashionable cousin of supervenience.'),
  Word('philosophy', 'fundamentality', 'n.', 'The status of being at the most basic level of reality', 'Discussions of fundamentality are as much physics as philosophy.'),
  Word('philosophy', 'ontological-pluralism', 'n.', 'A view that there are several distinct ways of being', 'Ontological pluralism distinguishes existence for numbers and for chairs.'),
  Word('philosophy', 'modal-collapse', 'n.', 'A theological worry that strong views imply all truths are necessary', 'Modal collapse threatens accounts of God as pure act.'),
  Word('philosophy', 'modal-logic', 'n.', 'A logic for reasoning about necessity and possibility', 'Modal logic systematizes claims about could and must.'),
  Word('philosophy', 'tense-logic', 'n.', 'A logic for reasoning about temporal operators like was and will be', 'Tense logic was pioneered by Prior to handle time talk.'),
  Word('philosophy', 'deontic-logic', 'n.', 'A logic for reasoning about obligation, permission, and prohibition', 'Deontic logic formalizes how oughts interact.'),
  Word('philosophy', 'epistemic-logic', 'n.', 'A logic for reasoning about knowledge and belief', 'Epistemic logic models multi-agent reasoning in games and security.'),
  Word('philosophy', 'fuzzy-logic', 'n.', 'A logic allowing truth values between true and false', 'Fuzzy logic was introduced to handle continuous gradations.'),
  Word('philosophy', 'paraconsistent-logic', 'n.', 'A logic that tolerates contradictions without collapse', 'Paraconsistent logic is useful in inconsistent databases.'),
  Word('philosophy', 'dialetheism', 'n.', 'A view that some contradictions can actually be true', 'Dialetheism accepts true contradictions in cases like the liar.'),
  Word('philosophy', 'square-of-opposition', 'n.', 'A diagram showing logical relations among categorical statements', 'The square of opposition organizes the four basic A, E, I, O forms.'),
  Word('philosophy', 'modus-ponens', 'phr.', 'A rule inferring the consequent from a conditional and its antecedent', 'Modus ponens is logic\'s most familiar move.'),
  Word('philosophy', 'modus-tollens', 'phr.', 'A rule denying the antecedent given a conditional and a denied consequent', 'Modus tollens is the engine of falsification.'),
  Word('philosophy', 'reductio', 'n.', 'A reductio ad absurdum argument deriving a contradiction to refute an assumption', 'A clever reductio can demolish a position in a single move.'),
  Word('philosophy', 'ad-hominem', 'phr.', 'A fallacy attacking the person rather than the argument', 'An ad hominem may sting, but it does not refute.'),
  Word('philosophy', 'straw-man', 'n.', 'A fallacy of misrepresenting an opponent\'s position to attack it', 'A straw man is easier to demolish than the real argument.'),
  Word('philosophy', 'red-herring', 'n.', 'A diversion that distracts from the issue at hand', 'A red herring detours debate without engaging the point.'),
  Word('philosophy', 'begging-the-question', 'phr.', 'A fallacy of assuming what one is trying to prove', 'Begging the question hides the conclusion among the premises.'),
  Word('philosophy', 'equivocation', 'n.', 'A fallacy of shifting a word\'s meaning between premises', 'Equivocation thrives on terms like natural and free.'),
  Word('philosophy', 'amphiboly', 'n.', 'An ambiguity arising from grammatical structure', 'Amphiboly is a perennial source of bad headlines.'),
  Word('philosophy', 'composition-fallacy', 'n.', 'Inferring that what holds of parts must hold of the whole', 'A composition fallacy assumes the team is great because each player is.'),
  Word('philosophy', 'division-fallacy', 'n.', 'Inferring that what holds of the whole must hold of each part', 'A division fallacy concludes each soldier is brave because the army is.'),
  Word('philosophy', 'genetic-fallacy', 'n.', 'Judging a claim by its origin rather than its merits', 'A genetic fallacy dismisses an idea because of where it came from.'),
  Word('philosophy', 'ad-populum', 'phr.', 'A fallacy appealing to popularity as evidence of truth', 'Ad populum confuses the comfort of agreement with proof.'),
  Word('philosophy', 'slippery-slope', 'n.', 'An argument predicting a cascade of bad outcomes without good warrant', 'A slippery slope needs evidence, not just imagination.'),
  Word('philosophy', 'false-dilemma', 'n.', 'A fallacy presenting only two options when more exist', 'Most binary framings deserve a false dilemma alarm.'),
  Word('philosophy', 'principle-of-charity', 'n.', 'A norm of interpreting others\' arguments in their strongest form', 'The principle of charity makes conversation worth having.'),
  Word('philosophy', 'steelman', 'v.', 'To restate an opposing position in its strongest form before responding', 'It is good practice to steelman before you criticize.'),
  Word('philosophy', 'zenos-paradoxes', 'n.', 'Ancient puzzles challenging the coherence of motion and plurality', 'Zeno\'s paradoxes still surprise calculus students.'),
  Word('philosophy', 'achilles-and-the-tortoise', 'n.', 'A zeno puzzle about a runner unable to overtake a slow rival', 'Achilles and the tortoise stages infinity as a daily problem.'),
  Word('philosophy', 'newcombs-problem', 'n.', 'A decision puzzle pitting expected utility against dominance', 'Newcomb\'s problem still splits decision theorists.'),
  Word('philosophy', 'prisoners-dilemma', 'n.', 'A game where mutual defection beats joint cooperation despite worse payoffs', 'The prisoner\'s dilemma haunts collective action problems.'),
  Word('philosophy', 'tragedy-of-the-commons', 'n.', 'A scenario where shared resources are overused by self-interested users', 'The tragedy of the commons motivates institutions of common management.'),
  Word('philosophy', 'veil-of-ignorance', 'n.', 'Rawls\'s device of impartial choice behind a curtain of self-ignorance', 'Behind the veil of ignorance, only fair principles survive.'),
  Word('philosophy', 'experience-machine', 'n.', 'Nozick\'s thought experiment about plugging into pleasant illusions', 'The experience machine probes whether pleasure exhausts the good life.'),
  Word('philosophy', 'demandingness', 'n.', 'An objection that an ethics asks too much of agents', 'Singer\'s charity arguments often draw the demandingness objection.'),
  Word('philosophy', 'separateness-of-persons', 'n.', 'A worry that aggregative ethics ignores individual lives', 'The separateness of persons cuts against utilitarian summing.'),
  Word('philosophy', 'effective-altruism', 'n.', 'A movement applying evidence to maximize the good one does', 'Effective altruism stresses cost-effective interventions over feel-good giving.'),
  Word('philosophy', 'longtermism', 'n.', 'An ethical stance taking the long-term future as a key moral priority', 'Longtermism widens the moral circle across centuries.'),
  Word('philosophy', 'population-ethics', 'n.', 'The study of how to evaluate outcomes that affect who exists', 'Population ethics generates puzzles like the repugnant conclusion.'),
  Word('philosophy', 'repugnant-conclusion', 'n.', 'Parfit\'s troubling outcome of preferring many barely-good lives to fewer great ones', 'The repugnant conclusion shadows total-view utilitarianism.'),
  Word('philosophy', 'fission-puzzle', 'n.', 'A thought experiment of one person seemingly becoming two', 'The fission puzzle pressures whatever theory of personal identity you pick.'),
  Word('philosophy', 'psychological-continuity', 'n.', 'A theory of personal identity through linked memories and intentions', 'Psychological continuity views are popular but not without trouble.'),
  Word('philosophy', 'biological-continuity', 'n.', 'A view of personal identity grounded in continued life of an organism', 'Animalists defend biological continuity over psychological accounts.'),
  Word('philosophy', 'animalism', 'n.', 'A theory that we are essentially human animals', 'Animalism asks why we should privilege the brain over the body.'),
  Word('philosophy', 'transhumanism', 'n.', 'A movement seeking to enhance humans beyond current limits', 'Transhumanism reframes old questions about human nature.'),
  Word('philosophy', 'environmental-ethics', 'n.', 'A field studying our moral relations to nature and non-human life', 'Environmental ethics expands the circle of moral patients.'),
  Word('philosophy', 'deep-ecology', 'n.', 'A view granting intrinsic value to all living beings and ecosystems', 'Deep ecology challenges anthropocentric assumptions.'),
  Word('philosophy', 'anthropocentrism', 'n.', 'A worldview that places humans at the moral or metaphysical center', 'Critics charge mainstream ethics with hidden anthropocentrism.'),
  Word('philosophy', 'biocentrism', 'n.', 'A view that all living things have moral standing', 'Biocentrism rejects ranking humans above other life.'),
  Word('philosophy', 'ecocentrism', 'n.', 'A view extending moral consideration to ecosystems as wholes', 'Ecocentrism cares about rivers and forests, not just creatures.'),
  Word('philosophy', 'land-ethic', 'n.', 'Leopold\'s ethic enlarging community to include soils, waters, and animals', 'A land ethic asks what is right for the biotic community.'),
  Word('philosophy', 'animal-rights', 'n.', 'A view that nonhuman animals have rights of their own', 'Animal rights theorists reject treating sentient beings as resources.'),
  Word('philosophy', 'speciesism', 'n.', 'A bias favoring one\'s own species in moral consideration', 'Singer popularized speciesism as a moral defect.'),
  Word('philosophy', 'moral-patient', 'n.', 'A being whose welfare counts morally even without agency', 'Infants and many animals are moral patients but not full agents.'),
  Word('philosophy', 'moral-agent', 'n.', 'A being capable of moral reasoning and responsibility', 'Only moral agents can be held morally accountable in the full sense.'),
  Word('philosophy', 'samkhya', 'n.', 'An ancient Indian dualist school of purusha and prakriti', 'Samkhya posits a witness consciousness and active material principle.'),
  Word('philosophy', 'advaita', 'n.', 'A nondualist Vedanta school identifying self and ultimate reality', 'Advaita Vedanta reads scripture as pointing to nonduality.'),
  Word('philosophy', 'dvaita', 'n.', 'A dualist Vedanta school distinguishing soul and supreme being', 'Dvaita defends a permanent difference between souls and God.'),
  Word('philosophy', 'vishishtadvaita', 'n.', 'A qualified nondualism in Vedanta', 'Vishishtadvaita unites souls with God while preserving their reality.'),
  Word('philosophy', 'ahimsa', 'n.', 'A principle of non-harm to living beings', 'Ahimsa is central to Jain, Buddhist, and Gandhian ethics.'),
  Word('philosophy', 'anatta', 'n.', 'The Buddhist doctrine of no permanent self', 'Anatta dissolves the soul into shifting aggregates.'),
  Word('philosophy', 'anicca', 'n.', 'The Buddhist doctrine of impermanence', 'Anicca reminds practitioners that all conditioned things pass.'),
  Word('philosophy', 'dukkha', 'n.', 'A Buddhist term for suffering or unsatisfactoriness', 'Recognizing dukkha is the first noble truth.'),
  Word('philosophy', 'pratitya-samutpada', 'n.', 'The Buddhist doctrine of dependent origination', 'Pratitya samutpada shows how phenomena arise in mutual conditioning.'),
  Word('philosophy', 'sunyata', 'n.', 'The Mahayana teaching of emptiness of inherent existence', 'Sunyata is not nothingness but the absence of self-standing essence.'),
  Word('philosophy', 'bodhisattva', 'n.', 'A being committed to awakening for the sake of all beings', 'The bodhisattva delays final liberation until others reach it.'),
  Word('philosophy', 'eightfold-path', 'n.', 'The Buddhist path of right view, intention, speech, and so on', 'The eightfold path treats ethics, meditation, and wisdom as inseparable.'),
  Word('philosophy', 'four-noble-truths', 'n.', 'The Buddha\'s diagnosis of suffering and its cure', 'The four noble truths form Buddhism\'s opening teaching.'),
  Word('philosophy', 'madhyamaka', 'n.', 'A Buddhist school analyzing reality through the middle way', 'Nagarjuna\'s Madhyamaka deploys emptiness against metaphysical extremes.'),
  Word('philosophy', 'yogacara', 'n.', 'A Buddhist school emphasizing mind-only analysis of experience', 'Yogacara explores the contents of awareness as the field of practice.'),
  Word('philosophy', 'zen', 'n.', 'A Mahayana school stressing direct insight through meditation', 'Zen prefers a finger pointing at the moon to a lecture about lunar essence.'),
  Word('philosophy', 'ren', 'n.', 'A Confucian virtue of humaneness or benevolence', 'Ren grows from family love outward to fellow citizens.'),
  Word('philosophy', 'li', 'n.', 'Confucian ritual propriety and well-ordered conduct', 'Li shapes the small gestures that hold a society together.'),
  Word('philosophy', 'junzi', 'n.', 'A Confucian gentleman or exemplary person', 'A junzi cultivates virtue without performing it for applause.'),
  Word('philosophy', 'mandate-of-heaven', 'n.', 'A Chinese doctrine that rulers govern by a moral mandate', 'A failing dynasty was said to lose the mandate of heaven.'),
];
