import 'words_data.dart';

const kPsychologyExtras2 = <Word>[
  Word('psychology', 'affect', 'n.', 'the outward expression of feeling or emotion', 'The patient showed a flat affect during the interview.'),
  Word('psychology', 'arousal', 'n.', 'a state of heightened physiological and psychological activation', 'High arousal can impair performance on complex tasks.'),
  Word('psychology', 'valence', 'n.', 'the intrinsic attractiveness or aversiveness of a stimulus', 'Words with negative valence are remembered more vividly.'),
  Word('psychology', 'salience', 'n.', 'the quality of standing out relative to surroundings', 'The salience of the red sign drew everyone\'s attention.'),
  Word('psychology', 'encoding', 'n.', 'the process of converting information into a memory trace', 'Deep encoding leads to stronger long-term retention.'),
  Word('psychology', 'retrieval', 'n.', 'the act of recovering stored information from memory', 'Retrieval practice strengthens learning more than rereading.'),
  Word('psychology', 'consolidation', 'n.', 'the stabilizing of a memory trace after initial learning', 'Sleep aids the consolidation of newly learned material.'),
  Word('psychology', 'mnemonic', 'n.', 'a device or strategy that aids memory', 'She used a mnemonic to memorize the list of cranial nerves.'),
  Word('psychology', 'engram', 'n.', 'the physical trace of a memory in the brain', 'Scientists search for the engram that stores a specific fear.'),
  Word('psychology', 'forgetting', 'n.', 'the loss or inaccessibility of stored information', 'Forgetting is fastest in the hours right after learning.'),
  Word('psychology', 'interference', 'n.', 'the disruption of memory by other learned material', 'Proactive interference made the new password hard to recall.'),
  Word('psychology', 'amnesia', 'n.', 'the partial or total loss of memory', 'The accident left him with amnesia for the prior week.'),
  Word('psychology', 'cognizance', 'n.', 'awareness or conscious knowledge of something', 'She acted without full cognizance of the consequences.'),
  Word('psychology', 'introspection', 'n.', 'the examination of one\'s own thoughts and feelings', 'Early psychologists relied on introspection to study the mind.'),
  Word('psychology', 'intrusion', 'n.', 'an unwanted thought or image that enters awareness', 'A traumatic intrusion can derail an otherwise calm afternoon.'),
  Word('psychology', 'obsession', 'n.', 'a persistent, intrusive, and unwanted thought', 'His obsession with symmetry made dressing a long ordeal.'),
  Word('psychology', 'compulsion', 'n.', 'a repetitive behavior performed to reduce anxiety', 'The compulsion to check the lock returned every night.'),
  Word('psychology', 'phobia', 'n.', 'an intense, irrational fear of an object or situation', 'Her phobia of heights kept her off the observation deck.'),
  Word('psychology', 'panic', 'n.', 'a sudden overwhelming surge of fear or anxiety', 'A wave of panic hit him as the elevator doors closed.'),
  Word('psychology', 'anxiety', 'n.', 'apprehension and tension about anticipated threats', 'Test anxiety can undermine even a well-prepared student.'),
  Word('psychology', 'apathy', 'n.', 'a lack of interest, motivation, or emotion', 'Deep apathy made it hard for him to start any task.'),
  Word('psychology', 'dysphoria', 'n.', 'a state of unease or generalized dissatisfaction', 'A creeping dysphoria settled over her during the long winter.'),
  Word('psychology', 'euphoria', 'n.', 'an intense feeling of happiness or well-being', 'The runner described a brief euphoria after the finish line.'),
  Word('psychology', 'mania', 'n.', 'a state of abnormally elevated mood and energy', 'During mania he barely slept yet felt unstoppable.'),
  Word('psychology', 'melancholia', 'n.', 'a profound and persistent state of sadness', 'The poem captured a quiet melancholia about lost youth.'),
  Word('psychology', 'lability', 'n.', 'rapid and exaggerated shifts in emotional state', 'Emotional lability made his reactions hard to predict.'),
  Word('psychology', 'ambivalence', 'n.', 'the simultaneous holding of conflicting feelings', 'Her ambivalence about the move left the decision stalled.'),
  Word('psychology', 'frustration', 'n.', 'distress arising from blocked goals or needs', 'Repeated failure bred frustration with the whole project.'),
  Word('psychology', 'aggression', 'n.', 'behavior intended to harm or dominate another', 'Frustration sometimes spills over into verbal aggression.'),
  Word('psychology', 'hostility', 'n.', 'a disposition of antagonism and ill will', 'Underlying hostility colored every reply she gave.'),
  Word('psychology', 'impulsivity', 'n.', 'the tendency to act without forethought', 'His impulsivity led to a string of regretted purchases.'),
  Word('psychology', 'inhibition', 'n.', 'the restraint of an impulse, behavior, or response', 'Response inhibition is measured by the stop-signal task.'),
  Word('psychology', 'disinhibition', 'n.', 'a reduced ability to suppress impulsive behavior', 'Alcohol-fueled disinhibition made him unusually talkative.'),
  Word('psychology', 'volition', 'n.', 'the capacity to make deliberate choices and act', 'Recovery required a renewed sense of volition.'),
  Word('psychology', 'agency', 'n.', 'the sense of being the author of one\'s actions', 'Therapy aimed to restore her feeling of personal agency.'),
  Word('psychology', 'autonomy', 'n.', 'the experience of acting from one\'s own values', 'Granting autonomy at work boosted employee engagement.'),
  Word('psychology', 'competence', 'n.', 'the felt sense of effectiveness and mastery', 'Mastering the skill gave him a real sense of competence.'),
  Word('psychology', 'relatedness', 'n.', 'the need to feel connected to and cared for by others', 'A sense of relatedness predicted classroom motivation.'),
  Word('psychology', 'motivation', 'n.', 'the internal force that energizes and directs behavior', 'Intrinsic motivation outlasts external rewards.'),
  Word('psychology', 'homeostasis', 'n.', 'the maintenance of a stable internal physiological state', 'Thirst is part of the body\'s homeostasis for fluid balance.'),
  Word('psychology', 'satiation', 'n.', 'the state of being fully satisfied beyond desire', 'Repeated exposure leads to satiation and reduced appeal.'),
  Word('psychology', 'craving', 'n.', 'an intense desire for a substance or experience', 'A sudden craving for nicotine struck him after meals.'),
  Word('psychology', 'addiction', 'n.', 'compulsive engagement with a reward despite harm', 'His gambling addiction strained the family finances.'),
  Word('psychology', 'tolerance', 'n.', 'the need for more of a stimulus to get the same effect', 'Growing tolerance led her to increase the dose.'),
  Word('psychology', 'withdrawal', 'n.', 'adverse symptoms following cessation of a substance', 'Caffeine withdrawal gave him a throbbing headache.'),
  Word('psychology', 'relapse', 'n.', 'a return to a problem behavior after improvement', 'A single stressful week triggered his relapse.'),
  Word('psychology', 'abstinence', 'n.', 'the deliberate avoidance of a substance or behavior', 'Six months of abstinence rebuilt his confidence.'),
  Word('psychology', 'reinforcer', 'n.', 'any event that strengthens the behavior it follows', 'Praise served as a powerful social reinforcer in class.'),
  Word('psychology', 'shaping', 'n.', 'reinforcing successive approximations toward a goal', 'The trainer used shaping to teach the dog to roll over.'),
  Word('psychology', 'generalization', 'n.', 'transfer of a learned response to similar stimuli', 'Fear generalization spread from one dog to all dogs.'),
  Word('psychology', 'discrimination', 'n.', 'responding differently to distinct stimuli', 'Stimulus discrimination lets the pigeon tell shapes apart.'),
  Word('psychology', 'acquisition', 'n.', 'the initial learning of a conditioned response', 'Acquisition was rapid once the cue reliably preceded food.'),
  Word('psychology', 'latent', 'adj.', 'present but not currently expressed or observable', 'Latent learning appears only when there is a reason to act.'),
  Word('psychology', 'conditioned', 'adj.', 'produced through learned association', 'The bell became a conditioned signal for dinner.'),
  Word('psychology', 'unconditioned', 'adj.', 'occurring naturally without prior learning', 'Salivation to food is an unconditioned response.'),
  Word('psychology', 'innate', 'adj.', 'present from birth rather than learned', 'Infants show an innate preference for face-like patterns.'),
  Word('psychology', 'instinct', 'n.', 'an inborn fixed pattern of behavior', 'The nest-building instinct emerges without instruction.'),
  Word('psychology', 'reflex', 'n.', 'an automatic, involuntary response to a stimulus', 'The knee-jerk reflex requires no conscious thought.'),
  Word('psychology', 'maturation', 'n.', 'biologically driven developmental change', 'Walking emerges through maturation more than training.'),
  Word('psychology', 'bonding', 'n.', 'the formation of a close emotional connection', 'Skin-to-skin contact promotes bonding after birth.'),
  Word('psychology', 'cognitive', 'adj.', 'relating to thinking, knowing, and mental processing', 'The therapy targets cognitive patterns behind the anxiety.'),
  Word('psychology', 'behavioral', 'adj.', 'relating to observable actions and responses', 'A behavioral plan rewarded the child for completed homework.'),
  Word('psychology', 'developmental', 'adj.', 'concerning growth and change across the lifespan', 'Developmental milestones vary widely among toddlers.'),
  Word('psychology', 'longitudinal', 'adj.', 'following the same subjects over an extended period', 'A longitudinal design tracked the children into adulthood.'),
  Word('psychology', 'normative', 'adj.', 'concerning typical or expected patterns', 'Normative data let clinicians compare a child to peers.'),
  Word('psychology', 'subjective', 'adj.', 'based on personal experience rather than outside fact', 'Pain is a deeply subjective experience.'),
  Word('psychology', 'objective', 'adj.', 'based on observable, measurable evidence', 'They sought an objective measure of attention span.'),
  Word('psychology', 'empirical', 'adj.', 'based on observation or experiment rather than theory', 'The claim lacked empirical support from controlled studies.'),
  Word('psychology', 'operationalize', 'v.', 'to define a concept in terms of measurable indicators', 'Researchers operationalize happiness with survey scores.'),
  Word('psychology', 'variable', 'n.', 'any factor that can change or be measured in a study', 'Sleep was the independent variable in the experiment.'),
  Word('psychology', 'correlation', 'n.', 'a statistical relationship between two variables', 'A correlation does not prove that one factor causes another.'),
  Word('psychology', 'causation', 'n.', 'a relationship in which one factor produces another', 'Only experiments can establish causation with confidence.'),
  Word('psychology', 'confounding', 'adj.', 'introducing an extraneous influence on results', 'A confounding variable can mimic a treatment effect.'),
  Word('psychology', 'placebo', 'n.', 'an inert treatment given to control for expectation', 'The placebo produced surprising symptom relief.'),
  Word('psychology', 'randomization', 'n.', 'assigning subjects to conditions by chance', 'Randomization balances unknown differences across groups.'),
  Word('psychology', 'replication', 'n.', 'repeating a study to verify its findings', 'Successful replication strengthens confidence in a result.'),
  Word('psychology', 'generalizability', 'n.', 'the extent findings apply beyond the sample', 'A narrow sample limits the generalizability of the results.'),
  Word('psychology', 'validity', 'n.', 'the degree to which a measure assesses what it claims', 'Face validity alone cannot confirm a test is sound.'),
  Word('psychology', 'baseline', 'n.', 'a measurement taken before an intervention', 'They recorded a baseline before introducing the new diet.'),
  Word('psychology', 'meta-analysis', 'n.', 'a statistical synthesis of many study results', 'A meta-analysis pooled findings from forty trials.'),
  Word('psychology', 'regression', 'n.', 'a return to an earlier, less mature pattern of behavior', 'Stress can trigger temporary regression in young children.'),
  Word('psychology', 'fixation', 'n.', 'a persistent focus arrested at a developmental stage', 'Freud linked nail-biting to an oral fixation.'),
  Word('psychology', 'catharsis', 'n.', 'the release of pent-up emotional tension', 'She found catharsis in writing about the loss.'),
  Word('psychology', 'abreaction', 'n.', 'emotional release through reliving a repressed memory', 'The session led to a powerful abreaction of old grief.'),
  Word('psychology', 'resistance', 'n.', 'a client\'s reluctance to confront difficult material', 'His resistance surfaced whenever childhood came up.'),
  Word('psychology', 'insight', 'n.', 'a sudden understanding of a problem or oneself', 'A flash of insight revealed why she avoided conflict.'),
  Word('psychology', 'empathy', 'n.', 'the capacity to share and understand another\'s feelings', 'Genuine empathy made the nurse a comfort to patients.'),
  Word('psychology', 'sympathy', 'n.', 'feelings of concern for another\'s misfortune', 'He offered sympathy without truly grasping her pain.'),
  Word('psychology', 'compassion', 'n.', 'concern for suffering joined with a wish to help', 'Compassion moved the volunteers to keep returning.'),
  Word('psychology', 'altruism', 'n.', 'selfless concern for the welfare of others', 'Pure altruism asks nothing in return for helping.'),
  Word('psychology', 'reciprocity', 'n.', 'the tendency to return favors and kindnesses', 'Norms of reciprocity sustain cooperation among strangers.'),
  Word('psychology', 'prosocial', 'adj.', 'intended to benefit other people', 'Toddlers show prosocial behavior surprisingly early.'),
  Word('psychology', 'antisocial', 'adj.', 'marked by disregard for others\' rights and norms', 'The diagnosis described a pattern of antisocial behavior.'),
  Word('psychology', 'affiliation', 'n.', 'the desire to associate with and belong to others', 'A strong need for affiliation drew her to group work.'),
  Word('psychology', 'cohesion', 'n.', 'the forces that bind members of a group together', 'High cohesion can improve morale but stifle dissent.'),
  Word('psychology', 'norm', 'n.', 'an unwritten rule governing group behavior', 'Violating a social norm draws subtle disapproval.'),
  Word('psychology', 'compliance', 'n.', 'changing behavior in response to a direct request', 'The foot-in-the-door tactic increases compliance.'),
  Word('psychology', 'persuasion', 'n.', 'the process of changing attitudes through communication', 'The ad relied on emotion rather than logical persuasion.'),
  Word('psychology', 'attitude', 'n.', 'an evaluative stance toward an object or idea', 'Her attitude toward exercise shifted after the class.'),
  Word('psychology', 'stereotype', 'n.', 'a generalized belief about members of a group', 'A stereotype can persist despite contradicting evidence.'),
  Word('psychology', 'prejudice', 'n.', 'a negative attitude toward a group and its members', 'Contact between groups can reduce mutual prejudice.'),
  Word('psychology', 'attribution', 'n.', 'an inference about the cause of a behavior', 'She made a dispositional attribution for his lateness.'),
  Word('psychology', 'dispositional', 'adj.', 'attributing behavior to internal traits', 'A dispositional explanation blamed his lazy character.'),
  Word('psychology', 'situational', 'adj.', 'attributing behavior to external circumstances', 'A situational view stressed the heavy traffic instead.'),
  Word('psychology', 'heuristic', 'n.', 'a mental shortcut used to make quick judgments', 'A simple heuristic let her decide without exhausting analysis.'),
  Word('psychology', 'bias', 'n.', 'a systematic deviation from rational judgment', 'Cognitive bias subtly skews everyday decisions.'),
  Word('psychology', 'fallacy', 'n.', 'a mistaken belief based on flawed reasoning', 'The sunk-cost fallacy kept him in a failing venture.'),
  Word('psychology', 'overconfidence', 'n.', 'excessive certainty in one\'s own judgments', 'Overconfidence led the forecasters astray.'),
  Word('psychology', 'metamemory', 'n.', 'awareness and knowledge of one\'s own memory', 'Poor metamemory makes students over-predict exam scores.'),
  Word('psychology', 'heuristics', 'n.', 'mental shortcuts that simplify complex judgments', 'Heuristics save effort but sometimes misfire.'),
  Word('psychology', 'satisficing', 'n.', 'choosing the first option that meets a threshold', 'Satisficing beats endless searching when time is short.'),
  Word('psychology', 'maximizing', 'n.', 'striving to make the best possible choice', 'Chronic maximizing left her dissatisfied with good options.'),
  Word('psychology', 'deliberation', 'n.', 'careful, effortful weighing of options', 'Slow deliberation reduced his impulsive errors.'),
  Word('psychology', 'judgment', 'n.', 'the process of forming an evaluation or conclusion', 'Fatigue impairs judgment under uncertainty.'),
  Word('psychology', 'appraisal', 'n.', 'the evaluation of an event\'s significance for oneself', 'Cognitive appraisal shapes whether a challenge feels stressful.'),
  Word('psychology', 'coping', 'n.', 'efforts to manage demands that tax one\'s resources', 'Active coping helped her face the diagnosis.'),
  Word('psychology', 'stressor', 'n.', 'an event or condition that produces stress', 'A looming deadline was the main stressor that week.'),
  Word('psychology', 'eustress', 'n.', 'a beneficial form of moderate, motivating stress', 'A touch of eustress can sharpen focus before a game.'),
  Word('psychology', 'distress', 'n.', 'harmful stress that overwhelms coping resources', 'Prolonged distress eroded his health and sleep.'),
  Word('psychology', 'adaptation', 'n.', 'adjustment to ongoing environmental demands', 'Sensory adaptation dims a smell after a few minutes.'),
  Word('psychology', 'plasticity', 'n.', 'the brain\'s capacity to reorganize and change', 'Plasticity allows recovery of function after injury.'),
  Word('psychology', 'lesion', 'n.', 'an area of damage in brain tissue', 'A frontal lesion altered the patient\'s personality.'),
  Word('psychology', 'cortex', 'n.', 'the outer layer of the brain governing higher functions', 'The visual cortex processes input from the eyes.'),
  Word('psychology', 'neuron', 'n.', 'a nerve cell that transmits information', 'Each neuron can connect to thousands of others.'),
  Word('psychology', 'synapse', 'n.', 'the junction where neurons communicate', 'Learning strengthens connections at the synapse.'),
  Word('psychology', 'neurotransmitter', 'n.', 'a chemical that carries signals between neurons', 'A neurotransmitter imbalance is linked to some depressions.'),
  Word('psychology', 'receptor', 'n.', 'a site that binds a chemical messenger', 'The drug blocks a receptor to reduce cravings.'),
  Word('psychology', 'myelin', 'n.', 'the fatty sheath that speeds neural transmission', 'Myelin damage slows signals in some disorders.'),
  Word('psychology', 'axon', 'n.', 'the long fiber that carries signals from a neuron', 'An action potential travels down the axon.'),
  Word('psychology', 'dendrite', 'n.', 'a branch that receives signals from other neurons', 'Each dendrite gathers input from neighboring cells.'),
  Word('psychology', 'arousability', 'n.', 'the readiness to become physiologically activated', 'High arousability may underlie his quick temper.'),
  Word('psychology', 'threshold', 'n.', 'the minimum stimulus level needed for detection', 'A faint tone below threshold goes unnoticed.'),
  Word('psychology', 'transduction', 'n.', 'converting physical energy into neural signals', 'Transduction turns sound waves into nerve impulses.'),
  Word('psychology', 'sensory', 'adj.', 'relating to the senses and incoming stimuli', 'Sensory overload left the toddler overwhelmed.'),
  Word('psychology', 'perceptual', 'adj.', 'relating to the interpretation of sensory input', 'A perceptual illusion fooled the entire audience.'),
  Word('psychology', 'figure-ground', 'n.', 'the organization of a scene into object and background', 'The figure-ground reversal made the vase look like faces.'),
  Word('psychology', 'closure', 'n.', 'the tendency to perceive incomplete figures as whole', 'Closure lets us read a word with missing letters.'),
  Word('psychology', 'illusion', 'n.', 'a misinterpretation of a real sensory stimulus', 'The Müller-Lyer illusion distorts perceived line length.'),
  Word('psychology', 'hallucination', 'n.', 'a perception without an external stimulus', 'An auditory hallucination led him to hear voices.'),
  Word('psychology', 'delusion', 'n.', 'a fixed false belief resistant to evidence', 'A delusion of persecution dominated his thinking.'),
  Word('psychology', 'paranoia', 'n.', 'unfounded suspicion that others mean one harm', 'His paranoia made him distrust even close friends.'),
  Word('psychology', 'psychosis', 'n.', 'a loss of contact with reality', 'Acute psychosis required immediate hospital care.'),
  Word('psychology', 'neurosis', 'n.', 'a non-psychotic disorder marked by chronic distress', 'In older texts, anxiety was classed as a neurosis.'),
  Word('psychology', 'syndrome', 'n.', 'a cluster of symptoms that occur together', 'The syndrome included fatigue, sadness, and poor sleep.'),
  Word('psychology', 'comorbidity', 'n.', 'the co-occurrence of two or more disorders', 'Anxiety and depression show high comorbidity.'),
  Word('psychology', 'prognosis', 'n.', 'the likely course and outcome of a condition', 'Early treatment improves the prognosis considerably.'),
  Word('psychology', 'etiology', 'n.', 'the set of causes of a disorder', 'The etiology of the illness remains poorly understood.'),
  Word('psychology', 'prevalence', 'n.', 'the proportion of a population with a condition', 'The prevalence of insomnia rises with age.'),
  Word('psychology', 'remission', 'n.', 'a period of reduced or absent symptoms', 'She has been in remission for over a year.'),
  Word('psychology', 'relabeling', 'n.', 'reframing a symptom as a manageable, separate event', 'Relabeling the urge weakened its grip on him.'),
  Word('psychology', 'desensitization', 'n.', 'a reduction in emotional response through exposure', 'Gradual desensitization eased her fear of spiders.'),
  Word('psychology', 'modeling', 'n.', 'learning by observing and imitating others', 'Children learn manners largely through modeling.'),
  Word('psychology', 'imitation', 'n.', 'copying the observed behavior of another', 'Infant imitation of facial expressions appears early.'),
  Word('psychology', 'vicarious', 'adj.', 'experienced indirectly through another person', 'Vicarious reinforcement shaped the bystander\'s choices.'),
  Word('psychology', 'self-regulation', 'n.', 'the control of one\'s own emotions and behavior', 'Strong self-regulation predicted academic success.'),
  Word('psychology', 'self-monitoring', 'n.', 'attending to and tracking one\'s own behavior', 'Self-monitoring of meals supported her health goals.'),
  Word('psychology', 'self-talk', 'n.', 'the internal dialogue one holds with oneself', 'Negative self-talk fueled his stage fright.'),
  Word('psychology', 'rumor', 'n.', 'unverified information spread among people', 'Anxiety accelerates the spread of a frightening rumor.'),
  Word('psychology', 'contagion', 'n.', 'the spread of emotions or behaviors through a group', 'Emotional contagion swept laughter across the room.'),
  Word('psychology', 'suggestibility', 'n.', 'the tendency to accept and act on others\' input', 'High suggestibility can distort eyewitness memory.'),
  Word('psychology', 'hypnosis', 'n.', 'a focused, relaxed state of heightened suggestibility', 'Hypnosis was used to help manage chronic pain.'),
  Word('psychology', 'trance', 'n.', 'an altered state of narrowed, absorbed awareness', 'The drummer slipped into a near-trance while playing.'),
  Word('psychology', 'consciousness', 'n.', 'awareness of oneself and the surrounding world', 'Anesthesia temporarily suspends consciousness.'),
  Word('psychology', 'unconscious', 'n.', 'mental processes outside of awareness', 'Freud believed the unconscious drives much behavior.'),
  Word('psychology', 'subconscious', 'adj.', 'just below the level of conscious awareness', 'A subconscious cue may guide a snap decision.'),
  Word('psychology', 'preconscious', 'adj.', 'not currently in awareness but readily retrievable', 'Your address sits in preconscious memory until needed.'),
  Word('psychology', 'lucid', 'adj.', 'clear-minded or aware while dreaming', 'In a lucid dream she knew she was asleep.'),
  Word('psychology', 'sleepwalking', 'n.', 'performing actions while remaining asleep', 'Childhood sleepwalking usually fades with age.'),
  Word('psychology', 'insomnia', 'n.', 'persistent difficulty falling or staying asleep', 'Chronic insomnia left her exhausted by midday.'),
  Word('psychology', 'narcolepsy', 'n.', 'a disorder of sudden, uncontrollable sleep attacks', 'Narcolepsy caused him to nod off mid-conversation.'),
  Word('psychology', 'fatigue', 'n.', 'extreme tiredness reducing mental and physical capacity', 'Decision fatigue degraded the judge\'s rulings.'),
  Word('psychology', 'vigilance', 'n.', 'sustained attention for detecting rare signals', 'Vigilance drops sharply after long monotonous shifts.'),
  Word('psychology', 'concentration', 'n.', 'the focusing of mental effort on one task', 'Open offices can shatter a worker\'s concentration.'),
  Word('psychology', 'distractibility', 'n.', 'the ease with which attention is diverted', 'High distractibility marks attention disorders.'),
  Word('psychology', 'perseveration', 'n.', 'repeating a response after it is no longer useful', 'Perseveration on the old rule slowed his sorting.'),
  Word('psychology', 'rigidity', 'n.', 'inflexibility in thought or behavior', 'Cognitive rigidity made adapting to change difficult.'),
  Word('psychology', 'flexibility', 'n.', 'the capacity to shift thoughts or strategies', 'Cognitive flexibility lets us switch tasks smoothly.'),
  Word('psychology', 'creativity', 'n.', 'the generation of novel and useful ideas', 'Constraints can paradoxically boost creativity.'),
  Word('psychology', 'divergent', 'adj.', 'generating many varied possible solutions', 'Divergent thinking favors brainstorming over a single answer.'),
  Word('psychology', 'convergent', 'adj.', 'narrowing many ideas toward one correct answer', 'Convergent thinking suits problems with a clear solution.'),
  Word('psychology', 'incubation', 'n.', 'unconscious problem solving during a break from a task', 'The solution arrived after a period of incubation.'),
  Word('psychology', 'functional', 'adj.', 'serving a purpose or operating effectively', 'Functional fixedness blocked him from improvising a tool.'),
  Word('psychology', 'mindset', 'n.', 'an established set of beliefs shaping responses', 'A learning mindset turned setbacks into feedback.'),
  Word('psychology', 'trait', 'n.', 'a stable characteristic that influences behavior', 'Conscientiousness is a trait that predicts job success.'),
  Word('psychology', 'disposition', 'n.', 'a person\'s habitual inclination or mood', 'His cheerful disposition lifted the whole office.'),
  Word('psychology', 'self-image', 'n.', 'the mental picture one holds of oneself', 'Therapy helped repair his battered self-image.'),
  Word('psychology', 'self-worth', 'n.', 'the value a person places on themselves', 'She tied her self-worth too tightly to grades.'),
  Word('psychology', 'self-disclosure', 'n.', 'revealing personal information to another', 'Gradual self-disclosure deepened their friendship.'),
  Word('psychology', 'codependency', 'n.', 'excessive reliance on a relationship for self-worth', 'Their codependency left both partners feeling trapped.'),
  Word('psychology', 'manipulation', 'n.', 'influencing others through indirect or deceptive means', 'Subtle manipulation framed his demand as her idea.'),
  Word('psychology', 'coercion', 'n.', 'pressuring someone through force or threat', 'Coercion produced compliance but deep resentment.'),
  Word('psychology', 'assertiveness', 'n.', 'expressing needs directly while respecting others', 'Assertiveness training helped her say no calmly.'),
  Word('psychology', 'passivity', 'n.', 'a tendency to yield rather than take initiative', 'His passivity let others make every choice for him.'),
  Word('psychology', 'submissiveness', 'n.', 'a readiness to comply with others\' wishes', 'Lifelong submissiveness made her avoid all conflict.'),
  Word('psychology', 'dominance', 'n.', 'the tendency to control or lead others', 'He asserted dominance the moment the meeting began.'),
  Word('psychology', 'temperance', 'n.', 'moderation and self-restraint as a strength', 'Temperance helped him resist the impulse to overspend.'),
  Word('psychology', 'perseverance', 'n.', 'sustained effort despite difficulty or delay', 'Her perseverance carried the project past every setback.'),
  Word('psychology', 'pessimism', 'n.', 'a tendency to expect unfavorable outcomes', 'Chronic pessimism colored every plan he made.'),
  Word('psychology', 'hopelessness', 'n.', 'the belief that improvement is impossible', 'Deep hopelessness is a warning sign for depression.'),
  Word('psychology', 'helplessness', 'n.', 'the felt inability to influence one\'s situation', 'Repeated failure bred a sense of helplessness.'),
  Word('psychology', 'mastery', 'n.', 'a sense of competence gained through achievement', 'Each solved problem added to her sense of mastery.'),
  Word('psychology', 'efficacy', 'n.', 'the belief in one\'s ability to succeed at a task', 'High efficacy encouraged him to tackle harder goals.'),
  Word('psychology', 'expectancy', 'n.', 'an anticipation that shapes behavior and outcome', 'Positive expectancy can improve actual performance.'),
  Word('psychology', 'aspiration', 'n.', 'a strong desire to achieve something high', 'Her aspiration to lead drove years of preparation.'),
  Word('psychology', 'ambition', 'n.', 'a strong desire for achievement or success', 'Healthy ambition pushed him without consuming him.'),
  Word('psychology', 'engagement', 'n.', 'absorbed and energetic involvement in activity', 'Student engagement rose with hands-on lessons.'),
  Word('psychology', 'absorption', 'n.', 'deep, total involvement in an experience', 'Absorption in the novel made hours vanish.'),
  Word('psychology', 'contentment', 'n.', 'a calm sense of acceptance and ease', 'A quiet contentment settled over the evening.'),
  Word('psychology', 'serenity', 'n.', 'a state of calm and untroubled peace', 'Meditation cultivated a lasting serenity.'),
  Word('psychology', 'equanimity', 'n.', 'mental calmness and composure under stress', 'He faced the bad news with surprising equanimity.'),
  Word('psychology', 'resignation', 'n.', 'passive acceptance of an unwanted situation', 'A weary resignation replaced her earlier protest.'),
  Word('psychology', 'bereavement', 'n.', 'the period of mourning after a loss', 'Bereavement leave gave him time to grieve.'),
  Word('psychology', 'mourning', 'n.', 'the outward expression and process of grieving', 'Cultural rituals structure the work of mourning.'),
  Word('psychology', 'regret', 'n.', 'distress over a past choice or missed chance', 'Regret over the unsent letter lingered for years.'),
  Word('psychology', 'remorse', 'n.', 'deep guilt and sorrow for a wrong committed', 'Genuine remorse softened the victim\'s anger.'),
  Word('psychology', 'embarrassment', 'n.', 'discomfort from a perceived social misstep', 'Embarrassment flushed her cheeks after the slip.'),
  Word('psychology', 'humiliation', 'n.', 'a painful loss of dignity before others', 'The public humiliation haunted him for weeks.'),
  Word('psychology', 'hubris', 'n.', 'excessive pride that invites a downfall', 'His hubris blinded him to obvious warnings.'),
  Word('psychology', 'vulnerability', 'n.', 'openness to emotional risk or harm', 'Sharing her fear took real vulnerability.'),
  Word('psychology', 'reactance', 'n.', 'resistance triggered by a threat to one\'s freedom', 'A blunt ban often sparks reactance instead of obedience.'),
  Word('psychology', 'inoculation', 'n.', 'building resistance to persuasion by mild exposure', 'Attitude inoculation prepared voters for misleading ads.'),
  Word('psychology', 'sublimate', 'v.', 'to redirect an impulse into a constructive outlet', 'He learned to sublimate his anger into hard training.'),
  Word('psychology', 'internalize', 'v.', 'to absorb beliefs or standards as one\'s own', 'Children internalize the values modeled at home.'),
  Word('psychology', 'externalize', 'v.', 'to attribute inner conflict to outside causes', 'He tended to externalize blame for every failure.'),
  Word('psychology', 'pathologize', 'v.', 'to treat a normal variation as a disorder', 'Critics warn against the urge to pathologize shyness.'),
  Word('psychology', 'normalize', 'v.', 'to frame an experience as common and acceptable', 'The therapist worked to normalize his grief.'),
  Word('psychology', 'destigmatize', 'v.', 'to remove shame attached to a condition', 'Campaigns aim to destigmatize seeking therapy.'),
  Word('psychology', 'ruminate', 'v.', 'to dwell repeatedly on distressing thoughts', 'She tended to ruminate over every awkward exchange.'),
  Word('psychology', 'catastrophize', 'v.', 'to assume the worst possible outcome', 'He began to catastrophize at the first sign of trouble.'),
  Word('psychology', 'decompensate', 'v.', 'to lose the ability to cope under stress', 'Without support he began to decompensate quickly.'),
  Word('psychology', 'titrate', 'v.', 'to adjust exposure or dosage in small steps', 'They chose to titrate the exposure to keep her calm.'),
  Word('psychology', 'attune', 'v.', 'to become responsive to another\'s emotional state', 'Good parents attune to a baby\'s subtle cues.'),
  Word('psychology', 'disengage', 'v.', 'to withdraw attention or involvement', 'Healthy people can disengage from unsolvable problems.'),
];
