import 'words_data.dart';

const kScienceExtras2 = <Word>[
  Word('science', 'abscission', 'n.', 'the natural shedding of leaves, fruit, or flowers from a plant', 'Cooler nights trigger the abscission of leaves in autumn.'),
  Word('science', 'acclimatization', 'n.', 'the process by which an organism adjusts to changes in its environment', 'Climbers spend days in acclimatization before attempting the summit.'),
  Word('science', 'acidosis', 'n.', 'an abnormal increase in the acidity of blood and tissues', 'Untreated diabetes can lead to dangerous metabolic acidosis.'),
  Word('science', 'acoustics', 'n.', 'the science of sound and how it travels through different media', 'The hall was redesigned with better acoustics for the orchestra.'),
  Word('science', 'actinide', 'n.', 'any of the radioactive metallic elements from actinium to lawrencium', 'Uranium is the most familiar actinide used in nuclear fuel.'),
  Word('science', 'adsorption', 'n.', 'the adhesion of molecules to the surface of a solid or liquid', 'Activated charcoal removes toxins through adsorption.'),
  Word('science', 'aeronautics', 'n.', 'the science and practice of flight through the atmosphere', 'Aeronautics advanced rapidly during the early jet age.'),
  Word('science', 'aerosol', 'n.', 'a suspension of fine solid or liquid particles in a gas', 'Volcanic aerosol can cool the planet for several years.'),
  Word('science', 'agar', 'n.', 'a gelatinous substance from seaweed used to culture microbes', 'Bacteria grew in tidy colonies across the agar plate.'),
  Word('science', 'agglomeration', 'n.', 'the clustering together of small particles into a larger mass', 'Dust agglomeration is the first step toward forming planets.'),
  Word('science', 'allopatric', 'adj.', 'describing populations separated by a geographic barrier', 'Allopatric speciation occurred after the river split the herd.'),
  Word('science', 'allotropy', 'n.', 'the existence of an element in two or more distinct physical forms', 'Carbon shows allotropy as diamond, graphite, and graphene.'),
  Word('science', 'amphibian', 'n.', 'a cold-blooded vertebrate that lives both in water and on land', 'The amphibian laid its eggs in the shallow pond.'),
  Word('science', 'anaerobic', 'adj.', 'occurring or living without the presence of free oxygen', 'Anaerobic bacteria thrive deep in the ocean sediment.'),
  Word('science', 'analgesic', 'n.', 'a drug that relieves pain without causing loss of consciousness', 'The doctor prescribed a mild analgesic for the headache.'),
  Word('science', 'anatomy', 'n.', 'the study of the structure of organisms and their parts', 'Medical students dissect cadavers to learn human anatomy.'),
  Word('science', 'antigen', 'n.', 'a substance that triggers an immune response in the body', 'The vaccine introduces a harmless antigen to train the immune system.'),
  Word('science', 'antioxidant', 'n.', 'a compound that inhibits the oxidation of other molecules', 'Berries are rich in antioxidant compounds.'),
  Word('science', 'aquifer', 'n.', 'an underground layer of rock that holds and transmits groundwater', 'The town drew its drinking water from a deep aquifer.'),
  Word('science', 'arboreal', 'adj.', 'living in or among trees', 'Sloths are arboreal mammals that rarely descend to the ground.'),
  Word('science', 'asexual', 'adj.', 'reproducing without the fusion of gametes from two parents', 'Many bacteria multiply by asexual division.'),
  Word('science', 'asthenosphere', 'n.', 'the soft layer of the mantle on which tectonic plates move', 'The plates glide slowly over the ductile asthenosphere.'),
  Word('science', 'astrobiology', 'n.', 'the study of the possibility of life beyond Earth', 'Astrobiology investigates whether microbes could survive on Mars.'),
  Word('science', 'astrolabe', 'n.', 'an old instrument for measuring the altitude of celestial bodies', 'Ancient sailors navigated using an astrolabe and the stars.'),
  Word('science', 'astrometry', 'n.', 'the precise measurement of the positions and motions of stars', 'Astrometry revealed the tiny wobble caused by an orbiting planet.'),
  Word('science', 'attenuation', 'n.', 'the gradual reduction of the strength of a signal or beam', 'Signal attenuation increases with the length of the cable.'),
  Word('science', 'auscultation', 'n.', 'listening to internal body sounds, usually with a stethoscope', 'Auscultation revealed a faint murmur in the patient\'s heart.'),
  Word('science', 'avirulent', 'adj.', 'not able to cause disease', 'The weakened strain was avirulent and safe for the vaccine.'),
  Word('science', 'bacteriophage', 'n.', 'a virus that infects and replicates within bacteria', 'A bacteriophage was used to kill the resistant infection.'),
  Word('science', 'basin', 'n.', 'a large depression in the land surface where sediment collects', 'Sediment piled up for millennia in the river basin.'),
  Word('science', 'bathymetry', 'n.', 'the measurement of the depth of bodies of water', 'Sonar bathymetry mapped the contours of the seafloor.'),
  Word('science', 'bedrock', 'n.', 'the solid rock lying beneath looser surface material', 'Engineers anchored the foundation deep into the bedrock.'),
  Word('science', 'benign', 'adj.', 'not harmful in effect, especially of a tumor that does not spread', 'The biopsy showed the growth was benign.'),
  Word('science', 'biofilm', 'n.', 'a thin layer of microorganisms adhering to a surface', 'A slimy biofilm coated the inside of the pipe.'),
  Word('science', 'biogeography', 'n.', 'the study of the distribution of species across geography', 'Biogeography explains why marsupials dominate Australia.'),
  Word('science', 'bioluminescence', 'n.', 'the production of light by living organisms', 'The bioluminescence of the plankton made the waves glow.'),
  Word('science', 'biomass', 'n.', 'the total mass of living organisms in a given area', 'Forests store enormous amounts of carbon as biomass.'),
  Word('science', 'bipedal', 'adj.', 'walking on two legs', 'Early humans became bipedal millions of years ago.'),
  Word('science', 'bolide', 'n.', 'an exceptionally bright meteor that often explodes in the air', 'A blazing bolide streaked across the night sky.'),
  Word('science', 'botany', 'n.', 'the scientific study of plants', 'Her interest in botany led her to catalog rare orchids.'),
  Word('science', 'bradycardia', 'n.', 'an abnormally slow heart rate', 'The athlete\'s resting bradycardia was a sign of fitness.'),
  Word('science', 'bronchus', 'n.', 'one of the two main airways branching from the windpipe', 'Inflammation narrowed the bronchus and made breathing hard.'),
  Word('science', 'caldera', 'n.', 'a large crater formed by the collapse of a volcano', 'A lake now fills the ancient volcanic caldera.'),
  Word('science', 'capillary', 'n.', 'the tiniest blood vessel connecting arteries and veins', 'Oxygen passes into tissue through the thin capillary walls.'),
  Word('science', 'carapace', 'n.', 'the hard upper shell of a turtle or crustacean', 'The crab withdrew its legs beneath its carapace.'),
  Word('science', 'carcinogen', 'n.', 'a substance capable of causing cancer', 'Tobacco smoke contains many known carcinogens.'),
  Word('science', 'cartilage', 'n.', 'firm flexible connective tissue found in joints and the nose', 'The runner damaged the cartilage in his knee.'),
  Word('science', 'cellulose', 'n.', 'a carbohydrate forming the main component of plant cell walls', 'Cotton fibers are almost pure cellulose.'),
  Word('science', 'chelation', 'n.', 'the binding of metal ions by a surrounding molecule', 'Chelation therapy removes heavy metals from the blood.'),
  Word('science', 'chitin', 'n.', 'a tough polysaccharide forming insect exoskeletons and fungal walls', 'The beetle\'s armor is made largely of chitin.'),
  Word('science', 'chromatography', 'n.', 'a technique for separating mixtures based on differential movement', 'Chromatography separated the dye into its component pigments.'),
  Word('science', 'chronobiology', 'n.', 'the study of biological rhythms and their timing', 'Chronobiology explains why jet lag disrupts sleep.'),
  Word('science', 'cilia', 'n.', 'tiny hair-like structures that beat to move fluid or cells', 'Cilia sweep mucus and debris out of the lungs.'),
  Word('science', 'clade', 'n.', 'a group of organisms sharing a single common ancestor', 'Birds and crocodiles belong to the same clade.'),
  Word('science', 'cleavage', 'n.', 'the tendency of a crystal to split along flat planes', 'Mica shows perfect cleavage into thin sheets.'),
  Word('science', 'climatology', 'n.', 'the scientific study of climate and long-term weather patterns', 'Climatology relies on decades of temperature records.'),
  Word('science', 'coagulation', 'n.', 'the process by which a liquid changes into a solid clot', 'Vitamin K is essential for blood coagulation.'),
  Word('science', 'cochlea', 'n.', 'the spiral cavity of the inner ear that converts sound to signals', 'Hair cells inside the cochlea translate vibrations into hearing.'),
  Word('science', 'cofactor', 'n.', 'a non-protein compound required for an enzyme to function', 'Magnesium acts as a cofactor for many enzymes.'),
  Word('science', 'cohesion', 'n.', 'the attraction between molecules of the same substance', 'Water\'s strong cohesion lets insects walk on its surface.'),
  Word('science', 'colloidal', 'adj.', 'consisting of fine particles dispersed throughout a medium', 'Milk is a colloidal mixture of fat droplets in water.'),
  Word('science', 'combustion', 'n.', 'a rapid chemical reaction with oxygen that releases heat and light', 'Combustion of fuel powers the engine.'),
  Word('science', 'commensal', 'adj.', 'benefiting from another organism without harming it', 'The commensal barnacle rides harmlessly on the whale.'),
  Word('science', 'conductivity', 'n.', 'the degree to which a material conducts electricity or heat', 'Copper has very high electrical conductivity.'),
  Word('science', 'congenital', 'adj.', 'present from birth', 'The baby was born with a congenital heart defect.'),
  Word('science', 'conifer', 'n.', 'a cone-bearing tree, usually evergreen with needle-like leaves', 'The mountainside was covered in dense conifer forest.'),
  Word('science', 'convection', 'n.', 'the transfer of heat by the movement of a fluid', 'Convection currents circulate warm water through the pot.'),
  Word('science', 'corona', 'n.', 'the outermost layer of the sun\'s atmosphere', 'The sun\'s corona becomes visible during a total eclipse.'),
  Word('science', 'corrosion', 'n.', 'the gradual destruction of metal by chemical reaction', 'Salt water accelerated the corrosion of the hull.'),
  Word('science', 'crepuscular', 'adj.', 'active during twilight at dawn and dusk', 'Deer are crepuscular, feeding at dawn and dusk.'),
  Word('science', 'cryosphere', 'n.', 'the frozen parts of Earth\'s surface, including ice and snow', 'The cryosphere is shrinking as the climate warms.'),
  Word('science', 'cytology', 'n.', 'the study of the structure and function of cells', 'Cytology revealed abnormal cells in the sample.'),
  Word('science', 'cytosol', 'n.', 'the fluid portion of the cytoplasm inside a cell', 'Many metabolic reactions occur in the cytosol.'),
  Word('science', 'deciduous', 'adj.', 'shedding leaves seasonally', 'The deciduous oaks dropped their leaves before winter.'),
  Word('science', 'deglaciation', 'n.', 'the retreat and melting of glaciers', 'Deglaciation carved deep valleys into the landscape.'),
  Word('science', 'deliquescent', 'adj.', 'tending to absorb moisture from the air and dissolve', 'The deliquescent salt turned to liquid in the humid room.'),
  Word('science', 'denaturation', 'n.', 'the loss of a protein\'s structure due to heat or chemicals', 'Cooking causes the denaturation of egg proteins.'),
  Word('science', 'dendrochronology', 'n.', 'dating events by analyzing patterns of tree rings', 'Dendrochronology pinpointed the year the timber was cut.'),
  Word('science', 'desiccation', 'n.', 'the process of extreme drying', 'Desiccation preserved the seeds for thousands of years.'),
  Word('science', 'detritus', 'n.', 'organic debris from decomposing organisms', 'Worms feed on the detritus on the forest floor.'),
  Word('science', 'diastole', 'n.', 'the phase when the heart relaxes and fills with blood', 'Blood pressure is lowest during diastole.'),
  Word('science', 'dimorphism', 'n.', 'the occurrence of two distinct forms within a species', 'Sexual dimorphism makes the male peacock far showier than the female.'),
  Word('science', 'diploid', 'adj.', 'having two complete sets of chromosomes', 'Most human body cells are diploid.'),
  Word('science', 'dissociation', 'n.', 'the splitting of a compound into smaller particles or ions', 'The dissociation of salt in water produces free ions.'),
  Word('science', 'diurnal', 'adj.', 'active during the daytime or occurring daily', 'Most birds are diurnal and rest at night.'),
  Word('science', 'dormancy', 'n.', 'a period of suspended growth or activity in an organism', 'Seeds can survive years of dormancy in dry soil.'),
  Word('science', 'ductility', 'n.', 'the ability of a material to be drawn into a wire', 'Gold\'s ductility lets it be stretched into fine threads.'),
  Word('science', 'echolocation', 'n.', 'locating objects by emitting sound and sensing its echoes', 'Bats hunt insects in the dark using echolocation.'),
  Word('science', 'ecotone', 'n.', 'a transitional zone between two ecological communities', 'The ecotone between forest and grassland hosts diverse wildlife.'),
  Word('science', 'efflorescence', 'n.', 'a powdery deposit left when a solution evaporates on a surface', 'White efflorescence appeared on the damp brick wall.'),
  Word('science', 'effusion', 'n.', 'the escape of a gas through a tiny opening', 'Lighter gases undergo effusion faster than heavier ones.'),
  Word('science', 'electrode', 'n.', 'a conductor through which electricity enters or leaves a substance', 'The battery\'s electrode slowly corroded with use.'),
  Word('science', 'electrophoresis', 'n.', 'separating molecules by moving them through a gel with an electric field', 'Electrophoresis sorted the DNA fragments by size.'),
  Word('science', 'embryology', 'n.', 'the study of the development of embryos', 'Embryology reveals how a single cell becomes a body.'),
  Word('science', 'emulsifier', 'n.', 'a substance that stabilizes a mixture of oil and water', 'Egg yolk acts as an emulsifier in mayonnaise.'),
  Word('science', 'endocrine', 'adj.', 'relating to glands that secrete hormones into the blood', 'The thyroid is part of the endocrine system.'),
  Word('science', 'endoskeleton', 'n.', 'an internal supporting skeleton', 'Vertebrates have an endoskeleton made of bone or cartilage.'),
  Word('science', 'endosymbiosis', 'n.', 'a relationship in which one organism lives inside another', 'Mitochondria likely arose through ancient endosymbiosis.'),
  Word('science', 'enzymatic', 'adj.', 'relating to or produced by enzymes', 'The enzymatic reaction sped up digestion dramatically.'),
  Word('science', 'epicenter', 'n.', 'the point on the surface directly above an earthquake\'s origin', 'The epicenter of the quake lay just offshore.'),
  Word('science', 'epidermis', 'n.', 'the outermost protective layer of skin', 'Sunlight damages cells in the epidermis.'),
  Word('science', 'erythrocyte', 'n.', 'a red blood cell that carries oxygen', 'Each erythrocyte is packed with hemoglobin.'),
  Word('science', 'estuary', 'n.', 'a coastal area where fresh river water meets the sea', 'The estuary teemed with fish and migrating birds.'),
  Word('science', 'eukaryote', 'n.', 'an organism whose cells contain a nucleus', 'Plants, animals, and fungi are all eukaryotes.'),
  Word('science', 'eutrophication', 'n.', 'excessive nutrient enrichment of water causing algal overgrowth', 'Fertilizer runoff drove eutrophication of the lake.'),
  Word('science', 'evapotranspiration', 'n.', 'the combined loss of water by evaporation and plant transpiration', 'Evapotranspiration returns much of the rainfall to the air.'),
  Word('science', 'excitation', 'n.', 'the raising of an atom or electron to a higher energy state', 'Light caused the excitation of electrons in the gas.'),
  Word('science', 'exoskeleton', 'n.', 'a rigid external covering that supports and protects the body', 'The crab molts its exoskeleton as it grows.'),
  Word('science', 'exothermy', 'n.', 'the release of heat during a chemical reaction', 'The exothermy of the reaction warmed the flask.'),
  Word('science', 'extant', 'adj.', 'still in existence and not extinct', 'The coelacanth is one of the few extant lobe-finned fish.'),
  Word('science', 'extracellular', 'adj.', 'located or occurring outside a cell', 'Nutrients diffuse through the extracellular fluid.'),
  Word('science', 'facultative', 'adj.', 'able to live under more than one set of conditions', 'Facultative bacteria survive with or without oxygen.'),
  Word('science', 'fauna', 'n.', 'the animals of a particular region or period', 'The island\'s fauna included many flightless birds.'),
  Word('science', 'fecundity', 'n.', 'the ability to produce abundant offspring', 'Rabbits are famous for their high fecundity.'),
  Word('science', 'filtrate', 'n.', 'the liquid that has passed through a filter', 'The clear filtrate was collected in a clean beaker.'),
  Word('science', 'flagellum', 'n.', 'a whip-like structure that propels a cell', 'The bacterium swims by rotating its flagellum.'),
  Word('science', 'flora', 'n.', 'the plants of a particular region or period', 'Alpine flora bloom briefly in the short summer.'),
  Word('science', 'fluvial', 'adj.', 'relating to or produced by a river', 'Fluvial deposits formed the fertile floodplain.'),
  Word('science', 'follicle', 'n.', 'a small cavity or sac, such as one from which hair grows', 'Each hair grows from its own follicle in the skin.'),
  Word('science', 'fontanelle', 'n.', 'a soft gap between the bones of an infant\'s skull', 'The baby\'s fontanelle had not yet closed.'),
  Word('science', 'foraminifera', 'n.', 'tiny marine organisms with shells that form ocean sediments', 'Fossil foraminifera help date ancient rock layers.'),
  Word('science', 'fractionation', 'n.', 'separating a mixture into components by their differing properties', 'Crude oil is split by fractionation in a refinery.'),
  Word('science', 'gamete', 'n.', 'a reproductive cell such as a sperm or egg', 'Each gamete carries half the parent\'s chromosomes.'),
  Word('science', 'ganglion', 'n.', 'a cluster of nerve cell bodies', 'The signal passed through a ganglion in the spinal cord.'),
  Word('science', 'gastropod', 'n.', 'a mollusk such as a snail or slug', 'The garden gastropod left a glistening trail.'),
  Word('science', 'genus', 'n.', 'a taxonomic rank above species and below family', 'The wolf and the dog belong to the same genus.'),
  Word('science', 'geochemistry', 'n.', 'the study of the chemical composition of the Earth', 'Geochemistry traced the origin of the volcanic rock.'),
  Word('science', 'geomorphology', 'n.', 'the study of landforms and the processes that shape them', 'Geomorphology explains how glaciers carved the fjords.'),
  Word('science', 'geophysics', 'n.', 'the physics of the Earth and its environment', 'Geophysics uses seismic waves to probe the planet\'s interior.'),
  Word('science', 'geothermal', 'adj.', 'relating to heat generated within the Earth', 'Iceland heats homes with geothermal energy.'),
  Word('science', 'glaciation', 'n.', 'the covering of land by glaciers or ice sheets', 'The last glaciation shaped much of the northern landscape.'),
  Word('science', 'glycogen', 'n.', 'a stored form of glucose found mainly in liver and muscle', 'The body taps its glycogen reserves during exercise.'),
  Word('science', 'gymnosperm', 'n.', 'a seed plant whose seeds are not enclosed in fruit', 'Pines and firs are gymnosperms that bear cones.'),
  Word('science', 'haploid', 'adj.', 'having a single set of chromosomes', 'Sperm and egg cells are haploid.'),
  Word('science', 'helix', 'n.', 'a spiral or coiled shape, as in the structure of DNA', 'The two strands twist around each other in a double helix.'),
  Word('science', 'hematology', 'n.', 'the study of blood and blood-forming tissues', 'Hematology tests measure the count of red cells.'),
  Word('science', 'hemoglobin', 'n.', 'the protein in red blood cells that carries oxygen', 'Hemoglobin gives blood its red color.'),
  Word('science', 'herbaceous', 'adj.', 'relating to plants with non-woody stems', 'The herbaceous border was full of soft green stems.'),
  Word('science', 'hibernation', 'n.', 'a dormant state of reduced activity during winter', 'The bear entered hibernation in its den.'),
  Word('science', 'histamine', 'n.', 'a compound released during allergic reactions', 'Pollen triggered a flood of histamine and sneezing.'),
  Word('science', 'homeothermic', 'adj.', 'maintaining a constant body temperature', 'Mammals are homeothermic regardless of the weather.'),
  Word('science', 'homologous', 'adj.', 'similar in structure due to shared ancestry', 'A whale\'s flipper and a human arm are homologous.'),
  Word('science', 'hydration', 'n.', 'the addition or combination of water with a substance', 'The hydration of cement makes it harden into concrete.'),
  Word('science', 'hydrodynamics', 'n.', 'the study of fluids in motion', 'Hydrodynamics governs how a ship moves through water.'),
  Word('science', 'hydrophobic', 'adj.', 'tending to repel or not mix with water', 'The hydrophobic coating made the fabric shed rain.'),
  Word('science', 'hydrothermal', 'adj.', 'relating to hot water beneath the Earth\'s surface', 'Strange creatures thrive near deep hydrothermal vents.'),
  Word('science', 'hyperbaric', 'adj.', 'relating to pressure greater than normal atmospheric pressure', 'Divers recover in a hyperbaric chamber.'),
  Word('science', 'hypertonic', 'adj.', 'having a higher solute concentration than another solution', 'Cells shrink when placed in a hypertonic solution.'),
  Word('science', 'hypothalamus', 'n.', 'a brain region that regulates temperature and hormones', 'The hypothalamus signals when the body is hungry.'),
  Word('science', 'hypoxia', 'n.', 'a deficiency of oxygen reaching the tissues', 'Climbers risk hypoxia at extreme altitudes.'),
  Word('science', 'immunology', 'n.', 'the study of the immune system', 'Immunology helped develop vaccines against many diseases.'),
  Word('science', 'inoculation', 'n.', 'the introduction of a microbe or vaccine into the body', 'Inoculation protected the village from the outbreak.'),
  Word('science', 'insolation', 'n.', 'the amount of solar radiation reaching a surface', 'Desert regions receive intense insolation year-round.'),
  Word('science', 'interstellar', 'adj.', 'occurring or located between the stars', 'The probe drifted into interstellar space.'),
  Word('science', 'invertebrate', 'n.', 'an animal lacking a backbone', 'Insects are the most numerous invertebrates on Earth.'),
  Word('science', 'isostasy', 'n.', 'the balance of the Earth\'s crust floating on the mantle', 'Isostasy explains why mountains have deep roots.'),
  Word('science', 'keratin', 'n.', 'a tough protein found in hair, nails, and feathers', 'A rhino\'s horn is made of densely packed keratin.'),
  Word('science', 'larva', 'n.', 'the immature feeding stage of an insect or amphibian', 'The butterfly larva devoured the leaf.'),
  Word('science', 'leukocyte', 'n.', 'a white blood cell that defends against infection', 'Leukocyte counts rise during an infection.'),
  Word('science', 'lichen', 'n.', 'a composite organism of fungus and alga living together', 'Gray lichen crept across the cold granite boulder.'),
  Word('science', 'lignin', 'n.', 'a rigid polymer that strengthens plant cell walls and wood', 'Lignin gives tree trunks their stiffness.'),
  Word('science', 'limnology', 'n.', 'the study of lakes, rivers, and other inland waters', 'Limnology examines how nutrients cycle through lakes.'),
  Word('science', 'lymph', 'n.', 'a clear fluid that bathes tissues and aids immunity', 'White cells travel through the body in lymph.'),
  Word('science', 'macrophage', 'n.', 'a large immune cell that engulfs pathogens and debris', 'A macrophage swallowed the invading bacterium.'),
  Word('science', 'malleability', 'n.', 'the ability of a metal to be hammered into thin sheets', 'Gold\'s malleability lets it be beaten into foil.'),
  Word('science', 'metallurgy', 'n.', 'the science of extracting and working with metals', 'Metallurgy improved the strength of the new alloy.'),
  Word('science', 'metamorphism', 'n.', 'the transformation of rock by heat and pressure', 'Metamorphism turned the limestone into marble.'),
  Word('science', 'meteorology', 'n.', 'the study of the atmosphere and weather', 'Meteorology lets forecasters predict tomorrow\'s storm.'),
  Word('science', 'microbe', 'n.', 'a microorganism, especially one causing disease or fermentation', 'A single drop of pond water teems with microbes.'),
  Word('science', 'microbiology', 'n.', 'the study of microscopic organisms', 'Microbiology revealed how the bacterium spreads.'),
  Word('science', 'migration', 'n.', 'the seasonal movement of animals from one region to another', 'The birds began their long autumn migration south.'),
  Word('science', 'mineralogy', 'n.', 'the study of minerals and their properties', 'Mineralogy identifies the crystals in a rock sample.'),
  Word('science', 'monomer', 'n.', 'a small molecule that can join with others to form a polymer', 'Glucose is the monomer that links to form starch.'),
  Word('science', 'morphology', 'n.', 'the study of the form and structure of organisms', 'The morphology of the beak revealed the bird\'s diet.'),
  Word('science', 'motile', 'adj.', 'capable of independent movement', 'Sperm cells are highly motile.'),
  Word('science', 'mycelium', 'n.', 'the thread-like vegetative body of a fungus', 'A vast mycelium spread unseen beneath the forest floor.'),
  Word('science', 'mycology', 'n.', 'the study of fungi', 'Mycology classifies thousands of mushroom species.'),
  Word('science', 'necrosis', 'n.', 'the death of cells or tissue', 'Lack of blood flow caused necrosis in the limb.'),
  Word('science', 'nephron', 'n.', 'the basic filtering unit of the kidney', 'Each kidney contains about a million nephrons.'),
  Word('science', 'neurogenesis', 'n.', 'the formation of new neurons in the brain', 'Exercise may promote neurogenesis in the hippocampus.'),
  Word('science', 'neuroscience', 'n.', 'the scientific study of the nervous system', 'Neuroscience seeks to explain how memory is stored.'),
  Word('science', 'nocturnal', 'adj.', 'active at night', 'Owls are nocturnal hunters with keen night vision.'),
  Word('science', 'nucleation', 'n.', 'the initial formation of a new phase, such as a crystal or bubble', 'A speck of dust provided a site for ice nucleation.'),
  Word('science', 'nucleotide', 'n.', 'a building block of DNA and RNA', 'Each rung of the DNA ladder is a pair of nucleotides.'),
  Word('science', 'olfactory', 'adj.', 'relating to the sense of smell', 'Dogs have an extraordinary olfactory ability.'),
  Word('science', 'organism', 'n.', 'an individual living thing', 'Even a single-celled organism can sense its surroundings.'),
  Word('science', 'osmoregulation', 'n.', 'the control of water and salt balance in an organism', 'Fish use osmoregulation to survive in salt water.'),
  Word('science', 'osteoporosis', 'n.', 'a condition of weakened, brittle bones', 'Calcium helps prevent osteoporosis in old age.'),
  Word('science', 'ozone', 'n.', 'a form of oxygen with three atoms that shields against UV light', 'The ozone layer protects life from harmful radiation.'),
  Word('science', 'paleontology', 'n.', 'the study of fossils and ancient life', 'Paleontology reconstructs creatures from their fossil bones.'),
  Word('science', 'parturition', 'n.', 'the act of giving birth', 'Parturition lasted several hours for the mare.'),
  Word('science', 'pasteurization', 'n.', 'heating a liquid to destroy harmful microbes', 'Pasteurization makes milk safe to drink.'),
  Word('science', 'pathogenesis', 'n.', 'the process by which a disease develops', 'Researchers traced the pathogenesis of the infection.'),
  Word('science', 'permafrost', 'n.', 'ground that remains frozen for two or more years', 'Thawing permafrost releases trapped methane.'),
  Word('science', 'petrology', 'n.', 'the study of the origin and structure of rocks', 'Petrology classifies rocks by how they formed.'),
  Word('science', 'phagocyte', 'n.', 'a cell that engulfs and digests foreign particles', 'A phagocyte surrounded and destroyed the debris.'),
  Word('science', 'phenology', 'n.', 'the study of the timing of recurring biological events', 'Phenology tracks when flowers bloom each spring.'),
  Word('science', 'photic', 'adj.', 'relating to light, especially the sunlit zone of water', 'Algae thrive in the warm photic zone near the surface.'),
  Word('science', 'photometry', 'n.', 'the measurement of the brightness of light', 'Photometry recorded the slow dimming of the variable star.'),
  Word('science', 'phylum', 'n.', 'a major taxonomic group ranking above class', 'Insects belong to the phylum of arthropods.'),
  Word('science', 'physiology', 'n.', 'the study of how living organisms and their parts function', 'Physiology explains how muscles contract.'),
  Word('science', 'plumage', 'n.', 'a bird\'s covering of feathers', 'The male\'s bright plumage attracted a mate.'),
  Word('science', 'pluripotent', 'adj.', 'able to develop into many different cell types', 'Pluripotent stem cells can become muscle or nerve.'),
  Word('science', 'precipitation', 'n.', 'water released from clouds as rain, snow, or hail', 'Heavy precipitation flooded the low-lying fields.'),
  Word('science', 'progesterone', 'n.', 'a hormone involved in pregnancy and the menstrual cycle', 'Progesterone prepares the uterus for a fertilized egg.'),
  Word('science', 'prokaryote', 'n.', 'a single-celled organism without a nucleus', 'Bacteria are prokaryotes lacking a true nucleus.'),
  Word('science', 'prophylaxis', 'n.', 'a measure taken to prevent disease', 'Travelers took malaria prophylaxis before the trip.'),
  Word('science', 'pseudopod', 'n.', 'a temporary extension of a cell used for movement or feeding', 'The amoeba reached out with a pseudopod.'),
  Word('science', 'pyroclastic', 'adj.', 'relating to fragmented rock and gas ejected by a volcano', 'A pyroclastic flow raced down the volcano\'s slope.'),
  Word('science', 'radioisotope', 'n.', 'a radioactive form of a chemical element', 'A radioisotope traced the path of the drug in the body.'),
  Word('science', 'radiometric', 'adj.', 'relating to the measurement of radiation for dating', 'Radiometric dating fixed the rock\'s age at two billion years.'),
  Word('science', 'recessive', 'adj.', 'describing a trait expressed only with two matching genes', 'Blue eyes result from a recessive allele.'),
  Word('science', 'recrystallization', 'n.', 'the purification of a solid by dissolving and reforming crystals', 'Recrystallization removed the impurities from the salt.'),
  Word('science', 'refractive', 'adj.', 'relating to the bending of light passing through a medium', 'Glass has a higher refractive index than water.'),
  Word('science', 'regeneration', 'n.', 'the regrowth of lost or damaged body parts', 'A starfish is capable of regeneration of a severed arm.'),
  Word('science', 'remission', 'n.', 'a period when disease symptoms lessen or disappear', 'The patient\'s cancer went into remission after treatment.'),
  Word('science', 'rhizome', 'n.', 'a horizontal underground plant stem that sends out roots', 'Ginger grows from a knobby rhizome.'),
  Word('science', 'sedimentation', 'n.', 'the settling of suspended particles out of a fluid', 'Sedimentation cleared the muddy water in the tank.'),
  Word('science', 'seismic', 'adj.', 'relating to earthquakes or vibrations of the Earth', 'Seismic waves rattled buildings across the city.'),
  Word('science', 'senescence', 'n.', 'the process of biological aging', 'Cellular senescence contributes to the aging of tissues.'),
  Word('science', 'sessile', 'adj.', 'fixed in one place and not free to move', 'Barnacles are sessile and cement themselves to rocks.'),
  Word('science', 'solubility', 'n.', 'the ability of a substance to dissolve in a solvent', 'Sugar has a high solubility in warm water.'),
  Word('science', 'solvation', 'n.', 'the interaction of solvent molecules with dissolved particles', 'Solvation surrounds each ion with water molecules.'),
  Word('science', 'spore', 'n.', 'a reproductive cell capable of developing without fertilization', 'The fern released thousands of tiny spores.'),
  Word('science', 'stalactite', 'n.', 'a mineral formation hanging from the roof of a cave', 'A long stalactite dripped from the cavern ceiling.'),
  Word('science', 'stoichiometry', 'n.', 'the calculation of quantities in chemical reactions', 'Stoichiometry tells us how much oxygen the reaction needs.'),
  Word('science', 'stomata', 'n.', 'tiny pores in a leaf that control gas exchange', 'The plant closes its stomata to conserve water.'),
  Word('science', 'subatomic', 'adj.', 'smaller than or occurring within an atom', 'Protons and electrons are subatomic particles.'),
  Word('science', 'supersonic', 'adj.', 'traveling faster than the speed of sound', 'The jet broke the sound barrier and went supersonic.'),
  Word('science', 'symbiotic', 'adj.', 'living together in a mutually dependent relationship', 'The clownfish and anemone have a symbiotic bond.'),
  Word('science', 'systolic', 'adj.', 'relating to the contraction phase of the heartbeat', 'Her systolic blood pressure was slightly elevated.'),
  Word('science', 'taxonomy', 'n.', 'the science of classifying living organisms', 'Taxonomy groups species into a branching hierarchy.'),
  Word('science', 'terrestrial', 'adj.', 'relating to or living on land or the Earth', 'Frogs begin life in water but become terrestrial adults.'),
  Word('science', 'thrombosis', 'n.', 'the formation of a blood clot inside a vessel', 'A clot caused a dangerous thrombosis in the leg.'),
  Word('science', 'topography', 'n.', 'the arrangement of the physical features of an area', 'The map showed the rugged topography of the mountains.'),
  Word('science', 'toxicology', 'n.', 'the study of poisons and their effects on living things', 'Toxicology determined the cause of the poisoning.'),
  Word('science', 'translucent', 'adj.', 'allowing light to pass through but diffusing it', 'The translucent glass softened the bright sunlight.'),
  Word('science', 'transpiration', 'n.', 'the loss of water vapor from plant leaves', 'Transpiration draws water upward from the roots.'),
  Word('science', 'tributary', 'n.', 'a stream or river that flows into a larger one', 'The creek is a tributary of the great river.'),
  Word('science', 'ungulate', 'n.', 'a hoofed mammal', 'Deer and horses are familiar ungulates.'),
  Word('science', 'vascular', 'adj.', 'relating to vessels that carry fluids in plants or animals', 'Vascular plants have tissues that conduct water.'),
  Word('science', 'vector', 'n.', 'an organism that transmits a disease from one host to another', 'The mosquito is a vector for malaria.'),
  Word('science', 'venom', 'n.', 'a toxic fluid injected by a bite or sting', 'The snake\'s venom paralyzes its prey.'),
  Word('science', 'vertebrate', 'n.', 'an animal possessing a backbone', 'Fish were the earliest vertebrates to evolve.'),
  Word('science', 'vestigial', 'adj.', 'remaining as a small reduced trace of a former structure', 'The whale\'s tiny hip bones are vestigial.'),
  Word('science', 'virulence', 'n.', 'the degree to which a pathogen can cause disease', 'The new strain showed alarming virulence.'),
  Word('science', 'virology', 'n.', 'the study of viruses', 'Virology raced to understand the emerging pathogen.'),
  Word('science', 'viviparous', 'adj.', 'giving birth to live young rather than laying eggs', 'Most mammals are viviparous.'),
  Word('science', 'xylem', 'n.', 'the plant tissue that conducts water from the roots upward', 'Water rises to the treetop through the xylem.'),
  Word('science', 'zooplankton', 'n.', 'tiny drifting animals in oceans and lakes', 'Whales feast on dense clouds of zooplankton.'),
];
