import 'words_data.dart';

const kSexologyExtras = <Word>[
  Word('sexology', 'libido', 'n.', 'A person\'s overall drive for sexual activity', 'Stress and poor sleep can quietly lower a healthy libido over time.'),
  Word('sexology', 'limerence', 'n.', 'The dizzy, obsessive state of new infatuation', 'In limerence, the smallest text from her felt like a major event.'),
  Word('sexology', 'eros', 'n.', 'Passionate, romantic, or sexual love', 'The Greeks set eros apart from the steadier love of friendship.'),
  Word('sexology', 'frisson', 'n.', 'A sudden thrill of excitement or attraction', 'A frisson passed between them when their hands touched over the menu.'),
  Word('sexology', 'sensuality', 'n.', 'Delight in the pleasures of the senses', 'The film treated the couple\'s sensuality with warmth rather than shock.'),
  Word('sexology', 'ardor', 'n.', 'Intense warmth of feeling or desire', 'His letters were full of an ardor he could never speak aloud.'),
  Word('sexology', 'refractory', 'adj.', 'Relating to the recovery period after arousal', 'The refractory phase is when the body simply cannot respond again yet.'),
  Word('sexology', 'oxytocin', 'n.', 'A hormone linked to bonding and closeness', 'A long embrace releases oxytocin, which deepens a sense of trust.'),
  Word('sexology', 'dopamine', 'n.', 'The brain\'s reward chemical tied to wanting', 'New attraction floods the brain with dopamine and makes time fly.'),
  Word('sexology', 'pheromone', 'n.', 'A chemical signal that may influence attraction', 'Researchers still debate how much a human pheromone really shapes desire.'),
  Word('sexology', 'courtship', 'n.', 'The behavior leading toward a romantic bond', 'Their slow courtship unfolded over months of letters and long walks.'),
  Word('sexology', 'infatuation', 'n.', 'An intense but often shallow attraction', 'She mistook her infatuation for love until the novelty wore off.'),
  Word('sexology', 'demisexual', 'adj.', 'Feeling attraction only after a deep bond forms', 'As a demisexual, he found chemistry grew only once a friendship did.'),
  Word('sexology', 'sapiosexual', 'adj.', 'Drawn primarily to a person\'s intelligence', 'A sapiosexual, she was far more moved by wit than by appearance.'),
  Word('sexology', 'paraphilia', 'n.', 'An atypical pattern of sexual interest', 'The textbook described paraphilia in clinical, non-judgmental terms.'),
  Word('sexology', 'anhedonia', 'n.', 'An inability to feel pleasure or desire', 'His depression brought an anhedonia that dulled even romantic interest.'),
  Word('sexology', 'monogamy', 'n.', 'The practice of having one partner at a time', 'They chose monogamy after a frank talk about their expectations.'),
  Word('sexology', 'polyamory', 'n.', 'Ethical relationships with multiple partners', 'Polyamory, they explained, relied on honesty rather than secrecy.'),
  Word('sexology', 'attachment', 'n.', 'The emotional bond formed with a partner', 'Her anxious attachment made every silence feel like rejection.'),
  Word('sexology', 'intimacy', 'n.', 'Close emotional or physical connection', 'For them, true intimacy meant being fully known and still accepted.'),
  Word('sexology', 'arousal', 'n.', 'The state of heightened sexual responsiveness', 'Arousal involves both the mind and a cascade of bodily changes.'),
  Word('sexology', 'consent', 'n.', 'Freely given agreement to intimate activity', 'Clear, ongoing consent is the foundation of any healthy encounter.'),
  Word('sexology', 'chemistry', 'n.', 'An instinctive spark of mutual attraction', 'They had obvious chemistry, finishing each other\'s sentences all night.'),
  Word('sexology', 'magnetism', 'n.', 'A powerful, almost physical pull toward someone', 'There was a quiet magnetism about her that the whole room felt.'),
  Word('sexology', 'yearning', 'n.', 'A deep, aching longing for someone', 'His yearning for her colored every letter he sent home.'),
  Word('sexology', 'allure', 'n.', 'A quality that strongly attracts or fascinates', 'The mystery she kept only added to her allure.'),
  Word('sexology', 'desire', 'n.', 'A strong wish for closeness or intimacy', 'Desire, the author argued, is as much imagined as it is felt.'),
  Word('sexology', 'vulnerability', 'n.', 'Openness to being emotionally exposed', 'Real intimacy asks for a vulnerability that can feel risky.'),
  Word('sexology', 'afterglow', 'n.', 'The warm calm felt after intimacy', 'They lay in the afterglow, talking softly until they drifted off.'),
  Word('sexology', 'erogenous', 'adj.', 'Highly sensitive to pleasurable touch', 'The neck is a classic erogenous zone for many people.'),
  Word('sexology', 'platonic', 'adj.', 'Affectionate but without sexual desire', 'Their bond stayed warmly platonic for the whole friendship.'),
  Word('sexology', 'celibacy', 'n.', 'Voluntary abstention from sexual relations', 'He chose a period of celibacy to focus on his own healing.'),
  Word('sexology', 'abstinence', 'n.', 'Refraining from sexual activity', 'The clinic discussed abstinence as one of several valid choices.'),
  Word('sexology', 'fidelity', 'n.', 'Faithfulness to a romantic partner', 'They valued fidelity but defined it openly together.'),
  Word('sexology', 'amorous', 'adj.', 'Showing or feeling romantic love', 'He sent an amorous note tucked inside her coat pocket.'),
  Word('sexology', 'flirtation', 'n.', 'Playful behavior signaling romantic interest', 'Their flirtation lived mostly in glances across the office.'),
  Word('sexology', 'coquetry', 'n.', 'Playful, teasing flirtatious behavior', 'A little coquetry in her smile kept him guessing all evening.'),
  Word('sexology', 'dalliance', 'n.', 'A brief or casual romantic involvement', 'It was only a summer dalliance, fond but never serious.'),
  Word('sexology', 'paramour', 'n.', 'A lover, especially an illicit one', 'The novel\'s heroine slipped away each night to meet her paramour.'),
  Word('sexology', 'tryst', 'n.', 'A secret meeting between lovers', 'They arranged a quiet tryst at the old lighthouse.'),
  Word('sexology', 'rendezvous', 'n.', 'A planned meeting, often romantic', 'Their weekly rendezvous at the café became a cherished ritual.'),
  Word('sexology', 'betrothal', 'n.', 'A formal agreement to marry', 'Their betrothal was announced at the harvest festival.'),
  Word('sexology', 'consummate', 'v.', 'To complete a marriage through intimacy', 'By custom, the couple did not consummate the union until the vows.'),
  Word('sexology', 'cohabitation', 'n.', 'Living together as a romantic couple', 'After a year of cohabitation, they decided to marry.'),
  Word('sexology', 'sensual', 'adj.', 'Relating to physical pleasure of the senses', 'The poem offered a sensual portrait of a slow summer morning.'),
  Word('sexology', 'voluptuous', 'adj.', 'Suggesting rich physical or sensual pleasure', 'The painting rendered the figure in voluptuous, glowing tones.'),
  Word('sexology', 'languorous', 'adj.', 'Pleasantly relaxed and unhurried', 'They shared a languorous afternoon tangled in conversation.'),
  Word('sexology', 'tactile', 'adj.', 'Relating to the sense of touch', 'She was a tactile person who expressed affection through small touches.'),
  Word('sexology', 'caress', 'n.', 'A gentle, affectionate touch', 'A light caress along his arm said more than words could.'),
  Word('sexology', 'tenderness', 'n.', 'Gentle warmth and care toward someone', 'There was a tenderness in how he tucked the blanket around her.'),
  Word('sexology', 'devotion', 'n.', 'Deep, loyal love and dedication', 'Decades together had only deepened their devotion.'),
  Word('sexology', 'rapport', 'n.', 'A close, harmonious understanding between people', 'Their easy rapport made strangers assume they were old friends.'),
  Word('sexology', 'reciprocity', 'n.', 'A mutual give-and-take in a relationship', 'Healthy intimacy depends on a steady reciprocity of effort.'),
  Word('sexology', 'compatibility', 'n.', 'The capacity to coexist well as partners', 'They discovered a quiet compatibility in their daily routines.'),
  Word('sexology', 'attraction', 'n.', 'The pull of interest toward another person', 'Physical attraction faded, but their friendship only grew.'),
  Word('sexology', 'enamored', 'adj.', 'Filled with love or fascination', 'He was utterly enamored after a single conversation.'),
  Word('sexology', 'smitten', 'adj.', 'Suddenly and strongly attracted', 'One look across the room and she was completely smitten.'),
  Word('sexology', 'besotted', 'adj.', 'Foolishly and intensely in love', 'He grew so besotted that friends teased him for weeks.'),
  Word('sexology', 'unrequited', 'adj.', 'Of love that is not returned', 'Her unrequited affection made every gathering bittersweet.'),
  Word('sexology', 'pining', 'v.', 'Longing painfully for an absent love', 'He spent the autumn pining for a woman who had moved abroad.'),
  Word('sexology', 'wistful', 'adj.', 'Full of gentle, yearning sadness', 'She gave a wistful smile at the mention of her first love.'),
  Word('sexology', 'ineffable', 'adj.', 'Too deep or great to be put in words', 'The first night they met had an ineffable quality she never forgot.'),
  Word('sexology', 'kindred', 'adj.', 'Sharing a deep, natural affinity', 'They felt like kindred spirits from the very first hour.'),
  Word('sexology', 'soulmate', 'n.', 'A person felt to be a perfect partner', 'He had stopped believing in a soulmate until he met her.'),
  Word('sexology', 'infidelity', 'n.', 'The act of being unfaithful to a partner', 'The novel traced how small secrets grew into infidelity.'),
  Word('sexology', 'jealousy', 'n.', 'Distress at a perceived romantic rival', 'A flash of jealousy surprised her at his easy laughter with another.'),
  Word('sexology', 'codependency', 'n.', 'An unhealthy reliance on a partner\'s needs', 'Therapy helped them name the codependency in their bond.'),
  Word('sexology', 'enmeshment', 'n.', 'A loss of boundaries between partners', 'Their enmeshment left little room for separate friendships.'),
  Word('sexology', 'projection', 'n.', 'Attributing one\'s own feelings to a partner', 'His jealousy was partly projection of his own restlessness.'),
  Word('sexology', 'transference', 'n.', 'Redirecting feelings onto a new figure', 'Old wounds surfaced as transference in her new relationship.'),
  Word('sexology', 'estrangement', 'n.', 'A growing emotional distance between partners', 'Months of silence had hardened into a quiet estrangement.'),
  Word('sexology', 'reconciliation', 'n.', 'The restoring of a broken relationship', 'A long talk led to a tearful reconciliation at last.'),
  Word('sexology', 'androgyny', 'n.', 'A blending of masculine and feminine traits', 'The model\'s androgyny made the campaign feel strikingly modern.'),
  Word('sexology', 'asexual', 'adj.', 'Experiencing little or no sexual attraction', 'As an asexual person, she still valued deep romantic closeness.'),
  Word('sexology', 'pansexual', 'adj.', 'Attracted regardless of gender', 'Being pansexual, he felt drawn to people for who they were.'),
  Word('sexology', 'heteronormative', 'adj.', 'Assuming heterosexuality as the default', 'The survey was criticized for its heteronormative wording.'),
  Word('sexology', 'orientation', 'n.', 'A person\'s pattern of romantic attraction', 'She came to understand her orientation slowly and without shame.'),
  Word('sexology', 'androgynous', 'adj.', 'Having both masculine and feminine qualities', 'His androgynous style defied easy categories.'),
  Word('sexology', 'titillation', 'n.', 'A pleasant, mildly exciting stimulation', 'The play offered more suggestion and titillation than spectacle.'),
  Word('sexology', 'seduction', 'n.', 'The art of enticing romantic interest', 'The novel treated seduction as a slow dance of attention.'),
  Word('sexology', 'enticement', 'n.', 'Something that tempts or attracts', 'The promise of a quiet weekend was enticement enough.'),
  Word('sexology', 'beguiling', 'adj.', 'Charming in a slightly tricky way', 'She had a beguiling habit of changing the subject mid-flirtation.'),
  Word('sexology', 'alluring', 'adj.', 'Powerfully and pleasantly attractive', 'There was something alluring about his quiet confidence.'),
  Word('sexology', 'captivating', 'adj.', 'Holding attention with charm', 'Her captivating laugh drew people across the room.'),
  Word('sexology', 'enthralling', 'adj.', 'So fascinating it holds one spellbound', 'He found her stories utterly enthralling.'),
  Word('sexology', 'ravishing', 'adj.', 'Strikingly and delightfully beautiful', 'She looked ravishing in the soft light of the terrace.'),
  Word('sexology', 'comely', 'adj.', 'Pleasant and attractive in appearance', 'The portrait showed a comely young woman with a knowing smile.'),
  Word('sexology', 'winsome', 'adj.', 'Charming in an innocent, appealing way', 'His winsome manner put even nervous dates at ease.'),
  Word('sexology', 'fervent', 'adj.', 'Showing intense, passionate feeling', 'Her fervent letters revealed a love she rarely spoke aloud.'),
  Word('sexology', 'impassioned', 'adj.', 'Filled with strong emotion or desire', 'He made an impassioned case for giving the romance one more try.'),
  Word('sexology', 'rapture', 'n.', 'Intense joy or delight in another', 'She described the first weeks together as pure rapture.'),
  Word('sexology', 'ecstasy', 'n.', 'An overwhelming feeling of joy or pleasure', 'The reunion left them both in quiet ecstasy.'),
  Word('sexology', 'euphoria', 'n.', 'A feeling of intense happiness', 'New love brought a euphoria that colored everything around her.'),
  Word('sexology', 'nuance', 'n.', 'A subtle shade of feeling or meaning', 'He learned to read every nuance of her changing moods.'),
  Word('sexology', 'restraint', 'n.', 'Self-control over impulse or desire', 'It took real restraint not to call her again that night.'),
  Word('sexology', 'abstemious', 'adj.', 'Sparing in indulgence of pleasure', 'He kept an abstemious lifestyle even in matters of romance.'),
  Word('sexology', 'wanton', 'adj.', 'Lacking restraint, especially in desire', 'The poem warned against a wanton heart that loved too freely.'),
  Word('sexology', 'lascivious', 'adj.', 'Openly expressing strong desire', 'The censors objected to a single lascivious glance in the film.'),
  Word('sexology', 'amatory', 'adj.', 'Relating to love or romantic desire', 'The collection gathered amatory verse from a dozen centuries.'),
  Word('sexology', 'conjugal', 'adj.', 'Relating to marriage and married partners', 'They settled into a quiet conjugal routine within the first year.'),
  Word('sexology', 'uxorious', 'adj.', 'Excessively fond of one\'s wife', 'Friends gently mocked his uxorious habit of quoting her constantly.'),
  Word('sexology', 'inamorata', 'n.', 'A woman with whom one is in love', 'He wrote sonnet after sonnet to his inamorata.'),
  Word('sexology', 'swain', 'n.', 'A young man who courts a woman', 'In the old ballad, a hopeful swain serenades beneath her window.'),
  Word('sexology', 'philander', 'v.', 'To engage in casual romantic affairs', 'He could not stop himself from philandering, and the marriage failed.'),
  Word('sexology', 'fervor', 'n.', 'Intense and passionate feeling', 'She spoke of her new partner with surprising fervor.'),
];
