import 'words_data.dart';

const kSocialScienceExtras = <Word>[
  Word('socialscience', 'anomie', 'n.', 'A breakdown of social norms and shared values', 'After the factory closed, a sense of anomie settled over the whole town.'),
  Word('socialscience', 'hegemony', 'n.', 'Dominance of one group or idea over others', 'Critics argued the company held cultural hegemony over the entire industry.'),
  Word('socialscience', 'gentrification', 'n.', 'Wealthier residents reshaping a poorer neighborhood', 'Rising rents from gentrification pushed lifelong tenants out of the district.'),
  Word('socialscience', 'meritocracy', 'n.', 'A system rewarding people by ability and effort', 'She insisted the firm was a true meritocracy where credentials meant nothing.'),
  Word('socialscience', 'normative', 'adj.', 'Concerned with how things ought to be', 'The debate shifted from facts to a normative question about fairness.'),
  Word('socialscience', 'externality', 'n.', 'A cost or benefit affecting uninvolved third parties', 'Factory smoke is a classic negative externality borne by nearby families.'),
  Word('socialscience', 'stratification', 'n.', 'The ranking of people into social layers', 'The study mapped income stratification across three generations.'),
  Word('socialscience', 'kinship', 'n.', 'Relationships based on family or shared ancestry', 'Anthropologists charted the village kinship ties going back centuries.'),
  Word('socialscience', 'diaspora', 'n.', 'A people scattered far from their homeland', 'The diaspora kept its language alive through weekend community schools.'),
  Word('socialscience', 'demographic', 'adj.', 'Relating to the makeup of a population', 'Marketers tracked demographic shifts among first-time voters.'),
  Word('socialscience', 'oligarchy', 'n.', 'Rule by a small, powerful group', 'Reformers warned the republic was sliding quietly into an oligarchy.'),
  Word('socialscience', 'populism', 'n.', 'Politics framed as ordinary people against elites', 'His campaign rode a wave of populism aimed at distant bankers.'),
  Word('socialscience', 'secularization', 'n.', 'The declining influence of religion in society', 'Surveys traced decades of secularization across European democracies.'),
  Word('socialscience', 'ethnography', 'n.', 'The close study of a culture by living within it', 'Her ethnography of dockworkers took two years of daily fieldwork.'),
  Word('socialscience', 'groupthink', 'n.', 'Bad decisions from a group craving agreement', 'The committee fell into groupthink and ignored every warning sign.'),
  Word('socialscience', 'meritocratic', 'adj.', 'Based on rewarding talent and achievement', 'They redesigned hiring to be more meritocratic and less reliant on referrals.'),
  Word('socialscience', 'collectivism', 'n.', 'Valuing the group above the individual', 'Her research compared collectivism in East Asia with Western individualism.'),
  Word('socialscience', 'individualism', 'n.', 'Valuing personal independence over the group', 'American individualism shows up even in how people furnish their homes.'),
  Word('socialscience', 'patriarchy', 'n.', 'A system where men hold most power', 'Historians traced how the patriarchy shaped inheritance laws.'),
  Word('socialscience', 'matriarchy', 'n.', 'A society where women hold central authority', 'The tribe was a rare matriarchy in which property passed through mothers.'),
  Word('socialscience', 'acculturation', 'n.', 'Adopting the traits of another culture', 'Acculturation often happens fastest among the children of immigrants.'),
  Word('socialscience', 'assimilation', 'n.', 'Blending fully into a dominant culture', 'The policy pushed assimilation by banning the use of native languages.'),
  Word('socialscience', 'ethnocentrism', 'n.', 'Judging other cultures by your own standards', 'The travel writer was criticized for unmistakable ethnocentrism.'),
  Word('socialscience', 'xenophobia', 'n.', 'Fear or dislike of people from elsewhere', 'The recession stoked a wave of xenophobia against newcomers.'),
  Word('socialscience', 'nativism', 'n.', 'Favoring native-born people over immigrants', 'Nativism surged in the speeches of the upstart party.'),
  Word('socialscience', 'mobility', 'n.', 'Movement between social or economic classes', 'Economists worry that upward mobility has stalled for younger workers.'),
  Word('socialscience', 'plutocracy', 'n.', 'Rule by the wealthy', 'Pamphlets warned the nation was drifting toward open plutocracy.'),
  Word('socialscience', 'technocracy', 'n.', 'Government run by technical experts', 'Critics called the agency a technocracy answerable to no voters.'),
  Word('socialscience', 'bureaucracy', 'n.', 'A system run by complex official procedures', 'Getting the permit meant weeks lost inside the housing bureaucracy.'),
  Word('socialscience', 'gerrymander', 'v.', 'To redraw voting districts for partisan gain', 'The legislature moved to gerrymander the map before the next election.'),
  Word('socialscience', 'disenfranchise', 'v.', 'To deprive someone of the right to vote', 'The new rules quietly disenfranchised thousands of rural residents.'),
  Word('socialscience', 'suffrage', 'n.', 'The right to vote in public elections', 'The movement fought for decades to win universal suffrage.'),
  Word('socialscience', 'incumbency', 'n.', 'The advantage of already holding office', 'Incumbency gave the senator a name recognition his rival lacked.'),
  Word('socialscience', 'partisan', 'adj.', 'Strongly loyal to one political side', 'The vote split along strictly partisan lines.'),
  Word('socialscience', 'polarization', 'n.', 'A split into two opposing extremes', 'Media habits have deepened political polarization across the country.'),
  Word('socialscience', 'demagoguery', 'n.', 'Stirring crowds with emotion over reason', 'His rallies traded careful policy for raw demagoguery.'),
  Word('socialscience', 'autocracy', 'n.', 'Rule by a single unchecked leader', 'The coup turned a fragile democracy into an autocracy overnight.'),
  Word('socialscience', 'federalism', 'n.', 'Power shared between central and regional governments', 'Federalism lets states experiment with their own health policies.'),
  Word('socialscience', 'devolution', 'n.', 'Transfer of power to lower levels of government', 'Devolution gave the region control over its own schools.'),
  Word('socialscience', 'protectionism', 'n.', 'Shielding home industries with tariffs and rules', 'Rising protectionism made imported steel far more expensive.'),
  Word('socialscience', 'mercantilism', 'n.', 'Building national wealth through trade surpluses', 'Colonial powers practiced mercantilism to enrich the mother country.'),
  Word('socialscience', 'monopsony', 'n.', 'A market with only one major buyer', 'In that company town, the mine operated as a labor monopsony.'),
  Word('socialscience', 'oligopoly', 'n.', 'A market dominated by a few firms', 'Three carriers formed an oligopoly that kept airfares high.'),
  Word('socialscience', 'monopoly', 'n.', 'Sole control of a market by one seller', 'Regulators broke up the monopoly to let rivals compete.'),
  Word('socialscience', 'arbitrage', 'n.', 'Profiting from price gaps between markets', 'Traders made millions through arbitrage across the two exchanges.'),
  Word('socialscience', 'liquidity', 'n.', 'How easily an asset turns into cash', 'The startup had assets on paper but almost no liquidity.'),
  Word('socialscience', 'inflation', 'n.', 'A general rise in prices over time', 'Stubborn inflation ate into every family\'s grocery budget.'),
  Word('socialscience', 'deflation', 'n.', 'A general fall in prices over time', 'Economists feared deflation would make people delay spending.'),
  Word('socialscience', 'stagflation', 'n.', 'Stagnant growth paired with rising prices', 'The 1970s taught policymakers how painful stagflation can be.'),
  Word('socialscience', 'recession', 'n.', 'A sustained decline in economic activity', 'The recession wiped out a fifth of the city\'s factory jobs.'),
  Word('socialscience', 'fiscal', 'adj.', 'Relating to government taxing and spending', 'The minister promised tighter fiscal discipline next year.'),
  Word('socialscience', 'monetary', 'adj.', 'Relating to money supply and interest rates', 'The central bank tightened monetary policy to cool demand.'),
  Word('socialscience', 'subsidy', 'n.', 'Government money supporting an activity or group', 'A fuel subsidy kept rural transport affordable for years.'),
  Word('socialscience', 'tariff', 'n.', 'A tax charged on imported goods', 'The new tariff raised the price of every imported car.'),
  Word('socialscience', 'austerity', 'n.', 'Sharp cuts in government spending', 'Years of austerity left the public hospitals badly understaffed.'),
  Word('socialscience', 'redistribution', 'n.', 'Shifting wealth from richer to poorer groups', 'The tax plan leaned heavily on income redistribution.'),
  Word('socialscience', 'commodify', 'v.', 'To turn something into a thing bought and sold', 'Critics warned the app would commodify ordinary friendships.'),
  Word('socialscience', 'precariat', 'n.', 'Workers stuck in insecure, low-paid jobs', 'Gig drivers form a growing precariat with no benefits.'),
  Word('socialscience', 'proletariat', 'n.', 'The class of workers who sell their labor', 'Marx argued the proletariat would eventually organize against owners.'),
  Word('socialscience', 'bourgeoisie', 'n.', 'The property-owning middle and upper class', 'The novel mocked the comfortable habits of the bourgeoisie.'),
  Word('socialscience', 'feudalism', 'n.', 'A system of land held in exchange for service', 'Under feudalism, peasants worked land they could never own.'),
  Word('socialscience', 'corporatism', 'n.', 'Organizing society through big interest groups', 'The deal reflected a corporatism that sidelined ordinary citizens.'),
  Word('socialscience', 'clientelism', 'n.', 'Trading favors and jobs for political loyalty', 'The party machine ran on decades of patient clientelism.'),
  Word('socialscience', 'patronage', 'n.', 'Handing out jobs or favors for support', 'Government posts went out as patronage to loyal donors.'),
  Word('socialscience', 'nepotism', 'n.', 'Favoring relatives in jobs or power', 'The firm reeked of nepotism, with cousins in every department.'),
  Word('socialscience', 'cronyism', 'n.', 'Rewarding friends with positions and contracts', 'The contracts smelled of cronyism rather than open bidding.'),
  Word('socialscience', 'kleptocracy', 'n.', 'Rule by leaders who steal public wealth', 'The regime had decayed into an open kleptocracy.'),
  Word('socialscience', 'irredentism', 'n.', 'Claiming territory based on shared ethnicity or history', 'Border tensions were fueled by decades of irredentism.'),
  Word('socialscience', 'nationalism', 'n.', 'Strong devotion to one\'s own nation', 'A surge of nationalism reshaped the country\'s politics.'),
  Word('socialscience', 'multiculturalism', 'n.', 'Many cultures coexisting within one society', 'The city celebrated its multiculturalism with a yearly festival.'),
  Word('socialscience', 'socialization', 'n.', 'Learning the norms and roles of a society', 'Schools play a huge part in the socialization of children.'),
  Word('socialscience', 'stigmatize', 'v.', 'To mark someone with strong social disapproval', 'Campaigns tried to stop society from stigmatizing mental illness.'),
  Word('socialscience', 'marginalize', 'v.', 'To push a group to the edges of society', 'The reforms aimed to stop marginalizing disabled workers.'),
  Word('socialscience', 'ostracize', 'v.', 'To deliberately exclude someone from a group', 'The villagers ostracized anyone who broke the old customs.'),
  Word('socialscience', 'conformity', 'n.', 'Matching one\'s behavior to group expectations', 'The classic experiment measured conformity under peer pressure.'),
  Word('socialscience', 'deviance', 'n.', 'Behavior that breaks social norms', 'Sociologists study how each culture defines deviance differently.'),
  Word('socialscience', 'taboo', 'n.', 'A strong social ban on something', 'Discussing salaries remains a workplace taboo in many offices.'),
  Word('socialscience', 'reciprocity', 'n.', 'The mutual exchange of favors or goods', 'Gift-giving among the clans ran on careful reciprocity.'),
  Word('socialscience', 'solidarity', 'n.', 'Unity built on shared interests or feeling', 'Workers across the plant showed solidarity during the strike.'),
  Word('socialscience', 'cohesion', 'n.', 'The degree a group sticks together', 'Shared rituals strengthened the team\'s social cohesion.'),
  Word('socialscience', 'tribalism', 'n.', 'Strong loyalty to one\'s own group above others', 'Online debates often collapse into pure tribalism.'),
  Word('socialscience', 'paternalism', 'n.', 'Restricting people for their supposed own good', 'Critics called the new rules an example of state paternalism.'),
  Word('socialscience', 'utilitarian', 'adj.', 'Judging acts by the greatest good produced', 'The policy took a utilitarian view, weighing total welfare gained.'),
  Word('socialscience', 'egalitarian', 'adj.', 'Believing all people deserve equal treatment', 'The commune was run on strictly egalitarian principles.'),
  Word('socialscience', 'libertarian', 'adj.', 'Favoring minimal government and maximum liberty', 'Her libertarian leanings made her wary of any new regulation.'),
  Word('socialscience', 'cosmopolitan', 'adj.', 'At home among many cultures and places', 'The port city had a cosmopolitan crowd from every continent.'),
  Word('socialscience', 'parochial', 'adj.', 'Narrow in outlook, limited to local concerns', 'His parochial views ignored anything beyond the county line.'),
  Word('socialscience', 'insular', 'adj.', 'Cut off and uninterested in outside ideas', 'The insular community rarely welcomed strangers.'),
  Word('socialscience', 'cleavage', 'n.', 'A deep dividing line within a society', 'The vote exposed a sharp urban-rural cleavage.'),
  Word('socialscience', 'enfranchise', 'v.', 'To grant someone the right to vote', 'The amendment finally enfranchised millions of young adults.'),
  Word('socialscience', 'plebiscite', 'n.', 'A direct popular vote on a single question', 'The borders were redrawn after a hastily called plebiscite.'),
  Word('socialscience', 'referendum', 'n.', 'A public vote on a specific proposal', 'Voters rejected the merger in a binding referendum.'),
  Word('socialscience', 'fertility', 'n.', 'The average number of children per woman', 'Falling fertility has reshaped the country\'s pension math.'),
  Word('socialscience', 'longevity', 'n.', 'How long people in a group tend to live', 'Rising longevity strains both budgets and family caregivers.'),
  Word('socialscience', 'cohort', 'n.', 'A group sharing a trait, often birth year', 'The study followed one cohort of graduates for forty years.'),
  Word('socialscience', 'urbanization', 'n.', 'The shift of people into cities', 'Rapid urbanization swelled the capital past its planning.'),
  Word('socialscience', 'sectarian', 'adj.', 'Driven by rivalry between religious groups', 'The region was scarred by years of sectarian conflict.'),
  Word('socialscience', 'theocracy', 'n.', 'Government run by religious authority', 'The revolution replaced the monarchy with a theocracy.'),
  Word('socialscience', 'meritocrat', 'n.', 'Someone who rose through talent and effort', 'He styled himself a meritocrat who owed nothing to family money.'),
  Word('socialscience', 'demagogue', 'n.', 'A leader who exploits fear and prejudice', 'The crisis gave the demagogue an eager audience.'),
];
