import 'words_data.dart';

const kTravelExtras2 = <Word>[
  Word('travel', 'excursion', 'n.', 'A short trip taken for pleasure or sightseeing', 'The ship offered a half-day excursion to the volcanic caves.'),
  Word('travel', 'sightseeing', 'n.', 'The activity of visiting interesting places as a tourist', 'They spent the morning sightseeing before the heat set in.'),
  Word('travel', 'wayfaring', 'adj.', 'Traveling on foot from place to place', 'The wayfaring monk had crossed three countries with only a satchel.'),
  Word('travel', 'sojournment', 'n.', 'A temporary stay in a place', 'Their brief sojournment in the alpine town stretched into a month.'),
  Word('travel', 'peregrination', 'n.', 'A long, wandering journey', 'His peregrination through the desert lasted nearly a year.'),
  Word('travel', 'commute', 'n.', 'A regular journey between home and work', 'Her daily commute by tram took just under forty minutes.'),
  Word('travel', 'thruway', 'n.', 'A major highway built for fast travel', 'We merged onto the thruway and finally picked up speed.'),
  Word('travel', 'byway', 'n.', 'A minor road or path away from the main route', 'They wandered down a quiet byway lined with olive trees.'),
  Word('travel', 'laneway', 'n.', 'A narrow lane, often between buildings', 'The cafe was tucked into a laneway you could easily miss.'),
  Word('travel', 'footpath', 'n.', 'A narrow path for people walking', 'A footpath wound up the hillside to the ruined tower.'),
  Word('travel', 'towpath', 'n.', 'A path beside a canal or river for towing boats', 'Cyclists glided along the towpath beside the slow green water.'),
  Word('travel', 'causeway', 'n.', 'A raised road or path across water or wet ground', 'At low tide we crossed the causeway to the island monastery.'),
  Word('travel', 'viaduct', 'n.', 'A long bridge carrying a road or railway over a valley', 'The train slowed as it crossed the towering stone viaduct.'),
  Word('travel', 'aqueduct', 'n.', 'A bridge or channel built to carry water across a gap', 'The Roman aqueduct still spanned the river after two thousand years.'),
  Word('travel', 'underpass', 'n.', 'A road or path that passes beneath another', 'We took the underpass to avoid the busy junction above.'),
  Word('travel', 'overpass', 'n.', 'A bridge that carries a road over another road', 'Traffic crawled along the overpass during rush hour.'),
  Word('travel', 'interchange', 'n.', 'A junction where roads or rail lines connect', 'Missing the interchange added an hour to the drive.'),
  Word('travel', 'junction', 'n.', 'A point where roads or railways meet', 'Change trains at the next junction for the coastal line.'),
  Word('travel', 'terminus', 'n.', 'The end of a railway or bus line', 'The bus emptied out at the terminus by the old harbor.'),
  Word('travel', 'depot', 'n.', 'A station or building where buses or trains are kept', 'We bought tickets at the bus depot before dawn.'),
  Word('travel', 'wagonlit', 'n.', 'A railway sleeping car', 'They booked a wagonlit for the long overnight journey south.'),
  Word('travel', 'carriage', 'n.', 'A separate section of a passenger train', 'The dining carriage was three cars back from their seats.'),
  Word('travel', 'caboose', 'n.', 'The last car on a freight train, for the crew', 'A red caboose rattled past at the end of the long freight train.'),
  Word('travel', 'locomotive', 'n.', 'The powered vehicle that pulls a train', 'A steam locomotive hauled the heritage train through the gorge.'),
  Word('travel', 'railhead', 'n.', 'The farthest point a railway line reaches', 'The expedition restocked supplies at the dusty railhead.'),
  Word('travel', 'sidetrack', 'n.', 'A short railway track branching off the main line', 'The freight cars were shunted onto a sidetrack overnight.'),
  Word('travel', 'trackside', 'adj.', 'Located beside a railway track', 'A small trackside stall sold tea to waiting passengers.'),
  Word('travel', 'fare', 'n.', 'The money paid for a journey on public transport', 'The ferry fare included a free shuttle to the old town.'),
  Word('travel', 'fareboard', 'n.', 'A sign showing the prices of journeys', 'She squinted at the fareboard to find the cheapest zone.'),
  Word('travel', 'turnaround', 'n.', 'The time a vehicle spends before its return trip', 'The plane had a tight turnaround of just forty minutes.'),
  Word('travel', 'gateside', 'adj.', 'Located near a departure gate', 'A gateside cafe sold overpriced coffee to hurried fliers.'),
  Word('travel', 'baggagehall', 'n.', 'The area where arriving passengers collect luggage', 'They waited in the baggagehall as the carousel finally creaked to life.'),
  Word('travel', 'carousel', 'n.', 'A rotating belt that delivers luggage to passengers', 'Her suitcase was the last bag left circling the carousel.'),
  Word('travel', 'duty-free', 'adj.', 'Sold without import tax, usually at airports', 'He browsed the duty-free shop while waiting to board.'),
  Word('travel', 'jetbridge', 'n.', 'The covered walkway connecting a gate to a plane', 'They shuffled down the jetbridge into the warm cabin.'),
  Word('travel', 'runway', 'n.', 'The long strip where planes take off and land', 'The plane idled at the end of the runway for clearance.'),
  Word('travel', 'taxiway', 'n.', 'The path planes use to move between runway and gate', 'The jet rolled slowly along the taxiway toward the terminal.'),
  Word('travel', 'apron', 'n.', 'The paved airport area where planes park and load', 'Ground crews scurried across the apron in the rain.'),
  Word('travel', 'hangar', 'n.', 'A large building where aircraft are kept', 'The vintage biplane was wheeled out of the hangar at dawn.'),
  Word('travel', 'cockpit', 'n.', 'The space where pilots sit and control an aircraft', 'A child peeked into the cockpit before takeoff.'),
  Word('travel', 'fuselage', 'n.', 'The main body of an aircraft', 'Rivets ran in neat lines along the polished fuselage.'),
  Word('travel', 'empennage', 'n.', 'The tail assembly of an aircraft', 'The airline\'s logo was painted across the empennage.'),
  Word('travel', 'altimeter', 'n.', 'An instrument that measures height above the ground', 'The pilot watched the altimeter as the plane descended.'),
  Word('travel', 'sextant', 'n.', 'An instrument used to navigate by the stars', 'The old captain still kept a brass sextant in his cabin.'),
  Word('travel', 'astrolabe', 'n.', 'An ancient device for measuring star positions', 'Sailors once crossed oceans guided by an astrolabe.'),
  Word('travel', 'lodestar', 'n.', 'A star used to guide the way, especially the North Star', 'They steered by the lodestar through the moonless night.'),
  Word('travel', 'cartography', 'n.', 'The science and art of making maps', 'His passion for cartography filled the study with old charts.'),
  Word('travel', 'cartographer', 'n.', 'A person who draws or makes maps', 'The cartographer marked the new road with a careful pencil line.'),
  Word('travel', 'atlas', 'n.', 'A bound collection of maps', 'She traced the river route across two pages of the worn atlas.'),
  Word('travel', 'gazetteer', 'n.', 'A geographical dictionary listing place names', 'He looked up the tiny village in an old gazetteer.'),
  Word('travel', 'topography', 'n.', 'The shape and features of a land surface', 'The rugged topography made the trail slow and steep.'),
  Word('travel', 'terrain', 'n.', 'A stretch of land with its natural features', 'The four-by-four handled the rocky terrain with ease.'),
  Word('travel', 'escarpment', 'n.', 'A long, steep slope at the edge of a plateau', 'The road clung to the escarpment high above the valley.'),
  Word('travel', 'promontory', 'n.', 'A high point of land jutting into the sea', 'A lighthouse stood on the wind-battered promontory.'),
  Word('travel', 'headland', 'n.', 'A narrow piece of land projecting into the water', 'They hiked out to the headland to watch the waves crash.'),
  Word('travel', 'foreland', 'n.', 'A region of land in front of a larger feature', 'The coastal foreland was dotted with grazing sheep.'),
  Word('travel', 'archways', 'n.', 'Curved structures forming passages, seen together', 'The bridge\'s stone archways framed the river beautifully.'),
  Word('travel', 'foothill', 'n.', 'A low hill at the base of a mountain', 'The vineyards spread across the gentle foothill slopes.'),
  Word('travel', 'piedmont', 'n.', 'An area of land lying at the foot of mountains', 'The piedmont was famous for its rolling wine country.'),
  Word('travel', 'ravine', 'n.', 'A deep, narrow valley cut by water', 'A rope bridge swayed across the misty ravine.'),
  Word('travel', 'gorge', 'n.', 'A deep, steep-sided valley', 'The river thundered through the narrow limestone gorge.'),
  Word('travel', 'canyon', 'n.', 'A deep valley with steep rocky sides', 'They rafted the rapids deep inside the red canyon.'),
  Word('travel', 'crevasse', 'n.', 'A deep crack in a glacier or thick ice', 'The climbers roped together to cross the hidden crevasse.'),
  Word('travel', 'moraine', 'n.', 'Rock and debris left behind by a glacier', 'A long moraine marked where the ice had once reached.'),
  Word('travel', 'tarn', 'n.', 'A small mountain lake', 'They camped beside a still tarn high in the hills.'),
  Word('travel', 'fenland', 'n.', 'Low, flat, marshy land', 'Migrating birds gathered across the misty fenland at dusk.'),
  Word('travel', 'heath', 'n.', 'An open area of wild, shrubby land', 'A cold wind swept across the purple heath.'),
  Word('travel', 'moor', 'n.', 'A broad area of open, often hilly, wild land', 'Fog rolled over the moor and swallowed the path.'),
  Word('travel', 'scrubland', 'n.', 'Land covered with low bushes and small trees', 'The trail crossed dry scrubland before reaching the springs.'),
  Word('travel', 'badlands', 'n.', 'Dry, heavily eroded terrain that is hard to cross', 'The badlands stretched out in eerie, wind-carved ridges.'),
  Word('travel', 'outback', 'n.', 'The remote, dry inland regions of Australia', 'They drove for hours through the empty red outback.'),
  Word('travel', 'hinterlands', 'n.', 'Remote areas far from cities or the coast', 'The road map ran out once they reached the hinterlands.'),
  Word('travel', 'backcountry', 'n.', 'Remote, undeveloped wilderness areas', 'A permit was required to camp in the backcountry.'),
  Word('travel', 'wilderness', 'n.', 'A wild region untouched by human development', 'The trail vanished into pure mountain wilderness.'),
  Word('travel', 'frontier', 'n.', 'The edge of settled or explored territory', 'The trading post sat on the dusty frontier of the map.'),
  Word('travel', 'borderlands', 'n.', 'Regions near the boundary between two countries', 'Their passports were stamped twice in the busy borderlands.'),
  Word('travel', 'checkpoint', 'n.', 'A place where travelers are stopped and inspected', 'Soldiers waved the bus through the mountain checkpoint.'),
  Word('travel', 'frontierpost', 'n.', 'A station at the border between countries', 'They queued for an hour at the remote frontierpost.'),
  Word('travel', 'embassy', 'n.', 'The official residence and office of an ambassador abroad', 'He renewed his passport at the embassy before the trip.'),
  Word('travel', 'consulate', 'n.', 'A government office abroad that helps its citizens', 'The consulate issued an emergency document within a day.'),
  Word('travel', 'expat', 'n.', 'A person living outside their native country', 'A small community of expats met weekly at the harbor cafe.'),
  Word('travel', 'emigrate', 'v.', 'To leave one\'s own country to settle in another', 'Her grandparents emigrated across the ocean in 1951.'),
  Word('travel', 'repatriate', 'v.', 'To return someone to their own country', 'The airline helped repatriate stranded passengers after the storm.'),
  Word('travel', 'disembarkation', 'n.', 'The act of leaving a ship or aircraft', 'Disembarkation was delayed while customs cleared the deck.'),
  Word('travel', 'gangplank', 'n.', 'A movable plank used to board or leave a ship', 'Passengers filed up the gangplank with their cases.'),
  Word('travel', 'stowaway', 'n.', 'A person who hides aboard a vehicle to travel secretly', 'A stowaway was found in the cargo hold at the next port.'),
  Word('travel', 'flotilla', 'n.', 'A small fleet of boats or ships traveling together', 'A flotilla of fishing boats set out at first light.'),
  Word('travel', 'armada', 'n.', 'A large fleet of ships', 'An armada of sailboats filled the bay for the regatta.'),
  Word('travel', 'schooner', 'n.', 'A sailing ship with two or more masts', 'They booked a sunset cruise aboard a wooden schooner.'),
  Word('travel', 'galleon', 'n.', 'A large sailing ship used in past centuries', 'The museum housed a full-scale model of a Spanish galleon.'),
  Word('travel', 'trawler', 'n.', 'A fishing boat that drags nets through the water', 'A weathered trawler returned to the quay at dawn.'),
  Word('travel', 'dinghy', 'n.', 'A small open boat', 'They rowed the dinghy out to the anchored yacht.'),
  Word('travel', 'outrigger', 'n.', 'A frame or float extending from the side of a boat', 'The outrigger canoe sliced steadily across the lagoon.'),
  Word('travel', 'paddle', 'n.', 'A short oar used to move a small boat', 'She dipped the paddle and the kayak glided forward.'),
  Word('travel', 'helm', 'n.', 'The wheel or tiller used to steer a ship', 'The captain stood calmly at the helm through the squall.'),
  Word('travel', 'moorage', 'n.', 'A place where a boat can be tied up', 'They found overnight moorage at the small island marina.'),
  Word('travel', 'anchorage', 'n.', 'A place where ships can safely drop anchor', 'The sheltered anchorage filled with yachts by evening.'),
  Word('travel', 'breakwall', 'n.', 'A barrier built to protect a harbor from waves', 'Spray leaped over the breakwall during the high tide.'),
  Word('travel', 'lockgate', 'n.', 'A gate that controls water levels in a canal', 'The barge waited while the lockgate slowly swung open.'),
  Word('travel', 'ferryman', 'n.', 'A person who operates a ferry', 'The ferryman knew every shoal in the dark estuary.'),
  Word('travel', 'boatman', 'n.', 'A person who rows or manages a small boat', 'A boatman poled them silently through the flooded temple.'),
  Word('travel', 'rambler', 'n.', 'A person who walks for pleasure in the countryside', 'A cheerful rambler waved from across the misty field.'),
  Word('travel', 'trekker', 'n.', 'A person who makes long, difficult journeys on foot', 'The trekker adjusted her boots before the steep ascent.'),
  Word('travel', 'mountaineer', 'n.', 'A person who climbs mountains', 'The mountaineer fixed her crampons before the icy traverse.'),
  Word('travel', 'spelunker', 'n.', 'A person who explores caves as a hobby', 'The spelunker switched on his headlamp at the cave mouth.'),
  Word('travel', 'caver', 'n.', 'A person who explores underground caves', 'A seasoned caver led them through the narrow limestone tunnel.'),
  Word('travel', 'cartload', 'n.', 'The amount a cart can carry', 'A cartload of melons rumbled past on the market road.'),
  Word('travel', 'packhorse', 'n.', 'A horse used to carry loads on a journey', 'Their gear was strapped to a sturdy packhorse for the climb.'),
  Word('travel', 'mule', 'n.', 'A sturdy animal often used to carry loads on trails', 'A train of mules hauled supplies up the canyon path.'),
  Word('travel', 'dromedary', 'n.', 'A one-humped camel used for desert travel', 'They crossed the dunes on a swaying dromedary at sunset.'),
  Word('travel', 'howdah', 'n.', 'A seat for riders carried on an elephant\'s back', 'Tourists wobbled in the howdah as the elephant lumbered on.'),
  Word('travel', 'palfrey', 'n.', 'A gentle riding horse for long journeys', 'The traveler rested her tired palfrey by the stream.'),
  Word('travel', 'wanderer', 'n.', 'A person who roams without a fixed destination', 'The old wanderer carried everything he owned on his back.'),
  Word('travel', 'drifter', 'n.', 'A person who moves from place to place without settling', 'A friendly drifter shared stories around the hostel fire.'),
  Word('travel', 'itinerary', 'n.', 'A planned route or schedule for a trip', 'She emailed the full itinerary to everyone before departure.'),
  Word('travel', 'wanderings', 'n.', 'Aimless or extended travels from place to place', 'His wanderings took him to ports he could no longer name.'),
  Word('travel', 'expeditionary', 'adj.', 'Relating to a journey of exploration', 'The expeditionary team mapped the unnamed glacier.'),
  Word('travel', 'voyaging', 'n.', 'The act of making long sea or space journeys', 'Years of voyaging had weathered the old sailor\'s face.'),
  Word('travel', 'crossingpoint', 'n.', 'A place where a border or river is crossed', 'The only crossingpoint for miles was a swaying rope bridge.'),
  Word('travel', 'wayfarers', 'n.', 'People who travel, especially on foot', 'A shrine by the road offered shelter to passing wayfarers.'),
  Word('travel', 'pathway', 'n.', 'A track or route along which one walks', 'A lantern-lit pathway curved toward the temple gate.'),
  Word('travel', 'walkway', 'n.', 'A passage or path for walking', 'A wooden walkway crossed the marsh above the reeds.'),
  Word('travel', 'boardwalk', 'n.', 'A raised wooden path, often along a beach', 'They strolled the boardwalk as the sun dipped into the sea.'),
  Word('travel', 'corniche', 'n.', 'A road running along a coast or cliff edge', 'The corniche offered dizzying views of the turquoise bay.'),
  Word('travel', 'highroad', 'n.', 'A main road between towns', 'They rejoined the highroad just before the storm broke.'),
  Word('travel', 'lowroad', 'n.', 'A lower or longer route, often through valleys', 'The lowroad took longer but spared them the icy pass.'),
  Word('travel', 'roadhouse', 'n.', 'An inn or restaurant beside a country road', 'They stopped at a dusty roadhouse for a late lunch.'),
  Word('travel', 'wayhouse', 'n.', 'A house offering rest to travelers along a route', 'An old wayhouse still served weary pilgrims tea and bread.'),
  Word('travel', 'tollroad', 'n.', 'A road that charges a fee to use', 'The tollroad was empty and fast at that early hour.'),
  Word('travel', 'milepost', 'n.', 'A post marking distance along a road', 'A faded milepost told them the city was thirty miles off.'),
  Word('travel', 'signpost', 'n.', 'A sign showing directions and distances', 'A weathered signpost pointed three ways at the crossroads.'),
  Word('travel', 'waystation', 'n.', 'A stopping place on a long journey', 'The mountain hut served as a waystation for climbers.'),
  Word('travel', 'mileagecap', 'n.', 'A limit on distance allowed, as for a rental', 'Their cheap car deal came with a strict mileagecap.'),
  Word('travel', 'roadworthy', 'adj.', 'Safe and fit to be driven on the road', 'The mechanic declared the old camper roadworthy at last.'),
  Word('travel', 'seaworthy', 'adj.', 'Safe and fit to sail on the sea', 'The little boat looked barely seaworthy in the swell.'),
  Word('travel', 'airworthy', 'adj.', 'Safe and fit to fly', 'Engineers confirmed the vintage plane was airworthy.'),
  Word('travel', 'pack', 'v.', 'To put belongings into bags for a journey', 'She learned to pack light after years on the road.'),
  Word('travel', 'unpack', 'v.', 'To take belongings out of bags after arriving', 'They didn\'t bother to unpack for just one night.'),
  Word('travel', 'embarkdeck', 'n.', 'The deck where passengers board a ship', 'A band played on the embarkdeck as the liner pulled away.'),
  Word('travel', 'portside', 'adj.', 'On the left side of a ship', 'Their portside cabin looked out over the open water.'),
  Word('travel', 'leeward', 'adj.', 'On the side sheltered from the wind', 'They anchored on the leeward side to escape the gale.'),
  Word('travel', 'windward', 'adj.', 'On the side facing the wind', 'Spray lashed the windward rail all through the night.'),
  Word('travel', 'becalmed', 'adj.', 'Unable to move because there is no wind', 'The yacht sat becalmed for hours under a glassy sky.'),
  Word('travel', 'seafaring', 'adj.', 'Relating to traveling by sea', 'The town had a proud seafaring history going back centuries.'),
  Word('travel', 'overnighter', 'n.', 'A short trip or stay lasting one night', 'They packed a small bag for the quick overnighter to the coast.'),
  Word('travel', 'daytripper', 'n.', 'A person who visits a place for just one day', 'The village swelled with daytrippers every summer weekend.'),
  Word('travel', 'gallivanting', 'adj.', 'Traveling around for fun and adventure', 'She spent the gap year gallivanting across the continent.'),
  Word('travel', 'transcontinental', 'adj.', 'Crossing a whole continent', 'They booked a transcontinental train through five time zones.'),
  Word('travel', 'circumnavigate', 'v.', 'To travel all the way around something', 'It took her three years to circumnavigate the globe by boat.'),
  Word('travel', 'traverse', 'v.', 'To travel across or through an area', 'They planned to traverse the salt flats before nightfall.'),
];
