import 'words_data.dart';

const kTravelExtras = <Word>[
  Word('travel', 'passport', 'n.', 'An official document letting you cross borders', 'I almost missed my flight because my passport was buried in a side pocket.'),
  Word('travel', 'visa', 'n.', 'A permission stamp to enter a foreign country', 'You need a visa on arrival for most travelers landing in Cambodia.'),
  Word('travel', 'boarding', 'n.', 'The act of getting onto a plane, train, or ship', 'Boarding starts an hour before takeoff at gate 42.'),
  Word('travel', 'customs', 'n.', 'The border checkpoint that inspects what you bring in', 'Customs flagged my suitcase for a slab of cheese I forgot to declare.'),
  Word('travel', 'terminal', 'n.', 'A building where passengers board planes or buses', 'Terminal three handles all the international long-haul flights.'),
  Word('travel', 'concourse', 'n.', 'A long open passage in an airport or station', 'The concourse stretches half a mile from security to the last gate.'),
  Word('travel', 'tarmac', 'n.', 'The paved runway area where planes taxi and park', 'We sat on the tarmac for forty minutes waiting for a clearance.'),
  Word('travel', 'jetway', 'n.', 'The movable corridor connecting gate to aircraft', 'The jetway smelled like jet fuel and coffee that morning.'),
  Word('travel', 'baggage', 'n.', 'The bags and cases a traveler carries', 'Baggage claim was a mess of identical black rollers.'),
  Word('travel', 'carryon', 'n.', 'A small bag you bring into the plane cabin', 'I live out of one carryon for trips up to a month.'),
  Word('travel', 'checkin', 'n.', 'The act of registering for a flight or hotel', 'Online checkin saved me from the queue at the counter.'),
  Word('travel', 'checkout', 'n.', 'Settling the bill and leaving a hotel', 'Late checkout is sometimes free if you ask the front desk politely.'),
  Word('travel', 'doorman', 'n.', 'A staff member who attends the entrance of a hotel', 'The doorman hailed a taxi and gave the driver our address in fast Italian.'),
  Word('travel', 'bellhop', 'n.', 'A hotel worker who carries guests\' luggage', 'A grinning bellhop wheeled our bags through the marble lobby.'),
  Word('travel', 'lobby', 'n.', 'The entrance hall of a hotel or building', 'We met in the lobby under a chandelier the size of a car.'),
  Word('travel', 'suite', 'n.', 'A set of connected hotel rooms', 'Our suite had a soaking tub overlooking the harbor.'),
  Word('travel', 'amenity', 'n.', 'A small comfort or service a hotel provides', 'The amenity kit included slippers, an eye mask, and lavender spray.'),
  Word('travel', 'minibar', 'n.', 'A small in-room fridge of overpriced drinks', 'I never touch the minibar after seeing the price of the peanuts.'),
  Word('travel', 'turndown', 'n.', 'Evening service that prepares the bed for sleep', 'Turndown left a chocolate and a weather card on the pillow.'),
  Word('travel', 'penthouse', 'n.', 'A luxurious top-floor apartment or suite', 'The penthouse had a private elevator and a wraparound terrace.'),
  Word('travel', 'riad', 'n.', 'A traditional Moroccan house with a courtyard', 'Our riad in the medina was a cool oasis behind a small wooden door.'),
  Word('travel', 'ryokan', 'n.', 'A traditional Japanese inn with tatami rooms', 'At the ryokan we slept on futons and bathed in a steaming onsen.'),
  Word('travel', 'hacienda', 'n.', 'A large rural estate in Spanish-speaking countries', 'The hacienda had been converted into a boutique hotel surrounded by agave fields.'),
  Word('travel', 'chalet', 'n.', 'A wooden mountain house, often used for ski stays', 'We rented a chalet for the week with a fireplace and bunk beds.'),
  Word('travel', 'pousada', 'n.', 'A Portuguese or Brazilian guesthouse in a historic building', 'Our pousada was a converted convent with stone walls and orange trees.'),
  Word('travel', 'gasthaus', 'n.', 'A small German inn serving food and drink', 'We ducked into a gasthaus for schnitzel and a stein of beer.'),
  Word('travel', 'caravanserai', 'n.', 'An old roadside inn for desert caravans', 'The caravanserai once sheltered Silk Road merchants and their camels.'),
  Word('travel', 'hammam', 'n.', 'A traditional Middle Eastern steam bath', 'After a long flight, the hammam scrubbed the city off my skin.'),
  Word('travel', 'banya', 'n.', 'A Russian steam bath with birch branches', 'In the banya old men laughed and slapped each other with veniks.'),
  Word('travel', 'onsen', 'n.', 'A Japanese hot spring bath', 'We soaked in an outdoor onsen while snow fell through the steam.'),
  Word('travel', 'sento', 'n.', 'A communal Japanese public bathhouse', 'The neighborhood sento closes at midnight and reopens at dawn.'),
  Word('travel', 'palanquin', 'n.', 'A covered chair carried by bearers', 'A photo on the wall showed the bride arriving in a flower-draped palanquin.'),
  Word('travel', 'rickshaw', 'n.', 'A small two-wheeled cab pulled or pedaled by a person', 'A rickshaw wove us through narrow lanes that no car could enter.'),
  Word('travel', 'tuktuk', 'n.', 'A three-wheeled motorized taxi in South Asia', 'The tuktuk driver took the long way but charged us a fair price.'),
  Word('travel', 'jeepney', 'n.', 'A flamboyantly painted Philippine shared van', 'A jeepney bound for Quiapo rattled past, every seat already full.'),
  Word('travel', 'dolmus', 'n.', 'A Turkish shared minibus that runs fixed routes', 'We jumped on a dolmus headed for the ferry terminal.'),
  Word('travel', 'matatu', 'n.', 'A Kenyan shared minibus, often loudly decorated', 'A matatu blasting Afrobeats pulled up to the curb.'),
  Word('travel', 'songthaew', 'n.', 'A Thai pickup truck with bench seats for passengers', 'We flagged a red songthaew bound for the night market.'),
  Word('travel', 'colectivo', 'n.', 'A Latin American shared taxi or minivan', 'The colectivo only leaves when every seat is full.'),
  Word('travel', 'shinkansen', 'n.', 'A Japanese high-speed bullet train', 'The shinkansen glides into the station without a sound.'),
  Word('travel', 'maglev', 'n.', 'A train levitated by magnets and moved electromagnetically', 'Shanghai\'s maglev reaches the airport in just over seven minutes.'),
  Word('travel', 'sleeper', 'n.', 'An overnight train car with beds', 'We booked a sleeper to save a hotel night and a long day of driving.'),
  Word('travel', 'couchette', 'n.', 'A simple shared bunk on a European night train', 'The couchette had four bunks, a tiny sink, and a window that opened.'),
  Word('travel', 'compartment', 'n.', 'A separated section of a train carriage', 'Our compartment held six strangers swapping snacks across the table.'),
  Word('travel', 'platform', 'n.', 'The raised area beside train tracks for boarding', 'Platform nine was packed with commuters and one confused tourist.'),
  Word('travel', 'turnstile', 'n.', 'A rotating gate at a station entrance', 'I tapped my card and pushed through the turnstile.'),
  Word('travel', 'mezzanine', 'n.', 'A partial intermediate level inside a building or station', 'The mezzanine had a bakery and a stand selling subway maps.'),
  Word('travel', 'overland', 'adv.', 'By road across long distances on land', 'They traveled overland from Istanbul to Singapore in six months.'),
  Word('travel', 'overlanding', 'n.', 'Self-reliant long-distance travel by vehicle', 'Overlanding through Patagonia means carrying spare fuel and patience.'),
  Word('travel', 'longhaul', 'adj.', 'Covering very long distances, especially by air', 'The longhaul to Sydney went smoother with melatonin and a fresh book.'),
  Word('travel', 'shorthaul', 'adj.', 'Covering relatively short distances by air', 'Shorthaul flights inside Europe rarely include a meal anymore.'),
  Word('travel', 'codeshare', 'n.', 'A shared flight number between two airlines', 'My ticket was a codeshare so I checked in with the operating carrier.'),
  Word('travel', 'tarpaulin', 'n.', 'A waterproof sheet used for shelter or covering', 'A tarpaulin kept the rain off our packs at the trailhead.'),
  Word('travel', 'duffel', 'n.', 'A long cylindrical bag for travel gear', 'A battered duffel held all the climbing gear we owned.'),
  Word('travel', 'rucksack', 'n.', 'A backpack, especially for hiking or travel', 'My rucksack weighed almost nothing once I cut the spare fuel canister.'),
  Word('travel', 'satchel', 'n.', 'A small bag with a long shoulder strap', 'I slung the satchel across my chest before walking through the bazaar.'),
  Word('travel', 'fannypack', 'n.', 'A small bag worn around the waist', 'A fannypack keeps your passport close in pickpocket-prone cities.'),
  Word('travel', 'packing cubes', 'n.', 'Fabric organizers that compress clothes in a bag', 'Packing cubes turned my chaos into three tidy stacks.'),
  Word('travel', 'organizer', 'n.', 'A pouch that keeps small items tidy in a bag', 'My organizer holds chargers, adapters, and a tiny first aid kit.'),
  Word('travel', 'adapter', 'n.', 'A plug converter for foreign outlets', 'I never travel without a universal adapter and two USB cables.'),
  Word('travel', 'converter', 'n.', 'A device that changes voltage between countries', 'A converter saved my hair dryer from frying on European current.'),
  Word('travel', 'powerbank', 'n.', 'A portable battery that recharges devices on the go', 'My powerbank lasted three flights without a wall outlet.'),
  Word('travel', 'esim', 'n.', 'A digital SIM activated by code instead of a chip', 'I bought an esim before landing and had data before the seatbelt sign turned off.'),
  Word('travel', 'roaming', 'n.', 'Using your phone\'s service in another country', 'Roaming used to be terrifying; now my plan covers ninety countries.'),
  Word('travel', 'wifi', 'n.', 'A wireless internet connection', 'The cafe wifi was fast enough to upload a whole video before lunch.'),
  Word('travel', 'hotspot', 'n.', 'A device or phone sharing its internet connection', 'My phone became a hotspot for the whole van after the campground wifi died.'),
  Word('travel', 'workation', 'n.', 'A trip that blends work and vacation', 'Our team did a month-long workation in a Lisbon coliving space.'),
  Word('travel', 'coliving', 'n.', 'A shared rented home for remote workers', 'Coliving in Bali came with yoga, fast internet, and free coffee.'),
  Word('travel', 'coworking', 'n.', 'A shared office space used by remote workers', 'I rented a coworking desk for three days to catch up on deep work.'),
  Word('travel', 'nomad', 'n.', 'A person who travels indefinitely, often working remotely', 'The cafe was packed with digital nomads on calls with three time zones.'),
  Word('travel', 'flashpacker', 'n.', 'A backpacker with a generous budget and good gear', 'He called himself a flashpacker because he paid for private rooms in hostels.'),
  Word('travel', 'voluntourism', 'n.', 'Travel combined with volunteer work', 'Voluntourism can do real good when the project is led by locals.'),
  Word('travel', 'agritourism', 'n.', 'Travel based on visits to working farms', 'Our agritourism stay let us help with the morning olive harvest.'),
  Word('travel', 'ecotourism', 'n.', 'Travel focused on conserving the natural environment', 'Real ecotourism means leaving the forest better than you found it.'),
  Word('travel', 'gastronomy', 'n.', 'The art and study of fine eating', 'Lyon\'s gastronomy alone is worth a long detour off any route.'),
  Word('travel', 'sommelier', 'n.', 'A wine expert who pairs and recommends wines', 'The sommelier suggested a chilled red I would never have picked.'),
  Word('travel', 'omakase', 'n.', 'A meal chosen entirely by the chef', 'We sat at the counter for an omakase that lasted three quiet hours.'),
  Word('travel', 'izakaya', 'n.', 'A casual Japanese pub serving small plates and drinks', 'A late-night izakaya by the river served grilled skewers and cold beer.'),
  Word('travel', 'taverna', 'n.', 'A small Greek restaurant serving traditional food', 'The taverna had blue tables right at the edge of the harbor.'),
  Word('travel', 'trattoria', 'n.', 'A casual Italian restaurant', 'A neighborhood trattoria served the best cacio e pepe of the trip.'),
  Word('travel', 'osteria', 'n.', 'A simple Italian eatery focused on wine and food', 'The osteria didn\'t have a menu — you ate what they cooked that day.'),
  Word('travel', 'brasserie', 'n.', 'A French restaurant serving hearty food all day', 'We ducked into a brasserie for steak frites at three in the afternoon.'),
  Word('travel', 'patisserie', 'n.', 'A shop selling French pastries and cakes', 'I left the patisserie with two croissants and zero regrets.'),
  Word('travel', 'boulangerie', 'n.', 'A French bakery specializing in bread', 'A boulangerie on every corner explains why Paris smells the way it does.'),
  Word('travel', 'cantina', 'n.', 'A casual Mexican or Italian eatery', 'The cantina filled up at lunch with construction workers and locals.'),
  Word('travel', 'feria', 'n.', 'A Spanish or Latin American open-air fair or festival', 'The feria filled the whole avenue with rides, music, and grilled corn.'),
  Word('travel', 'foodcourt', 'n.', 'A shared eating area surrounded by many vendors', 'The airport foodcourt was the only place I tasted local noodles before flying.'),
  Word('travel', 'streetfood', 'n.', 'Cheap food sold from stalls or carts on the street', 'We ate streetfood every night and never once got sick.'),
  Word('travel', 'hawker', 'n.', 'A vendor selling cheap food at a stall', 'A hawker poured chili crab onto our plate from a wok the size of a tire.'),
  Word('travel', 'sobremesa', 'n.', 'The lingering chat after a meal', 'Sobremesa stretched until midnight while the waiters folded napkins around us.'),
  Word('travel', 'aperitivo', 'n.', 'A pre-dinner drink served with small bites', 'Milan\'s aperitivo culture means dinner can cost the price of a cocktail.'),
  Word('travel', 'siesta', 'n.', 'An afternoon nap, especially in hot countries', 'Half the shops closed for siesta from two until five.'),
  Word('travel', 'hygge', 'n.', 'A Danish feeling of cozy contentment', 'A fire, a blanket, and a hot drink — pure hygge after a snowy hike.'),
  Word('travel', 'fika', 'n.', 'A Swedish coffee break with pastries', 'Our hosts insisted on fika at three in the afternoon every day.'),
  Word('travel', 'lagom', 'n.', 'A Swedish ideal of just-right balance', 'The minimalist guesthouse felt like lagom in physical form.'),
  Word('travel', 'wabisabi', 'n.', 'A Japanese aesthetic embracing imperfection and age', 'The cracked teapot was held in place with gold in true wabisabi fashion.'),
  Word('travel', 'shinrinyoku', 'n.', 'Japanese forest bathing to ease the mind', 'A guided shinrinyoku walk through cedars left us calmer than any spa.'),
  Word('travel', 'dolcefarniente', 'n.', 'The Italian pleasure of doing nothing', 'After a week of dolcefarniente on the Amalfi coast, my inbox felt very far away.'),
  Word('travel', 'passegiata', 'n.', 'A leisurely Italian evening stroll', 'The whole town came out for the passegiata at sunset.'),
  Word('travel', 'paseo', 'n.', 'A Spanish evening walk through public spaces', 'Families joined the paseo around the plaza once the heat broke.'),
  Word('travel', 'firsthand', 'adv.', 'From direct personal experience', 'We learned firsthand that the bus does not always leave on time.'),
  Word('travel', 'offthebeatenpath', 'adj.', 'Away from common tourist routes', 'Her favorite stops were always offthebeatenpath villages with no Wi-Fi.'),
  Word('travel', 'destination', 'n.', 'A place you intend to travel to', 'My next destination was a tiny island reachable only by ferry.'),
  Word('travel', 'sojourner', 'n.', 'A traveler making a temporary stay', 'A sojourner from Iceland shared the table next to ours.'),
  Word('travel', 'wayfarer', 'n.', 'A person who travels, especially on foot', 'The medieval wayfarer relied on monasteries for a night\'s rest.'),
  Word('travel', 'pathfinder', 'n.', 'A scout who finds new routes', 'Local pathfinders led us up a ridge no map showed.'),
  Word('travel', 'voyager', 'n.', 'A long-distance traveler, often by sea or space', 'The old voyager had ferry stickers from every Greek island.'),
  Word('travel', 'mariner', 'n.', 'A sailor or person who works at sea', 'A retired mariner taught us to read the harbor flags.'),
  Word('travel', 'pilot', 'n.', 'A person who flies aircraft or guides ships', 'The pilot warned us of a bumpy descent through coastal fog.'),
  Word('travel', 'copilot', 'n.', 'A second pilot who shares flight duties', 'The copilot handled the radio while the captain landed in crosswinds.'),
  Word('travel', 'navigator', 'n.', 'Someone who plots a course on a journey', 'Without a real navigator we got lost twice before lunch.'),
  Word('travel', 'cabincrew', 'n.', 'The flight attendants serving a flight', 'The cabincrew dimmed the lights as we crossed the dateline.'),
  Word('travel', 'flightdeck', 'n.', 'The cockpit area of an aircraft', 'A kid in a captain\'s hat got a peek of the flightdeck after landing.'),
  Word('travel', 'galley', 'n.', 'A small kitchen on a plane, ship, or train', 'The galley smelled like coffee and warm rolls.'),
  Word('travel', 'aisle', 'n.', 'The walkway between rows of seats', 'I always book the aisle so I can stretch on long flights.'),
  Word('travel', 'bulkhead', 'n.', 'A dividing wall on a plane or ship', 'Bulkhead seats have extra legroom but no under-seat storage.'),
  Word('travel', 'overhead', 'n.', 'The storage bin above plane seats', 'There was no room left in the overhead so my bag rode in business class.'),
  Word('travel', 'recline', 'v.', 'To tilt a seat backward for comfort', 'I never recline on short flights out of mercy for the row behind me.'),
  Word('travel', 'turbulence', 'n.', 'Bumpy air movement during a flight', 'A patch of turbulence sent the drinks cart hurrying back to the galley.'),
  Word('travel', 'taxiing', 'n.', 'A plane moving slowly on the ground', 'We spent half an hour taxiing before takeoff.'),
  Word('travel', 'deplane', 'v.', 'To get off an aircraft after landing', 'It took twenty minutes to deplane through a single jet bridge.'),
  Word('travel', 'gateagent', 'n.', 'An airline employee working at the boarding gate', 'The gateagent paged me by name when my seat got upgraded.'),
  Word('travel', 'standby', 'n.', 'A spot on a flight given out only if seats remain', 'I flew standby and somehow ended up in first class.'),
  Word('travel', 'bumped', 'adj.', 'Removed from an overbooked flight', 'We got bumped to the next morning and the airline paid for the hotel.'),
  Word('travel', 'overbooked', 'adj.', 'Sold more seats than the aircraft has', 'The flight was overbooked so they offered vouchers for volunteers.'),
  Word('travel', 'rebook', 'v.', 'To arrange a new ticket after a change', 'The agent rebooked us through Tokyo at no extra cost.'),
  Word('travel', 'reroute', 'v.', 'To send a traveler along a different path', 'A storm rerouted the whole flight north over Iceland.'),
  Word('travel', 'tailwind', 'n.', 'A wind from behind that speeds a flight', 'A strong tailwind shaved forty minutes off the eastbound flight.'),
  Word('travel', 'headwind', 'n.', 'A wind against your direction of travel', 'Headwinds made the westbound flight feel like an extra movie long.'),
  Word('travel', 'jetstream', 'n.', 'A fast high-altitude air current', 'The jetstream pushed us along like a moving sidewalk in the sky.'),
  Word('travel', 'altitude', 'n.', 'Height above sea level, especially in flight', 'At cruise altitude the cabin air gets bone dry.'),
  Word('travel', 'cruising', 'adj.', 'Travelling at a steady comfortable speed', 'We hit cruising altitude and the seatbelt sign blinked off.'),
  Word('travel', 'lavatory', 'n.', 'A small toilet on a plane or train', 'There was a queue for the lavatory the whole second half of the flight.'),
  Word('travel', 'pressurization', 'n.', 'Keeping cabin air at a survivable pressure', 'Cabin pressurization is why your bag of chips puffs up in flight.'),
  Word('travel', 'tarmacdelay', 'n.', 'A wait on the runway after pushback', 'A two-hour tarmacdelay cost us the connection in Frankfurt.'),
  Word('travel', 'interline', 'n.', 'An agreement letting airlines share baggage and tickets', 'An interline agreement got my checked bag onto a second carrier automatically.'),
  Word('travel', 'transfer', 'n.', 'A switch from one transport to another', 'The transfer between bus and ferry took us right through the old town.'),
  Word('travel', 'shuttle', 'n.', 'A short transport service between two points', 'A shuttle ran every fifteen minutes from the hotel to the convention center.'),
  Word('travel', 'limo', 'n.', 'A long luxury car often booked for transfers', 'A limo waited at arrivals with a sign spelling my name slightly wrong.'),
  Word('travel', 'rideshare', 'n.', 'A ride booked through an app', 'A rideshare from the airport cost less than the train.'),
  Word('travel', 'hailcab', 'v.', 'To wave down a taxi on the street', 'In New York you can still hailcab the old-fashioned way.'),
  Word('travel', 'roundtrip', 'n.', 'A journey to a destination and back', 'A roundtrip ticket can be cheaper than two one-ways.'),
  Word('travel', 'oneway', 'adj.', 'For a single direction only', 'I bought a oneway ticket and decided the return later.'),
  Word('travel', 'multicity', 'adj.', 'Covering more than two stops on one booking', 'A multicity itinerary let us stop in Reykjavik on the way home.'),
  Word('travel', 'openjaw', 'n.', 'A trip flying into one city and out of another', 'An openjaw into Rome and out of Athens saved us a long backtrack.'),
  Word('travel', 'frequentflyer', 'n.', 'A loyalty program for regular air passengers', 'My frequentflyer miles finally got me a free trip to Tokyo.'),
  Word('travel', 'milesrun', 'n.', 'A trip taken mostly to earn loyalty miles', 'He did a weekend milesrun to keep his elite status another year.'),
  Word('travel', 'redeyeflight', 'n.', 'An overnight flight that lands at dawn', 'A redeyeflight saved a hotel night but cost me a productive morning.'),
  Word('travel', 'hopper', 'n.', 'A short flight, often between nearby islands', 'A six-seater hopper carried us between two Caribbean islands.'),
  Word('travel', 'puddlejumper', 'n.', 'A small plane on short regional routes', 'The puddlejumper bounced through clouds the whole way to the lake.'),
  Word('travel', 'seaplane', 'n.', 'An aircraft that takes off and lands on water', 'A seaplane dropped us at a dock just feet from our beach hut.'),
  Word('travel', 'ferryboat', 'n.', 'A boat that carries passengers and cars across water', 'The ferryboat to the island ran twice a day in summer.'),
  Word('travel', 'catamaran', 'n.', 'A boat with two parallel hulls', 'Our catamaran sliced across the bay without rolling.'),
  Word('travel', 'dhow', 'n.', 'A traditional Arab sailing vessel', 'A dhow with red sails carried us up the Tanzanian coast.'),
  Word('travel', 'junk', 'n.', 'A traditional Chinese sailing ship', 'A wooden junk eased through Halong Bay\'s limestone karsts.'),
  Word('travel', 'sampan', 'n.', 'A small flat-bottomed Asian boat', 'A sampan ferried us across the Mekong before the bridge was built.'),
  Word('travel', 'longtail', 'n.', 'A Thai boat with an exposed propeller on a long shaft', 'The longtail roared us between limestone islands at sunrise.'),
  Word('travel', 'pirogue', 'n.', 'A small canoe-like boat, often hollowed from a log', 'A pirogue glided us through mangrove channels at low tide.'),
  Word('travel', 'kayak', 'n.', 'A narrow paddled boat for one or two people', 'We rented a kayak and paddled out to the kelp beds.'),
  Word('travel', 'paddleboard', 'n.', 'A long board you stand and paddle on', 'A paddleboard tour at dawn was the calmest hour of the whole trip.'),
  Word('travel', 'yacht', 'n.', 'A luxury private boat used for cruising', 'A yacht charter for a week split four ways is surprisingly doable.'),
  Word('travel', 'liveaboard', 'n.', 'A boat trip where you sleep onboard', 'A diving liveaboard in the Red Sea meant five wrecks in three days.'),
  Word('travel', 'portcity', 'n.', 'A city built around a working harbor', 'Every portcity has a fish market worth waking up early for.'),
  Word('travel', 'harbor', 'n.', 'A sheltered body of water for boats', 'The harbor was full of fishing boats and one massive cruise ship.'),
  Word('travel', 'marina', 'n.', 'A docking area for pleasure boats', 'The marina restaurant served the best grilled octopus of the trip.'),
  Word('travel', 'wharf', 'n.', 'A platform where ships unload', 'We bought oysters straight off a boat at the wharf.'),
  Word('travel', 'jetty', 'n.', 'A structure jutting into water for boats', 'A wooden jetty stretched into the lagoon for a hundred meters.'),
  Word('travel', 'pier', 'n.', 'A platform built over water for boarding boats or strolling', 'The pier had a tea stand at the far end and a queue for the ferry.'),
  Word('travel', 'breakwater', 'n.', 'A barrier that protects a harbor from waves', 'We walked along the breakwater past anchored fishing boats.'),
  Word('travel', 'quay', 'n.', 'A landing place built along the water\'s edge', 'Cargo crates were stacked along the quay waiting for the morning tide.'),
  Word('travel', 'cornice', 'n.', 'A seaside road carved into cliffs', 'The Amalfi cornice has hairpins that test even brave passengers.'),
  Word('travel', 'switchback', 'n.', 'A sharp zigzag turn on a mountain road', 'A switchback every two hundred meters made our brakes squeal.'),
  Word('travel', 'hairpin', 'n.', 'A very tight bend in a road, like a U-shape', 'The hairpin came up faster than expected on a damp morning.'),
  Word('travel', 'autostrada', 'n.', 'An Italian high-speed motorway', 'We took the autostrada south and watched the temperature climb.'),
  Word('travel', 'autobahn', 'n.', 'A German motorway, parts with no speed limit', 'The autobahn lets you stretch a fast car\'s legs legally.'),
  Word('travel', 'turnpike', 'n.', 'A toll highway, especially in the US', 'The turnpike rest stops are a road-trip food group of their own.'),
  Word('travel', 'freeway', 'n.', 'A controlled-access highway, often free of tolls', 'We got on the freeway and didn\'t stop for three hundred miles.'),
  Word('travel', 'expressway', 'n.', 'A fast urban highway with limited access', 'The expressway cuts driving time across the city by half.'),
  Word('travel', 'beltway', 'n.', 'A ring road circling a city', 'The beltway was crawling at five, so we cut through downtown instead.'),
  Word('travel', 'roundabout', 'n.', 'A circular intersection where traffic flows one way', 'A confused roundabout in Swindon took three loops to figure out.'),
  Word('travel', 'roadtrip', 'n.', 'A long leisure journey by car', 'A roadtrip up the California coast is a rite of passage.'),
  Word('travel', 'mileage', 'n.', 'The distance covered, often counted in a vehicle', 'The rental came with unlimited mileage which saved us on a long route.'),
  Word('travel', 'odometer', 'n.', 'The instrument measuring distance traveled', 'I took a photo of the odometer at the start of the trip.'),
  Word('travel', 'detour', 'n.', 'An alternative route, often forced by closures', 'A detour took us through a town we never would have seen.'),
  Word('travel', 'pullover', 'n.', 'A roadside stop, often by police', 'A polite pullover for a tail-light cost us five minutes and a warning.'),
  Word('travel', 'restarea', 'n.', 'A roadside place to stop on a highway', 'The restarea had a playground, vending machines, and surprisingly clean toilets.'),
  Word('travel', 'lookout', 'n.', 'A viewpoint along a road or trail', 'The lookout over the canyon was worth pulling over twice.'),
  Word('travel', 'vista', 'n.', 'A wide pleasing view', 'A vista of terraced rice fields opened up at the next bend.'),
  Word('travel', 'panorama', 'n.', 'An unbroken view of a wide area', 'The rooftop bar offered a panorama of the whole skyline.'),
  Word('travel', 'overlook', 'n.', 'A viewing platform on high ground', 'An overlook lets you see the river bend for miles.'),
  Word('travel', 'belvedere', 'n.', 'A structure designed to enjoy a view', 'A small belvedere on the hill offered the postcard shot of the village.'),
  Word('travel', 'skyline', 'n.', 'The outline of buildings against the sky', 'The Hong Kong skyline still drops jaws at dusk.'),
  Word('travel', 'cityscape', 'n.', 'A view of a city, especially as a scene', 'A cityscape mural decorated the bus station waiting room.'),
  Word('travel', 'landscape', 'n.', 'The features of an area of land', 'The Icelandic landscape switches from mossy lava to glaciers in an hour.'),
  Word('travel', 'seascape', 'n.', 'A view of the sea', 'A wall of windows turned the dining room into a moving seascape.'),
  Word('travel', 'streetscape', 'n.', 'The character and look of a street', 'Vienna\'s streetscape feels like wandering through a giant museum.'),
  Word('travel', 'oldtown', 'n.', 'The historic district of a city', 'The oldtown was traffic-free and lit by lanterns at night.'),
  Word('travel', 'medina', 'n.', 'The old walled quarter of a North African city', 'Inside the medina, every alley smelled of mint, leather, or saffron.'),
  Word('travel', 'kasbah', 'n.', 'A walled citadel inside a North African town', 'We climbed to the kasbah for a view over the desert palms.'),
  Word('travel', 'casbah', 'n.', 'An old citadel quarter in a North African city', 'The casbah\'s tiled fountains and narrow steps felt unchanged in centuries.'),
  Word('travel', 'citadel', 'n.', 'A fortified part of a city, usually on high ground', 'The citadel commands every approach to the valley below.'),
  Word('travel', 'rampart', 'n.', 'A defensive wall around a town or castle', 'We walked the rampart all the way around the medieval town.'),
  Word('travel', 'parapet', 'n.', 'A low protective wall along an edge', 'The parapet on the castle roof was just tall enough to lean against.'),
  Word('travel', 'turret', 'n.', 'A small tower on a castle or building', 'A spiral stair climbed inside the turret to a single round room.'),
  Word('travel', 'belltower', 'n.', 'A tower holding bells, often in a church', 'The belltower rang at six and started every pigeon in the square.'),
  Word('travel', 'minaret', 'n.', 'A tall slender tower on a mosque', 'A minaret called the city to dawn prayer before the sun appeared.'),
  Word('travel', 'pagoda', 'n.', 'A tiered tower used in East Asian temples', 'A five-story pagoda glowed gold against the autumn leaves.'),
  Word('travel', 'stupa', 'n.', 'A mound-shaped Buddhist monument', 'Pilgrims walked clockwise around the stupa, fingertips brushing the stone.'),
  Word('travel', 'ziggurat', 'n.', 'A terraced ancient Mesopotamian temple tower', 'The ziggurat rose in three steps out of the desert plain.'),
  Word('travel', 'obelisk', 'n.', 'A tall four-sided stone pillar', 'An Egyptian obelisk stood in the middle of the Roman square.'),
  Word('travel', 'plinth', 'n.', 'A heavy base supporting a statue or column', 'A bronze general balanced on a plinth of mossy granite.'),
  Word('travel', 'colonnade', 'n.', 'A row of evenly spaced columns', 'A long colonnade kept the market in cool shade all day.'),
  Word('travel', 'arcade', 'n.', 'A covered walk lined with shops or arches', 'The arcade behind the cathedral hid the city\'s best bookshops.'),
  Word('travel', 'cloister', 'n.', 'A covered walkway around a monastery courtyard', 'Monks paced the cloister in silence between bells.'),
  Word('travel', 'basilica', 'n.', 'A large important church', 'The basilica\'s mosaics shimmered the moment sunlight hit the dome.'),
  Word('travel', 'chapel', 'n.', 'A small place of worship', 'A cliffside chapel offered the best photo on the entire coast road.'),
  Word('travel', 'monastery', 'n.', 'A religious community building for monks', 'The monastery still brews beer to fund its renovations.'),
  Word('travel', 'convent', 'n.', 'A community for nuns', 'A converted convent became one of our quietest hotels.'),
  Word('travel', 'gurdwara', 'n.', 'A Sikh place of worship', 'The gurdwara fed every visitor lunch in its open kitchen.'),
  Word('travel', 'synagogue', 'n.', 'A Jewish place of worship', 'The old synagogue in Prague is a moving museum to a lost community.'),
  Word('travel', 'wat', 'n.', 'A Thai Buddhist temple compound', 'A morning visit to a quiet wat is the best counter to a loud market.'),
  Word('travel', 'pueblo', 'n.', 'A traditional Native American village of adobe homes', 'A pueblo in New Mexico has been continuously inhabited for a thousand years.'),
  Word('travel', 'adobe', 'n.', 'A building material of sun-dried earth', 'The walls were adobe two feet thick that kept the rooms cool.'),
  Word('travel', 'wattle', 'n.', 'A traditional building method of woven sticks and mud', 'A wattle and daub barn has stood here since the 1600s.'),
  Word('travel', 'thatch', 'n.', 'Plant material used for traditional roofing', 'The thatch roof needed replacing every fifteen years.'),
  Word('travel', 'longhouse', 'n.', 'A long communal traditional dwelling', 'A Borneo longhouse can shelter dozens of families under one roof.'),
  Word('travel', 'yurt', 'n.', 'A round portable tent used by Central Asian nomads', 'Our yurt had a wood stove and a skylight open to the stars.'),
  Word('travel', 'ger', 'n.', 'The Mongolian name for a round felt tent', 'A ger camp in the steppe was lit by paraffin lamps and laughter.'),
  Word('travel', 'tepee', 'n.', 'A conical tent of poles and skins', 'A tepee experience taught us how clever a single fire can be.'),
  Word('travel', 'hut', 'n.', 'A small simple shelter', 'The mountain hut had bunks for twelve and a stew pot on the stove.'),
  Word('travel', 'cabin', 'n.', 'A small simple wood house, often for getaways', 'A lakeside cabin in October was all the vacation I needed.'),
  Word('travel', 'cottage', 'n.', 'A small charming house, often in the countryside', 'Our cottage came with a creaky rocking chair and a stack of jigsaw puzzles.'),
  Word('travel', 'bungalow', 'n.', 'A small single-story house', 'A bungalow on stilts opened onto the turquoise lagoon.'),
  Word('travel', 'villa', 'n.', 'A large luxurious country or seaside home', 'We split a villa with friends and ate every meal on the terrace.'),
  Word('travel', 'manor', 'n.', 'A large country house, often historic', 'The manor had its own walled garden and a hedge maze.'),
  Word('travel', 'estate', 'n.', 'A large piece of land with a main house', 'A wine estate in Mendoza had cellars deep under the vines.'),
  Word('travel', 'chateau', 'n.', 'A large French country house or castle', 'A chateau in the Loire let us tour vineyards by bicycle.'),
  Word('travel', 'palazzo', 'n.', 'A large Italian historic mansion', 'A faded palazzo had been carefully restored into a hotel.'),
  Word('travel', 'finca', 'n.', 'A Spanish or Latin American country estate or farm', 'The finca produced its own olive oil and dried tomatoes.'),
  Word('travel', 'dacha', 'n.', 'A Russian country house, often used in summer', 'Friends invited us out to their dacha for pickles and steam baths.'),
  Word('travel', 'guesthouse', 'n.', 'A small lodging run by locals, simpler than a hotel', 'Our guesthouse owner walked us to the bakery on our first morning.'),
  Word('travel', 'homestay', 'n.', 'A stay in a local family\'s home', 'A homestay taught us how to make momos and how to drink butter tea.'),
  Word('travel', 'bedandbreakfast', 'n.', 'A small lodging that includes morning meal', 'The bedandbreakfast served homemade jam and warm scones every day.'),
  Word('travel', 'motel', 'n.', 'A motorist hotel with rooms off a parking lot', 'A roadside motel had neon signs older than the highway.'),
  Word('travel', 'capsulehotel', 'n.', 'A Japanese hotel of small sleeping pods', 'A capsulehotel in Tokyo is half hostel, half spaceship.'),
  Word('travel', 'pod', 'n.', 'A small enclosed sleeping space, often at airports', 'I rented a pod in Singapore Changi for the eleven-hour layover.'),
  Word('travel', 'hostal', 'n.', 'A small Spanish-style budget hotel', 'Our hostal had a tiled patio and rooms above a busy cafe.'),
  Word('travel', 'safarilodge', 'n.', 'A lodge from which guests go on safaris', 'The safarilodge had a watering hole visible from the dining room.'),
  Word('travel', 'glampsite', 'n.', 'A campsite with hotel-like comfort', 'Our glampsite had a tent with a wood floor and a real shower.'),
  Word('travel', 'campsite', 'n.', 'A place to pitch tents or park RVs', 'The campsite filled up by afternoon every summer weekend.'),
  Word('travel', 'campground', 'n.', 'A managed area with multiple campsites', 'The campground had hot showers and a kiosk selling firewood.'),
  Word('travel', 'firepit', 'n.', 'A pit or ring for an outdoor fire', 'We told stories around the firepit until the sparks gave out.'),
  Word('travel', 'tentpole', 'n.', 'A pole that holds a tent upright', 'A broken tentpole almost ended our first backpacking trip.'),
  Word('travel', 'sleepingbag', 'n.', 'An insulated bag for sleeping outdoors', 'My sleepingbag is rated for ten below and weighs almost nothing.'),
  Word('travel', 'sleepingpad', 'n.', 'A cushion that insulates you from the ground', 'A good sleepingpad makes the difference between a nap and a night.'),
  Word('travel', 'hammock', 'n.', 'A swinging fabric bed strung between two points', 'A hammock under two palm trees was my whole afternoon plan.'),
  Word('travel', 'thermos', 'n.', 'A vacuum flask that keeps liquids hot or cold', 'A thermos of tea on the train was the best decision of the trip.'),
  Word('travel', 'canteen', 'n.', 'A bottle for carrying water on the go', 'A metal canteen on the saddle clanked over every cobblestone.'),
  Word('travel', 'hydrationpack', 'n.', 'A backpack with a built-in water bladder', 'A hydrationpack lets you sip without unclipping the bag.'),
  Word('travel', 'headlamp', 'n.', 'A light worn on the forehead for hands-free use', 'A red headlamp let me find the trail without ruining my night vision.'),
  Word('travel', 'multitool', 'n.', 'A folding device combining many small tools', 'A multitool fixed the loose tent strap in under a minute.'),
  Word('travel', 'compass', 'n.', 'A magnetic device pointing to north', 'I still carry a compass even when the GPS is working perfectly.'),
  Word('travel', 'topomap', 'n.', 'A map that shows elevation with contour lines', 'A waterproof topomap helped us pick the gentler ridge route.'),
  Word('travel', 'waypoint', 'n.', 'A marked point along a navigation route', 'I saved a waypoint at the junction in case we backtracked in fog.'),
  Word('travel', 'bearing', 'n.', 'A direction expressed as an angle from north', 'A bearing of one-twenty east kept us pointed at the saddle.'),
  Word('travel', 'cairn', 'n.', 'A pile of stones marking a trail or summit', 'A small cairn confirmed we were still on route.'),
  Word('travel', 'blaze', 'n.', 'A paint mark on a tree showing a trail', 'A blue blaze led off the main trail toward the spring.'),
  Word('travel', 'trailhead', 'n.', 'The starting point of a trail', 'The trailhead had a logbook and a single toilet stall.'),
  Word('travel', 'switchbacks', 'n.', 'A series of zigzag turns climbing a slope', 'The switchbacks dragged on, but each one cooled my legs.'),
  Word('travel', 'scramble', 'v.', 'To climb a steep slope using both hands and feet', 'We had to scramble the last fifty meters to the summit.'),
  Word('travel', 'bushwhack', 'v.', 'To make your way through dense vegetation without a trail', 'We bushwhacked thirty minutes to a hidden waterfall.'),
  Word('travel', 'portage', 'n.', 'Carrying a boat between waterways', 'A short portage took us into a chain of quiet lakes.'),
  Word('travel', 'thru-hike', 'n.', 'Completing a long trail end to end', 'Her Pacific Crest thru-hike took five months and three pairs of shoes.'),
  Word('travel', 'dayhike', 'n.', 'A walk completed in a single day', 'A four-hour dayhike got us to the alpine lake and back by lunch.'),
  Word('travel', 'summit', 'n.', 'The top of a mountain', 'We hit the summit just as the clouds parted for ten clean minutes.'),
  Word('travel', 'col', 'n.', 'A low point between two mountains', 'The col was windy but offered a stunning view of the valley.'),
  Word('travel', 'ridgewalk', 'n.', 'A walk along the high spine of mountains', 'The ridgewalk gave us six summits in a single long day.'),
  Word('travel', 'glissade', 'v.', 'To slide down a snowy slope on your feet or seat', 'We glissaded down the snowfield, ice axes ready as brakes.'),
  Word('travel', 'belay', 'v.', 'To secure a climber with a rope', 'I belayed her up the cliff one careful arm length at a time.'),
  Word('travel', 'rappel', 'v.', 'To descend a cliff on a rope', 'We rappelled forty meters into the canyon to reach the river.'),
  Word('travel', 'crampons', 'n.', 'Spiked metal frames worn on boots for ice', 'We strapped on crampons before crossing the glacier tongue.'),
  Word('travel', 'piton', 'n.', 'A metal spike hammered into rock for climbing', 'An old piton stuck out of the wall, rusty but reassuring.'),
  Word('travel', 'snowpack', 'n.', 'The total accumulated snow on the ground', 'A heavy snowpack made the springtime rivers run brown and fast.'),
  Word('travel', 'avalanche', 'n.', 'A sudden mass of snow sliding down a slope', 'An avalanche advisory kept us off the steep north faces.'),
  Word('travel', 'avalanchebeacon', 'n.', 'A device that helps locate buried skiers', 'Every backcountry skier wore an avalanchebeacon and knew how to use it.'),
  Word('travel', 'pisteguide', 'n.', 'A booklet describing groomed ski runs', 'A pisteguide listed every lift and run on a single fold-out map.'),
  Word('travel', 'apresski', 'n.', 'Socializing after a day of skiing', 'Apresski meant mulled wine and a fire we never wanted to leave.'),
  Word('travel', 'gondolacar', 'n.', 'An enclosed cabin on a cableway', 'A gondolacar lifted us above the clouds in nine minutes.'),
  Word('travel', 'chairlift', 'n.', 'A ski lift of suspended open chairs', 'The chairlift swayed once as a gust caught us above the trees.'),
  Word('travel', 'cablecar', 'n.', 'A vehicle pulled along cables, often on slopes', 'San Francisco\'s cablecar climbs hills steep enough to walk on tiptoe.'),
  Word('travel', 'aerialtram', 'n.', 'A passenger cabin suspended on cables', 'An aerialtram in Portland carried commuters above the city in minutes.'),
  Word('travel', 'highspeedrail', 'n.', 'A train system designed for very high speeds', 'Spain\'s highspeedrail makes Madrid to Seville feel like a quick errand.'),
  Word('travel', 'monorail', 'n.', 'A train running on a single elevated rail', 'A monorail loops around the theme park every six minutes.'),
  Word('travel', 'lightrail', 'n.', 'A modern electric urban rail system', 'The lightrail extension finally connected the airport to downtown.'),
  Word('travel', 'subway', 'n.', 'An underground urban train system', 'The subway map looked like a noodle bowl until I bought a transit card.'),
  Word('travel', 'tube', 'n.', 'A British term for the London underground rail system', 'On the tube nobody talks and everyone reads.'),
  Word('travel', 'tramcar', 'n.', 'A street-running rail vehicle', 'A clanging tramcar squeezed past with centimeters to spare.'),
  Word('travel', 'trolley', 'n.', 'An electrically powered street rail vehicle', 'A trolley up Powell Street gave us the view I had only seen in postcards.'),
  Word('travel', 'doubledecker', 'n.', 'A bus or vehicle with two passenger levels', 'A doubledecker tour bus made for a cheap city overview on day one.'),
  Word('travel', 'coachbus', 'n.', 'A long-distance touring bus', 'A coachbus from London to Edinburgh was cheaper than the train.'),
  Word('travel', 'sleeperbus', 'n.', 'A long-distance bus with beds', 'The sleeperbus to Hanoi had three rows of bunks and zero legroom.'),
  Word('travel', 'minivan', 'n.', 'A small van used for groups or shared rides', 'A minivan shuttle dropped each guest at a different homestay.'),
  Word('travel', 'rentalcar', 'n.', 'A car hired for short use', 'A rentalcar was the only sensible way to see the volcano roads.'),
  Word('travel', 'campervan', 'n.', 'A van fitted out for sleeping and traveling', 'We slept in a campervan for two weeks along the Scottish coast.'),
  Word('travel', 'rv', 'n.', 'A motor home for traveling with living space', 'An rv park near the canyon had hot showers and a stargazing field.'),
  Word('travel', 'motorhome', 'n.', 'A vehicle designed as a mobile home', 'The motorhome had a tiny kitchen, a shower, and a fold-down bed.'),
  Word('travel', 'cyclepath', 'n.', 'A path reserved for bicycles', 'A cyclepath ran the entire length of the river through three towns.'),
  Word('travel', 'pannier', 'n.', 'A bag mounted on a bicycle for cargo', 'Each pannier held a few days of clothes and a small camp stove.'),
  Word('travel', 'bikepacking', 'n.', 'Travel by bicycle carrying lightweight gear', 'Bikepacking through Patagonia meant tents, tortillas, and ten thousand miles of wind.'),
  Word('travel', 'tandem', 'n.', 'A bicycle for two riders one behind the other', 'A tandem along the canal was hilarious until we tried to turn around.'),
  Word('travel', 'ebike', 'n.', 'A bicycle assisted by an electric motor', 'An ebike turned the alpine climb into a pleasure rather than a punishment.'),
  Word('travel', 'scooter', 'n.', 'A small two-wheeled motor vehicle', 'A scooter is the local way to get around a Mediterranean island.'),
  Word('travel', 'helmet', 'n.', 'Protective headgear for riders or climbers', 'A helmet is non-negotiable even for a five-minute ride.'),
  Word('travel', 'guardrail', 'n.', 'A safety barrier along a road', 'The guardrail was scratched by years of nervous drivers.'),
  Word('travel', 'tollbooth', 'n.', 'A station where drivers pay road tolls', 'We dug for coins at every tollbooth on the Italian coast.'),
  Word('travel', 'fuelpump', 'n.', 'A pump for putting petrol or diesel in vehicles', 'A self-serve fuelpump on a quiet rural road took only cash.'),
  Word('travel', 'petrolstation', 'n.', 'A roadside place selling vehicle fuel', 'The petrolstation also sold sandwiches and very strong coffee.'),
  Word('travel', 'icebox', 'n.', 'A small insulated cooler for keeping things cold', 'An icebox in the trunk made road snacks feel like a picnic.'),
  Word('travel', 'snackpack', 'n.', 'A small bag of food for the road', 'A snackpack of nuts and fruit kept us going to the next town.'),
  Word('travel', 'trailmix', 'n.', 'A mix of nuts and dried fruit for the trail', 'A handful of trailmix at every hour kept the energy steady.'),
  Word('travel', 'pemmican', 'n.', 'A traditional dried meat and fat trail food', 'Pemmican kept Arctic explorers alive on impossible journeys.'),
  Word('travel', 'rationpack', 'n.', 'A small parcel of food made for travel', 'A rationpack from a war surplus shop became our trail joke.'),
  Word('travel', 'mre', 'n.', 'A military meal that needs no refrigeration', 'An mre in the bottom of the pack felt like serious overkill on a weekend.'),
  Word('travel', 'campstove', 'n.', 'A small portable stove for outdoor cooking', 'A campstove boiled coffee in three minutes at the tarn.'),
  Word('travel', 'fuelcanister', 'n.', 'A pressurized container of gas for camp stoves', 'A spare fuelcanister adds peace of mind on multi-day trips.'),
  Word('travel', 'tinder', 'n.', 'Easily-burnt material to start a fire', 'Dry tinder is worth its weight in gold on a rainy night.'),
  Word('travel', 'kindling', 'n.', 'Small dry sticks that catch fire easily', 'A bundle of kindling sold for two dollars at the campground office.'),
  Word('travel', 'snowshoe', 'n.', 'A flat frame worn on boots to walk on snow', 'A snowshoe walk through quiet woods is a meditation in motion.'),
  Word('travel', 'gaiters', 'n.', 'Coverings worn over boots to keep snow or grit out', 'Gaiters saved my socks from a hundred miles of trail dust.'),
  Word('travel', 'snorkel', 'n.', 'A tube that lets you breathe while face-down in water', 'A snorkel and a curious turtle made for the trip\'s best afternoon.'),
  Word('travel', 'fins', 'n.', 'Flippers worn to help you swim underwater', 'A pair of fins doubled how far I could comfortably swim.'),
  Word('travel', 'rashguard', 'n.', 'A light shirt that protects skin in the water', 'A rashguard saved me from the worst beach sunburn of my life.'),
  Word('travel', 'wetsuit', 'n.', 'A neoprene suit worn for warmth in cold water', 'A wetsuit kept me in the water long after my fingers should have surrendered.'),
  Word('travel', 'drybag', 'n.', 'A waterproof bag for keeping gear dry', 'A drybag carried our phones safely through a soggy kayak day.'),
  Word('travel', 'travelinsurance', 'n.', 'Insurance covering trip mishaps and medical costs', 'Travelinsurance once paid me back for a missed cruise after a snowstorm.'),
  Word('travel', 'medevac', 'n.', 'Emergency medical evacuation, often by air', 'A medevac out of the trail cost more than the rest of the trip combined.'),
  Word('travel', 'vaccination', 'n.', 'A medical shot that protects against disease', 'A yellow fever vaccination was required before we could enter the country.'),
  Word('travel', 'malaria', 'n.', 'A tropical disease spread by mosquitos', 'Malaria pills started the week before the trip and continued after.'),
  Word('travel', 'altitudesickness', 'n.', 'Illness from going up too high too fast', 'Altitudesickness hit one of us hard on the second night at base camp.'),
  Word('travel', 'jetlagged', 'adj.', 'Tired and out of sync after long-distance flight', 'A jetlagged morning is best fixed with sunlight and a long walk.'),
  Word('travel', 'circadian', 'adj.', 'Tied to the body\'s 24-hour internal clock', 'Bright morning light is the fastest way to reset a circadian rhythm.'),
  Word('travel', 'timezone', 'n.', 'A geographical region with the same standard time', 'Crossing three timezones in a day always wrecks my appetite.'),
  Word('travel', 'meridian', 'n.', 'A line of longitude on the globe', 'The prime meridian cuts straight through the Greenwich observatory.'),
  Word('travel', 'equator', 'n.', 'The imaginary line around the middle of the earth', 'A tourist trap on the equator showed water spinning two ways for tips.'),
  Word('travel', 'tropics', 'n.', 'The hot region near the equator', 'In the tropics the rain arrives like a metronome each afternoon.'),
  Word('travel', 'subtropical', 'adj.', 'Of regions near the tropics, warm but not hottest', 'The subtropical garden had palm trees and frost most winters.'),
  Word('travel', 'temperate', 'adj.', 'Of a mild middle-latitude climate', 'A temperate forest has four real seasons and roads you can use.'),
  Word('travel', 'monsoon', 'n.', 'A seasonal wind bringing heavy rains', 'The monsoon turned every street into a shallow river by four.'),
  Word('travel', 'typhoon', 'n.', 'A powerful Pacific tropical cyclone', 'A typhoon shut down every flight out of Manila for two days.'),
  Word('travel', 'hurricane', 'n.', 'A powerful Atlantic or Caribbean tropical cyclone', 'A hurricane forecast canceled the cruise the day before boarding.'),
  Word('travel', 'cyclone', 'n.', 'A large rotating storm system', 'A cyclone was barreling toward the coast as we drove inland.'),
  Word('travel', 'dryseason', 'n.', 'The part of the year with little rain', 'Dryseason is the safest time to drive interior roads in the highlands.'),
  Word('travel', 'wetseason', 'n.', 'The part of the year with heavy rains', 'In the wetseason the waterfalls roar and the trails turn to mud.'),
  Word('travel', 'shoulderseason', 'n.', 'A period between peak and off-peak travel', 'Shoulderseason in Greece means warm seas and half the crowds.'),
  Word('travel', 'highseason', 'n.', 'The most popular and expensive travel time', 'Highseason here doubles every hotel rate without warning.'),
  Word('travel', 'lowseason', 'n.', 'The cheapest and quietest travel time', 'Lowseason has the smallest crowds and the biggest discounts.'),
  Word('travel', 'offseason', 'adj.', 'Outside the busy time for travel', 'Offseason on the Greek islands felt like a personal favor from the gods.'),
  Word('travel', 'peakseason', 'n.', 'The busiest period of the year for travelers', 'Peakseason in August fills every coastal road with rental cars.'),
  Word('travel', 'highnoon', 'n.', 'Midday when the sun is at its peak', 'Highnoon in the desert is for shade, not sightseeing.'),
  Word('travel', 'goldenhour', 'n.', 'The hour after sunrise or before sunset, ideal for photos', 'Every cathedral looks made of honey during goldenhour.'),
  Word('travel', 'bluehour', 'n.', 'The twilight before sunrise or after sunset', 'Bluehour over the canal turned every reflection into a painting.'),
  Word('travel', 'sunrise', 'n.', 'The moment the sun appears over the horizon', 'Sunrise at the temple was worth the four o\'clock alarm.'),
  Word('travel', 'sunset', 'n.', 'The daily descent of the sun below the horizon', 'A rooftop sunset with cold beers became our nightly ritual.'),
  Word('travel', 'midnightsun', 'n.', 'The sun visible at midnight in polar summers', 'The midnightsun made us forget to sleep for three days.'),
  Word('travel', 'polarnight', 'n.', 'A polar period when the sun never rises', 'Polarnight in Tromso meant chasing the aurora at any hour of work.'),
  Word('travel', 'aurora', 'n.', 'Colorful lights in polar skies', 'A green aurora rippled across the sky like fabric in slow motion.'),
  Word('travel', 'borealis', 'n.', 'The northern aurora visible in high latitudes', 'A faint borealis was just visible from the back porch.'),
  Word('travel', 'australis', 'n.', 'The southern aurora visible from high southern latitudes', 'Tasmania occasionally treats stargazers to a clear australis show.'),
  Word('travel', 'crossing', 'n.', 'A passage between two places, especially over water', 'The crossing took ninety minutes against a stiff Atlantic wind.'),
  Word('travel', 'embarkation', 'n.', 'The act of boarding a ship or plane', 'Embarkation took twice as long because two buses arrived together.'),
  Word('travel', 'gangway', 'n.', 'A movable bridge for boarding a ship', 'A wobbly gangway took us from the dock down onto the catamaran.'),
  Word('travel', 'portofcall', 'n.', 'A stop on a cruise itinerary', 'Each portofcall gave us six hours to explore and one to find the boat.'),
  Word('travel', 'shoreexcursion', 'n.', 'A guided trip from a docked cruise ship', 'A shoreexcursion to the ruins beat the hotter beach option.'),
  Word('travel', 'cabinroom', 'n.', 'A sleeping room on a ship', 'Our cabinroom had a window with a view of a relentless gray sea.'),
  Word('travel', 'porthole', 'n.', 'A small round window on a ship', 'Through the porthole I could see dolphins keeping pace at dawn.'),
  Word('travel', 'starboard', 'n.', 'The right-hand side of a vessel facing forward', 'A whale spout appeared two hundred meters off the starboard side.'),
  Word('travel', 'port', 'n.', 'A harbor where ships dock', 'The port had three cruise terminals lined up side by side.'),
  Word('travel', 'stern', 'n.', 'The back end of a ship', 'A wake stretched out behind us from the stern for miles.'),
  Word('travel', 'bow', 'n.', 'The front end of a ship', 'Spray flew over the bow as we hit the open sea.'),
  Word('travel', 'lifejacket', 'n.', 'A floatation vest worn over the chest', 'A safety briefing showed us how to fasten the lifejacket in the dark.'),
  Word('travel', 'lifeboat', 'n.', 'A small boat for emergency escape from a ship', 'A lifeboat drill before the first dinner was treated almost like a game.'),
  Word('travel', 'manifest', 'n.', 'A list of passengers or cargo on a vessel', 'The captain ran a quick manifest check before we cast off.'),
  Word('travel', 'tender', 'n.', 'A small boat ferrying passengers to a larger one', 'A tender carried us in groups of twenty from the cruise ship to shore.'),
  Word('travel', 'lifering', 'n.', 'A floating ring thrown to save someone in water', 'A bright lifering hung at each end of the ferry deck.'),
  Word('travel', 'lighthousekeeper', 'n.', 'The person who tends a lighthouse', 'The retired lighthousekeeper still climbed the steps each evening.'),
  Word('travel', 'lighthouse', 'n.', 'A tower with a light that warns ships', 'The lighthouse beam swept the harbor every fifteen seconds.'),
  Word('travel', 'reef', 'n.', 'A ridge of rock or coral near the sea surface', 'The reef was crowded with parrotfish and one shy octopus.'),
  Word('travel', 'shoal', 'n.', 'A shallow area in a body of water', 'A shoal near the marker forced us to detour around it.'),
  Word('travel', 'cay', 'n.', 'A small low island, especially of coral', 'A cay no bigger than a tennis court had one palm and zero people.'),
  Word('travel', 'sandbar', 'n.', 'A long bank of sand in the sea or river', 'The boat ran aground briefly on an unmarked sandbar.'),
  Word('travel', 'tidepool', 'n.', 'A pool of seawater left by the tide', 'Each tidepool held urchins, crabs, and the day\'s best science lesson.'),
  Word('travel', 'tidal', 'adj.', 'Relating to the rise and fall of the sea', 'A tidal causeway connects the island to the mainland twice a day.'),
  Word('travel', 'highwater', 'n.', 'The highest point of the tide', 'At highwater the path to the chapel disappears beneath the sea.'),
  Word('travel', 'lowwater', 'n.', 'The lowest point of the tide', 'At lowwater you can walk between two islands across wet sand.'),
  Word('travel', 'driftwood', 'n.', 'Wood washed up by the sea or river', 'A driftwood fire on the beach lasted into the small hours.'),
  Word('travel', 'cobble', 'n.', 'A rounded stone used to pave old streets', 'Every cobble felt loose to my tired ankles by evening.'),
  Word('travel', 'flagstone', 'n.', 'A flat slab of stone used for paving', 'A flagstone path led to a hidden walled garden.'),
  Word('travel', 'crossroads', 'n.', 'A junction where roads meet', 'A signpost at the crossroads pointed to four villages in four languages.'),
  Word('travel', 'cul-de-sac', 'n.', 'A street closed at one end', 'Our hotel hid down a quiet cul-de-sac off a busy avenue.'),
  Word('travel', 'thoroughfare', 'n.', 'A main road through a place', 'The main thoroughfare hummed with markets, mopeds, and music.'),
  Word('travel', 'avenue', 'n.', 'A wide street, often tree-lined', 'A long avenue of plane trees led to the chateau gates.'),
  Word('travel', 'mews', 'n.', 'A row of converted stable buildings on a small lane', 'A converted mews hid a row of tiny restaurants.'),
  Word('travel', 'piazzetta', 'n.', 'A small Italian square', 'A piazzetta with three tables made for the perfect espresso stop.'),
  Word('travel', 'square', 'n.', 'An open public space in a town', 'The square filled every evening with chess players and street musicians.'),
  Word('travel', 'rotunda', 'n.', 'A round building or room, often domed', 'A marble rotunda at the museum echoed every footstep.'),
  Word('travel', 'atrium', 'n.', 'A large open central area in a building', 'The hotel atrium soared eight stories with hanging vines.'),
  Word('travel', 'courtyard', 'n.', 'An open area enclosed by walls or buildings', 'A courtyard with a stone fountain was the quietest seat in town.'),
  Word('travel', 'patio', 'n.', 'An outdoor space attached to a building', 'Breakfast on the patio came with hummingbirds and warm bread.'),
  Word('travel', 'verandah', 'n.', 'A roofed open gallery along a building', 'Rocking chairs on the verandah were the unofficial lobby.'),
  Word('travel', 'archway', 'n.', 'A passage under an arch', 'An archway in the city wall framed the cathedral perfectly.'),
  Word('travel', 'colossus', 'n.', 'A huge statue or sculpture', 'A bronze colossus of an emperor guarded the harbor entrance.'),
  Word('travel', 'frieze', 'n.', 'A horizontal sculpted strip on a building', 'The Parthenon\'s frieze marches around the temple like a procession.'),
  Word('travel', 'facade', 'n.', 'The front face of a building', 'A facade of cracked pastel plaster hid a courtyard of orange trees.'),
  Word('travel', 'gargoyle', 'n.', 'A carved stone figure on a building, often a waterspout', 'Each gargoyle had a unique scowl carved by a different mason.'),
  Word('travel', 'flyingbuttress', 'n.', 'An external arched support for a tall wall', 'A row of flyingbuttress arms keeps the cathedral walls standing.'),
  Word('travel', 'apse', 'n.', 'A semicircular recess in a church', 'Sunlight through the apse window painted gold across the stone floor.'),
  Word('travel', 'nave', 'n.', 'The main central area of a church', 'The nave was so long that the choir sang from a distant cloud.'),
  Word('travel', 'transept', 'n.', 'The cross-arm of a church floor plan', 'A small chapel tucked into the transept held the city\'s relics.'),
  Word('travel', 'belfry', 'n.', 'The bell-housing part of a tower', 'A spiral staircase climbed two hundred steps to the belfry.'),
  Word('travel', 'crypt', 'n.', 'An underground chamber, often under a church', 'A guided tour of the crypt felt like stepping into the city\'s memory.'),
  Word('travel', 'catacomb', 'n.', 'An underground burial passage', 'The catacomb tour wound through five kilometers of lit tunnels.'),
  Word('travel', 'mausoleum', 'n.', 'A grand stone building housing a tomb', 'A marble mausoleum stood at the center of a peaceful walled garden.'),
  Word('travel', 'necropolis', 'n.', 'A large ancient burial ground', 'A pre-Roman necropolis lay just outside the city walls.'),
  Word('travel', 'ruin', 'n.', 'The remains of an old structure', 'A jungle ruin had stelae carved in a script no one alive could read.'),
  Word('travel', 'amphitheater', 'n.', 'A round or oval ancient open-air venue', 'A Roman amphitheater hosted summer plays again after two thousand years.'),
  Word('travel', 'forum', 'n.', 'An ancient Roman public meeting place', 'The forum is still where every walking tour begins.'),
  Word('travel', 'palace', 'n.', 'A large grand residence of royalty', 'A palace tour took two hours and we still saw only half the rooms.'),
  Word('travel', 'fortress', 'n.', 'A heavily fortified building or town', 'A hilltop fortress watched the river crossing for centuries.'),
  Word('travel', 'donjon', 'n.', 'The strong central tower of a castle', 'The donjon was the last place defenders would retreat to.'),
  Word('travel', 'keep', 'n.', 'The central tower or stronghold of a castle', 'A spiral stair inside the keep climbed five thick stone floors.'),
  Word('travel', 'moat', 'n.', 'A defensive ditch, often filled with water', 'A duck family paddled across the lily-covered moat.'),
  Word('travel', 'drawbridge', 'n.', 'A bridge that can be raised or lowered', 'The drawbridge no longer worked but still looked the part.'),
  Word('travel', 'portcullis', 'n.', 'A heavy grille that drops to block a gateway', 'The iron portcullis hung above the castle entrance like a row of teeth.'),
  Word('travel', 'museum', 'n.', 'A building that houses cultural exhibits', 'A small museum at the train station held a Roman mosaic floor.'),
  Word('travel', 'gallery', 'n.', 'A room or building displaying art', 'A gallery hidden up a stairway had only twelve paintings, all worth the climb.'),
  Word('travel', 'archive', 'n.', 'A collection of historical records', 'The town archive opened to visitors on Thursdays for two hours.'),
  Word('travel', 'reservation', 'n.', 'A booking held for a guest', 'My reservation was lost in the system but the manager waved us through.'),
  Word('travel', 'walkin', 'n.', 'A guest arriving without a reservation', 'A walkin paid more than we did for the same room.'),
  Word('travel', 'frontdesk', 'n.', 'The reception counter at a hotel', 'The frontdesk gave us a map with the cafe\'s breakfast hours circled.'),
  Word('travel', 'porterservice', 'n.', 'The service that helps with luggage at hotels', 'A porterservice took our bags up while we settled the bill.'),
  Word('travel', 'valet', 'n.', 'A staff member who parks guests\' cars', 'A valet whisked our car away and produced it five minutes after we called.'),
  Word('travel', 'dnd', 'n.', 'The do-not-disturb sign hung on a door', 'A dnd sign on the door bought me two more hours of sleep.'),
  Word('travel', 'housekeeping', 'n.', 'The hotel staff that cleans rooms', 'Housekeeping left an extra pillow before I even asked.'),
  Word('travel', 'bellservice', 'n.', 'Service that helps with luggage and errands', 'Bellservice held our bags for the afternoon between checkout and the train.'),
  Word('travel', 'kingbed', 'n.', 'A very wide hotel bed for two people', 'A kingbed with three pillows each felt like a small luxury after a long flight.'),
  Word('travel', 'twinbeds', 'n.', 'Two single beds in one hotel room', 'We requested twinbeds for the trip with my sister.'),
  Word('travel', 'rollaway', 'n.', 'An extra folding bed for hotel rooms', 'A rollaway turned our double into a family room.'),
  Word('travel', 'allinclusive', 'adj.', 'A resort price covering food and drinks', 'An allinclusive in Cancun is sometimes exactly what tired parents need.'),
  Word('travel', 'halfboard', 'n.', 'A meal plan including breakfast and dinner', 'Halfboard let us experience local lunches and trust the kitchen at night.'),
  Word('travel', 'fullboard', 'n.', 'A meal plan including all three daily meals', 'Fullboard at the remote eco-lodge meant we never had to wonder about lunch.'),
  Word('travel', 'breakfastbuffet', 'n.', 'A self-serve morning meal spread', 'The breakfastbuffet had fresh juice, six cheeses, and three kinds of bread.'),
  Word('travel', 'continentalbreakfast', 'n.', 'A simple morning meal of pastries and coffee', 'A continentalbreakfast in the lobby came with strong coffee and warm croissants.'),
  Word('travel', 'roomservice', 'n.', 'Food delivered to a hotel room', 'After a long delay home, roomservice was the only sensible dinner.'),
  Word('travel', 'spaprogramme', 'n.', 'A scheduled set of spa treatments', 'A spaprogramme of mud baths and massages cured the long drive.'),
  Word('travel', 'thalasso', 'n.', 'A spa therapy using seawater and seaweed', 'A thalasso center near the harbor used kelp from just outside.'),
  Word('travel', 'sauna', 'n.', 'A hot dry room for sweating in', 'The sauna held twelve quiet strangers and a quiet bucket of water.'),
  Word('travel', 'jacuzzi', 'n.', 'A hot bath with massage jets', 'A jacuzzi outdoors in January is its own travel goal.'),
  Word('travel', 'plunge', 'n.', 'A quick dip in cold water', 'A morning plunge in the lake set the rest of the day to a slower beat.'),
  Word('travel', 'springs', 'n.', 'Natural water rising warm or hot from the ground', 'A pool of springs at the bottom of the valley cured every sore muscle.'),
  Word('travel', 'geyser', 'n.', 'A hot spring that erupts in jets', 'A geyser sent steam fifty meters into the sky every two hours.'),
  Word('travel', 'caldera', 'n.', 'A large crater formed by a volcanic collapse', 'The caldera was three kilometers wide and held a perfect blue lake.'),
  Word('travel', 'volcano', 'n.', 'A mountain venting magma or ash', 'A drowsy volcano steamed lazily on the horizon every afternoon.'),
  Word('travel', 'lava', 'n.', 'Molten rock from a volcano', 'A fresh lava field looked like a frozen black ocean.'),
  Word('travel', 'fumarole', 'n.', 'A vent that releases volcanic gases', 'A fumarole hissed beside the trail, warming our hands as we passed.'),
  Word('travel', 'mudpot', 'n.', 'A boiling pool of muddy water near a hot spring', 'A mudpot bubbled like an oatmeal pot left on too long.'),
  Word('travel', 'cavern', 'n.', 'A large cave', 'A cavern as big as a cathedral hid a clear underground river.'),
  Word('travel', 'grotto', 'n.', 'A small cave, especially one beside the sea', 'A blue grotto glowed turquoise at exactly noon.'),
  Word('travel', 'stalactite', 'n.', 'A mineral spike hanging from a cave roof', 'Each stalactite was the slow work of a thousand years.'),
  Word('travel', 'stalagmite', 'n.', 'A mineral spike rising from a cave floor', 'A stalagmite the size of a man took the headlamp\'s entire beam.'),
  Word('travel', 'sinkhole', 'n.', 'A hole that opens when underground rock collapses', 'A sinkhole in Mexico became the best snorkeling we had ever done.'),
  Word('travel', 'cenote', 'n.', 'A natural pit revealing groundwater, found in the Yucatan', 'A cenote was a chamber of cool water under a dome of dripping vines.'),
  Word('travel', 'oasiscamp', 'n.', 'A campsite built around an oasis', 'An oasiscamp under date palms felt staged but smelled real.'),
  Word('travel', 'dune', 'n.', 'A hill of wind-shaped sand', 'A dune crawl at dawn made my legs forget that the sand was cold.'),
  Word('travel', 'salar', 'n.', 'A salt flat, especially in the Andes', 'The salar was a mirror after a thin layer of rain.'),
  Word('travel', 'pampas', 'n.', 'A vast South American grassland', 'A horseback ride across the pampas at dusk was almost silent.'),
  Word('travel', 'cordillera', 'n.', 'A long parallel mountain range', 'The cordillera ran the whole length of the country from north to south.'),
  Word('travel', 'massif', 'n.', 'A compact group of mountains', 'The Mont Blanc massif holds dozens of climbs in one cluster.'),
  Word('travel', 'highlands', 'n.', 'A mountainous part of a country', 'The Scottish highlands turn a deep rust gold every autumn.'),
  Word('travel', 'lowlands', 'n.', 'A relatively low and flat part of a region', 'The lowlands flooded gently every spring, on schedule, like a clock.'),
  Word('travel', 'wetland', 'n.', 'Land soaked or covered with water', 'A boardwalk wetland trail gave us five new bird species in an hour.'),
  Word('travel', 'bog', 'n.', 'Wet spongy ground of decaying plants', 'Each bog held two thousand years of preserved pollen and the occasional shoe.'),
  Word('travel', 'marshland', 'n.', 'Low watery land of reeds and grasses', 'A marshland boat tour came with mosquitos and a hundred herons.'),
  Word('travel', 'cataract', 'n.', 'A large powerful waterfall', 'A roaring cataract turned the canyon walls into a mist garden.'),
  Word('travel', 'cascade', 'n.', 'A small waterfall in a series', 'A series of cascades stepped down the mountain into a calm pool.'),
  Word('travel', 'rapids', 'n.', 'A fast turbulent stretch of river', 'Class three rapids gave us a wet shouted laugh for ten minutes.'),
  Word('travel', 'whitewater', 'adj.', 'Of fast foaming river water', 'A whitewater raft trip was the only way to see that canyon.'),
  Word('travel', 'fording', 'n.', 'Crossing a stream by wading', 'A fording of cold knee-deep water cut twenty minutes off the trail.'),
  Word('travel', 'tributary', 'n.', 'A smaller river feeding a bigger one', 'A pale-green tributary joined our river just above camp.'),
  Word('travel', 'delta', 'n.', 'The land where a river meets the sea in branches', 'The delta opened into a hundred channels we could explore by kayak.'),
  Word('travel', 'transhumance', 'n.', 'The seasonal movement of livestock and herders', 'Transhumance still moves sheep into the high pastures every June.'),
  Word('travel', 'pastoral', 'adj.', 'Of country life and grazing land', 'Our pastoral stay had goats, fresh cheese, and zero phone signal.'),
  Word('travel', 'wayside', 'n.', 'The side of a road, often with stalls', 'A wayside fruit stand sold mangoes for a fraction of the city price.'),
  Word('travel', 'roadside', 'n.', 'The area beside a road', 'A roadside shrine marked the highest point of the mountain pass.'),
  Word('travel', 'milestone', 'n.', 'A stone marker showing distances along a road', 'A worn milestone said three miles to a village that no longer existed.'),
  Word('travel', 'fingerpost', 'n.', 'A signpost with arms pointing in directions', 'A fingerpost in three languages helped us choose the village fork.'),
  Word('travel', 'wayfinding', 'n.', 'Navigating by signs and landmarks', 'Good wayfinding in airports saves hours of pure stress.'),
  Word('travel', 'tipping', 'n.', 'Giving small extra money for service', 'Tipping customs change every border so we always asked our host.'),
  Word('travel', 'haggling', 'n.', 'Negotiating a price, especially in markets', 'Haggling in the market is a friendly sport once you stop fearing it.'),
  Word('travel', 'phrasebook', 'n.', 'A small book of helpful foreign phrases', 'A pocket phrasebook saved us the time the only menu was hand-painted.'),
  Word('travel', 'guidebook', 'n.', 'A travel book of recommendations and maps', 'Our guidebook was twenty years old but the bakery on page sixteen was still there.'),
];

